### PR TITLE
Update for footer with G-plus

### PR DESCRIPTION
**Pull request by mbiesiad**
Hi. First of all, great work! 🚀

Currently the Google Plus platform (aka. Google+ or G+) is "no longer available for consumer (personal) and brand accounts".
That means the footer is little bit out of date (the link provided does not work properly).

Best wishes,
Michal

### CODE REVIEW

**Comment by mbiesiad** [comment]
Issue #6022

**Review by shaunanoordin — CHANGES_REQUESTED** [review]
## PR Review

(First off: thanks Michal!)

This PR removes links to the [no-longer-extant Google+ / Google Plus page for the Zooniverse](https://plus.google.com/+ZooniverseOrgReal)

- The G+ link is removed from the home page (when not signed-in)
- The G+ link is removed from the footer
- ❗ The ability to add OR EDIT a G+ link to a Project's "Social Links Section" (Build a Project -> Project 1234 -> Project Details -> Social Links Section)
  - _This, however, is causing issues. Please see Dev Notes._

_Example below: the Social Links Section of "Test Project 2021"_

Screenshot 2021-10-01 at 16 47 20

Not within scope of this PR:
- The G+ links in the [Contact Us](https://www.zooniverse.org/about/contact) page is not removed because, to be fair, _that will involve editing ~20 language files_ which will all needs its own language review, so best to leave that for a different PR.

### Dev Notes

Issue detected: if a project has an _existing_ Google Plus link, then the project builder page **crashes** completely.

To replicate:
- Go to zooniverse.org and edit any given Project X (e.g. https://www.zooniverse.org/lab/16927)
- In Project X's project builder page, go to Project Details, and scroll down to the Social Links Section
- Add a link for a Google Plus account
- Now, go to the localhost and edit the same Project X (e.g. https://local.zooniverse.org:3735/lab/16927?env=production)
  - Expected: the project builder page should load correctly
  - Actual: the project builder page (specifically, the Project Details section) crashes with the error: `Cannot read properties of undefined (reading 'pathBeforeSite')`

Analysis:
- Two files - `social-links-editor.jsx` and `ExternalLink.jsx` - use `socialIcons[site].pathBeforeSite` which (in one case) presumes that `site` will _always_ correspond to something in `socialIcons`
- When an unexpected `site` comes into play (i.e. GooglePlus, which no longer "exists" as of this PR), it just breaks everything.

Solution is pretty simple though - just add an existential `?.` check before calling `.pathBeforeSite`

### Status

Change Requested:
- Change all instances of `socialIcons[site].pathBeforeSite` to `socialIcons[site]?.pathBeforeSite`

There should be _3_ instances in the repo that should be changed. I know the error _only_ occurs in `SocialLinksEditor.renderRow()`, but I think this is a good opportunity to add some extra resilience to the code.

**Comment by mbiesiad** [comment]
Hi @shaunanoordin Thank you for your message! I will check it carefully (ASAP). Let's keep in touch. 

Best wishes,

**Comment by mbiesiad** [comment]
@shaunanoordin First of all, I am sorry for the late reply, I was quite busy that time..
Thank you so much again for your great CR! Full professional in my opinion. I like your style. ⭐ 

Requested changes done - used optional chaining operator (?.).
You're right. I agree with you.

Best wishes,

**Review by shaunanoordin — APPROVED** [review]
## PR Review (Update)

Changes look good! Thank you, @mbiesiad 👍

PR approved. I'm going ahead and running the automated tests and necessary merge-updates before merging.

**Comment by shaunanoordin** [comment]
Tests are failing for some reason. Give me a second to look into why.

**Review by shaunanoordin — CHANGES_REQUESTED** [review]
## PR Review (Update)

Ah, I've figured out what's wrong, and it's just a minor issue of an outdated test that needs to be updated.

**Change request:**

File: `app/pages/lab/social-links-editor.spec.js`

Change this...
```
it('should contain the correct number of rows', function () {
  const rows = wrapper.find('tr');
  assert.equal(rows.length, 13);
});
```

to this...
```
it('should contain the correct number of rows', function () {
  const rows = wrapper.find('tr');
  assert.equal(rows.length, 12);
});
```

Once this change is done, the automated tests should pass, and then I can merge this. 👌

**Comment by mbiesiad** [comment]
@shaunanoordin Once again, many thanks for your great CR here! 🎉 Changed. 👌 Best wishes

**Review by shaunanoordin — APPROVED** [review]
## PR Review (Update)

Changes look good, PR approved! Thanks again @mbiesiad 👍

**Comment by mbiesiad** [comment]
@shaunanoordin my pleasure! Thank you too! Best wishes, 🎉

**Pull request merged**
