### PR TITLE
Treat empty string redirects as not having one

### LINKED ISSUE #1645: Sidebar project Talk links don't work
The only one that seems to be working is Galaxy Zoo: Bar Lengths.

Everything else just leaves you on the current page.

Sometimes even Bar Lengths doesn't work.

Is anyone else also experiencing this? I tested it in Firefox and Chrome.

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #1645 
- Example on dev is fossil-finder

### CODE REVIEW

**Comment by chrissnyder** [comment]
Under what scenario would a blank redirect string be OK here? Wouldn't that lead the redirect link to go nowhere?

**Comment by aweiksnar** [comment]
This treats a redirect of `null` or `""` as not having one, so those can link to the project talk instead of main talk

**Comment by aweiksnar** [comment]
Just changed the commit message to be more descriptive

**Comment by chrissnyder** [comment]
Ah ok, I totally read that wrong, sorry.

**Comment by aweiksnar** [comment]
:bow:

**Pull request merged**
