### PR TITLE
Use window.prompt to confirm board deletion

### LINKED ISSUE #1778: Making it harder to delete a talk board/thread?
I accidentally deleted the wrong private moderator thread (no real harm done, just kept the test thread instead and deleted the thread with a single post reporting the possible issue). Right now Talk confirms with a yes/no question. Should it make you type in the name of the board? Definitely on me for doing something without triple checking, but thought I'd mention it for @aweiksnar and @parrish to decide.

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #1778

### CODE REVIEW

**Comment by parrish** [comment]
Looks good!  :+1:

**Comment by parrish** [comment]
Any thoughts on doing the same thing for discussions?

**Comment by aweiksnar** [comment]
I thought discussion titles tend to be a bit long to type out, maybe typing 'delete this discussion' instead?

**Comment by parrish** [comment]
Fair point.  Maybe even just "delete"

**Comment by aweiksnar** [comment]
Ok, yeah I'll PR that too in just a min

**Pull request merged**
