### PR TITLE
Fix 5527: prevent double annotations on touchscreen marking tasks

### LINKED ISSUE #5527: On touchscreen, "click to add annotation" creates two annotations
## UI Bug

On touchscreen devices, the "click to add annotation" action creates two annotations instead of one. Additionally, it is VERY difficult to select an existing annotation.

Tested on OSX+Chrome (emulating touchscreens) on https://www.zooniverse.org/projects/roxannebeltran/ano-nuevo-island-animal-count/classify

Original report: https://www.zooniverse.org/talk/17/1146166

### Expected behavior

- on touch screen devices, on projects where clicking on the Subject creates an annotation mark,
  - clicking on an empty space should create one (1) mark
  - clicking on an existing mark should select that mark

### Current behavior

- on touch screen devices,
  - clicking on an empty space should creates two (2) marks
  - clicking on an existing mark _sometimes_ creates two (2) marks

### Steps to replicate

1. open Chrome, enable touchscreen emulation - or use a native touchscreen device
2. go to https://www.zooniverse.org/projects/roxannebeltran/ano-nuevo-island-animal-count/classify and begin the main Task that uses Drawing Tool, point marker.
3. start clicking.

### Status

Issue is confirmed to exist. Investigation into the cause is ongoing.

Investigating:
- Is this occurring on other projects?
- What's causing the action to trigger twice with a touch interface?
- What's the difference between a touch interface and a mouse interface?
- Why is it difficult to select an existing annotation?
- When did this start happening?

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview

Fixes #5527 

Staging branch URL: https://pr-5528.pfe-preview.zooniverse.org

Currently, if we attempt to perform a marking task on a touchscreen device, _two_ annotation marks are created instead of one. This is caused by the `onPointerDown` and `onTouchStart` handlers (in the `Draggable` class) firing simultaneously when a touchscreen device detects touch input.

This PR fixes that issue by checking if Pointer Events exist on the browser, and if available, using it instead of Mouse Events or Touch Events. This prevents redundant events from firing.

(Note: we shouldn't remove Mouse Events or Touch Events altogether, since they're good fallbacks for less modern browsers.)

### Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

### Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] Are the tests passing locally and on Travis?

### Optional Checks

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [x] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### Status

Ready for review, and this might be of interest to @eatyourgreens and @simensta

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Wait, I still need to update the tests!

**Comment by shaunanoordin** [comment]
## Resources / Further Reading

W3C gives a good example of how to handle Pointer Events in an environment where Mouse Events and Touch Events might still trigger.
https://w3c.github.io/pointerevents/#examples

patrickhlauke's tests on touch/pointer events gives a very thorough breakdown of how these events interact with/prioritise over each other.
https://patrickhlauke.github.io/touch/tests/results/

**Comment by eatyourgreens** [comment]
The idea looks good but I think this needs tests.

**Comment by shaunanoordin** [comment]
The challenge I have with updating `draggable.spec.js` is that the whole `describe('Draggable')` block operates assuming that there's only one kind of browser window (with no PointerEvent), whereas the new `draggable.jsx` checks for two different possibilities (a window with PointerEvent, and one without).

The _rough_ solution to this is to have `describe('Draggable (old browser compatibility)')` and `describe('Draggable (browser with Pointer Events)')`.

The former runs `before(() => delete global.window.PointerEvent; ) testDrag('mousedown', 'mousemove', 'mouseup'); testDrag('touchstart', 'touchmove', 'touchend');` and the latter runs `before(() => global.window.PointerEvent = {}; ) testDrag('pointerdown', 'pointermove', 'pointerup');`, so we're basically testing for two different environments.

Problem is, the _rough_ solution will create a lot of code duplication, which I'd rather avoid.

**Comment by eatyourgreens** [comment]
Can you pass the a boolean into `testDrag()` as an additional argument that sets `window.pointerEvent`? It's been a while since I wrote those tests.

**Comment by shaunanoordin** [comment]
> Can you pass the a boolean into testDrag() as an additional argument that sets window.pointerEvent? It's been a while since I wrote those tests.

Unfortunately, no - I tried that at first. Turns out I need to set the window variable before the `wrapper` is declared, i.e. ...

```
before(function() {
  ...
  window.PointerEvent = {};
  wrapper = shallow(
    <Draggable
      onStart={onStart}
      onDrag={onDrag}
      onEnd={onEnd}
    >
      <p>Hello</p>
    </Draggable>
  );
  ...
});
```

I'm not sure how I can change the 'before()' code in between the `testDrag()` calls.
```
// use a before() version that has window.PointerEvent = undefined
testDrag('mousedown', 'mousemove', 'mouseup');
testDrag('touchstart', 'touchmove', 'touchend');
// change to a before() version that has window.PointerEvent = {}
testDrag('pointerdown', 'pointermove', 'pointerup');
// Have some code to reset global.window.PointerEvent to its original state in case other tests need it.
```

**Comment by eatyourgreens** [comment]
Good point. I'll have a look at those tests tomorrow. Mouse and touch are tested now when pointer events aren't available, but the tests don't check that mouse and touch are ignored when pointer events are enabled. In my head, the spec looks something like this:

- set `window.pointerEvent`
  - fire mock `pointerdown`, `mousedown` and `touchstart` events.
  - expect `pointerdown` to be handled but the others to be ignored.
- remove `window.pointerEvent`
  - fire mock `pointerdown`, `mousedown` and `touchstart` events.
  - expect `pointerdown` to be ignored but the others to be handled.

Does that mean splitting the tests for setting the event handlers (on start) out of the `testDrag` function and testing those separately? The tests for `move` and `end` don't change because those call the handlers directly.

**Comment by shaunanoordin** [comment]
## PR Update

I've added a very rough update to `draggable.spec.js` that splits `describe('Draggable')` to two versions - one version where the window is a "classic browser" without PointerEvent support, and another version is a "modern browser" with support.

Tests now pass, but I welcome any suggestions on how to make the test code more streamlined.

As pointed out in the above posts, the key challenge here is that the _"this window has/doesn't have PointerEvent support"_ logic needs to run _before_ the `wrapper = <Draggable>` is created.)

**Comment by shaunanoordin** [comment]
### Testing

To test this on touchscreen mobile devices, you can...
- go to https://pr-5528.pfe-preview.zooniverse.org/projects/deleted-1845/i-fancy-cats/classify
- go to the "Draw Cattail" Task
- each click should only create one annotation mark. (The Task panel counts the number of existing annotations.)
- for comparison, go to https://master.pfe-preview.zooniverse.org/projects/deleted-1845/i-fancy-cats/classify and note that a single click creates two annotation marks.

**Comment by eatyourgreens** [comment]
My phone doesn’t support pointer events so I get the same results on both branches. Anyone testing this on iOS might need iOS 13.

**Comment by eatyourgreens** [comment]
I've updated the tests in #5529.

**Comment by eatyourgreens** [comment]
This looks good. Should we deploy it today or wait until Monday?

**Comment by shaunanoordin** [comment]
Good point - let's not risk a Friday deploy. This PR is now scheduled for a Monday merge. In the meantime, I'm going to take a look at how existing Classifications might have been affected by the bug.

A big 👍 for Jim and Andrea for help with this PR

**Pull request merged**
