### PR TITLE
Tutorial scroll fix 2698

### PR DESCRIPTION
**Pull request by simensta**
Addresses #2698. Also adds an overflow scroll fix for IE.

### CODE REVIEW

**Comment by srallen** [comment]
Could we consider adding the scroll to top behavior to the tutorial component itself instead of to `StepThrough`? Conceivably `StepThrough` could be used by a component elsewhere, even though it's not at the moment (I almost used it with the mini-course, for instance). I think the `handleNextClick` found on [L117-118](https://github.com/zooniverse/Panoptes-Front-End/blob/fab2dafe95a91b1e64dcb2a7dbfe2f373fc8b737/app/lib/tutorial.cjsx#L117-L118) would be a good spot to add this behavior.

Alternatively, if it is in `StepThrough`, the scroll to top should be agnostic of the component it is used in and not rely on a specific class name.

**Comment by simensta** [comment]
When the scroll logic is handled by `handleNextClick` in the `Tutorial`, the scroll logic is only executed when Continue is pressed and not when the dots and arrows are pressed. In order to have consistent behavior across the `Tutorial`'s navigation elements, I kept the scroll logic in the `StepThrough` component. However, the scroll logic no longer relies on a specific class name. Thoughts?

**Comment by srallen** [comment]
Could you rebase this? A few big changes have come in since, like react-router upgrade, etc.

**Comment by simensta** [comment]
Good call -- will do.

**Pull request merged**
