### PR TITLE
IE11 fix for highligther tool

### PR DESCRIPTION
**Pull request by simensta**
Fixes two issues with the highlighter tool in IE11. 

Describe your changes.
In `#getOffset`, the `for...of` loop is replaced with a `for` loop.
In `#selectableArea`, `parentElement` is replaced with `parentNode`.

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://ie-fix-highligther-v2.pfe-preview.zooniverse.org
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
@simensta , the code changes LGTM, but I'm not sure where I can test the issue on IE11 + Edge. Is there a project that's set up to use the highlighter tool that I can examine?

**Comment by simensta** [comment]
@shaunanoordin, you can test the highlighter tool on the following project:
https://ie-fix-highligther-v2.pfe-preview.zooniverse.org/projects/scribe-2/demo-for-text-selection

**Comment by shaunanoordin** [comment]
Weird IE11 quirk 1: 

screen shot 2017-06-21 at 16 15 10
_The green-highlighted sentence suddenly forgot it's supposed to be on a new line, and merges into the previous line that says "June 3rd"_

Weird IE11 quirk 2:

screen shot 2017-06-21 at 16 17 08
_When the words "whether whether" are highlighted, the final "r" of the last "whether" duplicates itself. But... it only happens when the words "this rank signed Berlin Berlin" is highlighted beforehand. It's repeatable; it just doesn't make sense._

**Comment by rogerhutchings** [comment]
Is this good to go, or is it still being worked on?

**Comment by shaunanoordin** [comment]
This PR is good; the weird IE11 quirks follow up was just a footnote. PR is ready to merge.

**Comment by simensta** [comment]
Thanks @shaunanoordin! I'll make a note in #3738 about the IE11 quirks.

**Pull request merged**
