### PR TITLE
Clean up collections manager react-select

### LINKED ISSUE #2040: When you select a collection from the drop down menu it's name changes to a number
I'm not sure why this is happening, but when you select the collection from the drop down menu the form autofills to a number. I find it a bit confusing at first since no good way to know if you've accidentally selected the wrong collection. 

screen shot 2015-12-17 at 11 10 24 pm

screen shot 2015-12-17 at 11 10 28 pm

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #2040

### CODE REVIEW

**Comment by aweiksnar** [comment]
mention-bot is alive! :octocat:

**Comment by camallen** [comment]
Nice one mention-bot! @aweiksnar so the reason i initially used the onChange hook was the selected state was always 1 behind what it should have been, see [here](https://github.com/zooniverse/Panoptes-Front-End/pull/1886#discussion_r43690069). I assume that i just missed the correct API call from react-select but can you make sure that when adding multiples the selected state is reported correctly?

**Comment by aweiksnar** [comment]
Ah gotcha! Yeah I think reading the values state from the react-select will work here too, been testing things out and the selected state seems to always be in sync with single/multiple selections

**Comment by camallen** [comment]
LGTM - i won't have time to test till tomorrow, anyone else?

**Pull request merged**
