### PR TITLE
add text-align left to survey task button

### PR DESCRIPTION
**Pull request by mcbouslog**
Staging branch URL: https://survey-task-button-text-align.pfe-preview.zooniverse.org/
- to project with issue: https://survey-task-button-text-align.pfe-preview.zooniverse.org/projects/amyrobey996/numbat-discovery?env=production

Fixes https://www.zooniverse.org/projects/amyrobey996/numbat-discovery.

Describe your changes.
- add `text-align: left` to `survey-task-chooser-choice-button` class

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [x] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Code update looks good of course. 😄 I'll just run a quick check on the browsers. (Oh, IE11...)

**Comment by simoneduca** [comment]
LGTM, I'll wait for Shaun to feedback on IE.

**Comment by shaunanoordin** [comment]
For the record, the problem that "a Survey Answer is centre-aligned" is consistent across _all_ survey task projects, but _only if_ the Survey Answer text is longer than its container.

Apparently this was an issue even for WildCam Darien, but nobody noticed because the animal names were pretty short and weren't replaced by Disney song lyrics.

screen shot 2018-02-01 at 16 24 32
_The visual error as it currently stands on the Numbat Discovery project._

screen shot 2018-02-01 at 16 24 07
_Simulated error on the WildCam Darien page indicating this was a hidden issue all along._

**Comment by mcbouslog** [comment]
Thanks guys!

**Pull request merged**
