### PR TITLE
Link discussions to last page, no cache for links

### LINKED ISSUE #873: Most recent post link doesn't go to the most recent post
The front page of Talk, when showing recent threads, displays not the name of the most recent person to post, but instead the name of the person who started the thread.

screen shot 2015-06-29 at 1 09 01 pm

when you can see that Chris' post was actually from a long time back, and the most recent posts were mine and Janet's

screen shot 2015-06-29 at 1 10 37 pm

### PR DESCRIPTION
**Pull request by aweiksnar**
- Link discussions to last page from board preview
  - Also no cache for links - I believe this closes #873
- Add talk config to store page sizes and such

### CODE REVIEW

**Comment by DarrenMcRoy** [comment]
Will it link to the bottom of the last page, where the most recent comment is?

**Comment by aweiksnar** [comment]
Not currently, Let me update. So you just want the same behavior as linking to the comment, but without the highlighted background

**Comment by DarrenMcRoy** [comment]
That would be ideal, yeah. That's how virtually every forum works. :+1:

**Comment by chrissnyder** [comment]
Should I hold on looking at this PR?

**Comment by aweiksnar** [comment]
Yeah sorry I'll let you know when it's ready. Looks like a merge conflict popped up, and I believe Darren's scrolling request may be related to the other PR I have open now (#917)

**Comment by chrissnyder** [comment]
No worries, just ping me when ready.

**Comment by aweiksnar** [comment]
Actually I close it up for now and then reopen when ready

**Comment by chrissnyder** [comment]
:shipit: :shipit: :shipit:

**Pull request merged**
