### PR TITLE
Enable image selection for project avatar and background image

### PR DESCRIPTION
**Pull request by brian-c**
Allows setting project avatars and background images

### CODE REVIEW

**Comment by chrissnyder** [comment]
UI seems to act weird when first adding these to a fresh project

1. Initial state, brand new project - http://i.imgur.com/jnEWk8J.png
2. State after adding avatar - http://i.imgur.com/mvxDqU6.png
3. State after adding background - http://i.imgur.com/HZ80imz.png

Step 3 seems pretty variable, in that sometimes both images will disappear, or both will work. Some race condition maybe?

Refreshing the page solves all the above and makes it work just fine.

**Comment by brian-c** [comment]
Ooo, yeah, something funny going on there. I'll look into it.

**Comment by brian-c** [comment]
Race condition indeed. The JSON-API lib doesn't cache failed requests, so if the project didn't originally have an avatar or background, it would request it again every time the component rendered, so it'd end up trying to get the image at the same time it was trying to create it.

Should be fixed now.

**Comment by chrissnyder** [comment]
Tried again, worked like a charm. Merging...

**Pull request merged**
