### PR TITLE
Autofocus the alert box close button

### LINKED ISSUE #4006: help button box opens with scroll not at the top of the content
In Firefox and Chrome (latest versions on Mac OS X)  I get that the helpbox is down scrolled all the not at the top, but a few scrolls down. Would it be possible to have the help box open with the scroll bar set to the top? I tried three projects - one was with Chrome the other two were with Firefox  - screenshots below of what pops up right after clicking on the help button. 

screen shot 2017-08-25 at 8 29 26 am
screen shot 2017-08-25 at 10 39 18 am
screen shot 2017-08-25 at 8 20 56 am

### PR DESCRIPTION
**Pull request by eatyourgreens**
Autofocus the close button at the top of alert dialogs.
Remove autofocus from the task help close button.

Fixes #4006 .

Converts the `alert()` helper and the `Dialog` component to ES6.

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://fix-4006.pfe-preview.zooniverse.org/
- [x] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

## Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
@mschwamb here's a link to Comet Hunters on this branch of the code https://fix-4006.pfe-preview.zooniverse.org/projects/mschwamb/comet-hunters?env=production

**Comment by mschwamb** [comment]
@eatyourgreens does there need be a focus on the top x? Hitting escape closes the window so there's already a keyboard shortcut. Maybe I'm just having a hard time with all these focuses for keyboard-usage, but I find it  a bit odd to have the x highlighted in a box.

**Comment by eatyourgreens** [comment]
Yes. The escape key is only detected if it's pressed while the dialog has focus. Also, if focus doesn't shift to the dialog, but remains with the task buttons, you'll find you can still use tab and the arrow keys to interact with the classification task, even though they're blocked from mouse interaction. So you could, for example, tab to the Talk link and activate it, even though you can't click it with the mouse.

Currently, focus shifts to the Close button at the bottom of the dialog, which then gives us the bug where the browser scrolls down to bring that button into view.

**Comment by eatyourgreens** [comment]
@mschwamb the change in 7f823eb might be better for Comet Hunters. It allows you to control the scrolling content with the keyboard once the help dialog opens.

https://fix-4006.pfe-preview.zooniverse.org/projects/mschwamb/comet-hunters/classify?env=production (long help content: focus switches to the scrolling content when the help dialog opens.)

https://fix-4006.pfe-preview.zooniverse.org/projects/mschwamb/comet-hunters/classify?env=production (short help content: focus switches to the close button when the dialog opens.)

**Comment by mschwamb** [comment]
https://fix-4006.pfe-preview.zooniverse.org/projects/skymap/supernova-sighting/classify?env=production the focus went to the top x maybe it should go the blue close button to help mobile users if the content is short. Not sure if that's easily doable. 

I like the long content version for Comet Hunters. If you have the two scenarios, then I think that would work well.

**Pull request merged**
