### PR TITLE
Change PromiseRenderer default pending to null

### PR DESCRIPTION
**Pull request by aweiksnar**
- Opt-in to the loading state instead of out
- Prevents jumpiness during loading
- @edpaget, @brian-c You guys cool with this?

### CODE REVIEW

**Comment by DarrenMcRoy** [comment]
HURRAH for anything that fixes the jumpy loading! <3

**Comment by brian-c** [comment]
Isn't some feedback better than a blank page by default? That issue seems pretty specific to the classification page.

**Comment by aweiksnar** [comment]
I've been using it mostly with pending={null} or something custom, and #625 also provides feedback on load state for panoptes requests. 

I'm cool keeping as is if you feel differently.

**Comment by brian-c** [comment]
Ah, I guess the global open-connections thing works well enough.

**Comment by edpaget** [comment]
I'm cool to merge if you're good Brian :shipit:

**Comment by brian-c** [comment]
Yeah, sorry, the reps in my repo are kinda screwy and I can't stash my changes right now so I can't try this out. Please go ahead and merge.

**Pull request merged**
