### PR TITLE
Prepend replies to text instead of having separate

### LINKED ISSUE #888: Select how much of a post you want to quote in a reply
Currently, the only thing you can do as far as replying to a post is to quote the entire post in your reply, in one huge chunk, at the very beginning.

This is cumbersome and limiting, especially if you want to reply to an extremely long post, or if you want to reply to a post in bits and pieces, or if you want to reply to multiple posts.

Most forums manage this by having the "reply" button add code inline to your post, code that you can then manage, crop, break apart, etc. ... any chance we could have our system work similarly?

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #888

### CODE REVIEW

**Comment by DarrenMcRoy** [comment]
Question: does this include an automatic permalink to the quoted comment? Would be good for it to.

**Comment by aweiksnar** [comment]
Not in this PR, I'll put in an issue to add that to the api though. I believe this will solve the problem of people wanting to abridge replies  though.

**Comment by DarrenMcRoy** [comment]
Okay. It's important for navigation purposes. Thanks! :+1:

**Comment by edpaget** [comment]
When I hit submit after editing the quoted text, I see the original text reappear in the box. It saves correctly, but the behaviour is odd.

**Comment by aweiksnar** [comment]
Yeah I'll get that fixed

**Comment by aweiksnar** [comment]
@edpaget That text flash on submit should be resolved now

**Pull request merged**
