### PR TITLE
Add explicit spacing between login bar sub elements

### LINKED ISSUE #1795: Spacing between Sign In/Register links
screen shot 2015-10-19 at 15 23 42

On smaller screens there's no space between the links.

### PR DESCRIPTION
**Pull request by chrissnyder**
Closes #1795

### CODE REVIEW

**Comment by astopy** [comment]
Is this deployed anywhere so I can test it?

**Comment by camallen** [comment]
should be - master is auto deployed.

**Comment by astopy** [comment]
I’m talking about testing it *before* merging it to master, as that will deploy it to zooniverse.org <http://zooniverse.org/>.

**Comment by camallen** [comment]
my bad, thought it was merged. No you have to checkout the code branch and run a local server. it'll run off staging by default. see, https://github.com/zooniverse/Panoptes-Front-End/#development

**Pull request merged**
