### PR TITLE
Acknowledgements Page

### PR DESCRIPTION
**Pull request by BNewing**
Fixes # .

Creation of an Acknowledgements page so that people can more easily find information on how to acknowledge the Zooniverse in their papers. At the moment, the information is at the bottom of the Policies page and takes a little bit of finding.

Describe your changes.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://acknowledgements.pfe-preview.zooniverse.org/

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?

### CODE REVIEW

**Comment by mschwamb** [comment]
I would add a link to the acknowledgements on the quick links on the project builder non-logged in page as well https://www.zooniverse.org/lab

**Comment by mschwamb** [comment]
address #3051

**Comment by amyrebecca** [comment]
noticed that it word-wraps for me in chrome
screen shot 2016-11-08 at 3 51 28 pm

**Comment by mschwamb** [comment]
Could the easy fix be to just cut the padding between navigation links on that bar/header?

**Comment by mschwamb** [comment]
@BNewing also spotted a typo in my text. sorry! 'published accepted' --> 'published'

**Comment by BNewing** [comment]
Added the typo fix and addition of link to the landing page :) 

Would it make sense to add this to a separate Project Builder Documentation area/separate navbar (which doesn't really exist as such at the moment other than buttons on the Project Builder page) rather than putting it in the About section? The About section is getting quite busy and a bit squashed up. That would also mean About could stay focused on more general Zooniverse stuff and the alternate Project Builder Documentation area could focus on stuff related to building projects. But that's just my inexperienced two cents!

**Comment by mschwamb** [comment]
@BNewing I'd keep it on the about page, so it's prominent. It is for project builders,  but also good that people can easily find the grants that funded the development of the platform. I'd confirm with @chrislintott as he might have other ideas.

**Comment by BNewing** [comment]
Given that there is now less on the navbar, do you think the wrapping issue will be okay now @amyrebecca?

Otherwise I think I've now done everything that needs to be done on this. Chris has looked it over and made some amendments which have been added in too :)

**Comment by mschwamb** [comment]
@BNewing  looking great. 

Two things: 

You might want to double check if in Chris' wording edits if  'development of which funded' should be 'development of which was funded' 

and looks like my typo got reintroduced 'publish accepted' --> 'published'

**Comment by BNewing** [comment]
Thanks @mschwamb ! 

The wording was copied and pasted from Chris :) I'm not sure how the typo got back in, I thought I'd changed that! I will remove it and push it back up!

**Comment by mschwamb** [comment]
Thanks @BNewing  'publish accepted ' --> published. Can you make that change? thanks

**Comment by BNewing** [comment]
Oh! I misunderstood what the typo was, sorry! Adding in now.

**Comment by rogerhutchings** [comment]
Just a typo in there, otherwise looks good to me!

**Comment by BNewing** [comment]
Eek addressed the typo @rogerhutchings! Is it now okay to hit the merge button :D? (i get so nervous about that bit)

**Comment by marten** [comment]
looks-good-to-me

**Pull request merged**
