### PR TITLE
Featured projects: welcome banner

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add a featured projects banner to the projects page.
Add some projects page styles.
Add projects page text to the English locale file.

Staging branch URL: https://pr-5650.pfe-preview.zooniverse.org

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by camallen** [comment]
the API will allow more than 1 featured project once https://github.com/zooniverse/Panoptes/pull/3274 is deployed

**Comment by beckyrother** [comment]
This looks great Jim! The last sentence is missing a full stop

**Comment by eatyourgreens** [comment]
Thanks @beckyrother that should be fixed now.

**Comment by beckyrother** [comment]
Thanks Jim! Approved on my end, this looks great 🎉

**Comment by eatyourgreens** [comment]
One other thing to do, I think, is to lift the 'one featured project' restriction from the code for project admin pages.

**Comment by beckyrother** [comment]
I've been going back and forth on the bottom 'scroll down' message. On one hand it feels slightly outdated, but on the other hand this section does take up quite a large space so it might be useful for smaller screens. 
Thoughts?

**Comment by wgranger** [comment]
I've looked at this PR on multiple browsers and have also added several projects to the `featuredProjects` array and saw it renders the cards neatly. 

@beckyrother I don't have much of an opinion on the "scroll down" message as it is fairly innocuous. However, the only other place where we have a sort of "scroll down" messaging is under the user ribbon on the home page, and it is a down arrow.

**Comment by beckyrother** [comment]
Happy to keep it for now, don't want to be a blocker. Thanks Will!

**Pull request merged**
