### PR TITLE
Add delete button to collection subject viewer

### LINKED ISSUE #830: No way to remove a subject from a collection
lower on the queue - I don't see an obvious way of removing a subject from a collection once it's added

### PR DESCRIPTION
**Pull request by chrissnyder**
- Closes #830

### CODE REVIEW

**Comment by edpaget** [comment]
Is it possible to check if the user is allowed to delete subjects from a collection before showing the button?

**Comment by chrissnyder** [comment]
Sure. Does the owners link contain collaborators as well, or do I need to stick to the roles link?

**Comment by camallen** [comment]
Owners link will just contain the owner. However you probably want to use the collection roles since owners and collaborators can delete collections.

**Comment by chrissnyder** [comment]
@edpaget Should be good now.

**Comment by edpaget** [comment]
:shipit:

**Pull request merged**
