### PR TITLE
Update privacy policy

### PR DESCRIPTION
**Pull request by lcjohnso**
REQUIRED REVIEW & CONFIRMATION BY C. Lintott

Staging branch URL: https://pr-6425.pfe-preview.zooniverse.org

Minor changes and updates to Zooniverse privacy statement:
- Edit names of relevant regulations
- Edit cloud provider and relevant statement regarding data transfer compliance
- Edit data controller and methods of contact

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by chrislintott** [comment]
I suggest swapping round the sentences in the last paragraph so that it reads: 

For information and questions regarding this policy and Zooniverse data, please contact the Zooniverse team at [contact@zooniverse.org](mailto:contact@zooniverse.org).

The Data Controller is the University of Oxford (Chancellor, Masters and Scholars of the University of Oxford). 
Information on your rights, including the right of access, in relation to your personal data are explained here: https://compliance.admin.ox.ac.uk/individual-rights. If you want to exercise any of the rights or are dissatisfied with the way we have used your information, you should contact the University’s Information Compliance Team at [data.protection@admin.ox.ac.uk](mailto:data.protection@admin.ox.ac.uk).

I think that's clearer.

**Comment by lcjohnso** [comment]
Note: I've removed `privacy` section from all non-`en` locale files.  Only the `it` and `es` locales had translated content; default behavior is to use `en` content by default if missing in non-`en` locale, so no change in resulting behavior.

Strong recommendation that we do not translate user agreement & privacy doc in English only -- best to keep this important doc in `en` only for legal clarity / no versioning issues. Otherwise, importance of checking translation accuracy is critical if content is translated in the future.

**Comment by lcjohnso** [comment]
@goplayoutside3

To test for review:
- Check that new text renders on https://pr-6425.pfe-preview.zooniverse.org/privacy (vs. [current version](https://www.zooniverse.org/privacy))
- Check that text defaults to `en` version for non-`en` languages: check https://pr-6425.pfe-preview.zooniverse.org/privacy?language=es renders with same content as default `en` version.
- Anything else from a technical perspective? Can you confirm there's no need to touch Lokalise (privacy content is not yet hosted there, only within PFE locale files)?

**Review by goplayoutside3 — APPROVED** [review]
Looks good! Yes, can confirm that no updates to Lokalise are needed.

**Pull request merged**
