### PR TITLE
Update mock data file

### PR DESCRIPTION
**Pull request by simoneduca**
Describe your changes.
Add user and preferences

### CODE REVIEW

**Comment by simoneduca** [comment]
Sorry, my bad. I changed the code order to be alphabetical, to make it easier to look for the definitions. Fix coming.

**Comment by eatyourgreens** [comment]
Can you please test changes before committing and pushing?

**Comment by eatyourgreens** [comment]
One small question about `activity_count`. Otherwise, looks good. However, I don't think `mockData.user` is used in the [dev classifier](/zooniverse/Panoptes-Front-End/blob/master/app/pages/dev-classifier/index.cjsx#L62-L64).

**Comment by simoneduca** [comment]
You're right. I was thinking of mock-data as a general purpose file, not restricted to dev-classifier. If that's not its intended purpose, perhaps I should just remove `user`.

**Comment by eatyourgreens** [comment]
`mock-data` is the config script for the dev classifier. It sets up a mock project, workflow, subject and classification for testing out the classification tools.

If you're declaring variables to use in tests, [declare those with the test functions themselves](/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/home/home-workflow-buttons.spec.js#L26-L28).

**Comment by simoneduca** [comment]
Makes sense. I'll remove the polluting `user` then.

**Comment by eatyourgreens** [comment]
Are the new preferences used by the dev classifier? It seemed to be working without them, but I haven't looked at it for a while so maybe I'm missing something.

**Comment by simoneduca** [comment]
Not really https://github.com/zooniverse/Panoptes-Front-End/blob/5bbd29f44fa354a735f0a9edcb08dc4ca26de00c/app/pages/dev-classifier/index.cjsx#L64
Feels like this PR wasn't really necessary. I think I'll jut close it.

**Pull request closed without merging**
