### PR TITLE
Resources page

### PR DESCRIPTION
**Pull request by srallen**
Staging branch URL: https://resources-page.pfe-preview.zooniverse.org/about/resources

This adds the resources page! @beckyrother @snblickhan and @hrspiers 

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by snblickhan** [comment]
Before we merge this, I wonder if we could amend the 2nd bullet point in the Press section? There was a ? on the doc about it -- I'm hesitant to commit to a structured definition without running it by the PIs at least. I amended it when I wrote the press bit for Acknowledgements, so maybe we could use that text instead?

**Comment by beckyrother** [comment]
@snblickhan of course, maybe the updated text can be posted here on the PR?

**Comment by snblickhan** [comment]
I wonder if we just don't need any press information here, since it's already in the Acknowledgements section (or will be as soon as it's merged)?

**Comment by beckyrother** [comment]
I'd rather we have it in multiple locations just to cover our bases. Maybe link to the Acknowledgements page just in case?

**Comment by snblickhan** [comment]
Smort. Let's do that.

**Pull request merged**
