### PR TITLE
Link to subjects when in project and set as focus

### LINKED ISSUE #916: Adding a link to the subject pages from the notes discussions
The discussion page is keeping an index of all discussions started from clicking talk in the interface. Currently in the notes threads you only see that conversation, so there's no way to know there are other discussions. It would be helpful if there's a way to get back to the subjects page - perhaps making the title of the subject into a link

The only way currently to see the subjects page is to manually type it
Being able to access the subject page from a link from a discussion  would allow science teams to quickly see all the discussions going on about a subject

screen shot 2015-07-01 at 10 45 56 am

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #916
- Right now only from projects ~ #1020
- Can be seen on demo at
  - `#/projects/alex-panoptes/test-proj/talk/42/51`
  - `#/talk/20/82`
- I've got another branch up called `link-to-subjects-in-discussion-titles` where the links happen in titles, but I think this is a bit cleaner

### CODE REVIEW

**Comment by DarrenMcRoy** [comment]
Does this add a link from a Notes thread, as well as from anywhere else that a subject is linked/featured?

**Comment by aweiksnar** [comment]
It does this anywhere a subject is linked/featured in a project. Link is pointed to subject page
screen shot

**Comment by DarrenMcRoy** [comment]
:+1:

**Comment by chrissnyder** [comment]
So it's clear, `#/talk/20/82` should or shouldn't have a link? http://i.imgur.com/cadg4OX.png

**Comment by aweiksnar** [comment]
@chrissnyder That shouldn't have a link, goes back to the question of not assuming that a subject belongs to a specific project since they can be in multiple

**Comment by DarrenMcRoy** [comment]
My proposed answer to that is to always link to the project where the subject was initially uploaded.

**Pull request merged**
