### PR TITLE
Changed galaxy-builder webgl error message to be more specific and helpful

### PR DESCRIPTION
**Pull request by tingard**
Addresses concerns raised in  #4550 

Changed error message from 
> We’re afraid your browser doesn’t support the WebGL we need to render galaxies. You can comment on photos (the second image) in Talk, but won’t be able to classify.

To
> Sorry, this project requires features which are not supported by your device. Please try again on a desktop computer, and let us know in talk if you're still having problems. You can comment on photos (the second image) in Talk, but please do not classify!

### CODE REVIEW

**Comment by tingard** [comment]
Let me just make sure this works before merging

**Comment by tingard** [comment]
Okay we're good

**Comment by eatyourgreens** [comment]
Minor point but “your device” may well be a desktop computer. One of the people reporting problems on Talk gave Windows XP as their OS.

**Comment by tingard** [comment]
@astopy as one of the messages is being called during the `super` function (inside `setModel`, which is called by the constructor of the parent) , I can't define a constant on `this` as I'd like. I could pass it as a param to super but that seems messy. Open to suggestions!

Good point re. device assumptions, maybe "try again on a different computer" instead?

**Comment by astopy** [comment]
Yeah that sounds good.

**Pull request merged**
