### PR TITLE
Towards user as prop everywhere

### PR DESCRIPTION
**Pull request by chrissnyder**
Started a new PR because the last one was horribly out of sync with master.

- Same comments as https://github.com/zooniverse/Panoptes-Front-End/pull/998
- This PR should be close to ready. Needs a couple pairs of eyes on it though.
- Would be great to not have it for awhile, as most changes result in merge conflicts.

Available for viewing at http://demo.zooniverse.org/panoptes-front-end/user-as-prop/

### CODE REVIEW

**Comment by brian-c** [comment]
- Lab index doesn't display landing page when signed out.
- On lab/collaborators: "ReferenceError: projectOwner is not defined"

**Comment by parrish** [comment]
A few quirks, probably connected

Without a login:
  1. log out
  2. [visit the inbox](http://demo.zooniverse.org/panoptes-front-end/user-as-prop/#/inbox)
  3. doesn't require login
  4. fires API requests that are 4xx responses and doesn't report error messages


Trying to login:
  1. [visit the inbox](http://demo.zooniverse.org/panoptes-front-end/user-as-prop/#/inbox)
  2. log in
  3. `this.props.user is null`


Logging out and back in:
  1. log in
  2. [visit the inbox](http://demo.zooniverse.org/panoptes-front-end/user-as-prop/#/inbox)
  3. log out
  4. Displays "Please sign in to view your inbox," but attempts to request user conversations
  5. log in
  6. Continues to display "Please sign in to view your inbox," and doesn't request user conversations

**Comment by chrissnyder** [comment]
Bugs fixed, redeployed to demo.

**Comment by parrish** [comment]
:ok_hand:

**Comment by brian-c** [comment]
Looks good to me.

**Comment by edpaget** [comment]
:fire: :100:

**Comment by aweiksnar** [comment]
:sunny: :bow: :sunny: 
Super PR

**Comment by parrish** [comment]
:emoji: :emoji: :emoji:

Think we're good to merge this?

**Comment by aweiksnar** [comment]
Yeah, I'll merge it in

**Pull request merged**
