### PR TITLE
Optimize field guide

### PR DESCRIPTION
**Pull request by simensta**
Addresses the field guide portion of #3492. 

**Describe your changes.**
I added the parameter `include: 'attached_images'` when requesting the field guide resource. This eliminates the need to fetch the resources for the field guide icons (i.e., attached_images) in a later request. 

Also, I added the `displayName` property to the PotentialFieldGuide, FieldGuide, and ProjectPage.

# Review Checklist
- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by simensta** [comment]
Good catch. After adding more than ~20 articles to a field guide the icon images fail to load. Also related, deleting an article does not cause the associated icon id to be deleted from `link.attached_images.ids` for the field guide.

**Comment by srallen** [comment]
The Gravity Spy field guide has 20 items, so I would think it would work, but it sounds like we're hitting a page size issue. With this in mind, we might not be able to use the include in the original query if we need to deal with pagination. I'm not sure about the links, but that sounds like a bug or maybe it's done in a sidekiq worker so it's not immediate.

**Comment by srallen** [comment]
I am wondering if the best solution for this is not to make it an included resource request, but request for the field guide in the classifier like the tutorial and chain the get request for the included media with an increased page size, then store it in the classifier state.

**Comment by simensta** [comment]
Good point. In addition, since the field guide now only appears on the '/classify' page, it makes sense for the field guide request and component to move to the classifier. I'll try that approach.

**Comment by simensta** [comment]
Closing in favor of #3574.

**Pull request closed without merging**
