### PR TITLE
Allow drawing inside freehand lines

### PR DESCRIPTION
**Pull request by rogerhutchings**
Sets the `pointerEvents` prop to stop clicks inside a shape triggering click the select event, allowing users to draw inside.

Test project: https://freehand-fix.pfe-preview.zooniverse.org/projects/rogerhutchings/etch-a-cell/classify

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://freehand-fix.pfe-preview.zooniverse.org
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by rogerhutchings** [comment]
How to test:

1. Go to https://www.zooniverse.org/projects/h-spiers/etch-a-cell/classify
1. Draw a circle
1. Try drawing another circle inside
1. Confirm it fails
1. Go to https://freehand-fix.pfe-preview.zooniverse.org/projects/rogerhutchings/etch-a-cell/classify
1. Draw a circle
1. Try drawing another circle inside
1. It should work

**Comment by eatyourgreens** [comment]
Drawing inside a shape selects the previous drawing for me. Chrome OSX.

I can draw overlapping shapes if I start the drawing outside the existing shape, but that works with the existing code so I'm not seeing any difference.

**Comment by rogerhutchings** [comment]
Weird. I've just tried it and it works...

untitled

**Comment by eatyourgreens** [comment]
The tool I'm looking at has a red line. I think we're looking at different workflows 😳

**Comment by rogerhutchings** [comment]
Aha - go to https://freehand-fix.pfe-preview.zooniverse.org/projects/rogerhutchings/etch-a-cell and choose the Freehand Line workflow

**Comment by eatyourgreens** [comment]
Works for me but I'm finding it hard to select the delete button. I keep accidentally creating new shapes when I'm trying to delete an existing shape.

**Comment by rogerhutchings** [comment]
Okay, I've reset pointer events on the delete button (which has fixed it, I think) and restaged the branch.

**Comment by eatyourgreens** [comment]
Looks good to me.

**Comment by rogerhutchings** [comment]
Thanks @eatyourgreens

**Pull request merged**
