### PR TITLE
Allow the Zoo Logo title to be overridden

### PR DESCRIPTION
**Pull request by eatyourgreens**
Set the title to 'Show navigation' for the nav toggle button.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
That's right. When you use an image as the content for a control or a link, the image alt text is applied as the control's label. So the advice for images in links and buttons is to use alt text which describes the purpose of the link or the button, rather than the image itself.

**Comment by brian-c** [comment]
Huh, I did not know that! Still, I'd make that change only when the logo toggles the site header.

**Comment by srallen** [comment]
Yeah, the logo const is being used both in the link and button, but I agree the title should only apply to the button case.

**Comment by eatyourgreens** [comment]
My bad, I'll fix the link.

At the moment, the home link text is picked up on zooniverse.org as "Zooniverse logo". "Zooniverse home" might be clearer labelling but, yeah, it shouldn't be "Show navigation."

**Comment by eatyourgreens** [comment]
Should be fixed now. I get this as the list of form controls on a project page
image
and this as the list of links on the home page
image

**Pull request merged**
