### PR TITLE
Add Researcher Quote to Project Lab

### PR DESCRIPTION
**Pull request by wgranger**
Describe your changes.
This adds the Researcher Quote field to the project lab page. It also allows for a primary researcher to be selected, whose avatar will appear on the project landing page. This should probably be merged concurrently with #3368.

https://researcher-quote.pfe-preview.zooniverse.org/

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [X] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
One minor comment about API performance, otherwise this looks good to me.

**Comment by eatyourgreens** [comment]
Sorry, I missed this yesterday. React is also warning about invalid element nesting in the DOM: `<div> cannot appear as a descendant of <p>. See EditProjectDetails > p > ... > Select > Option > div`

Trying this out on staging, I can choose a researcher for projects that I'm a collaborator on but the select options are empty on a project where I'm the owner.

**Comment by eatyourgreens** [comment]
👍 are we good to merge this?

**Comment by wgranger** [comment]
This shouldn't be merged until #3368 is ready to go and merge. You won't be able to see any changes made in this PR with the researcher quote until it's available on the new project landing page.

**Pull request merged**
