### PR TITLE
FEM Lab: build fem-version of multi-image subject options

### PR DESCRIPTION
**Pull request by goplayoutside3**
Staging branch URL: https://pr-6418.pfe-preview.zooniverse.org

Related Slack Convo: https://zooniverse.slack.com/archives/C06LHUC6R/p1674576134599589
Merging this PR will be followed up with: https://github.com/zooniverse/front-end-monorepo/pull/4181

I created a multi-image-subject-options-editor specifically for fem-lab to add autoplay to flipbook projects. This component only includes features that are already built into FEM (flipbook for non-transcription multi-image subjects, play iterations, and the upcoming addition of autoplay). This component excludes "separate frames view first" because that feature is not built in FEM yet.

You can test this branch by loading a project with `femLab=true` in the url and viewing the Multi-Image Options section. I recommend my test project locally: [https://local.zooniverse.org:3735/lab/19645/workflows/22532?femLab=true&env=production](https://local.zooniverse.org:3735/lab/19645/workflows/22532?femLab=true&env=production).

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by goplayoutside3** [comment]
@seanmiller26 I'm going to tag you as reviewer as well. Here's a link to an example project's lab on this PR branch: https://pr-6418.pfe-preview.zooniverse.org/lab/19645/workflows/22532?femLab=true

A screenshot of the multi-image options section edited in this PR for FEM projects. Please let me know if any change in the label text or arrangement is needed: 
Screenshot 2023-02-10 at 11 54 22 AM

**Review by seanmiller26 — APPROVED** [review]
LGTM!

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Affects: Project Builder -> Workflow Editor (FEM Lab ver)

This PR re-introduces the "Multi Image Viewer" (MIV) section to FEM Lab's Workflow Editor, but with settings configured for the new FEM Subject Viewer.

- Behaviour change: MIV section was previously deprecated, now it's enabled
- Functionality:
  - User can change Play Iteration options via dropdown to Infinite / 3 _(implicit default)_ / 5
  - User can toggle Autoplay on/off (default: off)
  - User can toggle Allow Separate Frames View on/off (default: off)

image

### Dev Notes / Recommendations

I have some notes & recommendations, but _none of them are blockers._

Noted differences between PFE Lab ver and FEM Lab ver of MIV section:
- Option to choose between Show Flipbook/Show Separate Frames deferred to a later update.
- Clone Marks options removed. (Note to self: check FEM's default behaviour on this)
- Flipbook Play Iterations now limited to three preset options instead of an open number input.
  - 🤔💭 [minor][curiosity only] This might be a question for Sean, but why use a dropdown with limited options instead of a number input? 

image

Code recommendations:
- [ ] [minor] The _fem-multi-image-subject-options-editor.jsx_ file could be moved into a new _lab-fem/components_ folder. I suspect we'll have more components like this in the future.
- [x] [minor] for the commented-out section of the code that says _"Un-comment when ready to implement separate-frames-view-first in FEM",_ it'd be great we also include a link to the corresponding FEM Issue (if there's one).

UI recommendations:
- [x] [medium] ⭐ the PFE Lab's version has a very simple line of text that explains what the MIV section does: _"Choose how to display multiple images"_
  - I think that this explanatory text would do a lot to explain to new Project Owners _when_ these settings would apply, so I'd recommend putting this back in.

Other notes:
- [noActionsToBeTaken][i_just_want_to_complain] I am _absolutely annoyed_ that the config for play iterations is done in camelCase (`configuration.playIterations`) while the others are in snake_case (`configuration.flipbook_autoplay`) 

Note: for UI/UX recommendations, if Sean has already given notes that contradict any of my own notes, I'd always defer to his opinion first.

### Testing

Tested on macOS + Chrome on localhost

Testing steps:
- Open a test WF in FEM Lab mode: https://local.zooniverse.org:3735/lab/1982/workflows/3711?femLab=true
- Toggle/change various values in the MIV section.
- Reload the page to confirm changes
- Observe changes in Workflow configuration (view WF resource being received from Panoptes via Chrome's Network tab)
- Expectations:
  - users should be able to change all values via the UI
  - changes to the UI should reflect on the WF resource sent to Panoptes (i.e. saved to database)
  - WF's MIV values should show correctly on the MIV section when page loads
- Additional test: compare with PFE Lab version

Tests all look good.

### Status

LGTM! This is good to merge as is, but please consider the recommendations above 👆 before doing so.

**Comment by eatyourgreens** [comment]
>[noActionsToBeTaken][i_just_want_to_complain] I am absolutely annoyed that the config for play iterations is done in camelCase (`configuration.playIterations`) while the others are in snake_case (`configuration.flipbook_autoplay`)

Snake case should be used for anything that's saved to Panoptes, just for consistency with Rails conventions.

**Comment by seanmiller26** [comment]
@shaunanoordin  It was explained to me that we (the project reviewers) give the options of 3, 5, or infinite playbacks. Maybe this isn't the way it happens? I am trying to 'automate' the project builder wherever possible so we don't need as much hands-on time.

Are there any cases where another playback count would be useful?

Also +1 to adding the explanatory text blurb back in.

Screen Shot 2023-02-15 at 10 37 58 AM

**Comment by goplayoutside3** [comment]
> This is good to merge as is, but please consider the recommendations above 👆 before doing so.

Done! I decided to remove the commented code for `mode` because a well documented FEM issue doesn't exist yet. There's still a lot of decisions to be made about how we want FEM to handle separate frames view options, and that `mode` code is still available for reference in PFE's /lab.

> [curiosity only] This might be a question for Sean, but why use a dropdown with limited options instead of a number input?

An additional place where @seanmiller26 recommended that a dropdown with three choices (3, 5, infinite) simplifies the choice for research teams: https://zooniverse.slack.com/archives/C06LHUC6R/p1674586529556819?thread_ts=1674576134.599589&cid=C06LHUC6R

> [noActionsToBeTaken][i_just_want_to_complain] I am absolutely annoyed that the config for play iterations is done in camelCase (configuration.playIterations) while the others are in snake_case (configuration.flipbook_autoplay)

Agreed 🤷‍♀️

**Pull request merged**
