### PR TITLE
Facelift header

### PR DESCRIPTION
**Pull request by eatyourgreens**
Staging branch URL: https://facelift-header.pfe-preview.zooniverse.org

Redo of #4218, hopefully without unexpected upgrades/installs of unrelated npm modules.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by srallen** [comment]
Checking out the lock file from the master branch doesn't get the new packages this branch introduces.

**Comment by srallen** [comment]
Just confirmed the expected packages are in the lock json data. Github search wasn't initially coming up with it.

**Comment by eatyourgreens** [comment]
Seems to be working on https://facelift-header.pfe-preview.zooniverse.org/projects/brooke/i-fancy-cats?facelift=true

**Comment by srallen** [comment]
Tabbing on NfN looks ok: https://facelift-header.pfe-preview.zooniverse.org/projects/zooniverse/notes-from-nature/classify?reload=1&workflow=5180&env=production&facelift=true

This seems good to approve and merge on Monday?

**Comment by eatyourgreens** [comment]
Sounds good to me. 👌

**Comment by eatyourgreens** [comment]
I'm not sure why I had to install `request` to get this to work, but it seems to be required as a peer dependency somewhere in `jsdom`'s dependencies.

**Comment by eatyourgreens** [comment]
@srallen I had some problems with `request` not being installed any more after I rebased to upgrade enzyme, but this should be good to go now.

**Comment by srallen** [comment]
@eatyourgreens hm, that seems odd. I'll take a look.

**Comment by srallen** [comment]
@eatyourgreens it's not explicitly listed as a peer dependency, but I read over some of their open issues and it looks like it's being used for supporting fetch right now. 🤷‍♀️ Installing it gets the latest version to work, so let's keep this in mind because from the thread I read it sounds like they might remove request later.

**Pull request merged**
