### PR TITLE
Add clear button to user profile media

### LINKED ISSUE #1903: Add ability to remove profile pic
-- in addition to being able to upload a new/different one, have the ability to just remove it.

### PR DESCRIPTION
**Pull request by brian-c**
@aweiksnar mind giving this a shot? It works on a new account I just created, but on my usual dev account deleting my avatar _appears_ to replace it with an older avatar resource. @camallen any idea off hand why that might be happening?

Closes #1903.

### CODE REVIEW

**Comment by aweiksnar** [comment]
This is working great for me - Tested pretty thoroughly on a few of my dev accounts and my ouroboros-created one and all were clearing the avatar when needed.

The only thing I noticed is dragging/dropping an avatar over a pre-existing one and then clicking clear deletes it in the api but doesn't clear the image-selector afterwards

**Comment by camallen** [comment]
@brian-c nope, PM me the login of the account that's problematic.

**Comment by brian-c** [comment]
Thanks @aweiksnar, fixed by removing the local image state from the ImageSelector component. It now relies on one to be passed down as `src` instead of `defaultValue`. That way there's nothing to get out of sync.

**Comment by aweiksnar** [comment]
Awesome yeah that did it :shipit:

**Pull request merged**
