### PR TITLE
Add deleteIfOutOfBounds to markings renderer

### LINKED ISSUE #4579: Out-of-bounds marks can be submitted in a completed classification
## Expected behavior
Drawing tasks that lie outside the subject image area should be automatically detected and deleted.

## Current behavior
Marks that are created by a mouseup/touchend event outside the subject image are deleted. However, if the mouseup/touchend event that creates the mark is inside the subject, the mark is not deleted, even if its final (x,y) coordinates lie outside the subject area.

## Steps to replicate
Draw a point and drag it quickly upwards to fling it outside the subject. Lift your finger (or lift the mouse button) while still inside the subject. It's possible for the subject to end up outside the image area, but the mark is not deleted and remains in the submitted classification.

## Additional information

- **Operating system:** n/a
- **Browser:** n/a

### PR DESCRIPTION
**Pull request by eatyourgreens**
Store a list of current marking tools in the markings renderer. Check `deleteIfOutOfBounds` for each tool on every update and delete any tools that are outside the subject.

The subject bounds are calculated from the SVG image, for image subjects, or from the SVG scaled size rectangle otherwise. 

Image bounds are calculated at runtime, rather than calculated once and cached, to avoid bugs where a mark's position is compared with stale image bounds after a reset or resize.

This is a redo of #4580, but with a change to the bounds calculation in order to avoid regressing #4607. The changes here should fix the original bug (touch events create accidental marks that can't be removed) without deleting marks that are outside the SVG viewbox when an image is zoomed. Marks that lie outside the bounds of the zoomed image should be removed automatically on the next render.

https://github.com/zooniverse/Panoptes-Front-End/assets/59547/2caeb59e-d807-40dc-b0e9-1cb723fc6542

Staging branch URL: https://pr-6889.pfe-preview.zooniverse.org/projects/aprajita/space-warps-des-vision-transformer

Fixes #4579.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Another bug that came up while testing this: The `containerRect` prop caches a stale copy of the image bounds, which doesn't update when you press the Reset button. Pressing Reset here deletes all placed marks, even ones that are still inside the subject image, because it compares their positions with the previous rendered image.


Uploading Screen Recording 2023-10-23 at 11.04.09.mov…

**Comment by shaunanoordin** [comment]
Beep boop, looking at this now!

**Comment by eatyourgreens** [comment]
Here’s a screen recording from my phone, showing that marks from accidental swipes are detected and deleted. 


https://github.com/zooniverse/Panoptes-Front-End/assets/59547/269ec3d0-8610-4d5e-88ac-1ec128c9ed3a

**Review by shaunanoordin — COMMENTED** [review]
## PR Review

This PR improves on the functionality of ensuring that _drawing marks_ (from drawing tools) that are created (or rather, _created, and then moved to)_ outside of _the bounds of the Subject image_ are deleted.

In general, the code read makes sense. The major updates include...

1. changing `const clientRect = this.sizeRect && this.sizeRect.getBoundingClientRect();` to `const subjectNode = this.subjectImage || this.sizeRect; const clientRect = subjectNode?.getBoundingClientRect();`
2. calling `deleteIfOutOfBounds()` on MarkingsRenderer.componentDidUpdate()

So (1) means our bounds is now defined by the subject image if available (falling back to the old sizeRect otherwise), and (2) running the delete code more often. In theory, cool. 👍

Unfortunately, additional testing has found a critical issue ❗ that need to be debugged. (Plus some small quirks that are interesting to note.)

### Problems Detected

❗ **Critical Issue 1:** when I create a mark _and immediately move it out of bounds_ (see 🍎 below), **all existing marks will be deleted.**

Error message in dev console, as soon drag action exceeds bounds of image:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'tool')
at ReactClassComponent.handleInitDrag (marking-initializer.cjsx:74:1)
at HTMLDivElement.handleDrag (draggable.jsx:69:1)
// will trigger multiple times, for as long as I continue the "drag" action.
```
followed by:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'tool')
at ReactClassComponent.handleInitRelease (marking-initializer.cjsx:88:1)
at HTMLDivElement.handleDrag (draggable.jsx:69:1)
// triggers when I release the pointer button/end the drag action
```

Video:
- at 0:04 I create a Point mark, as a baseline.
- at 0:05 I make second mark, release the pointer, _then_ drag it out of bounds (🍏). The second mark is deleted. ✔️ 
- This is repeated at 00:10 (🍏). The third mark is deleted ✔️ 
- At 00:12, I create a fourth mark _and immediately (without releasing the pointer down action that created the mark) moved it out of bounds. (🍎) This causes the first baseline mark to also disappear. ❌ 

https://github.com/zooniverse/Panoptes-Front-End/assets/13952701/7d6acc8f-8293-4ad6-bb12-9de5fe356e6b

**Quirk 2:** (non-blocking) when I create a mark, _and then_ drag to move it out of bounds (see 🍏 below), I see the error in the dev console:
```
Error: Unable to find node on an unmounted component.
at findDOMNode, at deleteIfOutOfBounds, at HTMLDivElement.handleEnd (draggable.jsx:82:1)
```

This is fine in the sense that nothing's crashing, but it does add some noise to the dev console... but on the other hand I'm not sure if there's a more elegant way of handling `ReactDOM.findDOMNode`'s feisty failure mode. (No return null, just straight up error, wow.) It does explain why this PR adds that try-catch block into deleteIfOutOfBounds though.

Video:
- Mix of different "move mark out of bounds" actions. Note the different flavours of error messages.
- 🍏 at 0:04 and 0:06.
- 🍎 at 0:09, 0:11, and onwards

https://github.com/zooniverse/Panoptes-Front-End/assets/13952701/ade298af-9b00-429a-949f-563775db5e88

**Quirk 3:** (minor) (niche) (non-blocking) if I rotate an image to 30º or 45º or any non-90º rotation I can move a mark outside the visible subject image. (because a 1000x1000 image rotated 45º will have an effective bounding box of 1414x1414)

I genuinely can't think of a solution for this, but it's non-breaking and ONLY applies to project with the `SubjectViewer-freeRotation` experimental tool. [(example)](https://local.zooniverse.org:3735/projects/darkeshard/test-project-2022/classify?reload=0&workflow=3596&demo=true) So I'm just marking this quirk with a stamp of "eh, whatever".

### Testing

Tested on localhost with macOS + Chrome, on a variety of test projects and production projects (with demo mode),

Note: set `webpack.dev.js`'s _config.devserver.client.overlay_ to _false,_ or else certain drag interactions will be interrupted by the error overlay.

Testing conditions:
- Baseline: we're testing on _PFE workflows_ with _single image_ Subjects with a Drawing Task (with, e.g., a simple Point tool). [(example 1)](https://local.zooniverse.org:3735/projects/darkeshard/test-project-2022/classify?reload=0&workflow=3596&demo=true) [(example 🐧)](https://local.zooniverse.org:3735/projects/penguintom79/penguin-watch/classify?env=production&demo=true)
  - Variation 1: multi-image Subjects displayed in a single frame (no current example)
  - Variation 2: multi-image Subjects displayed in multi frames (no current example)
  - Variation 3: multi-image Subjects displayed in multi frames, with drawing marks cloned across each frame [(example)](https://local.zooniverse.org:3735/projects/aprajita/space-warps-des-vision-transformer/classify?env=production&demo=true)

Expected functionality:
- When I create a Point mark on the Subject image (within bounds), it should remain there.
  - Specifically: click (pointer down, pointer up) on the image, while in annotate mode, while the drawing task + tool is selected.
- When I try to create a Point mark outside the Subject image, it should fail. (i.e. clicking does nothing.)
- When I move a Point mark outside the Subject image, that mark should be deleted.
  - Method 1 🍏 : click to create a mark on the image. Drag that (or any other existing) mark out of bounds.
  - Method 2 🍎 : pointer down on Subject image to create a new mark, **and without lifting the pointer button,** move cursor to move the mark out of bounds.
- When using the Rectangle tool (or Circle, Ellipse, etc), then the mark is out of bounds only if the ENTIRE mark('s bounding box) is out of bounds (i.e. no part of the drawn shape still touches the image.)  
- The above should all be true even when the image has been panned or zoomed.
- The above should all be true even when the (esp. rectangular) image has been rotated 90º, 180º, and 270º. 
  - (non-90º rotation is a special condition)
- Valid marks should never be automatically deleted.

### Status

I was going to write an Analysis section for this, but that would have consisted entirely of a shrug 🤷 emoji. I got as far as trying to trace that "onDestroy()" being triggered, but the multiple error messages kept flooding my dev console with noise, so I need to think of a better debug process tomorrow.

For now, this PR is being held back by Critical Issue 1, _but only that issue._ All other tests seem fine!

**Comment by shaunanoordin** [comment]
Here's an additional video of Critical Issue 1 triggering.
- This time, we're looking at 4-image multi-frame subjects with cloned marks.
- First 🍎 instance occurs at 00:12 but I have no idea why the first mark wasn't deleted while the other 5 were. _And there were no error messages?_
- Second 🍎 instance at 00:14, third 🍎 instance at 00:18, fourth 🍎 at 00:21. Error messages occurs as previously documented.

https://github.com/zooniverse/Panoptes-Front-End/assets/13952701/ee7de1dd-4c3c-4641-a2ce-f16a1dce457f

**Comment by eatyourgreens** [comment]
Here’s a couple more recordings of Space Warps on my phone. 

- main branch. Marks are added to the classification and can’t be deleted (#4579.)
- this branch. Swiping can remove all drawn marks (not ideal for Penguin Watch!)

Uploading RPReplay_Final1698204938.mp4…

**Comment by eatyourgreens** [comment]
@shaunanoordin thansk for finding that bug. I've fixed the errors in the `MarkingInitializer`, where it continues to try to rerender marks after they've been deleted. I've also converted `deleteIfOutOfBounds` from CoffeeScript to JavaScript. However, that bug remains.

**Comment by eatyourgreens** [comment]
@shaunanoordin I think that bug is fixed now. `MarkingInitializer` was set to delete the last item in the drawing annotation on touch end, but of course that can change now if the mark is deleted while being dragged.

Here's Penguin Watch now, with multiple marks in place.

https://github.com/zooniverse/Panoptes-Front-End/assets/59547/50d2374c-b900-4a6a-8954-5e6cfc1b2dff

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Follows [earlier review](https://github.com/zooniverse/Panoptes-Front-End/pull/6889#pullrequestreview-1696176208)

Looking good! I've re-run the tests I've done earlier, and could not find any problems. The critical issue in particular has been resolved - nice work solving that, Jim! ✅ 

Additional notes since last review:
- deleteIfOutOfBounds() has been decaffeinated
- MarkingInitializer component has been updated with more safeties (i.e. prevent operations from being done on missing/unmounted marks)

LGTM! 👍

**Pull request merged**
