### PR TITLE
add owner display name to collection search

### PR DESCRIPTION
**Pull request by camallen**
Staging branch URL: https://pr-5947.pfe-preview.zooniverse.org

Fixes https://www.zooniverse.org/talk/17/1990968?comment=3246122

This PR disambiguates the collection names by providing the owner display name as well. 

Possible improvements to this PR: 
1. Since the data is already available for the component, i was thinking this could be a checkbox behaviour toggle as well as most of the time this will be redundant information (as folks normally don't collaborate on collections). 
2. Alternatively - this could be automated and only add the owner suffix when the logged in user and the collection owner differ (we have this information). 

I'd be happy to iterate on this solution, thoughts?

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Looks good to me. I agree that it might be better if the owner's name isn't shown for my own collections. We could ask a few Gravity spy volunteers to try this branch and get their opinions?

**Review by eatyourgreens — COMMENTED** [review]
Forgot to add my original comment as a review. After thinking about this a bit more, I'd be in favour of changing this so that the name is only added when the collection isn't yours. That way, the UX won't change for the majority of our users, but should be improved for cooperative collections on Gravity Spy.

**Comment by camallen** [comment]
> Forgot to add my original comment as a review. After thinking about this a bit more, I'd be in favour of changing this so that the name is only added when the collection isn't yours. That way, the UX won't change for the majority of our users, but should be improved for cooperative collections on Gravity Spy.

ok - I think that's better UX for the requested use case 👍🏼. However how do i get the logged in user state in this component? Is it globally available by a context in PFE? Pointers welcome 🙏🏼

**Comment by eatyourgreens** [comment]
Good question. I'll take a look. I think PFE uses global context to store the logged-in user.

**Comment by eatyourgreens** [comment]
The user is passed in to parent components as a prop:
https://github.com/zooniverse/Panoptes-Front-End/blob/819875b286fbda8398d103b788766905cc070ab2/app/collections/show-list.cjsx#L48-L50

**Review by eatyourgreens — APPROVED** [review]
Looks good to me. I don't have any shared collections but the code changes look good.

**Comment by camallen** [comment]
> Looks good to me. I don't have any shared collections but the code changes look good.

I tested on staging API and it works well

**Pull request merged**
