### PR TITLE
Validate project before allowing beta application

### PR DESCRIPTION
**Pull request by rogerhutchings**
Now requires the following statements to be true about a project before an owner can apply for beta:

- Must have an active workflow
- Must have all about pages filled in (doesn't check very hard, just to see how many pages are attached to a project; you can circumvent this by entering some content and deleting it again :/ )
- ~~Must have at least 100 subjects in active workflows~~ [see below](https://github.com/zooniverse/Panoptes-Front-End/pull/3523#issuecomment-282685877)

@mrniaboc 

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://validate-project.pfe-preview.zooniverse.org/
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by mschwamb** [comment]
@rogerhutchings I wouldn't require all of the about pages to be filled if I read this correctly. Because on the about section is results that won't necessarily be filled out. None of my panoptes projects did I put content at  launch, since those are supposed to be for news about results from then project.

 Also for example there's an Education tab, we didn't make one for P4: Ridges because there's not really much a class could do with that project that we could think of so we skipped that page. 

 Can you just check the FAQ and the research are pages are filled out only? I think those are two that should be required, but everything else I think depending on the project could be optional.

**Comment by mschwamb** [comment]
or maybe just count for 3 pages:about, faq, and team ( as team is autogenerated)?

**Comment by CKrawczyk** [comment]
I just want to point out that this validation uses `set_member_subjects_count` for subject sets, and this counter is know to be wrong for some projects (https://github.com/zooniverse/Panoptes/issues/2155), so this PR should wait until that bug is fixed.

**Comment by rogerhutchings** [comment]
@mschwamb Fair enough on Results, I'll change it to require two pages called "Research" and "FAQ". "Team" isn't actually autogenerated as a page, only the list of collaborators; there's also a page resource called Team that goes with it.

@CKrawczyk Good catch - I can separate this into two PRs so we can get the other validations in now.

**Comment by rogerhutchings** [comment]
Okay, this now checks explicitly for the Research and FAQ changes, and no longer checks the number of active subjects - that's been moved to #3525. This should now be ready for review.

cc @mrniaboc

**Comment by rogerhutchings** [comment]
Having spoken to @camallen, he reckons not to let the Panoptes issue stop this PR, so I'm closing in favour of #3525

**Pull request closed without merging**
