### PR TITLE
Glossary

### PR DESCRIPTION
**Pull request by BNewing**
Creating a glossary page to go with the Project Builder Documentation.

Working on the definitions separately with @mschwamb 

So far the page is all linked up and can be accessed from both the logged-in and not-logged-in Project Builder page.

Next steps:
- get the Table of Contents bit to work (something odd is happening at the moment - this is working in Talk but not in this markdown) so that anchor tags can be added in 
- add in a search bar so you can more easily navigate what will be the long list of terms

### CODE REVIEW

**Comment by BNewing** [comment]
I've staged this PR now @mschwamb so you can have a look over it :) https://glossary.pfe-preview.zooniverse.org/ does anybody have any feedback on any of it? 

The terms are now all added in. I can't find a way to add space between the headers - I think because coffeescript is compiling out the spaces I'm trying to add between them. Having glossary included in the table of contents can't be gotten around at the moment with how the markdownz toc section works.

In the future I'd like to add in a search bar for navigating the terms but that feels optional so I might work on that separately later on once I've figured out React a bit more. I'd also like to alter the structure of the documentation and have it similar to the About page - where all of the various pages are shown on a header navigation bar type thing so you can see the neighbouring pages and navigate between them more easily. But I'd like to do this in a separate pull request too, as it also feels like a bit of a tangent.

**Comment by mschwamb** [comment]
@BNewing it's coming along really nicely. 

A few things:

[ ] I'd also have a link in the project builder help section when you're in the project design bit. I'm talking about this side bar:

screen shot 2016-10-30 at 11 54 16 am

[ ] Some definitions should be linked together to make it easier to understand. See below for two suggestions on that:

document6

[ ]  might look into adding a horizontal line after your bit of intro text to separate it from the glossary definitions a bit more. Not sure that it will look good

[ ] Every time there is a mention of a project, if the project is live link to the project website.

[ ] Talk and Talk tags should go under Project specific

[ ] Project builder - don't need to spell out the hyperlink. Just link to it in the definition. So remove 'It can be found at http://www.zooniverse.org/lab' and on the last bit of the definition where it says  'Project Builder page' make that the hyperlink. 

[ ] Some categories it will be better to have the main term and sub terms under it:

[ ] You might add the teal bar so it has a bit more style like the other Zooniverse home pages (see below for what I'm talking about and See the Lab How to https://www.zooniverse.org/lab-how-to):

screen shot 2016-10-30 at 11 25 31 am

@astopy, since this was your initial suggestion, what do you think?

**Comment by astopy** [comment]
This is a great start and seems pretty comprehensive. I agree that it'd be good to link to it from more places.

Let's try and get it live soon and we can always make further tweaks to it later.

**Comment by BNewing** [comment]
Thank you for the suggestions @mschwamb ! I'll keep on working through them today and hopefully will have addressed them all by the end of today so we can take the WIP off :)

**Comment by eatyourgreens** [comment]
Weird bug: the policies page at https://glossary.pfe-preview.zooniverse.org/lab-policies is showing the glossary page for me.

**Comment by astopy** [comment]
Nice catch. This line will need to be updated: https://github.com/zooniverse/Panoptes-Front-End/pull/3135/files#diff-912115cede2e245d874cac600d381c76R6

**Comment by BNewing** [comment]
Thank you for spotting that! 

I've addressed most of the issues raised. I've not addressed the header bar one yet because I'd like to do a separate pull request for a nav bar that links all of the Project Builder documentation together (which might be a bit tricky because of the Best Practises page which already has its own nav bar).

I've also not put spaces in between the different sections because I can't figure out how to. Markdown documentation says leave two trailing spaces at the end of the line before where you want the break to be, but it's not working for me at the moment.

I'll take the [WIP] tag off...

**Comment by mschwamb** [comment]
@BNewing one thing still missing is the hyperlinks for active projects for example Camera CATalog and Snapshot Serengeti are mentioned. People reading this doc might not know what it is,so we need to link to those active projects so the reader can take a look. There's a few other references we have some mentioning live projects, can you add in hyperlinks for those?

**Comment by mschwamb** [comment]
@BNewing I just realized you might have done this, but it's not showing on the staged version. Can you update the staged version for me? Thanks

**Comment by BNewing** [comment]
Ah! I forgot that bit. Here it is restaged again:  https://glossary.pfe-preview.zooniverse.org/glossary

**Comment by mschwamb** [comment]
@BNewing minor fix:  Snapshot Serengeti  needs a hyperlink. Looks good to me other than that issue. Though one of the developers needs to give a final okay to merge.

**Comment by BNewing** [comment]
Ah good catch!

**Comment by mschwamb** [comment]
@astopy I think things are good to go on this. Maybe since you proposed this initially, you can do the final review?

**Comment by mschwamb** [comment]
this closes #2912

**Pull request merged**
