### PR TITLE
Add survey task feedback

### PR DESCRIPTION
**Pull request by mcbouslog**
Staging branch URL: https://pr-6008.pfe-preview.zooniverse.org

Staging project: https://pr-6008.pfe-preview.zooniverse.org/lab/1810/workflows/3516

Duplicate of zooniverse/front-end-monorepo/pull/2403 , holding this as draft until that PR is reviewed and merged.

Initially the goal was to add the bare minimum so a project builder could select the survey strategy from the Lab feedback editor dropdown, which is populated from app/features/feedback/shared/strategies/index.js , which caused the realization FEM PR 2403 could be practically copy-pasted to add the full functionality to PFE as well.

Describe your changes.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Review by srallen — CHANGES_REQUESTED** [review]
Similarly here let's name the strategy "Survey: Simple" and `surveySimple`

Here, though, we'll have a defined lab component once it is added? Is that coming next?

**Comment by mcbouslog** [comment]
> Similarly here let's name the strategy "Survey: Simple" and `surveySimple`
> 
> Here, though, we'll have a defined lab component once it is added? Is that coming next?

I think the existing lab component (app/features/feedback/lab/components/rule-editor-modal.jsx), which just handles success and failure default messages and has a dropdown (populated by the strategies listed in app/features/feedback/shared/strategies/index.js) to set the more specific feedback type works. I tried it and the workflow task settings looked good, but I didn't link a subject set to test it completely, can do that today though, should only take a few minutes.

**Comment by mcbouslog** [comment]
Meant to include (and will update) in the original comment:

https://pr-6008.pfe-preview.zooniverse.org/lab/1810/workflows/3516

Feel free to edit existing or create new workflow and task and test feedback related components.

**Comment by mcbouslog** [comment]
Updated with changes per zooniverse/front-end-monorepo/pull/2403.

**Review by srallen — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
