### PR TITLE
[Security] Upgrade markdownz to 7.7.2

### PR DESCRIPTION
**Pull request by eatyourgreens**
Security patch for markdownz, including adding `noreferrer` to external links. See https://github.com/zooniverse/how-to-zooniverse/issues/143

Staging branch URL: https://pr-5968.pfe-preview.zooniverse.org

To test this, try the link to IPAC in this thread. On master, it redirects back to zooniverse.org.
https://pr-5968.pfe-preview.zooniverse.org/talk/17/2024167?env=production
Also fixed is the IRSA Finder Chart link for each Backyard Worlds subject.
eg. https://pr-5968.pfe-preview.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9/talk/subjects/28039200?env=production

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Code read looks good, I'm running tests to see if everything's registering as expected.

**Comment by shaunanoordin** [comment]
Part 1: External Links block works exactly as expected. 👍 

Test URL: https://pr-5968.pfe-preview.zooniverse.org/projects/darkeshard/transformers

Screen Shot 2021-06-09 at 12 27 14

_The link to IRSA, which originally started off this whole thing (see how-to-zooniverse issue 143), works correctly in this context_

⚠️ Part 2: wait, I need a sanity check here - don't our Project->About pages also use Markdownz?

Test URL: https://pr-5968.pfe-preview.zooniverse.org/projects/darkeshard/transformers/about/research

**Comment by eatyourgreens** [comment]
I don't think the changes in https://github.com/zooniverse/markdownz/pull/93 affect bare URLs, but it's odd that `rel` isn't being added to all links.

**Review by shaunanoordin — APPROVED** [review]
## PR Review

This PR fixes the issue reported in https://github.com/zooniverse/how-to-zooniverse/issues/143

- Updating the Markdownz component now correctly adds the `rel="noopener nofollow noreferer"` safety attributes to external links, in places such as...
  - Talk posts, e.g. https://pr-5968.pfe-preview.zooniverse.org/talk/17/2024167?comment=3303024
  - A project's "External Links" block, e.g. https://pr-5968.pfe-preview.zooniverse.org/projects/darkeshard/transformers

I'm noting that there are still some places where the safety attributes aren't being auto-added to links/external links in certain circumstances (e.g., Project About pages) but that is a separate investigation.

This PR LGTM 👍

**Comment by eatyourgreens** [comment]
Markdownz has a `relNofollow` prop, but it's turned off by default. 🤔 
https://github.com/zooniverse/markdownz/blob/af0338244a3bd8cdf2ea6cf138393eab87fa31cb/src/components/markdown.jsx#L115

**Pull request merged**
