### PR TITLE
[WIP] Upgrading enzyme to 3.x

### PR DESCRIPTION
**Pull request by tingard**
Staging branch URL:

Upgrades enzyme to 3.3.0. Enzyme migration guide can be found [here](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#lifecycle-methods)

Currently have a few tests still failing, have already corrected a few.

### Currently failing tests

- [ ] Shortcut functionality should show an active button with a shortcut
- [ ] ShortcutEditor methods should call toggleShortcut with an input toggle
- [ ] ShortcutEditor methods should call remove handler when clicked
- [ ] ShortcutEditor methods should call add handler when clicked
- [ ] SVGImage it should contain an image element
- [ ] SocialLinksEditor should call handleRemoveLink() when link is removed

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Travis is complaining about a missing adapter. I'm not sure what's going on there. I can see it in the enzyme config file.

@simoneduca is good at figuring out broken tests, so I'm pinging him on this PR too.

**Comment by eatyourgreens** [comment]
There's a warning about `React.PropTypes` when I run this locally. Does it need rebasing to the latest master?

No problems finding the adapter when I run it locally, so I'm really not sure what is going on with Travis.

**Comment by simoneduca** [comment]
Looking into this now.

**Comment by tingard** [comment]
nevermind haha

**Comment by simoneduca** [comment]
Cool. I wonder how version 3 will play with the `test-and-watch` command.

**Comment by tingard** [comment]
Whoops forgot to save package.json after adding the command to test-and-watch, so didn't commit properly. Will update and force with lease

**Comment by tingard** [comment]
Answer regarding test-and-watch: not very well. Interrupting the re-running tests (sometimes) causes `TypeError: Attempted to wrap subscribeTo which is already wrapped`

**Comment by eatyourgreens** [comment]
That error should have been fixed in #4301.

I've set up a branch for this on zooniverse/Panoptes-Front-End. I'm going to merge this to that branch, then open a new PR from there so that anyone with access to the zooniverse repo can update the tests.

**Pull request merged**
