### PR TITLE
Fixed markup and styling on project team page

### LINKED ISSUE #2557: Team roles not wrapping in Safari
screen shot 2016-05-10 at 12 02 29

### PR DESCRIPTION
**Pull request by srallen**
Redid some of the markup on the project team page and added css fixes for #2626 and fixed #2557. While I was at it, also fixed the avatar.

### CODE REVIEW

**Comment by srallen** [comment]
Oh, and should note, that I ran by changes with @jwbmartin and she ok'd it.

**Comment by astopy** [comment]
The spacing/wrapping of roles on the team page could probably do with a bit more tidying I think. It's a little hard to read at the moment.

https://fix-2557.pfe-preview.zooniverse.org/projects/zooniverse/snapshot-wisconsin/about/team?env=production

screen shot 2016-07-12 at 16 54 17

**Comment by srallen** [comment]
@jwbmartin thoughts? Also I just had a thought that readability of the projects roles could be improved if we just used the same styling on Talk (and also would be more consistent), which is `background-color: #555` and `color: #fff`.

**Comment by srallen** [comment]
@astopy Just pushed up some more css changes and clean up to make the project role css consistent across the project team page, Zooniverse talk, and project talk. 👍 by @jwbmartin. Also updated the staged link so you can preview.

**Comment by mschwamb** [comment]
If you're making changes here  to the team page you might consider both showing display name and username if the account has a displayname. Currently on the team page if you have a display name your username doesn't show at all. Related to #2284

**Comment by astopy** [comment]
@srallen Great, LGTM. Feel free to merge, pending the question above from @mschwamb.

**Comment by srallen** [comment]
@mschwamb, I spoke with @jwbmartin about showing both display name and username here. There isn't much space in the design for both, so a possible solution could be to link back to the profile? I'd like to get this merged, so this could come in a later PR that also fixes the lab page as noted in #2284.

**Pull request merged**
