### PR TITLE
Organization landing page redesign - base

### PR DESCRIPTION
**Pull request by mcbouslog**
HOLD: until Notes from Nature and Snapshot Safari can update their organization content for new design, most notably about section.

Staging branch URL: https://pr-5554.pfe-preview.zooniverse.org

Helpful links:
- staging test organization: https://pr-5554.pfe-preview.zooniverse.org/organizations/markb-panoptes/urban-wildlife-org-test
- Snapshot Serengeti: https://pr-5554.pfe-preview.zooniverse.org/organizations/meredithspalmer/snapshot-safari?env=production
- Notes from Nature: https://pr-5554.pfe-preview.zooniverse.org/organizations/md68135/notes-from-nature?env=production

[InVision organization landing page redesign](https://projects.invisionapp.com/d/main/default/#/console/12924056/391430827/preview)

I've separated the organization landing page redesign work into several small PRs.
~This PR is primarily linting and is intended to be a base for other related PRs to merge into.~
[EDIT] ^ This is PR now the combined changes.

Recommended order of related PR review and merge:
- [x] 1. #5555 - Add project state sections to organization landing page 
- [x] 2. #5556 - Update organization landing page style
- [x] 3. #5557 - Refactor external links section for organization redesign
- [x] 4. #5577 - Refactor stats section for organization redesign

ToDos:
- [x] review content section headings for proper spacing and content
- [x] add light grey border around content boxes
- [x] project cards are squished to the left of the screen (e.g., iPhone 8 iOS 13.0 | mobile_Safari, Samsung Galaxy S10 Android 9.0 | mobile_Chrome)
- [x] `.organization-page__section-title` should have margin-top: 60px (now has top & bottom of 30px, combined with neighboring elements, I think gets desired result)
- [x] fully left align project cards, currently there's a small margin/padding between first card and left side of container

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [x] Can you post a talk comment?

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by simensta** [comment]
LGTM, I'll review this PR again before we merge this branch into the main branch.

**Comment by mcbouslog** [comment]
Initial comment has been updated.

I think this is looking good, ready for final review.

@beckyrother I think I made your final design review edits, but let me know if not, or if there's anything else.

Punting the project card mobile icon and progress bar for another day.

**Comment by simensta** [comment]
@beckyrother, can we add a heading element to the active projects section of the organization landing page? I think adding this heading element will increase screen reader navigability and provide more context to folks not already familiar with Zooniverse. I've added a note to the InVision design as well.

I think this would be especially helpful for organizations without the category filter, such as Snapshot Safari.
snapshot safari organization landing page

**Comment by beckyrother** [comment]
Good call @simensta, updated the InVision

**Comment by mcbouslog** [comment]
Thank you both! I think this is looking good now. I used my Mac Voiceover and it stepped through and announced what I expected in a logical way, but I'm not confident that's sufficient testing. Let me know what you think. Thanks!

**Comment by eatyourgreens** [comment]
If you know how to open the VoiceOver rotor, that will give you an option to navigate the page by landmarks and headings too. It looks something like the screenshot here. https://github.com/zooniverse/front-end-monorepo/issues/657#issue-429783990

**Comment by simensta** [comment]
I've tested this branch on the following os/browser pairings:

- OS X Catalina | Chrome Version 78.0.3
- Windows 10 | Edge 18.0
- Windows 10 | Firefox 71.0
- Samsung Galaxy S10 Android 9.0 | mobile_Chrome
- iPad Pro 11 2018 iOS 12.0 | tablet_Safari
- OS X Catalina | Safari 13.0

When using VoiceOver on Chrome, adding the _Active Project_ heading and specifying the type of element for the translation component improved the screen reader experience.

**Comment by mcbouslog** [comment]
Got approval from NfN and Snapshot Safari, went through again without issue, I think this is good to go!

Will merge shortly...

**Pull request merged**
