### PR TITLE
Remove Title Mixin

### PR DESCRIPTION
**Pull request by wgranger**
Removes the TitleMixin from several components (#3218): 

`app/collections/show.jsx `
`app/pages/collections/collections-list.cjsx`
`app/pages/collections/favorites-list.cjsx `
`app/pages/collections/index.cjsx`
`app/pages/lab/project.cjsx`
`app/pages/project/classify.cjsx`
`app/pages/project/index.cjsx`
`app/pages/sign-in.cjsx`

Describe your changes.
I rewrote the mixin as a higher-order component (HOC), and applied changes to each component it touched. Some changes were made to `project.cjsx` to remove the `PromiseRenderer` so the title could be set solely from the wrapper instead of using the HOC in the wrapper and the wrapper's child. However, determining when the user prop is received seemed a bit tricky (see `getProjectAndOwners()`.

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

https://remove-title-mixing.pfe-preview.zooniverse.org/

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [x] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by amyrebecca** [comment]
This fails to build for me right now under node 8.1.2

screen shot 2017-07-05 at 12 48 00 pm

**Comment by srallen** [comment]
Rewriting the mixin as a HOC is good practice, but I think long term, we could use [react-helmet](https://github.com/nfl/react-helmet). Apologies if I didn't mention this at the start of the PFE work week.

**Comment by wgranger** [comment]
Ok, rewrote that component a bit in a more straightforward way that should be easier to read. The components still all include HOC, but if a change needs to be made to React Helmet I can do so, either in this PR or a subsequent one.

**Comment by wgranger** [comment]
Closed in favor of #3938

**Pull request closed without merging**
