### PR TITLE
Add notification preference and help text for group mentions

### PR DESCRIPTION
**Pull request by parrish**
I'm opening this just to get it up, but the backend is going to only be deployed to staging for the moment.

I'll comment/assign when it's ready for production.

### CODE REVIEW

**Comment by DarrenMcRoy** [comment]
We may have to discuss this further down the road, based on some of what came out of the Best Practices seminar.

This tool will allow ANYONE to alert the researchers, when there was pretty universal agreement from the seminar that only moderators should be allowed to flag posts for researchers.

However, it's a good start!

**Comment by parrish** [comment]
I don't think that's an issue at all.  Any time a comment is reported moderators/admins are notified.

If a researcher doesn't want to receive these notifications, or prefers to receive them as a digest, they can manage these notifications separately.  Abuse can be handled the same as anything else.

I think it's more appropriate to allow anybody to do this rather than have to try to push something up a chain.

If, for instance, a project team would rather it come via the moderators then they simply unsubscribe and have their community mention the moderators instead.

**Comment by DarrenMcRoy** [comment]
"If, for instance, a project team would rather it come via the moderators then they simply unsubscribe and have their community mention the moderators instead."

In which case the moderators are required to manually assemble a separate digest for the researchers, instead of just clicking a button that says "researchers should look at this" -- a feature idea that was met at the workshop with *universal* acclaim from volunteers, moderators, researchers, everyone.

The entire problem in the first place is that researchers don't have time to answer all the questions asked of them, and need to know which are the important ones (and which the moderators can just handle themselves). This is why the idea of a moderator-operated flag for the researchers was so popular. Group mentions are nice, but they don't quite solve that core problem.

**Comment by parrish** [comment]
Happy to reevaluate in a few months if there ends up being too much noise.  Right now, group mentions haven't even been used yet.

Right now, we should work on a better presentation of what features are currently available.

**Comment by DarrenMcRoy** [comment]
Agree 100%. All I was saying is, let's discuss further down the road. :-)

**Comment by chrislintott** [comment]
@parrish Hang on, this exists? Let's trial it with a science team. I nominate Galaxy Zoo.

**Comment by parrish** [comment]
It's live with all Panoptes projects.  We just need to figure out a good way to present it as an available feature.

**Comment by DarrenMcRoy** [comment]
I'm going to be working with a developer to build a "guide to Talk functionality" which explains everything that you can do, but @chrissnyder has asked me to hold off until we have our new developer (see: #1517)

**Pull request merged**
