### PR TITLE
Scroll up between project list pages

### PR DESCRIPTION
**Pull request by itsravenous**
Added this as a callback on the card list - i.e. the parent component/page decides what to do on page change - I can imagine cases where you wouldn't want to jump to the top of the document when changing the list page (e.g. a list buried halfway down a long page)

### CODE REVIEW

**Comment by brian-c** [comment]
Components generally shouldn't concern themselves with managing scroll position on navigation.

Looks like something's been written to deal with this, probably worth looking into: https://github.com/rackt/scroll-behavior

**Comment by amyrebecca** [comment]
May want to consider this issue as part of #2149 ?

**Comment by marten** [comment]
Shall we either close or merge this?

**Comment by srallen** [comment]
Let's close this. The project page overhaul will be done soon and this functionality can be added via the scroll-behavior router plugin mentioned above in a PR later.

**Pull request closed without merging**
