### PR TITLE
Preload assets used on main pages

### PR DESCRIPTION
**Pull request by aweiksnar**

### CODE REVIEW

**Comment by brian-c** [comment]
Why load these on page load instead of as they're needed?

**Comment by aweiksnar** [comment]
I think it provides a smoother experience for users changing between pages on the site for the first time. Would you rather not load these ahead of time?

**Comment by brian-c** [comment]
The page already super heavy at load. I don't think we should be loading anything we don't have to until we need it.

**Comment by aweiksnar** [comment]
Okay that's fair

**Pull request closed without merging**
