### PR TITLE
Fix relative path includes

### PR DESCRIPTION
**Pull request by edpaget**

### CODE REVIEW

**Comment by brian-c** [comment]
This will break deploys to anywhere but the root, no?

**Comment by edpaget** [comment]
Yes, but https://github.com/zooniverse/Panoptes-Front-End/pull/1492 already did, and it turns out its important for getting google to index project pages. I'll add a configuration option shortly that will restore the ability to deploy to other places.

**Comment by astopy** [comment]
Might be worth adding a variable to change the root prefix for non-root deploys.

**Comment by edpaget** [comment]
Yup am planning to.

**Pull request merged**
