### PR TITLE
Refactor workflow selection

### PR DESCRIPTION
**Pull request by srallen**
This is a refactor on how the workflows are selected and fetched for projects. The goal is to reduce the number of API calls for workflows since now it is no longer fetched after every classification. This also moves the code into the index file of the project (`ProjectPageController` and `ProjectPage` components) which I think will get us one step closer to eventually refactoring to use a store or observables based framework (Redux, Rx.js, and/or MobX). In addition, this necessitated a refactor on some of the code I wrote for the workflow promotion for Gravity Spy.

The workflow selection will now be consistent whether a user is logged in or not, navigates directly to a project's `/classify` page, navigates from a project's talk, or uses the button(s) available on the project home page.

Projects to test with:

Gravity Spy's workflow promotion: 
https://refactor-workflow-selection.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy?env=production
Their promotion algorithm is now working, so you should get promoted using the beginner workflow relatively quickly. There is a known issue where the dialog pops up twice. This PR does not fix this and I'll submit a separate PR for it.

A project that is finished, since that is part of the code that got moved with the workflow selection:
https://refactor-workflow-selection.pfe-preview.zooniverse.org/projects/jukoch/pattern-perception?env=production

A project that allows users to choose which workflow to work on:
https://refactor-workflow-selection.pfe-preview.zooniverse.org/projects/mschwamb/comet-hunters?env=production

A project that uses random workflow selection:
https://refactor-workflow-selection.pfe-preview.zooniverse.org/projects/mschwamb/planet-four-terrains?env=production

Sometimes the workflow is fetched a couple of times when you first visit the project since I think some further refactoring could be done with the `componentWillReceiveProps` moment in the controller's component lifecycle, however, I added several conditionals to hopefully reduce this as much as possible, by checking if the project has finished loaded, if we know if there's a user or not, and if the preferences have finished loading. 

I'm hoping to get this merged sometime early next week for the Gravity Spy beta, but it's not essential. Since this touches an important part of the classifier, I'd like a couple of people to review if you have the time. Feel free to reassign if not.

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch?

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
P4:Terrains hangs for me (signed in). Just says 'Loading classification' then doesn't display the classifier. No obvious errors in the console, that I can see.

**Comment by srallen** [comment]
Yep it seems to be doing that on staging, though, I don't recall it hanging when running locally. I'll check it out today.

**Comment by srallen** [comment]
Gonna relabel as WIP as I'm finding a couple related issues.

**Comment by srallen** [comment]
Ok, I discovered an instance of the workflow being fetched for and set as state in the classifier. I switched that to use the props as well as did a bit more further refactoring. I think everything is working as it should, but the Gravity Spy workflow promotion algorithm isn't active at a moment since an issue is currently being debugged with it. If anyone wants to see the workflow promotion dialog, I can promote you on a test project on staging. Their algorithm should hopefully be back up tomorrow sometime.

**Comment by eatyourgreens** [comment]
Looks good to me.

**Comment by eatyourgreens** [comment]
Just did a few Gravity Spy classifications and I'm still seeing a GET request for workflow 1610 after every classification.

**Comment by srallen** [comment]
@eatyourgreens There was one last workflow get request in the classification save that I missed. Thanks for pointing that out.

**Comment by srallen** [comment]
FYI, the Gravity Spy promotion algorithm is back up again.

**Comment by mcbouslog** [comment]
LGTM

**Pull request merged**
