### PR TITLE
React 16.5

### PR DESCRIPTION
**Pull request by eatyourgreens**
Bump react, react-dom and react-test-renderer to 16.5.1.

Staging branch URL: https://react-16.pfe-preview.zooniverse.org

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [x] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This throws a fatal error in the sticky modal form.
```
sticky.js?163c:76 Uncaught TypeError: Cannot read property 'style' of undefined
    at StickyModalForm.reposition (sticky.js?163c:76)
    at StickyModalForm.componentDidMount (base.js?cd89:81)
    at StickyModalForm.componentDidMount (sticky.js?163c:47)
```

**Comment by eatyourgreens** [comment]
Rebased and bumped to React 16.5.2, which came out last week.

**Comment by srallen** [comment]
Looks ok running locally and trying test projects. Gonna look over a few more in production projects first before approving.

**Comment by srallen** [comment]
This just needs the package-lock.json conflict to be resolved and then can merge.

**Pull request merged**
