### PR TITLE
Survey task styles

### PR DESCRIPTION
**Pull request by srallen**
- Added lots of styles and changed some markup for the survey task that'll be used for Wildlife Watch USA (aka Snapshot Wisconsin). 
- It was mostly borrowed from what I did for Wildcam. 
- :+1:  by @jwbmartin.

### CODE REVIEW

**Comment by brian-c** [comment]
Can you point me to an example project?

**Comment by srallen** [comment]
I've added you as a collaborator on the wildlife watch project and also to my test project on staging: http://demo.zooniverse.org/panoptes-front-end/#/projects/srallen086/survey-test/classify/?workflow=1905&reload=0

**Comment by brian-c** [comment]
Thanks. Looks like layout/image display gets a little wonky as the list narrows down:

screen shot 2015-11-16 at 3 23 32 pm

screen shot 2015-11-16 at 3 24 03 pm

screen shot 2015-11-16 at 3 24 29 pm

**Comment by srallen** [comment]
Cool, I just missed grabbing those styles fixing that in wildcam. Also got rid of the `white-space: nowrap`. It made sense in wildcam, but doesn't here.

**Comment by brian-c** [comment]
Thanks, looks good, but I'm still only getting thumbnails when `data-breakpoint="20"`. Should be there in 10 and 5 too.

**Comment by srallen** [comment]
Ok, I changed the markup to use a `img` tag instead of `span` and now am seeing images in the other breakpoints.

**Comment by brian-c** [comment]
Great! Thanks for all that.

**Pull request merged**
