### PR TITLE
Expose Owner in Researcher List

### PR DESCRIPTION
**Pull request by wgranger**
Describe your changes.
This adds a project owner as an an avatar choice in the Words from the Researcher section. 

# Review Checklist

- [X] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [X] Does it work on mobile?
- [X] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [X] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

https://add-owner.pfe-preview.zooniverse.org/

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by mschwamb** [comment]
Is this live on the site or perhaps hasn't been deployed until the update of the front page? I don't show up on any of my projects in the drop down menu and I own the projects

**Comment by wgranger** [comment]
This is live and deployed. It should be working. I cannot find a use case when it is not displaying the project owner.

**Comment by eatyourgreens** [comment]
I'm not showing up in the list for Diagnosis London, which I own. https://www.zooniverse.org/lab/396

**Comment by mschwamb** [comment]
Here's what I'm seeing. My username is not appearing:

dropdown

**Comment by wgranger** [comment]
Hmm. Interesting. I'll investigate.

**Comment by eatyourgreens** [comment]
@wgranger Maybe it's an issue where the number of people on a project is larger than the page size for the roles API query?

**Comment by mschwamb** [comment]
Slightly related to this from the email that just went out from the Zooniverse ' If you do decide to add a quote, you will be able to choose your project avatar, or the avatar of any of your team members to go alongside.', I didn't see the option to select the project avatar. Not sure if it's not showing up and related to this  or there's a different way to select that.

**Pull request merged**
