### PR TITLE
Preserve the @symbol in username mentions

### PR DESCRIPTION
**Pull request by aweiksnar**

### CODE REVIEW

**Comment by chrissnyder** [comment]
Mentions work either way. I assume this is just to make it more explicit that you are mentioning someone?

**Comment by edpaget** [comment]
Big :+1: from me. Makes the process more discoverable.

**Comment by aweiksnar** [comment]
Yeah I guess so, kinda following github's lead on this

**Comment by chrissnyder** [comment]
Roger that, merging!

**Pull request merged**
