### PR TITLE
Basic styles for embedded youtube videos

### PR DESCRIPTION
**Pull request by eatyourgreens**
Depends on zooniverse/markdownz#40
Should allow Solar Stormwatch to embed their youtube video tutorial.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Test video here: https://embed-video.pfe-preview.zooniverse.org/projects/eatyourgreens/diagnosis-london/about/research and also in the tutorial for that test project.

**Comment by srallen** [comment]
@eatyourgreens zooniverse/markdownz#40 is now merged. Needs a version bump on npm.

**Comment by eatyourgreens** [comment]
@srallen 👍 4.1.4 just published on npm.

**Comment by srallen** [comment]
@eatyourgreens I don't have permission to that project. Could you add `srallen086` as a collaborator or make it public?

**Comment by eatyourgreens** [comment]
@srallen sorry, I renamed it today while playing around with the project builder. Try https://embed-video.pfe-preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify

**Comment by srallen** [comment]
The video in the tutorial is pretty small. I'm not sure if that'll be very effective for the purposes of the tutorial, but iteration on video use there can come in a subsequent PR. Basic styles are fine for now.

**Pull request merged**
