### PR TITLE
Improve discussion and board pagination

### LINKED ISSUE #955: Browser's back button does not work on talk
Currently if you change pages in a talk tread, and then use the browsers back button, the url changes but the content of the page does not.  Note how in the screenshot below the url says "page=7" but the drop down menu (and the forum's content) are still page 6.

screen shot 2015-07-03 at 10 09 26 am

Tested in both firefox 38.0.5, chrome 36.0.1985.125, and safari 8.0.6 on Mac OS X.

### LINKED ISSUE #1046: If someone writes out a Talk thread link in a post and you click on the link it doesn't take you there
If someone writes out the url for a talk thread in a different Talk post, you see that the url is a hyperlink from the look of it, but when you click nothing happens. You don't get redirected to the where the url says - the address bar says the address for the url you clicked on but you don't move threads. 

Tried this on firefox and chrome - 

If you can see admin/moderator only boards try the link in this post https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/23/112?page=1&comment=1367

Also the very top navigation links change but the thread content doesn't (seen screenshot below)

screen shot 2015-07-13 at 10 03 57 am

### LINKED ISSUE #1121: Link to a comment from another discussion thread doesn't work properly
I wanted to send someone a link to a comment from another discussion thread but it doesn't work properly for me. 

When I open the link in the new tab (or copy it into my comment and then click on it), it loads the discussion but doesn't take me to the correct page and doesn't highlight the linked comment anyhow.

When I stay on the page with the linked comment and click on the link, it does appear highlighted as expected.

### LINKED ISSUE #1150: Delete a Talk thread from a project talk it takes you to Zooniverse talk
One of the Planet Four: Terrains moderators had to delete a few duplicate discussion threads on P4T Talk yesterday. He reported that each time he deleted a thread he got put into Zooniverse Talk and had to navigate back. I think the default behavior should be to bring you to the front page of your project Talk.

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #955
- Closes  #1150
- Closes #1046
- Closes #1121

### CODE REVIEW

**Comment by edpaget** [comment]
Deleting a discussion still seems to take me back to the Zooniverse Talk

**Comment by edpaget** [comment]
It laos looks like #1046 and #1121 are not resolved.

**Comment by aweiksnar** [comment]
Ah sorry I misread those issues - Just pushed an update for the delete redirect & will get the page links updating in tomorrow!

**Comment by aweiksnar** [comment]
Should be ok to close the advertised issues now - I put in a test link at `#/projects/alex-panoptes/test-proj/talk/21/57` to try it out

**Comment by edpaget** [comment]
:ok_hand:

**Pull request merged**
