### PR TITLE
Expand the allowed subject upload list

### PR DESCRIPTION
**Pull request by eatyourgreens**
Remove the admin restriction for video and audio uploads.
Add `text/*` and `application/json` to the list of allowed MIME types.
Add `.txt` and `.json` to the list of allowed file extensions.

Staging branch URL: https://pr-5532.pfe-preview.zooniverse.org

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
No hurry to merge this. I had to upload some text files today and thought it would be useful to have a branch which allows the project builder to upload files other than images.

**Comment by shaunanoordin** [comment]
### Update

So I was an idiot yesterday and didn't properly check my code that was checking if the uploaded files in the AWS S3 buckets existed. Because they did! They did exist. ...or maybe I'm misunderstanding how immediate the subject upload process is, because perhaps's there are two queues - one visible between client web browser and Panoptes, and another behind-the-scenes one between Panoptes and the AWS S3 bucket.

Anyway, updated test results:
- Sample JPG - uploaded OK
- Sample JSON - uploaded OK
- Sample TXT - uploaded OK

If you're curious to check, they're staging Subjects 84017, 84018, 84019

More test results:
- Sample MPG - (.mpg renamed to .mpeg) uploaded OK, but can't fully confirm that the file works as intended...? (staging Subject 84023 FYI)
- Sample MP3 - ⚠️ 403 Forbidden when trying to `PUT https://zooniverse-bucket-dot-com/panoptes-uploads.zooniverse.org/staging/subject_location/2b32d53d-d423-4f66-a355-c10982452d50.mpga?bla-de-bla-de-bla` (wait, mpga?)

Overall, I can confirm that the code changes for this PR correctly enable the file uploads to the _front end,_ but there may be some follow up investigations needed with Panoptes or the AWS setup to confirm that video and audio files are getting sent through properly.

**Comment by shaunanoordin** [comment]
I'm going ahead and merging this; the audio upload issue shall be treated as a separate item to be investigated later. 👌 Let's gooo!

**Comment by srallen** [comment]
Merging since @eatyourgreens is out. @shaunanoordin would you open an issue about the trouble you had with the audio file uploads?

**Pull request merged**
