### PR TITLE
Move pan/zoom into its own component

### PR DESCRIPTION
**Pull request by eatyourgreens**
Moves the pan/zoom controls into their own component, rewritten in ES6.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Still needs work, I think, because of the close coupling between the pan/zoom controls and the SVG image in the `FrameAnnotator` component.

**Comment by brian-c** [comment]
Not sure if it's helpful, but I hacked out a little zoom-anything component a while back: https://github.com/brian-c/react-zoomable/blob/master/index.js

It's not SVG-specific, but I assume it'll work fine with SVGs. There's an example.html file in the repo.

I wouldn't recommend using it directly, but maybe as some inspiration for the decoupling?

**Comment by eatyourgreens** [comment]
@brian-c thanks! I'll take a look.

I'm happy now that I think I've got all the pan zoom code moved into its own component, so this is ready for review when someone has time to look at it.

**Comment by eatyourgreens** [comment]
Staged at https://pan-zoom-component.pfe-preview.zooniverse.org/

**Comment by simensta** [comment]
This is great -- thank you @eatyourgreens! 

One can no longer zoom by pressing enter after focusing the "+"/"-" interface button. Is that intentional? One can still zoom by pressing the keyboard "+"/"-" button.

**Comment by eatyourgreens** [comment]
@simensta should be fixed now. A misplaced `)` meant the callback wasn't being invoked after a `keyDown` event.

**Comment by simensta** [comment]
Looks good!

**Pull request merged**
