### PR TITLE
[project page branch] Delete old and unused disciplines code

### PR DESCRIPTION
**Pull request by alexbfree**
These old group-by-discipline routes and components can be deleted... the new approach will integrate directly into the "All Disciplines" view within the main project list page.

### CODE REVIEW

**Comment by alexbfree** [comment]
Looks like this PR has got messed up as the base has changed since i created it. trying to fix it with rebase.

**Comment by alexbfree** [comment]
Note to self. The only changes we need are https://github.com/zooniverse/Panoptes-Front-End/pull/2369/commits/a776834d45b55822f0f277c6731e3596a11d1a15 . I will create a new branch and PR with just those and close this one.

**Comment by eatyourgreens** [comment]
@alexbfree if it helps, create a new branch then `git cherry-pick a776834` and you should be all set.

**Comment by alexbfree** [comment]
Thanks @eatyourgreens !

**Comment by alexbfree** [comment]
Superseded by #2417

**Pull request closed without merging**
