### PR TITLE
Project pages demote site nav

### PR DESCRIPTION
**Pull request by brian-c**
This is a great big rewrite of the main app layout components (the header, main content area, and footer) to allow for @jwbmartin's new project navigation design where the site nav is tucked away behind the project.

ui_animation trim

Also added a super cool construction border when admin mode is active to discourage people from hanging out in admin mode all the time.

Also added eslint, and stuck to it for the most part (although I have a feeling it wasn't running on a few files).

https://project-demotes-site-nav.pfe-preview.zooniverse.org/

### CODE REVIEW

**Comment by jwbmartin** [comment]
Oh man it's working! Some details that I think I might have just forgot to mention: I had a request that request that it say something like The Zooniverse next to the logo for those who might not be aware. 
Example: screen shot 2016-06-24 at 11 06 24 am

**Comment by parrish** [comment]
Looks awesome.

I'd add a `cursor: pointer` to `.app-layout__main--set-aside` just to hint that it's clickable though.

**Comment by brian-c** [comment]
> I'd add a cursor: pointer to .app-layout__main--set-aside just to hint that it's clickable though.

I left that out to indicate to the user that whatever action they think might happen by clicking (i.e. if they're hovering over a button in the reduced project view) will not actually take place. Sorta like how modal dialogs don't indicate that the background is clickable, but clicking anyway usually dismisses the dialog.

**Comment by parrish** [comment]
> will not actually take place
Fair enough.  I think that's pretty standard for modals and I suppose this is basically a modal.

**Comment by brian-c** [comment]
> Some details that I think I might have just forgot to mention: I had a request that request that it say something like The Zooniverse next to the logo for those who might not be aware.

The nav-toggle button sits in kinda a weird place in the DOM where the project nav doesn't know about it, so a long enough project nav will overlap it. They also don't share a baseline, so it looks weird unless everything's set up just-so. Happy to iterate on this more in the future, but for now I've switched the "Home" link to say "Zooniverse".

screen shot 2016-06-24 at 11 40 13 am

**Comment by brian-c** [comment]
Feelin' pretty good about this now. Checked in IE and edge, too, all's well. Sorry for the massive PR, it's mostly a rewrite.

**Comment by parrish** [comment]
Only issue I can see is that the topbar has a color issue in projects without a background image:

https://project-demotes-site-nav.pfe-preview.zooniverse.org/projects/drrogg/annotate/talk

vs

https://pfe-preview.zooniverse.org/projects/drrogg/annotate/talk

**Comment by brian-c** [comment]
Ah! Fix for that got lost in some rebases. Will correct in a minute. Thanks!

**Comment by brian-c** [comment]
Fixed now.

**Comment by parrish** [comment]
I just tracked down an error coming from [site-nav.jsx](https://github.com/zooniverse/Panoptes-Front-End/blob/7bac2323b371d6a3be9a41ac3eb8a4e4e1d4cf55/app/layout/site-nav.jsx#L93):

> Warning: Failed propType: Invalid prop `onClick` of type `boolean` supplied to `Link`, expected `function`.

Looks like the links with props like `onClick={!!this.logClick && this.logClick.bind(this, 'mainNav.projects')}` are the culprit.

`onClick={this.logClick ? this.logClick.bind(this, 'mainNav.projects') : () => {} }` would cover it.

Makes me miss coffeescript's `?.` a bit.

**Comment by brian-c** [comment]
Found a bunch searching `on[A-Z].+=.+&&`, will update soon.

**Comment by brian-c** [comment]
There we go, thanks.

**Comment by parrish** [comment]
:+1:

**Pull request merged**
