### PR TITLE
Use Webpack!

### PR DESCRIPTION
**Pull request by brian-c**
Lots of hard work from @amyrebecca and some rebasing and petty tweaking of scripts from me.

`npm run stage` now stages to the branch subdomain. Having everybody stage to the same place was pretty silly.

Continued-from and closes #2524 (had to make a new branch, so it gets a new PR, sorry).

### CODE REVIEW

**Comment by parrish** [comment]
Ready to hit merge on this.

Any objections?

**Comment by amyrebecca** [comment]
No objections here!

**Comment by brian-c** [comment]
I'm going to do a manual deploy to www.zooniverse.org first. If that goes well I think we're good. That work for you @srallen?

**Comment by srallen** [comment]
@brian-c Sounds good to me. Go for it! 🎆

**Comment by brian-c** [comment]
I think this is good to go. Who wants to push the button?

**Comment by parrish** [comment]
🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈 🎉 🎈

**Pull request merged**
