### PR TITLE
Markdown tutorial

### LINKED ISSUE #1517: Adding Zooniverse markdown specifics like the +tab+ to the project builder markdown help
If possible, it would be really helpful to add the +tab+ syntax for making links open in new tabs and any other syntax specific to the Zooniverse markdown listed on the project builder help as an addition to the generic markdown tutorial currently linked

screen shot 2015-09-03 at 9 06 10 am

### PR DESCRIPTION
**Pull request by mcbouslog**
Markdown help window expansion.  Closes #1517.

### CODE REVIEW

**Comment by aweiksnar** [comment]
Guide looks nice :+1:  Can you squash these in to a single commit and also capitalize the `U` in the `Use this...` links and then looks good to merge

**Comment by DarrenMcRoy** [comment]
I kept it all lower-case -- if you capitalize that U, you have to capitalize a few other things, too, it seemed. It made sense to have it lower-case everywhere except there, so... seemed weird to have just the one capital letter!

**Comment by aweiksnar** [comment]
Thanks @mcbouslog! Volunteers are going to be pumped for this

**Comment by mschwamb** [comment]
This doesn't close #1517 since it's not been implemented in the project builder. The project builder still shows the old version.

**Comment by mcbouslog** [comment]
Hi Meg, you're absolutely right, and Darren has opened issue #1969 with a few tweaks to the markdown tutorial merged last week specifically for the project builder version. I'll have the project builder version up hopefully early this week. Thanks,

**Comment by mschwamb** [comment]
Great. Thanks @mcbouslog

**Pull request merged**
