### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by brian-c**
This adds a display for Floating Forests-style project tutorials (really more like a welcome-to-the-classifier message).

It's made up of:

* A `Tutorial` component, which also handles starting the tutorial (if necessary) and recording that a user has seen it (per-session, if nobody's logged in).

* A `StepThrough` component, for sliding between steps (swiping works on mobile)

* A `MediaCard` component, for showing an image or video on top of some markdown content (this mostly exists for style and consistency)

* A little :mortar_board: button in the classification interface that'll restart the tutorial

The classifier is responsible for checking to see that a project has a tutorial and starting it automatically if the user hasn't seen it.

The back end of this is not ready yet, but I've got some steps mocked into my project at http://localhost:3735/projects/brian-testing/ghosts/classify/

### CODE REVIEW

**Comment by aweiksnar** [comment]
Looks solid. Thoughts on either giving the top of tutorial media-card-media a border-radius or removing the border-radius from the content area?

**Comment by brian-c** [comment]
Just pushed up a fix for the corners.

**Comment by aweiksnar** [comment]
Cool thanks, better way to handle that too :+1: 
One more- should all the `project.configuration.etc` statements have a null check on `configuration`? I noticed my dev project (alex-panoptes/test-proj) throws an error from that when visiting the classifier

**Comment by brian-c** [comment]
Oh yeah, gross. That probably shouldn't be allowed to be null, anyway. Fixed.

**Comment by edpaget** [comment]
Added back-end support here https://github.com/zooniverse/Panoptes/pull/1414

**Comment by aweiksnar** [comment]
Sweet! @brian-c this looks good to me. Ready to merge in or do you want to handle api integration here?

**Comment by brian-c** [comment]
I'd merge this. Proper integration will probably have to wait until the editor is working.

**Comment by aweiksnar** [comment]
Roger that :shipit:

**Pull request merged**
