### PR TITLE
Adds invert subject to Talk, refactors invert to css filter

### LINKED ISSUE #5094: Add invert button to Talk subject viewer
## Requested behavior
Add invert button to Talk subject viewer.

## Current behavior
Subjects viewed within Talk do not have the invert button.

### PR DESCRIPTION
**Pull request by mcbouslog**
Staging branch URL: https://pr-5276.pfe-preview.zooniverse.org/projects/markb-panoptes/backyard-worlds-test-project-mb/talk/187/319

Closes #5094.

Describe your changes.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by mcbouslog** [comment]
Getting some weird subject shifting when in multi-image layout.

**Comment by mcbouslog** [comment]
Also I think I can cleanup svg-image and svg-transparent-rect more without the modification object coming through.

**Comment by mcbouslog** [comment]
Ok I think this is ready for review now.

**Comment by eatyourgreens** [comment]
I could be wrong, but isn't the SVG invert filter used by the classifier? I think this PR is going to break projects that use that filter.

**Comment by mcbouslog** [comment]
Thanks @eatyourgreens, I'll refactor, possibly on different branch, to leave classifier invert functionality as is, but add Talk invert button via CSS filter.

**Comment by mcbouslog** [comment]
Closing in favor of #5284

**Pull request closed without merging**
