### PR TITLE
Delete index.html and commit_id.txt after upload

### PR DESCRIPTION
**Pull request by eatyourgreens**
Upload `index.html` and `commit_id.txt` with a cache lifetime of 60s. Delete them after upload then upload the rest of the build with a cache lifetime of 60,4800s (1 week.)

This should fix any scenarios where `index.html` could be served out to the CDN with a lifetime of 1 week, before it's overwritten with a cache lifetime of 60s.

Staging branch URL: https://pr-5965.pfe-preview.zooniverse.org

Screenshot of the Zooniverse staging home page on this branch, showing the cache-control header in the Network panel, with a max-age of 60s.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by zwolf** [comment]
The CacheControl attributes on the files in blob storage are not wrong: 

blobprops

This only started happening yesterday. Overwriting index.html with the different CC header has worked since we started using Actions on every site that this has been adopted on, so there's still a mystery here. Even assuming a race condition situation where a request comes in after the first upload (week long header) but before the new one and the CDN caches the file for that long, why did a purge of both the FD cache and the nginx cache not cause the file to be reacquired from the origin, regardless of the headers? Please read the whole conversation in slack for more context.

All that said, this reordering and a quick rm isn't going to hurt anything and probably is better for higher traffic sites for the racy reason above.

**Comment by eatyourgreens** [comment]
I'm baffled as to why purging the FrontDoor cache didn't work either, but I can't see any other way that files would be served from the origin with a max-age of 1 week.

**Comment by zwolf** [comment]
I'm seeing a CORS error on the main site for the file zooniverse.org-status.txt. Is this related to getting chatops deployment working on PFE? Is it different somehow from commit_id.txt?

**Comment by eatyourgreens** [comment]
`status.txt` is the popup we use when we're having technical problems. I'm not sure, off the top of my head, where that file is stored.

**Review by zwolf — APPROVED** [review]
This LGTM and at the minimum is a good excuse to see if another deploy makes AFD have any embarrassing realizations.

**Comment by eatyourgreens** [comment]
Let’s see what happens!

**Pull request merged**
