### PR TITLE
Fix stats avatars

### PR DESCRIPTION
**Pull request by eatyourgreens**
Describe your changes.
Should fix project avatars not being shown on the user profile stats page.

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://stats-avatars.pfe-preview.zooniverse.org/

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [x] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Not the world's greatest fix: GET `avatars/avatar_id`, which succeeds if the avatar is cached, errors out otherwise. On error, fallback to `projects/project_id/avatar`.

This seems to be a workaround for what are probably bugs in the API client's implementation of resource caching.

**Comment by srallen** [comment]
Just a thought, maybe we can absorb the `ClassificationRibbon` changes from #2979 into this to reduce the changes come in with that PR. @camallen suggest sounds like a good idea too.

**Comment by wgranger** [comment]
I'm in the process of moving the `ClassificationRibbon` changes from the new home page over to this PR to make that merge easier. One note about sideloads I'm curious about. Yes, pulling the entire project into a call does slow things down a bit. We've been doing this with the new home page because it requires the `updated_at` tag from each project the user subscribes to in order to sort those projects, and this tag isn't available with project cards. 

Is there any change we can include the `updated_at` tag with the `cards: true` call? That way we could avoid pulling the entire project resource with a sideload. 

@camallen ideas?

**Comment by eatyourgreens** [comment]
Maybe add that as a sort parameter to the cards API route? `sort=-updated_at`. I don't know if it supports that at the moment.

**Comment by wgranger** [comment]
Wow, that worked, but we're also using the `updated_at` tag to show how recently each project was updated on the pull out tab, so it might be that we need the specific time/date each project was updated.

**Comment by eatyourgreens** [comment]
After chatting to @camallen we're going to merge this, so that the volunteers aren't seeing broken avatars on their stats pages. I'm going to keep this branch open so that we can continue to work on optimising that API query, and merge those changes later.

@wgranger feel free to push to this branch and reopen when it's ready to merge again.

**Comment by wgranger** [comment]
Gotcha. Yes, at this point I have all the changes moved over from the new signed in home page, just waiting to see how we want to approach the sideload.

**Comment by camallen** [comment]
Feel free to merge this and we'll discuss the sideload in the new signed in PR

**Pull request merged**
