### PR TITLE
changing Grant's team pic

### PR DESCRIPTION
**Pull request by mrniaboc**

### CODE REVIEW

**Comment by mrniaboc** [comment]
Hahaha!

**Comment by mrniaboc** [comment]
"Merging can be performed automatically." O rly?

**Comment by mrniaboc** [comment]
@chrissnyder I think this is a very important commit to merge. We have multiple requests from volunteers saying they are leaving the site upon viewing my profile pic. It's harming the projects.

**Comment by chrissnyder** [comment]
Yes, but what about the silent majority that find the current picture captivating? Do we have any data to back up your anecdotes?

**Comment by aliburchard** [comment]
I vote for keeping the current image. We could poll zootown...

**Comment by camallen** [comment]
hard data, real internal panoptes project ?

**Comment by aliburchard** [comment]
best use of panoptes yet!

**Comment by mrniaboc** [comment]
This graph is of traffic to Zoo Home. The very right-hand edge is when I uploaded that profile pic...

image

**Comment by chrissnyder** [comment]
I can't argue with data.

**Comment by eatyourgreens** [comment]
Wait! Here's a much better picture of Grant http://ecx.images-amazon.com/images/I/71zI8rwWxHL._SL1305_.jpg

**Pull request merged**
