### PR TITLE
Rotate and Draw

### PR DESCRIPTION
**Pull request by simensta**
Addresses #2867 by adding a rotate feature to PanZoom and scaling drawn marks, handles, and delete buttons using a SVG transformation matrix. Staged [here](https://rotate-and-draw.pfe-preview.zooniverse.org/dev/classifier).

Describe your changes.
**frame-annotator.cjsx**: added methods for scaling marks using an SVG transformation matrix.

**[drawing_tool_name].cjsx**: uses a new method from frame-annotator, #normalizeDifference(), to scale the difference when the component is dragged. 

**pan-zoom.cjsx**: added a rotate feature. The reset button should also reset the rotation.

**delete-button.cjsx, drag-handle.cjsx**: scales SVG elements using a transformation matrix.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
## PR Review
Looking good so far! I'm still running tests across all browsers before I merge this PR. (And to give anybody else a chance to take a look at this.) Here are my current thoughts:

* I like how the coordinate inversion magic is packaged into `normalizeDifference()` and `eventCoordsToSVGCoords()`...
* ...and I feel that these are candidates to be included into a generalised 'Zooniverse SVG Library', should we ever get around to that. (The Zooniverse never has enough projects!)
* Code looks good and sensible to me, but I'm curious if another dev without as much matrix/transformation experience will be OK without more documentation.

## Test Plan
* On the Classifier,
* (1) I should be able to place a Point, e.g. on the Rhino's horn
* (2) I should be able to rotate the image 90 degrees and manipulate (move, adjust) the Point
* (3) I should be able to translate and zoom in on the _rotated image_ and manipulate the Point
* (4) I should be able to add a second Point, e.g. on the Rhino's ear, on the _rotated/translated/zoomed image_ 
* (5) I should be able to reset the image back to 0 degrees rotation, 0-0 translation, 100% zoom, and the Points should remain in the correct position.
* Steps 1-5 should be repeated with Lines, Rectangles, Circles and Polygons

* Testing on https://rotate-and-draw.pfe-preview.zooniverse.org/dev/classifier and localhost equivalent
* Testing on OSX+Chrome54/FF50/Safari9, Win7+IE11

## Status
Testing is ongoing; OSX+Chrome54 has passed all tests so far

**Comment by shaunanoordin** [comment]
## PR Review (Update)
The PR tests worked fine with **one** odd exception.

* On the Classifier, I can...
  * place and manipulate and delete...
  * a Point/Lines/Rectangles/Circles/Polygons...
  * on the Subject image whether it's rotated/translated/zoomed...
  * and the position of those markers would be maintained when the Subject image's transformation is reset.
* Tested on OSX+Chrome54/FF50/Safari9, Win7+IE11

However, on all browsers, the **Point** tool cannot be placed at **certain points** of the Subject image, when the Subject image is **rotated**.

In this example below...
screen shot 2016-12-13 at 12 33 38
...you can place a Point at the Rhino's foot (see first yellow arrow) but you can NOT place a Point at the Rhino's ear (see second yellow arrow)

## Analysis Notes
Yeah I'm not sure what's going on here. The Line and Polygon tools all work fine, so I suspect it might be something to do with the Point's singular click interaction (other tools have a click-and-drag interaction) combined with the fact that, maybe, the x-y coordinates of the Mouse Click event is somehow "Out of Bounds" with the original (wide, not tall) dimensions of the image.

If you're not certain about what I just wrote, don't worry, I'm confused too.

## Status
I'm leaning towards merging this and then investigating the Point + Rotation fix separately. Any thoughts from anybody else?

**Comment by simensta** [comment]
Hey @shaunanoordin, thanks for your review! I am working on a fix for the out-of-bounds issue with the point tool.

**Comment by shaunanoordin** [comment]
## PR Review (Update)
* Looking good to me!
* Point tool bug has been _fixed._ Points can now be placed on any part of the image, even when rotated/zoomed/translated.
* All other features - as a re-tested Test Plan shows - are also functional.
* `npm run test` shows no explicit errors and a happy nyancat.
* Tested on localhost with OSX+Chrome54/FF50/Safari9, Win7+IE11

## Status
LGTM, merging.

**Comment by denslowm** [comment]
Hi All,
Transcribers at Notes From Nature are enjoying the rotate tool. Thanks so much. We have received the following feedback so far:
the image window be made as tall as it is wide, so that parts of the labels don't get cut off when the image is rotated (or alternatively, the window size also rotates, or the image can be dragged around once rotated). 
If you take a look at one of the images at the link below you can see what is meant by images being cut off.
https://www.notesfromnature.org/active-expeditions/Magnified

**Comment by shaunanoordin** [comment]
Noted on your comments, @denslowm , and thank you for your feedback. The problem of rotations with tall/wide images is now formally filed under issue #3373

**Pull request merged**
