### PR TITLE
Supply frame for thumbnails src in discussion link

### LINKED ISSUE #1649: Broken thumbnails for discussion preview in Talk
I'm testing subject comments for the Wellcome project. When I list comments in Talk, the discussion preview thumbnail is trying to use the `text/plain` subject location, even though there is also a location with a MIME type of `image/jpeg`.
https://www.zooniverse.org/projects/eatyourgreens/diagnosis-london/talk/100/

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #1649

### CODE REVIEW

**Comment by brian-c** [comment]
Works for me, but should we just make the default `0`?

The default was set to the middle one because in Snapshot Serengeti, an animal moving in front of the camera would presumably be most likely centered in the middle image. Not sure if that ended up being true or if it matters.

**Comment by aweiksnar** [comment]
Cool, yeah that sounds good me. Just pushed to make that function have a default

**Comment by brian-c** [comment]
Sorry, mind deleting the old default?

**Comment by aweiksnar** [comment]
Yeah where at? I think that was the only one

**Comment by aweiksnar** [comment]
Ah sorry! thought you meant in the original call itself. Just took it out

**Comment by brian-c** [comment]
Thanks!

**Pull request merged**
