### PR TITLE
Add list of orgs a user owns to user admin page

### PR DESCRIPTION
**Pull request by mcbouslog**
Staging branch URL: https://admin-user-orgs.pfe-preview.zooniverse.org/
- [user with an organization](https://admin-user-orgs.pfe-preview.zooniverse.org/admin/users/1325836)
- [user without an organization](https://admin-user-orgs.pfe-preview.zooniverse.org/admin/users/1325844)

Describe your changes.
- misc linter clean-up
- edit related test to expect to Resource components
- create Resource component, refactor related code

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [ ] Can you submit a classification?
- [x] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by camallen** [comment]
@mcbouslog - out of scope so it's ok to say no. can you link the id of the org on this page to the lab links url so we can get straight there from the admin page? similar to #4148

**Comment by mcbouslog** [comment]
Have to be signed in to the lab app and have admin enabled for org lab links to work, but certainly helpful! Thanks Cam, great suggestion.

I've added refactoring the "Set organization status" admin section to a todo list. Among other things, it needs UX to filter by `listed: true`, which currently works if add `?listed=true` param.

**Comment by simoneduca** [comment]
Picking up from our Slack convo, @mcbouslog I can't see any difference between the two links above, i.e. user with/without org. But I might be looking in the wrong place.

**Comment by mcbouslog** [comment]
the key change is for the first link, user with an organization.

currently, if you go to that user, you won't see any orgs they've built, if they have built any: https://master.pfe-preview.zooniverse.org/admin/users/1325836

but with this PR, it will list any orgs they've built just like it does for projects they've built: https://admin-user-orgs.pfe-preview.zooniverse.org/admin/users/1325836

**Comment by mcbouslog** [comment]
cleaned up some linter errors and added prop validation

**Pull request merged**
