### PR TITLE
es6 conversion of stats page

### PR DESCRIPTION
**Pull request by CKrawczyk**
This PR converts the project stats page to ES6 using the airbnb style guide at a template.

~~Do not merge this until we are ready to bring the stats page back online (we have a holding page up at the moment due to API issues).~~

### CODE REVIEW

**Comment by camallen** [comment]
@CKrawczyk can you stage this and any other PR to a deploy branch for testing?

**Comment by CKrawczyk** [comment]
It is staged here: https://es6-stats-page.pfe-preview.zooniverse.org/projects/?env=production

**Comment by CKrawczyk** [comment]
I (finally) had some time to finish up the es6 conversion of the stats page.  The preview link has been updated and this is ready for review.

**Comment by srallen** [comment]
@CKrawczyk looks like there's a merge conflict now. Could you do a rebase? Also feel free to assign me and I can always reassign to someone else if I'm too busy.

**Comment by CKrawczyk** [comment]
I just rebased and updated staging.

**Pull request merged**
