### PR TITLE
Add bug warning to exports

### PR DESCRIPTION
**Pull request by rogerhutchings**
screenshot 2018-12-17 16 41 59

Adds a warning box to the data exports page for projects that have been affected by the recent workflow bugs. Projects are identified by id, and taken from the bug spreadsheet at https://docs.google.com/spreadsheets/d/15pIyy-MKKmSAdpresK4VSTlFfQFAs96DwUnZkzpMEck

This also converts the data exports page to ES6, and adds tests.

Status is currently blocked until wording is sorted out with @mrniaboc 

Staging branch URL: https://add-bug-warning-to-exports.pfe-preview.zooniverse.org/
- https://add-bug-warning-to-exports.pfe-preview.zooniverse.org/lab/825/data-exports?env=production

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by mrniaboc** [comment]
I think it would be good to add the two date ranges to the message to make it slightly less alarming.

**Comment by rogerhutchings** [comment]
Sure, what's the final word on the date range?

**Comment by mrniaboc** [comment]
6th-12th and 20th-29th November 2018.

Here's the link to the blog post
https://blog.zooniverse.org/2018/12/19/zooniverse-workflow-bug/. Can you
also add the instruction to Look for "translation_bug: true" please?

**Comment by mcbouslog** [comment]
I'll try and get this done asap.

This is what I've currently updated it to, though it feels like it could use an edit:
"Your project may have been affected by a bug which could compromise some of your data. The bug was effective between November 6-12, and 20-29, 2018. Your data export will reflect `translation_bug: true` if your data was potentially impacted. To read more, visit [the Zooniverse blog](https://blog.zooniverse.org/2018/12/19/zooniverse-workflow-bug/)."

I'm not sure if after "potentially impacted" it could use something along the lines of ", though that does not guarantee any data is compromised."

**Comment by mcbouslog** [comment]
Noting for easy ref staged branch and included project: https://add-bug-warning-to-exports.pfe-preview.zooniverse.org/lab/825/data-exports?env=production

I think we're using affective and effective properly, but seeing both in the same paragraph is making me nervous.

**Comment by mcbouslog** [comment]
@mrniaboc does the message look good? Otherwise I think this is good to go.

**Pull request merged**
