### PR TITLE
Add project prefix to user profile URLs when in project

### LINKED ISSUE #2866: User profile links are inconsistent within a project's Talk pages
If you click on a username from this page, https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/talk/115 it will take you to a user profile page for that project https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/users/StarwatcherHB

On other Talk pages, the username links back to the top-level Zooniverse profile
https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/talk/115/74131
https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/talk/recents

### PR DESCRIPTION
**Pull request by alexbfree**
Fixes a few places where I'd missed adding the project prefix - it was missing and wrongly sending people back to Zoo-wide context.

Thanks @eatyourgreens for spotting this.

Fixes #2866

### CODE REVIEW

**Comment by alexbfree** [comment]
Deployed to https://fix-bad-user-profile-links.pfe-preview.zooniverse.org/ in case you want to test.

**Comment by eatyourgreens** [comment]
Is the inbox used anywhere other than zooniverse.org/inbox? I'm not sure about modifying that, because the list of messages there will have come from people on a mixture of projects, so I'm not sure if there is a specific project context for the inbox.

Other than that, looks ok to me but I'm not very familiar with the Talk components.

**Comment by alexbfree** [comment]
good point about inbox. It would jump to the context of the project you are in, rather than the context of the message, which isn't what we want. i'll remove that one.

**Comment by eatyourgreens** [comment]
Yeah, private messages don't have a project context, as per #1868

**Comment by alexbfree** [comment]
Actually on second thoughts it wouldn't jump to a project context... it's impossible for @props.project to be set while viewing the inbox. So the links will remain without a project context. It'll make no difference to the rendered links (just tested this too)

I'll remove it anyway, in case we ever use that page from a project context.

**Comment by alexbfree** [comment]
ok @eatyourgreens that should be good to merge now. Thanks in advance.

**Pull request merged**
