### PR TITLE
Adds German translation to PFE

### LINKED ISSUE #5452: Add a German translation
Chimp and See would like to publish their project in German, so German language translations are needed in this file:
https://github.com/zooniverse/Panoptes-Front-End/blob/ae5d4c70b59445a09f3138ab2eeadc1c112d2fb0/app/locales/de.js

### PR DESCRIPTION
**Pull request by AnLand**
Provides a German translation for major parts of Panoptes Front-End. Missing texts will be provided in a second commit in a few days (FAQ, Education in the Zooniverse, How to volunteer). I will also hopefully catch any typos in this second commit.

Note: lines 266 – 287 (about publications) are part of the English en.js version, but not in the de.js file that I translated. I added these and translated them, but did not compare both documents furthermore. If there are other differences that need to be taken into account for the translation, please let me know.

Staging branch URL: https://pr-5460.pfe-preview.zooniverse.org

Fixes #5452.

Describe your changes.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Many thans for doing this work @AnLand. I've added your translation to the main project template, and you should be able to check it at this address. https://pr-5460.pfe-preview.zooniverse.org/projects/sassydumbledore/chimp-and-see/?env=production&language=de

I don't think the Publications page supports other languages at the moment, so translating that page is probably not so important.

**Comment by eatyourgreens** [comment]
Looks good to me!
Chimp & See home page in German.

**Comment by AnLand** [comment]
Looks good to me. Where can I translate the "Field Guide" button on the far right? I think that would be important for the project.

**Comment by eatyourgreens** [comment]
Good question. Looking at Variable Star Zoo in English and Spanish, Field Guide isn't translated. Looks like it is missing from the language files. https://www.zooniverse.org/projects/ilacerna/variable-star-zoo/classify

**Pull request merged**
