### PR TITLE
Small CSS fix to ensure vertical alignment of each member's image…

### PR DESCRIPTION
**Pull request by alexbfree**
...alongside their row (important for 4-line descriptions)

### CODE REVIEW

**Comment by chrissnyder** [comment]
Without playing designer, I disagree this is needed. I like the current behavior better.

**Comment by alexbfree** [comment]
OK well let's get a designer's opinion then - @jwbmartin what do you think? My view is that since there is no delineation between rows, the spacing looks messed up when descriptions flow onto four lines... e.g. see Chris Doogue's row:
screenshot

**Comment by jwbmartin** [comment]
I do agree that it is a little bothersome from a design perscpective, and this spacing changes depending on the size of the screen too. But on the list of things that need to be fixed this is probably not an extremely pertinent issue.

**Comment by DarrenMcRoy** [comment]
If it does ever get changed, maybe someone could look at #1226 too? :-)

**Pull request closed without merging**
