### PR TITLE
Upgrade to React 15

### PR DESCRIPTION
**Pull request by eatyourgreens**
Updates other react-\* modules to latest versions too.
Depends on zooniverse/markdownz#47

# Review Checklist
- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://react-15.pfe-preview.zooniverse.org/
## Optional
- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Seems OK on Win7+IE11

Tested OK:
* Logging in and logging out
* Viewing Home page, logged-in home page
* Browsing projects on Projects page
* Classifying in projects (basic radio button selection, circle marker, rectangle marker, basic transcribe, cropping)

**Comment by eatyourgreens** [comment]
There are warnings on the Talk and inbox pages because MarkdownEditor uses `defaultValue` and `value` together on a textarea. React 15 will says you can have one, but not both, so we have to choose.

**Comment by rogerhutchings** [comment]
Okay, looks like React 15 is pretty noisy when it comes to validating props and such, so there are a bunch of warnings elsewhere too - the site nav component. But I haven't found anything that doesn't work yet, so I reckon this is all good :)

**Comment by rogerhutchings** [comment]
That said, let's not merge and deploy today

**Comment by eatyourgreens** [comment]
Yeah, the `Link`, `Translate` and `PromiseRenderer` components pass their props through to their children, so will throw [unknown props warnings](https://facebook.github.io/react/warnings/unknown-prop.html) on HTML elements.

I've been going through cleaning up `...@props` when I've found it in the coffeescript. A lot of the time, it seems to be used to pass CSS classes and styles through to elements.

Speaking of which, should we move inline styles into the CSS files anyway? I don't like them because they're impossible to override.

**Comment by eatyourgreens** [comment]
@srallen looks like `react-select 1.0` introduces breaking changes. I'm going to try rolling back to `0.9.1`

**Comment by eatyourgreens** [comment]
#3233 updates `react-select`, which will fix the invalid peer warnings, when it's finished.

**Pull request merged**
