### PR TITLE
fix project backgrounds on staging API

### PR DESCRIPTION
**Pull request by camallen**
**Do not merge this till the API changes are deployed to production** - see https://github.com/zooniverse/Panoptes-Front-End/pull/5864#issuecomment-747553525

Linked to the API changes in https://github.com/zooniverse/panoptes/pull/3532 (note that change is only deployed to staging API  right now so this doesn't impact www.zooniverse.org.... yet)

use the project.avatar_src url from the API as it is now a valid URL (with scheme) and not a path only, thus the UI code can trust the url from the API and use this attribute directly vs using the `//` prefix.

Staging branch URL: https://pr-5864.pfe-preview.zooniverse.org/projects

Describe your changes.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Review by eatyourgreens — COMMENTED** [review]
Looks good to me. I'll hold off on approving and merging to production until the production API changes.

**Comment by camallen** [comment]
> Looks good to me. I'll hold off on approving and merging to production until the production API changes.

Right - i'm not sure when that will be and coupling these deploys might break things on the projects landing page. I can get another PR up to detect the `avatar_src` has a scheme and use the URL if present or the path if not. 

This PR can stand as a cleanup PR post production deploy.

**Comment by eatyourgreens** [comment]
👍 

Just to double-check that this change does break the live projects page: https://pr-5864.pfe-preview.zooniverse.org/projects?env=production

I think the project cards route is used for your recent projects on the home page too.

**Review by eatyourgreens — APPROVED** [review]
I can't remember what the code changes are doing but the staging site looks good. I didn't see any broken cards on the projects page, and the Gravity Spy home page looks good.

**Pull request merged**
