### PR TITLE
Replace all createClass calls with createReactClass and add required imports

### PR DESCRIPTION
**Pull request by tingard**
Staging branch URL: https://replace-react-create-class.pfe-preview.zooniverse.org/

Fixes use of `React.createClass` by replacing with `createReactClass` from `create-react-class` as detailed [here](https://reactjs.org/docs/react-without-es6.html).

Used a python script [temporarily hosted here](https://www.dropbox.com/s/xtds2x47te3gydq/fixPfeCreateClassPropTypes.py?dl=0) (TODO set up a repo) to automatically replace all instances of `createClass` in zooniverse.

Others also running the script and checking all required files are changed would be appreciated.

Script can also be used to replace `React.PropTypes` with `PropTypes` from `react-prop-types`.

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by tingard** [comment]
I've realised it would be better to run the Facebook plugin first, as it cleverly creates classes sometimes, rather than blindly moving to `create-react-class`. Worth re-doing things in that order?

**Comment by eatyourgreens** [comment]
Sounds like it's worth trying.

**Comment by tingard** [comment]
After reading through [all this](https://github.com/reactjs/react-codemod#explanation-of-the-new-es2015-class-transform-with-property-initializers) I've become prohibitively paranoid that I'm not being nearly careful enough, and that something has almost definitely broken here.

**Comment by eatyourgreens** [comment]
I'm happy to stage this on Monday, so we can check if anything broke. Unfortunately, the files that this changes will mostly be ones that haven't had tests written yet.

**Comment by eatyourgreens** [comment]
Staged at https://replace-react-create-class.pfe-preview.zooniverse.org/?env=production

**Comment by eatyourgreens** [comment]
> I've realised it would be better to run the Facebook plugin first, as it cleverly creates classes sometimes, rather than blindly moving to create-react-class. Worth re-doing things in that order?

Would it make sense to run the Facebook codemod across javascript files, and use the Python script only to convert coffeescript?

Staging branch looks good, from a preliminary browse around the site and doing a few classifications.

**Comment by tingard** [comment]
I tried the codemod over the weekend and it did break things, working today to understand why.

This PR is only a first step towards react 16, there's a fair few calls to depreciated functions as far as I can see, so definitely worth going via 15.6 and watching for console warnings, as that should be easier to debug. This is what I'll spend a majority of this week on I think.

**Comment by tingard** [comment]
Cool, ~16 jsx files now using `class __ extends React.Component`, rest on `createReactClass`. All cjsx components on `createReactClass`.
Easy enough to do the same for `PropTypes` in a different (same?) PR, though I'll just use the python script as it's a simple switch.
From there I'll create a new branch and attempt the react-15.6 switch, see what pops up and report back to slack because I'll probably be a little out of my depth.

**Comment by eatyourgreens** [comment]
Cheers. I've pushed the latest changes to https://replace-react-create-class.pfe-preview.zooniverse.org/

If nothing major comes up on this branch, I'd say merge it and deal with the React and PropTypes upgrades in separate PRs.

**Comment by mcbouslog** [comment]
I also tried a handful of what I thought are typical actions on staging (classifying, messaging, collecting, logging in/out, etc.) and encountered no issue. Thanks @tingard!

**Comment by eatyourgreens** [comment]
Looks like this needs an update because `ActiveUsers` was converted to ES6.

**Pull request merged**
