### PR TITLE
Fix min/max for drawing tools

### LINKED ISSUE #3014: Small bugs in Project Builder markings tasks
## Expected behavior
~~1. Checkbox for "Clone markers in all frames" should stay checked once checked.~~
2. Min and Max boxes for tool types should have minimum of 0 and a way to select 'infinity' for Max. 

## Current behavior
~~1. On refresh, "Clone markers in all frames" becomes unchecked in the Project Builder interface (but task behavior remains).~~
2. Min and Max boxes can take on negative values. Once the Max box is changed to a non-infinity number, there's no way to change it back to 'infinity'. And having played with these boxes a bit, they have become stuck, and I can no longer change them. Buggy.

## Steps to replicate
~~1. Check "Clone markers in all frames". Refresh browser page.~~
2. Click the up and down buttons next to Min and Max a bunch. Click and change them by keyboard, too. At some point they'll stop behaving properly.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fixes #3014 .

Describe your changes.
Deletes max/min keys from a drawing tool when their value is an empty string.
Sets some sensible minimum values for min and max number of points.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://fix-min-max.pfe-preview.zooniverse.org/

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I'd be much happier if this removed the `min` and `max` keys from a tool when the value is an empty string.

Also, it looks like you can set `max < min` and save those values, or set either value to a negative number and save.

**Comment by simoneduca** [comment]
Is this still WIP or is it ready for review?

**Comment by eatyourgreens** [comment]
Feel free to leave comments, but I wouldn't be happy merging this at the moment as I'm not sure what side effects would be produced by the changes to `handle-input-change`.

**Comment by simoneduca** [comment]
I see. An idea would be to not using the `handle-input-change` at all by having the min-max settings in a little component with its own logic and event handling.

**Comment by eatyourgreens** [comment]
I like that idea a lot better than changing the change handler for all project builder input fields. Maybe have our own number input component that validates its value before calling the change handler.

**Comment by srallen** [comment]
I've come across the `handle-input-change` handler before and decided not to use it with a new feature I added. IMO, it's an abstraction that isn't helpful in all cases. It's inconsistently used in the code base and I'm of the opinion that it'd be better to have separate handlers/components for more specific use cases even if it means a bit of code repetition.

**Comment by eatyourgreens** [comment]
@srallen Agreed. There's a component now with its own change handler. I still need to add some more validation of the fields, as I think it's still possible to save null or empty values, which might mess up the front-end display of the tool. However, it should stop you from entering a max value which is smaller than the min value.

**Comment by eatyourgreens** [comment]
Updated to remove the min/max keys from the drawing tool if their values are empty strings. This should be ready now.

**Comment by shaunanoordin** [comment]
Code looks fine to me, so here're the user tests.

Test Description
* We're testing two linked features:
* (1) Users can set a drawing tool's Min/Max values on admin, and these values can be blank.
  * We're testing four permutations of Min/Max values: blank/blank, 1/blank, blank/3, 1/3.
* (2) Once set, Min/Max values for the drawing tools are stated clearly on Classify interface
  * e.g. with text "X of 1 required, 3 maximum drawn" for Min/Max values of 1/3.
  * e.g. with text "X of 1 required" for Min/Max values of 1/blank.
* Known quirk: Users can manually type in negative numbers into Min or Max fields.
* Known quirk: Users can manually set Min value to be larger than Max value.

screen shot 2016-09-19 at 17 46 57
_Setting Min and Max values in the admin_

screen shot 2016-09-19 at 17 47 38
_The Min and Max values reflecting correctly on the Classify interface._

Test Results:
* OSX+Chrome53: OK
* Win7+IE11: OK, with a quirk...
  * Min/Max `<input>` boxes on the admin appear to be normal `type=text` boxes instead of `type=range`
* OSX+FF48: OK
* OSX+Safari9: OK

Status: LGTM! Will merge in 3 hours unless someone wants to add their comments.

**Comment by eatyourgreens** [comment]
Thanks @shaunanoordin Updating the min value to larger than the max value should now update both.

**Comment by shaunanoordin** [comment]
Status: Nice one! Update looks good to me.
Actions: Merging

**Pull request merged**
