### PR TITLE
Add support for another custom Gravity Spy feedback message

### PR DESCRIPTION
**Pull request by srallen**
In anticipation of the announcement next Thursday, this adds support for subjects that have the specified metadata fields to show a custom message. We should get this merged by Tuesday next week at the latest.

CC @rogerhutchings we'll need to consider adding into the generalized feedback feature a way for projects to show a custom feedback message regardless of the annotation. I would have liked Gravity Spy to use the new generalized feedback feature, but I don't think it is designed to handle this use case even if we had survey task support added. 

This test project has a couple of subjects labelled as 'special' that comes up and has a feedback message that says 'congrats': https://gs-special-event-feedback-message.pfe-preview.zooniverse.org/projects/markb-panoptes/gravity-spy-gold-standard-notice-test-project/classify

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by rogerhutchings** [comment]
Sorry, not sure I understand exactly what circumstances you need a special message for. Any message, success or failure, can be custom set on a subject metadata field with generalised feedback. It doesn't support survey tasks yet, however.

**Comment by srallen** [comment]
They want this message to show up for these subjects regardless of success or failure of the annotation. I might have missed it, but I think the way the feedback works now checks the annotations against the correct answers?

**Comment by rogerhutchings** [comment]
Got it. So actually, maybe this needs to be a feature outside of feedback _anyway_. We could create a metadata field called something like `#post_classification_message`, and add in an additional hook for it in the classification summary component if it happens to exist?

**Comment by rogerhutchings** [comment]
Took me a while to get through to a 'special' subject, but saw the message as expected. LGTM

**Comment by srallen** [comment]
Yeah that would work. I'll open an issue up about it. Thanks!

**Comment by eatyourgreens** [comment]
Is this going to be another piece of UI text that can't be translated, since it's stored in the subject metadata?

**Comment by srallen** [comment]
Yeah, this would have the same issue with translation as the other metadata based content.

**Pull request merged**
