### PR TITLE
Update fr.js

### PR DESCRIPTION
**Pull request by Orohena**
French version by Flavie from line 259 to the end.

Staging branch URL: https://pr-5505.pfe-preview.zooniverse.org?language=fr

Fixes # .

Describe your changes.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Thanks very much for this! Just waiting for tests to pass so that we try it out on a copy of the web site.

**Comment by eatyourgreens** [comment]
https://pr-5505.pfe-preview.zooniverse.org/?language=fr&env=production to try this out with live projects.

**Comment by eatyourgreens** [comment]
I'm not sure but I think Chimp & See is the only project available in French at the moment:
https://pr-5505.pfe-preview.zooniverse.org/projects/sassydumbledore/chimp-and-see?language=fr&env=production

**Comment by trouille** [comment]
Translation looks great!

In spanish, the translation changes the 'lab' tab to 'laboratorio'. For consistency, we could have the French translation change the 'lab' tab to 'laboratoire'.

**Comment by AnLand** [comment]
> Another minor edit is to capitalize 'Evolutive' in l'institut Max Planck d'Anthropologie évolutive on the landing page 'about' info (near the bottom of the page).

> And a final suggestion is: to update "Que peuvent nous apprendre les comportements des chimpanzés sur les origines de l'humanité? to "Que pouvons-nous apprendre sur les comportements des chimpanzés sur les origines de l'humanité?"

These parts are not part of the general translation file, but translations of the Chimp&See science team via Pandora. This can't be done by @Orohena in this file, but maybe by @gabocks or you need to directly contact the science team.

**Comment by Orohena** [comment]
> I'm not sure but I think Chimp & See is the only project available in French at the moment:
> https://pr-5505.pfe-preview.zooniverse.org/projects/sassydumbledore/chimp-and-see?language=fr&env=production

I think it is the only one yes, but if someone want me to translate other project in french, let me know. It was nice to do.

**Comment by Orohena** [comment]
> Translation looks great!
> 
> In spanish, the translation changes the 'lab' tab to 'laboratorio'. For consistency, we could have the French translation change the 'lab' tab to 'laboratoire'.
> 
> Another minor edit is to capitalize 'Evolutive' in l'institut Max Planck d'Anthropologie évolutive on the landing page 'about' info (near the bottom of the page).
> 
> And a final suggestion is: to update "Que peuvent nous apprendre les comportements des chimpanzés sur les origines de l'humanité? to "Que pouvons-nous apprendre sur les comportements des chimpanzés sur les origines de l'humanité?"

As @AnLand said, it was not part of my translation bit of Zooniverse in general.
I also would suggest, for Chimp and See, to put MonkeySee in brackets next to the french translation, or to translate the button, so people don't get confuse. Right now, we see "Singe – Je te vois" and then on the button it says "MonkeySee". (I think we will have the same issue with Ungulate identification. Maybe you @trouille or @gabocks can change that ?

**Comment by eatyourgreens** [comment]
Sounds like this can be merged. Any small changes can be made in a separate PR.

@Orohena if you'd like to help translate Chimp & See, ask the project team to add you to their project as a translator. They can do that in the project builder. When that's done, you can log in to https://translations.zooniverse.org and edit translations for individual projects.

**Pull request merged**
