### PR TITLE
Fix internal links for comments

### LINKED ISSUE #2798: if you go to a subject page directly from a link posted in a talk post it shouldn't go to the zoomed out
If you click on the links to the subject pages in a Talk post non-logged in, it switches back to the zoomed out menu. If you've dismissed the bar it should stay down I think if you're navigating within Talk

https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/213/68083?comment=130663

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fixes #2798 .

Describe your changes.
Replaces `<a>` with `<Link>` for internal links, so that the page doesn't reload when the link is followed.

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://fix-2798.pfe-preview.zooniverse.org/?env=production

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Pinging @srallen and @parrish in case they know of any other places in the code where links need to be updated.

**Comment by parrish** [comment]
It wasn't a relative link because we wanted to provide an absolute link as the permalink.

This would be fine if the link text included `window.location.origin`

**Comment by eatyourgreens** [comment]
@parrish Thanks! Comment permalinks should be fixed now.

**Comment by eatyourgreens** [comment]
It occurs to me that the project page reloading (and zooming back out) problem will still occur for links inside markdown text, but I'll leave that as a separate problem.

**Comment by srallen** [comment]
LGTM

**Pull request merged**
