### PR TITLE
Updating styling for images in tool labels

### PR DESCRIPTION
**Pull request by alexbfree**
Vertically middle align with text
Add slight padding so that when embeded with text they have room to breathe.

### CODE REVIEW

**Comment by alexbfree** [comment]
deployed here if anyone wants to test https://tool-label-styling.pfe-preview.zooniverse.org/projects/alexbfree/computer-vision-serengeti/classify?env=production

**Comment by alexbfree** [comment]
before:
screenshot 2016-05-06 12 18 22

after:
screenshot 2016-05-06 12 19 11

(suggestions welcome on how to vertically align the rectangles too - but don't delay the merge of this PR while we discuss that, as would like to have this in ASAP for project launch)

**Comment by simoneduca** [comment]
Would adding `padding-top` suit?
screen shot 2016-05-06 at 12 17 58

**Comment by alexbfree** [comment]
@simoneduca it would for this project; but need a solution that'll work for any project - we can't know the height of the label or image(s) in advance

**Comment by alexbfree** [comment]
thanks for merge!

**Pull request merged**
