### PR TITLE
Add break-word styling to anchor

### LINKED ISSUE #4691: styling issue of the anchor tag within the markdown (wrapping text in tutorial)
## Expected behavior
Be able to wrap URL text to fit within tutorial window

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

text does not get wrapped (see link below)

## Steps to replicate
see: 
https://www.zooniverse.org/projects/zooniverse/notes-from-nature/classify?reload=1&workflow=6014&_ga=2.184423526.1576714224.1528666194-301989501.1485808297

See the last page of the Tutorial there.

## Additional information
Some further discussion here: #4659 

- **Operating system:**
OS X 10.11.6

- **Browser:**
Chrome

### PR DESCRIPTION
**Pull request by mcbouslog**
Staging branch URL: 
- (metadata info) https://metadata-link-styling.pfe-preview.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9/talk/subjects/13772456?env=production
- (last page of tutorial) https://metadata-link-styling.pfe-preview.zooniverse.org/projects/zooniverse/notes-from-nature/classify?reload=1&workflow=6014&env=production

Fixes #4691, #5095 

Adds `word-break: break-word` and `overflow-wrap: break-word` styling to anchors.
Would a new/specific class for the above linked instances be preferred? 
The anchors are nested with `markdownz`.
I navigated around the site and anchors appear to look normal otherwise, but certainly could be missing something.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I think NfN should be reminded that it's not good to have bare URLs embedded in tutorials, like the second example above. Links should be easy to read!

**Comment by eatyourgreens** [comment]
With this styling, links are being wrapped mid-word on the FAQ page, which is not great.
https://metadata-link-styling.pfe-preview.zooniverse.org/about/faq

**Comment by mcbouslog** [comment]
Nice catch! Yes that looks bad. I changed it to `word-break: break-word` and I think it looks ok, better?
screen shot 2018-11-28 at 10 49 50 am

**Comment by eatyourgreens** [comment]
Sounds good but [probably won't work in Firefox or IE](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#Browser_compatibility).

**Comment by eatyourgreens** [comment]
Looks like [`overflow-wrap: break-word`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) has better browser compatibility.

**Comment by mcbouslog** [comment]
`overflow-wrap` isn't working for me, but I think the issue may lie with `[standard-table](https://github.com/zooniverse/Panoptes-Front-End/blob/master/css/tables.styl#L1)`, or at least something to do with the table width. I can limit the width when I set a specific pixel on the subsequent `td`, but attempts with %'s or similar don't limit the width.

**Comment by mcbouslog** [comment]
It doesn't make sense to me per the MDN compatibility docs ([`overflow-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap#Browser_compatibility) and [`word-break`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#Browser_compatibility)), but `overflow-wrap` doesn't get the desired result for Chrome or Safari while `word-break` does. Firefox works as desired with `overflow-wrap`. I couldn't get anything to work with IE or Edge (even using the old `word-wrap` as noted above and in https://caniuse.com/#feat=wordwrap), though it looks like Edge 18 should work.

Is it ok to cover what we can with `overflow-wrap` and `word-break`? I don't like it, but maybe it's ok.

**Comment by eatyourgreens** [comment]
One of the nice things about CSS is that parsers skip past declarations they don't understand, without breaking, so you could include both rules in the stylesheet, in an order that catches most browsers.

Each browser will have its own implementation of word wrapping at the end of lines, so I don't think you can expect the same results in every browser anyway.

**Pull request merged**
