### PR TITLE
Remove the main layout overlay

### LINKED ISSUE #2787: A way of removing the extra click for non-logged in users on the landing page
The new Zooniverse navigation header layout now reveals the zoom out with the Zooniverse navigation bar if you're not logged in the first time.  I really appreciate that panoptes front end now shows that  when you first get to the first project page to help get people to login  but  because of the  zoomout you have to click once to zoom in and hide the bar and the blue sides and then once to click Get Started!  I find that a bit weird and I think new people will find it weird when they try to click on the Get Started! button that it doesn't just go. As the goal is get people in fast who are checking out the site, is there something that can be done to make it one click?

What about removing the blue sides so it's just the top blue navigation bar appearing and disappearing, then it wouldn't be a zoomout, zoomin which might save the click?

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fixes #2787

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Staged at https://delete-layout-overlay.pfe-preview.zooniverse.org/

**Comment by chrislintott** [comment]
Do not merge without talking to me. #

**Comment by eatyourgreens** [comment]
Looks like clicking on a project page zooms it out to full size, except on the Classify page. I'm not entirely sure why that's happening, but the behaviour should be consistent.

**Comment by srallen** [comment]
Seems that there's an issue with drawing tools or at least the point tool. When zoomed out, the marks are off. Try it out here: https://delete-layout-overlay.pfe-preview.zooniverse.org/projects/srallen086/srallen-test/classify?workflow=1817

Navigating between pages zooms back in. If someone chooses to stay zoomed out, it should be consistent between pages.

**Comment by mschwamb** [comment]
Also if possible can the subject size not change with the zoom out. The main goal of these sites is to review and classify the image/data presented so from a science team perspective if there's a way to keep the image size regardless of whether you have the blue border visible to see the account info or whether you hide it, I would greatly appreciate that.  


Subject image when the border on the left and right aren't showing

screen shot 2016-07-27 at 5 39 28 am

same subject image when the border showing (it's slightly smaller)
screen shot 2016-07-27 at 5 39 21 am

**Comment by eatyourgreens** [comment]
@srallen I've removed the listener that zoomed in when you navigated between views. Is that any better? Worse?

Looks like the CSS transform that's used to rescale the page messes up the calculation of subject image scale for the drawing tools. Fixing the image size might be tricky with flex display, since we essentially let the browser determine the image size, based on the user's display size.

I'm marking this 'Do not merge' because of the drawing tool bug.

**Comment by eatyourgreens** [comment]
@srallen I've confirmed that drawing tool bug on the live site too: #2836

**Comment by jwbmartin** [comment]
Since Brooke has complained that people can't figure out that the logo is the menu we could just add the word menu beneath it 

Example:
screen shot 2016-07-29 at 10 22 12 am

**Comment by jwbmartin** [comment]
The screen was supposed to zoom out a bit because I really wasn't imagining people having the navigation open and trying to classify at the same time since the whole goal was to reduce the clutter.

**Comment by mschwamb** [comment]
@jwbmartin  adding in 'menu' or something that indicates that you can click the zooniverse icon to logout helps with #2800 but if you're going to add in the notifications as an icon and then hide it on the blue bar isn't helpful for the reasons I've argued in  #2825  

The reason I'm harping on this is because the way the original design was, it was not clear or apparent that you can login with /register for a Zooniverse account to classify.  It promoted classifying not-logged in and research teams get way more information about a person if they login (we can track them better for weighting schemes and such and we get their email for newsletters).  This is why I opened #2733 Right now I'm generating gold standard classification data for Planet Four: Terrains and with  I have to be logged in so I can pull out the classifications later. With the current setup, I have to sign in and then always double  check again I'm logged in and my avatar is showingbecause there's now nothing on the project page that indicates I'm logged in other the addition of the Notifications link.  

I get why you might want to hide the Zooniverse navigation, but I don't get why the account profile/logout/login and mailbox, the proposed notifications icon  buttons can't be moved  next to the Zooniverse icon at  the project level.  That would be the simplest solution if you want to keep the Zooniverse navigation bar hidden. Honestly with the blue bar you've setup, it now for me clearly differentiates the two navigation menus, but if you want to still hide the Zooniverse menu that's fine by me as long as there's an obvious way to register, login/logout and access your notifications.

**Comment by eatyourgreens** [comment]
Rebased to remove merge conflicts, and taking off the "do not merge" now that #2836 is fixed.

**Comment by srallen** [comment]
PR LGTM for resolving #2787. Will open separate issue for adding 'menu' to the project nav zooniverse logo.

**Comment by jwbmartin** [comment]
I'm still trying to work out so sort of solution for these problems so sit tight

**Pull request merged**
