### PR TITLE
Add ability to edit a discussion's title

### LINKED ISSUE #813: Can't edit the title of a Talk thread
There currently appears to be no way to edit the title of a thread that you start in Talk.

screen shot 2015-06-25 at 6 51 03 pm

Can edit the post, not the thread title?

### PR DESCRIPTION
**Pull request by chrissnyder**
- Closes #813

### CODE REVIEW

**Comment by edpaget** [comment]
Who can edit the title? I just made a discussion, but I can't edit it.

**Comment by chrissnyder** [comment]
You should be able to edit title's of discussions you create. If you can't , then something is wrong.

**Comment by edpaget** [comment]
Yeah I see a Not Allowed to edit this discussion in the console, but there's no error in the UI

**Comment by chrissnyder** [comment]
Alright, I'll take a more thorough peek at it tomorrow.

**Pull request closed without merging**
