### PR TITLE
Enable additional webpack config options

### PR DESCRIPTION
**Pull request by rogerhutchings**
Allows webpack to pass in additional environment variables used to configure the Panoptes Javascript Client, and adds a note to the README explaining them.

Ultimately I'd probably like these to be in an `.env` file, we'd have multiple `.env`s for our environments, and no environment variables set in `package.json`.

cc #5586.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Code changes look good, let me run the build locally to confirm.

**Comment by eatyourgreens** [comment]
Do these need to be added to the docker-compose setup?
https://github.com/zooniverse/Panoptes-Front-End/blob/538b01a1488690873ce6d87b23fbb4c22c653933/docker-compose.yml#L13-L19

**Comment by eatyourgreens** [comment]
https://pr-5597.pfe-preview.zooniverse.org/ is showing info from the staging API, so the Jenkins build looks good.

**Comment by rogerhutchings** [comment]
> Do these need to be added to the docker-compose setup?
> 
> https://github.com/zooniverse/Panoptes-Front-End/blob/538b01a1488690873ce6d87b23fbb4c22c653933/docker-compose.yml#L13-L19

Couldn't hurt!

**Pull request merged**
