### PR TITLE
Use markdown in profile private message form

### LINKED ISSUE #1033: Size of the private message text box is extremely small
low in the queue, The current reply box for a private message is not very user friendly in terms of size. It's only big enough to view one or two lines. I'm constantly resizing it

Can it be made longer by default? 

Below is what size it looks like for me on Firefox

screen shot 2015-07-11 at 8 07 48 am

screen shot 2015-07-11 at 8 02 30 am

screen shot 2015-07-11 at 8 19 45 am

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #1033

### CODE REVIEW

**Comment by aweiksnar** [comment]
Closes #937 too

**Comment by edpaget** [comment]
Can we do a `max-width`?

**Comment by aweiksnar** [comment]
I just set overflow to auto on the footer in 47bbb89 which should fix that site width issue. Let me know if that works for you

**Comment by edpaget** [comment]
Sorry I meant on this page
screenshot from 2015-07-24 12-53-29

**Comment by aweiksnar** [comment]
Ahh gotcha, for line width, not overflow! Yeah I'll set that

**Comment by edpaget** [comment]
:ok_woman:

**Pull request merged**
