### PR TITLE
Talk sidebar

### LINKED ISSUE #892: Having the talk sidebar show up everywhere in Talk
low in the queue, but this might be a simple adjustment so I'm suggesting it now - For helping promote hashtags, I was wondering if the side bar you see on the front Talk page could be everywhere  in Talk so that when you're in a discussion you can see the most popular hashtags like you can on Talk 2.0. Also would help with fast transitions between project Talks

screen shot 2015-06-30 at 11 30 01 am

compared to

screen shot 2015-06-30 at 11 36 37 am

### PR DESCRIPTION
**Pull request by parrish**
Organizes talk sidebars and makes them consistent throughout talk.

Closes #892 
Related to #1017

### CODE REVIEW

**Comment by parrish** [comment]
Believe it or not, the `min-width: 1px` is actually required.

In Firefox (and IE I think), `max-width` is broken inside `display: flex` containers.

Don't ask me ***why*** that fixes it though.  :rage4: 

flex

**Comment by parrish** [comment]
Also, this does feel like a bit of duplication, but I'm not sure how to approach refactoring this.

The flex layout from `talk-list-content` needs to come from the layout using the sidebar.  Also, different views have different items (or project contexts) available -- e.g. recent comments.

**Comment by srallen** [comment]
@parrish, this might be the same issue I encountered with flex that fixed in #1750. According to the bugzilla reports I linked to, Mozilla devs are saying this is how the flex spec should be working and that a min-width or max-width should be specified:

> Basically: flex items will refuse to shrink below their minimum intrinsic width, unless you explicitly specify "min-width" or "width" or "max-width" on them.

> You get the expected result if you add "min-width: 0;"

**Comment by parrish** [comment]
Wacky.  Most of the issue came from the image tag.

> flex items will refuse to shrink below their minimum intrinsic width

I don't think this is *entirely* an issue with the intrinsic width of the flex child.  I think it had more to do with how that width propagated through the child elements (and vice-versa through the percentages).

On the image:

  - `max-width: 100%` worked, but used the wrong width (larger than the parent), so it broke the flex layout
  - `width: 100%` worked great, except for images that were smaller than the parent.

On the flex children:
  - `width: 100%` and `max-width: 100%` didn't affect the image.
  - `min-width: whatever` caused the `max-width` on the image to work correctly.

In any case.  Yay CSS.  :broken_heart:

**Comment by aweiksnar** [comment]
Yeah agree that the sidebar doesn't work as part of the talk base view component. I'm hoping that in the next talk design iteration the sidebar format will be changed up, but this looks great until then.

Do the sugarClient subscriptions need be moved to the top level route-handlers now? `/talk/index` & `/pages/talk` so they don't unsubscribe when the board view unmounts

**Comment by parrish** [comment]
Good catch.  I'll look at a more general fix for sugar subscriptions

**Comment by parrish** [comment]
Should be fixed now.  Thanks!

**Comment by aweiksnar** [comment]
:shipit:

**Pull request merged**
