### PR TITLE
Project home page: translate workflows

### LINKED ISSUE #5451: 'Choose a workflow' section on project home does not use translations
The workflow description, and workflow titles, are not using translations.

@eatyourgreens There's a new text section "workflow description" that we translated in Pandora but when previewing the translations, it keeps appearing in English. 
Is that a bug or something that just won't display translated anytime soon (like the workflow names)?Here's what I mean - the text above the workflow buttons: 

ysh_Screenshot_2019-07-11_09-23-48

It would really help if it was understandable since the names cannot be translated now.
Thanks.

_Originally posted by @yshish in https://github.com/zooniverse/pandora/issues/146#issuecomment-510364799_

### PR DESCRIPTION
**Pull request by eatyourgreens**
Staging branch URL: https://pr-5626.pfe-preview.zooniverse.org

Fixes #5451.

Connect up the project homepage workflow buttons to the redux store. Display translations for the workflow display names.

Chimp & See with workflow names in English.
https://pr-5626.pfe-preview.zooniverse.org/projects/sassydumbledore/chimp-and-see?env=production

Chimp & See with workflow names in German.
https://pr-5626.pfe-preview.zooniverse.org/projects/sassydumbledore/chimp-and-see?env=production&language=de

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [x] Can you post a talk comment?

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by wgranger** [comment]
This code looks good, but I'd like to double check switching between projects with translations. Do we have any active projects using translations aside from Chimp & See?

**Comment by eatyourgreens** [comment]
There must be a bunch of translated projects now but I can't think of any names off the top of my head.

**Comment by eatyourgreens** [comment]
I'm pretty sure Galaxy Zoo is available in other languages. Maybe Penguin Watch too.

**Comment by wgranger** [comment]
I found a few projects using translations. Looked good when switching between projects on several browsers. Going through the checklist, everything looked good. The only discrepancy was WWT tests passing on Travis, but not locally. However, that is a separate issue unrelated to this branch.

LGTM, merging.

**Pull request merged**
