### PR TITLE
Add anchored ellipse tool

### PR DESCRIPTION
**Pull request by srallen**
Staging branch URL: https://add-anchored-ellipse-tool.pfe-preview.zooniverse.org/

Supersedes #4681. This adds a new type of ellipse tool that is centered in the subject and can't be moved. 

It's the second step on my test project: https://add-anchored-ellipse-tool.pfe-preview.zooniverse.org/projects/srallen086/srallen-testing/classify
  - I have two kinds of subjects, one envelope and one letter, so you can see it centers in various kinds of subjects.

Also testable in the dev classifier: https://add-anchored-ellipse-tool.pfe-preview.zooniverse.org/dev/classifier

@tlalka I've enabled the tool on production using this staged branch for Spiral Graph (using `?env=production` query param in the URL): https://add-anchored-ellipse-tool.pfe-preview.zooniverse.org/?env=production

I've converted it ES6 javascript and also modified the tool slightly to be centered by calculation rather than a fixed x and y that only works for Spiral Graph. 
Does this work for the project?

@rogerhutchings, @mcbouslog whoever has time to review, please assign and/or remove yourself if you can't.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Looks good to me. On my phone, it's easy to place two ellipses by accidentally tapping the screen twice, so maybe enforce a maximum of 1 shape when using this tool in a project.

**Comment by eatyourgreens** [comment]
If it helps to simplify the calculation of the initial position, the subject dimensions are already passed as props to the drawing mark here: https://github.com/zooniverse/Panoptes-Front-End/blob/c52965c51b3f67d48cbe4f8598fe8acc4d953727/app/classifier/annotation-renderer/svg.jsx#L103-L104

**Comment by srallen** [comment]
@eatyourgreens thanks for the suggestion. That is a simpler calculation.

**Comment by tlalka** [comment]
Awesome! How or when can I get access to use this tool on my zooniverse project?

**Comment by srallen** [comment]
@tlalka The new code finished deploying a few minutes ago and it's enabled for Spiral Graph. You should see it in the project builder in the list of other available drawing tool.

**Pull request merged**
