### PR TITLE
Modal feedback: keyboard focus management and styling

### PR DESCRIPTION
**Pull request by eatyourgreens**
Staging branch URL: https://modal-feedback.pfe-preview.zooniverse.org/

Fixes some of the points raised in #4320.

Adds autofocus behaviour to the feedback popup, and traps focus until the modal is closed. Changes the order in which feedback is checked, so that feedback can steal focus from the task navigation buttons when it opens.

Also adds some basic styling to the OK button and restricts the height of large subjects to around 60% of the viewport height.

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [x] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by mcbouslog** [comment]
This is outside of the scope of this PR, but just noting feedback hasn't initially been designed to support multiple tasks, as demonstrated with this staging workflow - https://modal-feedback.pfe-preview.zooniverse.org/projects/markb-panoptes/feedback-testing-mb/classify?reload=0&workflow=3147, the feedback will load prematurely.

**Comment by eatyourgreens** [comment]
Rebased and restaged. The classifier update in #4295 might also mean that feedback is triggered more often now than it should be.

**Comment by eatyourgreens** [comment]
> This is outside of the scope of this PR, but just noting feedback hasn't initially been designed to support multiple tasks, as demonstrated with this staging workflow - https://modal-feedback.pfe-preview.zooniverse.org/projects/markb-panoptes/feedback-testing-mb/classify?reload=0&workflow=3147, the feedback will load prematurely.

Looking at that workflow in the project builder, you've set up feedback for the question task, but not for the drawing task. I've updated the workflow and added feedback for the drawing task.

**Comment by eatyourgreens** [comment]
Having said that, PFE still only renders feedback for the question task, but not the drawing task. Something is broken in the way that feedback rules are parsed, I think. Probably a big enough problem to warrant its own issue/PR, rather than trying to fix it here.

**Comment by eatyourgreens** [comment]
Finding more bugs in the original feedback code, now that I'm looking at @mcbouslog's test workflow. I'm going to merge this and we can deal with those later.

**Pull request merged**
