### PR TITLE
Add autocompleting field for tagging projects

### PR DESCRIPTION
**Pull request by edpaget**
...in the Project Lab details page

### CODE REVIEW

**Comment by edpaget** [comment]
Still waiting for design stuff for tag search on the main projects page. This just adds a field to project details for adding tags.

**Comment by edpaget** [comment]
Also there's a bug were you can't delete the last tag from a project at the moment. It's a backend issue I will have a fix for soon.

**Comment by brian-c** [comment]
This doesn't seem to register a change unless it autocompletes, and it doesn't autocomplete unless the tag has been used before.

Looks like tags are resources, so should these be links instead?

**Comment by edpaget** [comment]
@brian-c it should complete the tag when you type a comma. I don't want to implement it as a resource link, so you don't have to search the tags resource first to find ids.

**Comment by edpaget** [comment]
I will set it up so clicking out side converts whatever remains to a tag too though.

**Comment by edpaget** [comment]
@brian-c changed it to add the current tag when you blur the tag input. Let me know if that works for you.

**Comment by brian-c** [comment]
Cool, works for me.

**Pull request merged**
