### PR TITLE
update utils to add manuscripts of medieval spain

### PR DESCRIPTION
**Pull request by yuenmichelle1**
Staging branch URL: 
https://pr-6109.pfe-preview.zooniverse.org/

Redirecting manuscripts of medieval spain 

**Related to PR on static https://github.com/zooniverse/static/pull/264**

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Review by shaunanoordin — APPROVED** [review]
## PR Review

This PR ensures that the "Deciphering Secrets: Unlocking the Manuscripts of Medieval Spain" [(link)](https://www.zooniverse.org/projects/profdrrogerlouismartinez-davila/deciphering-secrets-unlocking-the-manuscripts-of-medieval-spain) uses the _FEM_ front end instead of the _PFE_ front end.

The code change is pretty standard for FEM projects, and I can manually confirm that the project the link's pointing towards does exist on production. LGTM. 👍

**Comment by yuenmichelle1** [comment]
@shaunanoordin  thanks for reviewing. 👍  i havent pinged anyone yet since ive been trying to figure out why the test pr link isnt opening for me (I usually test before I ping). Does it work for you?

**Comment by eatyourgreens** [comment]
I think our Azure deploys are broken at the moment.

**Comment by eatyourgreens** [comment]
The browser is asking you to download `index.html` because it has the wrong content type.

**Comment by eatyourgreens** [comment]
I ran the deploy again but now it’s complaining about the `—overwrite` argument. 
Azure deploy logs erroring because the AZ CLI doesn’t recognise the `overwrite` argument.

**Comment by eatyourgreens** [comment]
Staging is deployed now.

**Pull request merged**
