### PR TITLE
Fix 1669

### PR DESCRIPTION
**Pull request by CKrawczyk**
This fixes https://github.com/zooniverse/Panoptes-Front-End/issues/1669

This makes the front-end work as expected, but it does not address the root cause of this problem.  The reason this is happening is when the API creates a new workflow the retirement section is not formatted correctly.  It returns
```js
{workflows: {retirement: {classification_count: {count: 15}}}
```
instead of
```js
{workflows: {retirement: {criteria: "classification_count", options: {count: 15}}}}
```
This should probably be addressed in the back-end code.

### CODE REVIEW

**Comment by camallen** [comment]
@CKrawczyk thanks, I've issued a PR to fix the default format in the backend.

**Comment by edpaget** [comment]
Fixed via https://github.com/zooniverse/Panoptes/pull/1402

**Comment by CKrawczyk** [comment]
https://github.com/zooniverse/Panoptes/pull/1402 only fixes this issue for newly created workflows, any workflow made before the fix will still fail.  Either a patch similar to this one is needed to check on the front end if the workflow is formatted correctly, or a one time code needs to run to update all the older workflows.

**Comment by camallen** [comment]
@CKrawczyk - it should fix the default serialized format so all workflows should be fixed. Have you got an example workflow that is still broken?

**Comment by CKrawczyk** [comment]
When the workflow editor is working again I will give it a try.

**Comment by CKrawczyk** [comment]
Yep, you are right, everything works as intended now.

**Pull request closed without merging**
