### PR TITLE
Optimize menu

### LINKED ISSUE #2825: UX for notifications in nav
Work with @jwbmartin to integrate her design and UX for notifications in the navbar. Possibly use an icon [like this](https://thenounproject.com/search/?q=notification&i=492155) next to the mail icon.

### LINKED ISSUE #2873: Submenu looks odd on mobile
Ideally we should show this as a single list on mobile:

img_0290

### PR DESCRIPTION
**Pull request by parrish**
Fixes #2873.  Closes #2825.  Somewhat helps #2858

Deployed at https://optimize-menu.pfe-preview.zooniverse.org/

### CODE REVIEW

**Comment by parrish** [comment]
Sorry to lump multiple fixes together, but they're so closely related I thought it might make sense.

**Comment by parrish** [comment]
@trouille

**Comment by jwbmartin** [comment]
Awesome! Solves a few issues. Can you reduce the padding around the bell icon a little bit? The username-letter-bell all look a little too far apart and disjointed from one another.

**Comment by eatyourgreens** [comment]
Looks good to me. One small issue: I was a little confused that the destination of the notifications link changed according to whether or not I was on a project page. Probably not a big deal, but I thought that might be confusing to volunteers too.

**Comment by parrish** [comment]
Spacing is adjusted now.  Yeah, I could see how it's confusing, but I think it's worth testing.  I thought it would be even weirder to put an icon in the project sub-menu.

**Comment by jwbmartin** [comment]
Yeah that is a bit weird. I'm sketching up some possibilities for a better option right now.

**Comment by srallen** [comment]
LGTM. Much better on mobile, too.

**Comment by jwbmartin** [comment]
LGTM. 

Damn @srallen I just had to google what that acronym was 😐

**Comment by parrish** [comment]
Good to merge then?

**Comment by srallen** [comment]
Good with me, but I wasn't sure if @jwbmartin wanted something to change.

**Comment by jwbmartin** [comment]
I say merge! 

I'm trying to work out how we can just have one notifications page where projects and personal notifications are divided somehow but that's probably going to be a separate problem for someone to tackle in the coming weeks.

**Pull request merged**
