### PR TITLE
Upgrade marked to 0.3.9

### LINKED ISSUE #4260: Update Marked dependency
screen shot 2018-01-05 at 10 59 12

### PR DESCRIPTION
**Pull request by eatyourgreens**
Closes #4260 

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Bumps `marked` to 0.3.9 because the github security warning is getting on my nerves.

**Comment by simoneduca** [comment]
From the conversation we had on the relevant issue, I was under the impression that this was more involved than just adding the package to the app. Isn't the problem still that publisssh is relying on Docco?

**Comment by eatyourgreens** [comment]
This ought to bump the version that Docco is using. `npm ls marked`.

**Comment by eatyourgreens** [comment]
Here's what I see after the version bump.
```shell
Panoptes-Front-End odonnell$ npm ls marked
panoptes-front-end@ /Users/odonnell/zooniverse/Panoptes-Front-End
├── marked@0.3.9 
└─┬ publisssh@1.1.0
  └─┬ iced-coffee-script@1.8.0-e
    └─┬ docco@0.6.3
      └── marked@0.3.9  deduped
```

**Comment by simoneduca** [comment]
I didn't know we could affect other libs dependencies by adding the dep we wanted to upgrade to the main app. Did you just run `npm install marked --save-dev`?

**Comment by eatyourgreens** [comment]
`npm install marked@~0.3.9 --save-dev`.

**Comment by simoneduca** [comment]
Cool, thank you. LGTM.

**Pull request merged**
