### PR TITLE
Edit org landing category buttons, scroll behavior

### PR DESCRIPTION
**Pull request by mcbouslog**
No rush, not sure needs 2 reviewers (though of course welcome), if first to review is content.

Staging branch URL: https://org-landing-ux-edits.pfe-preview.zooniverse.org/

- demo org with these PR changes: https://org-landing-ux-edits.pfe-preview.zooniverse.org/organizations/markb-panoptes/nfnorgtest

**Changes**:
- Edits organization landing category buttons to radio inputs so user can arrow between, cycle through, as requested by @eatyourgreens.
- Edits scroll behavior so there's no scroll on category change

**Question**
~~Might not be implementing radio buttons correctly, but if so not sure radio buttons preferable to current UX where can tab through categories? The radio inputs work as desired in Chrome, but not in Firefox or Safari, whereas the tabing works in Chrome and Firefox, but not in Safari. I'll update with Edge results tomorrow.~~ See activity below.

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [x] Can you post a talk comment?

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
If you wrap the label text in a span, you can use `input:checked + span` to select and style it for the selected option.

**Comment by eatyourgreens** [comment]
Firefox and Safari should work if you add `name=category` to each input. The name attribute is needed to group the radio buttons as a single grouped control.

**Comment by mcbouslog** [comment]
Chrome, Edge and Firefox now respond as expected, allowing user to arrow back and forth between categories, but Safari is still giving me trouble, though with Safari I couldn't get the [MDN input radio example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio) to work with arrow keys either, so I think it's an issue with Safari.

Otherwise I think this is good for review.

**Comment by mcbouslog** [comment]
Ah yes! Fixed.

**Pull request merged**
