### PR TITLE
Set default avatar on error loading avatar

### LINKED ISSUE #967: Why is this user's avatar not working?
https://www.zooniverse.org/#/talk/13/102?page=1&comment=283

What's with the error message where this user's avatar should be?

### PR DESCRIPTION
**Pull request by edpaget**
Closes #967

### CODE REVIEW

**Comment by edpaget** [comment]
I broken @aweiksnar's avatar on staging so you can look at it. I'll restore it after this is merged.

**Comment by aweiksnar** [comment]
Ha I noticed that - username is `alex-panoptes` btw

**Comment by brian-c** [comment]
Looks good to me.

**Comment by DarrenMcRoy** [comment]
Does this cover all types of loading errors? It looked in #967 like there were a few different ways that avatars could go wrong.

**Comment by edpaget** [comment]
yes if it fails to load an image it will replace it with the default image.

**Pull request merged**
