### PR TITLE
Always submit classifications via the stored queue

### PR DESCRIPTION
**Pull request by eatyourgreens**
Push completed classifications into the stored queue and submit from there.
Don't resubmit 422 errors.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://classification-queue.pfe-preview.zooniverse.org/
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This might help fix #3729. I'm not sure.

**Comment by eatyourgreens** [comment]
Rebased to the latest master.

**Comment by simoneduca** [comment]
I'm happy to take a look.

**Comment by srallen** [comment]
Thanks Simone.

**Comment by eatyourgreens** [comment]
Thanks Simone. @yshish has also been using this branch to submit classifications. There's an intermittent classification bug which also occurs on master. Otherwise, no problems reported.

**Comment by simoneduca** [comment]
Did the user have problems on this branch too?

**Comment by eatyourgreens** [comment]
Yes. It's written up in #3729

**Comment by simoneduca** [comment]
The code it's an improvement on old one. It waits until classification is saved before loading next subject and it handles `422`s, by storing failed classifications. So LGTM.
Tested with staged url, done 30+ classification and could not replicate #3729. However @yshish said they could reproduce the bug also on this branch so I won't be closing the issue yet.

**Pull request merged**
