### PR TITLE
Towards user as an app wide prop

### PR DESCRIPTION
**Pull request by chrissnyder**
Putting this out there for discussion, not for merging. I only made the changes to a fraction of the codebase.

This PR would remove any and all `auth.checkCurrent()` from anywhere within the app, except for at the top-level `<App/>` component and have it's currrent value passed down via props throughout the entire app.

Benefits:

- No need for any ChangeListeners, PromiseRenderers, or PromiseToSetState for the user resource anywhere in the app, except at the top. Simply make your render method depend upon @props.user and you are good.
- Formalize the user resource as app-level state, which is what it is.
- Followed correctly, would eliminate bugs where component-level user state gets out of sync with app-level user state, e.g. #969, #879, and others.

Cons:

- Have to pass user down the entire tree of components, as far as is needed.

Thoughts?

### CODE REVIEW

**Comment by camallen** [comment]
This makes a lot of sense to me. Is there any way to make the user available as a top level prop on some component that is embedded in each page?

**Comment by brian-c** [comment]
I'm really not crazy about trickling down app-wide state like this.

The reason for the current `<ChangeListener><PromiseRenderer>` stuff is that I wanted each component to be able to render itself without much context. In practice this was way less useful than I thought it'd be, but I still think a component should generally be able to stand on its own and not have to belong to a specific rendering hierarchy just to access the data it needs.

A sorta middle-ground I tried was re-rendering from the top on auth change and providing a direct reference to the current user from the auth module. It made changing the rendering based on the user smoother, but accessing links from the user still meant manually updating state in `componentDidMount` and `componentWillReceiveProps`. It was less verbose, but only slightly. I trashed that code but could rewrite it pretty quickly if we want to compare.

**Comment by aweiksnar** [comment]
Strongly in favor of this. For the reasons Chris mentioned, and also so that the user is accessible anywhere inside the component. The `<ChangeListener><PromiseRenderer>` pattern scopes it to the children, and then requires rewriting to state/parent-props if needed outside of that. I like this because there's only one way to get a user. Also for less verbosity.

**Comment by chrissnyder** [comment]
@camallen You get that for free by doing https://github.com/zooniverse/Panoptes-Front-End/commit/d7222a5b612467a6496b349e4073b0e69f3bf15a#diff-c13222b43536c8bbe0f944e7ded691c0R41

@brian-c From a page components perspective, I definitely disagree, as their place in the hierarchy is pretty well set as-is. For a more pure component's perspective, I can sort of understand, but I still disagree. I find components most reusable when they are kept as close to pure views as possible where dependencies are declared and passed as props, rather than having to require in dependencies within the component. 

More broadly, I actually like the fact that you have to pass user down throughout the whole tree. I find having an explicit dependency makes reasoning about the app easier. If the user isn't passed to a component, then I know immediately that nothing within that sub-tree depends upon the user. Same for the flip side.

It also gives us more flexibility to iterate on the auth module, as app dependency upon the current implementation is greatly lessened.

@edpaget @parrish Thoughts?

**Comment by parrish** [comment]
Actually, we started off by doing it this way originally.  I can't completely remember exactly why we moved away from it.

**Comment by brian-c** [comment]
```
Foo = React.createClass
  render: ->
    <Bar />
```

Here, let's say `Bar` doesn't need the current user, but its context `Foo` shouldn't have any idea if one of its eventual descendants does. If it did then every component would have to know about every other component that could be rendered under it. That's way too much responsibility.

**Comment by srallen** [comment]
Passing a user down from a top level parent as a prop makes more sense to me too. I did that with Chimp&See and am starting out mammoth bats that way too. I didn't find having to pass down the user as a prop as too much responsibility, but the scale is much smaller for individual projects than it is here. I think that ```<ChangeListener><PromiseRenderer>``` are still useful and could be used in cases where a parent doesn't need to know about the user and only a specific child does (if for instance a component on an About page needed to know, but the parent About page doesn't and none of the other children need to know either). Otherwise, it's passed down as a prop from the main app component.

**Comment by chrissnyder** [comment]
Messed with this a bit more last night, some thoughts below.

I converted the Collections set of routes to use this pattern, and a couple things stood out.

There were a couple instances of just passing `@props.user` down rather than actually using it in the component itself, though never more than one level skip (`<CollectionsPage/>` into `<CollectionsNav />` for example.

It also sort of depends upon how you design your components. So for a simple example, you could design `CollectionsManagerIcon` like this:

```
module.exports = React.createClass
  displayName: 'CollectionsManagerIcon'

  toggleCollectionsManagerPopup: ->
    alert (resolve) =>
      <div className="content-container">
        <CollectionsManager user={@props.user} project={@props.project} subject={@props.subject} onSuccess={resolve} />
      </div>

  render: ->
    <button
      className="collections-manager-icon"
      onClick={@toggleCollectionsManagerPopup}>
      <i className="fa fa-list" />
    </button>
```

or you could do it like this:

```
module.exports = React.createClass
  displayName: 'CollectionsManagerIcon'

  propTypes:
    user: React.propTypes.object
    
  getDefaultProps:
    user: null

  toggleCollectionsManagerPopup: ->
    alert (resolve) =>
      <div className="content-container">
        <CollectionsManager user={@props.user} project={@props.project} subject={@props.subject} onSuccess={resolve} />
      </div>

  render: ->
    <div>
      {if @props.user
        <button
          className="collections-manager-icon"
          onClick={@toggleCollectionsManagerPopup}>
          <i className="fa fa-list" />
        </button>}
    </div>
```

which loosens up the requirement to pass everything down. I still prefer making the eventual dependency explicit, as it's still a dependency, whether you declare it or not. Though that might be hairy in a very deeply nested page structure.

Brian, would you be up for seeing what the `ComponentDidMount` and `ComponentWillReceiveProps` looks like and comparing?

**Comment by parrish** [comment]
Something to consider:

If (basically) all components have the user as a prop, they'll need to resend all of their API requests whenever the user state changes -- even if the result of the request doesn't depend on the current user.  I'm not sure how much request thrashing that would cause, but probably a fair amount.

On the other hand, we already have a decent amount of request thrashing on a logged in page load. -- e.g. we request a lot of stuff, get the user session, then have to re-request the resources.  If we make the user dependency explicit, we could defer those requests until the user session has resolved.

**Comment by chrissnyder** [comment]
Like so https://github.com/zooniverse/Panoptes-Front-End/blob/top-level-user-prop/app/main.cjsx#L40-L41

**Comment by brian-c** [comment]
Found my old commit: https://github.com/zooniverse/Panoptes-Front-End/compare/experimental-rerendering?w=1

Changes to the auth module make `auth.pending` and `auth.current` available. `.current` is a reference to the current user, not a promise, and because the app re-renders when the user changes it's right whenever you access it. (I'm not 100% that this is always in sync right now, I just hacked it into some reasonable spots on the existing auth module.)

The Lab index is the only page I've updated to use the new stuff, just to see if it worked.

I believe I abandoned this because it didn't reduce the amount of code needed as much as I expected it to.

**Comment by edpaget** [comment]
Closed by #1094

**Pull request closed without merging**
