### PR TITLE
Galaxy builder bugfixes

### LINKED ISSUE #4542: Classifier for Galaxy Builder doesn't load subjects on iOS
## Current behavior

img_1578
screen shot 2018-04-24 at 20 21 36

## Additional information

Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1

### PR DESCRIPTION
**Pull request by tingard**
Fixes #4542

Describe your changes.
Added error catching for canvas-viewer where text is displayed rather than any image. Howerver, volunteers could still hypothetically complete a classification.

Added a dynamic scaling to the maximum number of points in a spiral arm. This will not fix mobile classifying, as PSF convolution requires a minimum of 121 uniforms, which significantly eats into the 256 most mobile devices allow.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by astopy** [comment]
Shouldn't we stop people from submitting classifications if their browser isn't supported?

**Comment by astopy** [comment]
The message should also tell the user which browsers _are_ supported. We can't expect them to know what WebGL is and which browsers support it...

**Comment by eatyourgreens** [comment]
It’s actually hardware that’s limiting this. Mobile Safari supports WebGL, but crashes on the old rendering code. The dynamic point allocation in this PR might allow it to run on some phones. 

The subject viewer doesn’t know anything about the classifier, or workflow tasks, so I’m not sure how we’d disable classifications. Maybe bubble subject viewer errors up to the classifier and disable the task components on error.

**Comment by tingard** [comment]
@astopy In an ideal world probably, but the nature of this particular project means isolating bad classifications afterwards should be pretty okay, as it's a really just a regression problem so you have a goodness-of-fit criteria.

**Comment by astopy** [comment]
> It’s actually hardware that’s limiting this. Mobile Safari supports WebGL, but crashes on the old rendering code. The dynamic point allocation in this PR might allow it to run on some phones.

In that case can we reword the message to say something like "Sorry, this project requires features which are not supported by your device. Please try again on a desktop computer."?

> In an ideal world probably, but the nature of this particular project means isolating bad classifications afterwards should be pretty okay,

I'm concerned we might waste people's time. I can still view the photo and draw ellipses on it, which some people might do thinking they're still helping.

**Comment by tingard** [comment]
> We’re afraid your browser doesn’t support the WebGL we need to render galaxies. You can comment on photos (the second image) in Talk, but won’t be able to classify.

**Comment by tingard** [comment]
Current error message:
> We’re afraid your browser doesn’t support the WebGL we need to render galaxies. You can comment on photos (the second image) in Talk, but won’t be able to classify.

New message (something like):
> Sorry, this project requires features which are not supported by your device. Please try again on a desktop computer, and let us know in talk if you're still having problems. You can comment on photos (the second image) in Talk, but won’t be able to classify.

Shall I do a quick follow-up PR?

**Comment by astopy** [comment]
👍 sounds good, thanks!

**Pull request merged**
