### PR TITLE
Language/Locale Updates: edit zh-tw.js, add ur

### PR DESCRIPTION
**Pull request by mrniaboc**
Staging branch URL: https://pr-5832.pfe-preview.zooniverse.org

Translation updates from Lauren Huang:

"Here are what I would like to niote in Chinese
line 4: back: 'Back' --> 返回
line 13: next: '下一個' --> 繼續
line 17: tutorialTab: '教程' --> 說明
line 19: recents: 'Your recent classifications' --> 這些是你最近完成的分類
line 37: fieldGuide: 'Field Guide' --> 實戰手冊
line 42: results: 'Results' --> 成果
line 43: faq: 'FAQ' --> 常見問題
line 44: education: 'Education' --> 教育應用
line 82: joinIn: 'Join in' --> 加入
line 183: signIn: 'Sign in' -->登入
line 184: register: 'Register' -->註冊"

(Added by Cliff) Also adding `ur` locale option, closing #5831 

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Does this overlap with #5827, #5826 and #5825?

**Comment by lcjohnso** [comment]
PRs #5827, #5826 and #5825 are now duplicates; I will close those in favor of this single PR.

**Comment by lcjohnso** [comment]
I'm also taking the opportunity to close #5831 while spending time on locale files with one additional commit.

**Comment by mcbouslog** [comment]
What's the project utilizing `zh-tw` I could preview with? No worries if there isn't, I think I can test with a staging project I'd setup.

**Comment by lcjohnso** [comment]
Hi @mcbouslog -- GZ will work:
https://pr-5832.pfe-preview.zooniverse.org/projects/zookeeper/galaxy-zoo/?env=production

**Comment by eatyourgreens** [comment]
Not a problem with any of the translations here, but there's an extra space at the beginning of the Chinese project title, which is breaking the markdown formatting of the project Talk text.
Screenshot of the Join In text showing an extra space between ** and the project title.

**Review by mcbouslog — APPROVED** [review]
LGTM! Thank you all

**Pull request merged**
