### PR TITLE
Fix tutorial rendering bug

### PR DESCRIPTION
**Pull request by eatyourgreens**
The tutorial renders much too narrow, unless you call swipe.setup() twice.

Staging branch URL: https://fix-tutorial-width.pfe-preview.zooniverse.org

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
## PR Review
This PR attempts to fix the issue where - after the recent update to React 16 - the Tutorial component's pages ("media cards") no longer render properly.

screen shot 2018-05-29 at 13 46 49
_Note that each "media card" (tutorial page) is 228px wide in a container that's 400px wide. This causes each tutorial page to appear as narrow strips bunched up together in the Tutorial component._

Unfortunately, there are issues with this solution - please see **Testing** for details.

### Analysis
Analysis indicates that the likely root of the issue is that the 'swipe library' code is now longer able to correctly calculate the width of the parent container before determining the size of the children (tutorial pages). (See Jim's comments re: [the code](https://github.com/voronianski/swipe-js-iso/blob/dd5e0f3f907cc3561801ad847861686d44df49f6/swipe.js#L62-L65))

Early tests indicate that calling the `.setup()` call _twice_ seems to solve the Tutorial setup problem, although reasons for why is unclear.

Also note that setting the `setup()` call to trigger later - e.g. by setting the timeout to after 2 seconds - did not work as solution.

### Testing
Unfortunately, the double `.setup()` call only works in a certain subset of Tutorials, and fails in others. Here are two Tutorials implementing this PR's fix:

screen shot 2018-05-29 at 13 44 50
_In Workflow X, the tutorial pages still appear clumped up._

screen shot 2018-05-29 at 13 45 16
_In Workflow Y, of the same project, the tutorial pages appear as intended._

Repeatedly refreshing the page to see the tutorials render always present the results consistently: Workflow X has a bad tutorial render, Workflow Y has a good tutorial render. This may indicate that the double `setup()` solution may only work under specific tutorial content conditions?

Tested in OSX+Chrome, with a fairly wide desktop view. Not tested: any sort of mobile view.

### Status
The proposed fix needs further investigation.

**Comment by shaunanoordin** [comment]
Update: I'm actually tempted to give this PR a 👍 just to fix the existing tutorial for the 95% of projects that the code changes actually work for.

At the moment, the double `.setup()` call works for every _production_ project's tutorial I've tested, _except for_ Penguin Watch's "Aerial Photos" workflow.

**Comment by eatyourgreens** [comment]
Maybe that tutorial actually has images that are smaller than 400px?

**Comment by shaunanoordin** [comment]
## PR Review Update
Tutorials that test OK with this PR's fix:
- [Penguin Watch, Time Lapse Camera workflow](https://fix-tutorial-width.pfe-preview.zooniverse.org/projects/penguintom79/penguin-watch?env=production)
- [Rainforest Flowers](https://fix-tutorial-width.pfe-preview.zooniverse.org/projects/tomomi/rainforest-flowers/classify?env=production)
- [Protect Our Planet From Solar Storms](https://fix-tutorial-width.pfe-preview.zooniverse.org/projects/lepnoir/protect-our-planet-from-solar-storms/classify?env=production)
- [Numbat Discovery](https://fix-tutorial-width.pfe-preview.zooniverse.org/projects/amyrobey996/numbat-discovery/classify?env=production)
- [Space Warps](https://fix-tutorial-width.pfe-preview.zooniverse.org/projects/aprajita/space-warps-hsc/classify?env=production)
- [Project Plumage](https://fix-tutorial-width.pfe-preview.zooniverse.org/projects/ghthomas/project-plumage/classify?env=production)
- [Cheetahs of Central Namibia](https://fix-tutorial-width.pfe-preview.zooniverse.org/projects/danberinger/cheetahs-of-central-namibia/classify?env=production)

Tutorials that have issues despite this PR's fix:
- [Penguin Watch, Aerial Photos workflow](https://fix-tutorial-width.pfe-preview.zooniverse.org/projects/penguintom79/penguin-watch?env=production)
- [Galaxy Zoo](https://fix-tutorial-width.pfe-preview.zooniverse.org/projects/zookeeper/galaxy-zoo/classify?env=production)
- [SCOTUS Notes, Transcribe workflow](https://fix-tutorial-width.pfe-preview.zooniverse.org/projects/zooniverse/scotus-notes-behind-the-scenes-at-supreme-court-conference/classify?env=production)

Semi-random sampling of 10 projects on production.

### Addendum
I forgot to mention this in my earlier review notes, but it's worth noting that any wonky-looking Tutorial will fix itself if you resize the window.

**Comment by eatyourgreens** [comment]
The broken tutorials all seem to be ones where the width should be smaller than 400px anyway, so there's still an issue where the tutorial renders at 400px, even if the content is not wide enough to fill that.

**Comment by eatyourgreens** [comment]
I'm tempted to merge this now but maybe open an issue about tutorial sizing being broken in general?

**Pull request merged**
