### PR TITLE
Fan tool: make default spread 10º

### LINKED ISSUE #5604: Changing the default spread angle of the fan tool for Planet Four
The default spread for the fan tool on panoptes is 30 degrees, We found in the P4 beta test that this is causing problems in the sense that people are adjusting it the spread of the fan tool.  This is because 30 degrees spread is  near the peak of the fan distribution observed in the P4 catalog. The original default value was 5 degrees spread on the original Ouroboros P4.  Can the default spread be changed to 5 degrees. 

P4 catalog spread:

catalog_spread

There is a peak at 5 degrees the default value but that's very tiny features the wider distribution is the one to look at. 

The disribution of fan spreads from P4 panotpes beta test from the two interfaces:

spread

We think the spike at 30 is saying people aren't adjusting the fan tool spread because it looks close enough the average value. We think we're losing information about areal coverage and having a small value like 5 degrees would help get people to fit the fan shape more accurately. 

Would you be able to make the change or if other groups are using the fan tool can a P4 clone version be generated with a 5 degree default spread? We think once this is done, P4 will very close to launching on panoptes 

cc @eatyourgreens @lcjohnso

### PR DESCRIPTION
**Pull request by eatyourgreens**
Change the default fan tool spread angle to 10º.

Staging branch URL: https://pr-5605.pfe-preview.zooniverse.org

Fixes #5604.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
>I'm guessing the configuration is being added to support backward compatibility in case it is needed? 

If we don't have an initial estimate for the spread angle, the tool simply doesn't work. You'll get `NaN` for the drag handle coordinates if `spread` is 0.

**Comment by srallen** [comment]
I'd prefer to have a discussion if this should be configurable or if there is no default, if the interaction of the tool must change so the volunteer can set the angle. Since this is a new change, I'd like this to be part of the ADR of the rewritten tools rather than paint ourselves into a corner prematurely here.  

Making this default to 5 here is fine for now as it enables P4 to launch and we can query the database in case we need to communicate this change to anyone else.

**Comment by eatyourgreens** [comment]
>if the interaction of the tool must change so the volunteer can set the angle.

The tool must render with some guess at the initial angle before the volunteer can set the angle. Similarly, ellipses must render with an initial guess at the minor axis before a volunteer can adjust it.

**Comment by srallen** [comment]
Can we scope this PR to just make the default 5 for the current fan tool, put off the configuration addition, and move the conversation on if we should do this to https://github.com/zooniverse/front-end-monorepo/pull/1390? I'd like researcher input into this one.

**Comment by eatyourgreens** [comment]
I'd like Meg to be able to adjust the default until she finds a value that she's happy with.

**Comment by srallen** [comment]
It's harder to take features away than to give them. It's not clear to me if more experimentation is needed since the request is directly to make it 5, so I'd rather not add the ability to configure and then take away if we don't need to.

**Comment by eatyourgreens** [comment]
Tool options aren't a new feature. Point tools are already configurable in the project builder, so I reused that idea.

**Comment by eatyourgreens** [comment]
Sorry, I should have added that my concern here is that the tool is almost unusable with an angle of 5, but I'd like Meg's opinion.

**Comment by eatyourgreens** [comment]
Here's Planet Four on this branch. https://pr-5605.pfe-preview.zooniverse.org/projects/mschwamb/planet-four/classify?env=production

I'm finding that when the fan angle is initially very small, the drag handles are all so close together that they merge on the screen.

**Comment by srallen** [comment]
I suggested default values that make the tool unusable in my comment [here](https://github.com/zooniverse/front-end-monorepo/pull/1390#issuecomment-571187469), but I'm not sure that's a good solution.

As for configurability in general, yes we have some tools that have some configurable values, but in this case I think we should be really thoughtful in how we approach this to avoid creating new issues for ourselves.

**Comment by mschwamb** [comment]
I think 10 degrees spread is working okay I think. It's larger than 5  and less than the previous default value of 30.  I was able to adjust the fan in mobile. How about the spread be change to 10, and we do the final beta test for P4 and I can look at the spread of values?

**Comment by eatyourgreens** [comment]
Sounds good to me.

**Comment by eatyourgreens** [comment]
I'm inclined to close this and just set the default value to 10, as per https://github.com/zooniverse/Panoptes-Front-End/issues/5604#issuecomment-573685213.

**Comment by srallen** [comment]
Ok, I'm fine with delaying the updates for the lab for when the fan tool gets added to the new classifier.

**Comment by eatyourgreens** [comment]
@mschwamb Sorry for the delay in getting to this. I've set the default spread angle to 10º.

**Pull request merged**
