### PR TITLE
Force reload of publications page route

### PR DESCRIPTION
**Pull request by rogerhutchings**
Uses the RELOAD component to force a reload of `/about/publications` and ensure it's fetched from the new content pages app

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Same with the staged version: https://pr-5342.pfe-preview.zooniverse.org/about/publications

**Comment by camallen** [comment]
> Trying this out on a local copy of PFE, the browser is just going into a loop and constantly reloading the publications page.

same on preview deploy - https://pr-5342.pfe-preview.zooniverse.org/about/publications

**Comment by rogerhutchings** [comment]
There won't be anything for it to resolve to on localhost / preview, so it'll fall back to the original route (which triggers another reload)

**Comment by rogerhutchings** [comment]
And unfortunately, it looks like there's isn't a Cloudfront distribution for `preview.zooniverse.org`, so it's not like I can just copy over the behaviour rule

**Comment by camallen** [comment]
So this works in production but not on staging, we'd have to setup a mirror CF distribution for staging that we add path matches for the deployed FE apps. 

Is this safe to merge and to deploy to prod?

**Comment by rogerhutchings** [comment]
It is, but I'm closing it in favour of #5345, which has staging support as well.

**Pull request closed without merging**
