### PR TITLE
Hamburger icon to reveal top nav on project pages

### LINKED ISSUE #2846: Add 'menu' to project nav zooniverse logo
Originally mentioned in [this comment](https://github.com/zooniverse/Panoptes-Front-End/pull/2831#issuecomment-236231882). Add 'menu' to zooniverse logo used in the project level navigation. Related to #2800

### PR DESCRIPTION
**Pull request by eatyourgreens**
Uses a hamburger icon for the toggle button when the top nav is hidden, Zooniverse logo when visible.
Closes #2846

### CODE REVIEW

**Comment by camallen** [comment]
@eatyourgreens looking good! However when viewing on smaller view ports (simulating mobile devices in browser) both the hamburger and the zoo icon show up instead of just the zoo icon. 

image

**Comment by eatyourgreens** [comment]
@camallen Yeah, the hamburger icon is used as the toggle for the navigation menu on mobile, so it will show instead of the menu links when the menu is visible.

**Comment by camallen** [comment]
the main issue is that it doesn't revert the open zoo wide links behaviour

**Comment by eatyourgreens** [comment]
If it does that, how would you open the main nav menu to get to the links?

Agreed that having the same icon do two different things is confusing. https://github.com/zooniverse/Panoptes-Front-End/issues/2846#issuecomment-238504674

**Comment by camallen** [comment]
not explaining myself well..i think it should replicate larger viewport behaviour where the hamburger icon disappears leaving just the zoo icon.

**Comment by camallen** [comment]
AH - i get it now. Did not even see that. the hamburger has 2 functions on mobiles...so we've totally overridden the behaviours here and that is what is confusing me. Not sure what todo here....

**Comment by eatyourgreens** [comment]
We could rewrite the layout component to give a different behaviour on mobile, where the hamburger opens the nav menu popup and the page content doesn't shrink down. Or have two different components, one for mobile and one for larger viewports.

That might be out of scope of the quick fix that was suggested in #2846. Depends how much needs to be changed in the layout component.

**Comment by eatyourgreens** [comment]
Latest commit is a bit of a hack, but should make things better on small viewports.

**Comment by astopy** [comment]
This doesn't look quite right in Safari:

screen shot 2016-08-09 at 13 27 19

**Comment by astopy** [comment]
Also, on Mobile Safari tapping the hamburger icon doesn't close the menu when it's already open.

**Comment by astopy** [comment]
This submenu looks a little strange on mobile too.

img_0290

**Comment by astopy** [comment]
Ah, yes it does. I'll open a new issue about that then.

**Comment by camallen** [comment]
This looks good to me, can we get another reviewer on this @srallen @trouille ?

**Comment by trouille** [comment]
@wgranger Can you pause this afternoon to do another review on this this? Thanks!

**Comment by eatyourgreens** [comment]
If someone has time to check this branch on Android, that would be great. 

Seemed good to me in Safari on latest iOS.

**Comment by eatyourgreens** [comment]
Staged at https://fix-2846.pfe-preview.zooniverse.org/

**Comment by wgranger** [comment]
Couple thing I noticed in reviewing this:

IE11/Win 7 - Hamburger icon is invisible, but still functioning. Noticed this using VirtualBox. The icon still toggles to reveal the Zooniverse logo.

iPhone 5 (via Chrome) - Noticed some strange functionality. Some of the menu items overlapped (note the mail icon behind the project title in the image). Also, with the burger menu opened you can scroll to the right forever, which is an annoying little bug.

screen shot 2016-08-10 at 1 41 53 pm

**Comment by astopy** [comment]
The [issue I mentioned in the desktop version of safari](https://github.com/zooniverse/Panoptes-Front-End/pull/2871#issuecomment-238537485) is still there -- the icon doesn't look right.

**Comment by camallen** [comment]
hmm - that's hamburger doesn't working on linux desktop firefox for me.

**Comment by eatyourgreens** [comment]
@camallen same here with Firefox 48.0. The button is rendering with `height: 0px`.

**Comment by eatyourgreens** [comment]
@camallen might be fixed now. It's working for me in Firefox now that I've taken out that CSS style.

@wgranger that change may have fixed it in IE11 too. I'm not sure.

**Comment by wgranger** [comment]
Looks good on IE now. Still a little jumbled looking on mobile. 

screen shot 2016-08-15 at 8 03 59 pm

**Comment by eatyourgreens** [comment]
Without the top margin on projects, the navigation overlaps the user profile button.
Screenshot from Computer Vision: Serengeti showing the navigation menu overlapping the user profile controls
From https://fix-2846.pfe-preview.zooniverse.org/projects/alexbfree/computer-vision-serengeti?env=production

**Comment by eatyourgreens** [comment]
I've rebased this and removed the changes to the project nav top margin, because of the problems with overlapping text. Project nav styling should probably be dealt with as a separate issue. I think this is ready now.

**Comment by wgranger** [comment]
LGTM. Unless there are any suggestions or qualms, I think this is good to merge.

**Pull request merged**
