### PR TITLE
Adds status to query params on projects page.

### LINKED ISSUE #3169: Rewrite project status filters as query params
Project status filters - active, paused (out of data) and finished - were added in #3085. However, they were implemented as different routes (e.g. `/projects/finished`), rather than query params like the other filters. After asking around in #3152, the consensus is that they should be query params instead, so they will need to be reimplemented (and tests added!)

### PR DESCRIPTION
**Pull request by simoneduca**
Fixes #3169 .

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Staging branch https://add-status-to-query-params.pfe-preview.zooniverse.org/

## Optional

- [x] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?

### CODE REVIEW

**Comment by rogerhutchings** [comment]
- Changing the status filter wipes out any other query parameters; we want to keep them, really. You can do that by using the `onClick` method to trigger `updateQuery()`
- I'd suggest moving that `componentWillMount` method to its own method, just for clarity.
- Remove that `|| null` check

**Comment by simoneduca** [comment]
Meh. Since we're using buttons instead of links now, if one clicks 'Projects' on the main nav, active state is lost on 'Active'.

**Comment by simoneduca** [comment]
@rogerhutchings this should be good to go, except for the little bug in the screenshot above. Any suggestions welcome!

**Comment by rogerhutchings** [comment]
You could check the location as it's passed in as a prop and see if it has the default query params?

**Comment by simoneduca** [comment]
On `StatusLink` component? But the problem is clicking on "projects" in the main nav component `site-nav`

**Comment by rogerhutchings** [comment]
No, in the projects component. It won't help, because the location is just a prop that's being updated - the projects component isn't remounted or anything like that. So if you check the props when they change, and the location doesn't have a query, you can add it in

**Comment by simoneduca** [comment]
Thanks, that should be it.

**Comment by camallen** [comment]
@simoneduca have you tested that this only shows the non-retired / paused projects on the main live section now?

**Comment by simoneduca** [comment]
I did, restaged here https://add-status-to-query-params.pfe-preview.zooniverse.org

**Comment by simoneduca** [comment]
And I don't it's right still. I can still see a paused project under active tab.

**Comment by simoneduca** [comment]
Waiting on this https://github.com/zooniverse/Panoptes/pull/2028

**Comment by simoneduca** [comment]
Backend should be sorted now. @rogerhutchings I think this is good to go.

**Comment by rogerhutchings** [comment]
Looks good. The only outstanding thing I can see from the staged branch is that the top links use a different font to the regular Zoo one

**Comment by simoneduca** [comment]
Well spotted, thanks. This is sorted now.

**Comment by rogerhutchings** [comment]
okay, lgtm

**Pull request merged**
