### PR TITLE
Drawing: cancel drag events to prevent window scrolling

### PR DESCRIPTION
**Pull request by eatyourgreens**
https://pr-5411.pfe-preview.zooniverse.org

Cancel drag events so that you can draw on a touchscreen without scrolling the page.

Moves the drag event listeners from the body down to the PFE app container div. Cancels move events, but not start events, and stops them from propagating up to the body.

Adds `touch-action: pinch-zoom` to the drawing/zooming styles so that panning is disabled but pinch-zoom is allowed while drawing. I'm not sure how usable this is, so it needs testing.

This [stackoverflow discussion about cancelling touch scrolling](https://stackoverflow.com/questions/16348031/disable-scrolling-when-touch-moving-certain-element) is useful.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
@eatyourgreens Questions:
1. on which page are you testing this? (/dev/classifier ?)
2. on what device are you testing this?

Thoughts:
1. I remember that I managed to get touch actions working for a previous project, and I had a shotgun method for killing the [native touch-to-scroll actions.](https://github.com/shaunanoordin/avo-adventure/blob/master/src/avo/utility.js#L18) IIRC the event-killer performed a `return false` in addition to `e.returnValue = false; e.cancelBubble = true;`... but that was for old versions of web browsers so I need to see if those solutions are still applicable
2. Is the `e` Event that `handleStart(e)` is handling a React Event or a native browser event?
3. a quirk I noticed on some devices (non-MS Surface touch laptops, really) is that they use mouse events to emulate touch events, which may lead to further testing wonkiness.

**Comment by eatyourgreens** [comment]
Hi Shaun, I'm testing this with the default 'Test workflow' at https://pr-5411.pfe-preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground and I'm using the XCode iOS simulator to emulate an iPad Pro.

**Comment by eatyourgreens** [comment]
Hmmm, I can't go back and delete marks on this branch.

**Comment by shaunanoordin** [comment]
I created a basic test to see what's required to kill a touch-to-scroll event. I'll break down what I've discovered in this experiment - https://shaunanoordin.github.io/js-stop-pointer-events/ - but before that, I wanted to check what you meant by _"can't go back and delete marks "?_

The 'X' (delete) buttons stop responding after the addition of the Stop Event code? Whaaa? OK, let me give that a shot.

**Comment by shaunanoordin** [comment]
OK, I see what you mean.

Experimental observations, tested on OSX+Chrome in iPad emulation mode:
- Went to dev classifier (see below for specific URLs)
- clicked "Draw Stuff"
- clicked "Point"
- clicked on Subject image twice, to add two "Point"-type drawing marks.
- _attempted to_ click on each Point, then click on the 'X' button to delete them.

On `https://master.pfe-preview.zooniverse.org/dev/classifier`, the attempt to delete the Points work as expected.

On `https://pr-5411.pfe-preview.zooniverse.org/dev/classifier`, I can only see the 'X' button the most _recently-created Point._ The problem seems to boil down to this: _in the new branch, I am unable to select (make "active") any drawing mark (other than the most recently selected on) by clicking on them._

My surface-level guess - which needs way more testing - is that the "click" event is trigger at a child element of the drawing mark, and the new `e.stopPropagation()` code is preventing the parent element of the drawing mark to receive the "hey, I just clicked this drawing mark, so please make it active" intent.

```
<g class="point-type drawing-mark" onClick="makeActive(this)">
  <circle />
  <line />
  <line />  <-- the click event might be hitting this, but the e.stopPropagation stops the parent's onClick from hearing it.
  <line />
  <CloseButton />
</g>
```

**Comment by eatyourgreens** [comment]
Commenting out `e.StopPropagation()` fixes it. Weird that it's the `onDrag` handling that seems to be controlling mark selection.

**Comment by eatyourgreens** [comment]
[`touch-action: none`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) seems like it should be the fix here, but I cannot figure out how to get it to work.

**Comment by eatyourgreens** [comment]
This is still a problem. See the videos on #5536.

**Comment by eatyourgreens** [comment]
@shaunanoordin I've updated this and it now works in the iOS simulator. I haven't tried it out on a real touch screen device.

**Comment by shaunanoordin** [comment]
Primary testing looks good so far:
- Click to add annotation works fine on mouse, and emulated touchscreen
- Click to select annotation works fine on mouse, and emulated touchscreen
- Drag to move annotation works fine on mouse, **and emulated touchscreen** 👍 

Tested on OSX+Chrome (localhost), targetting [I Fancy Cats](https://localhost:3735/projects/brooke/i-fancy-cats/classify)'s "Cattail" (point-type drawing tool) task.

`pinch-move` seems to do the trick, but I need to read up on it a bit to see if there are any gotchas. (Specifically, does Safari on iPhones - the only unknown for me at this moment - support it?)

I'm going to give the staging branch a shot on my Android phone, then when I'm back home with my Dell touchscreen laptop I'll try it again.

(Note: I'm assuming that the staging branch has been automatically updated)

**Comment by shaunanoordin** [comment]
Android looks good 😄 👍

**Comment by eatyourgreens** [comment]
Seems to work in the dev classifier on my very old phone (iOS 11.) Drawing is slow and fiddly but moving my finger doesn’t scroll the window.

**Comment by shaunanoordin** [comment]
Sweet, thanks for confirming iPhones!

I looked up `touch-action: pinch-zoom` on [CanIUse](https://caniuse.com/#search=pinch-zoom) and turns out it was only recently supported by Safari 13 (released 13 Sep 2019) so this is good news.

I can't help but think that your earlier solution of setting `touch-action: none` is the "correct" solution, due to an edge case: specifically, although `pinch-zoom` effectively solves the huge problem of "dragging annotation marks causes page to scroll", it still allows the unexpected behaviour where if a user zoom-pinches on the Subject Viewer, they will zoom the browser view and _then_ create an annotation where one of their fingers was last at.

But as I said, I consider that an edge case. `touch-action: pinch-zoom` works whereas IIRC we encountered problems with `touch-action: none`, so this PR is a 👍 for me. I'll write a proper review shortly and we can get this merged.

(Side note: double-tap to zoom has no effect or side effects on PFE's classifiers, phew.)

**Comment by eatyourgreens** [comment]
Trying it out on my test workflow here, I find that the window still scrolls if I try to draw a vertical line. https://pr-5411.pfe-preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground

**Comment by shaunanoordin** [comment]
> Trying it out on my test workflow here, I find that the window still scrolls if I try to draw a vertical line. https://pr-5411.pfe-preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground

For which task/tools? _Test Workflow > Draw Something Else > Line_ and _ ...ditto... > Freehand segment_ tools work fine for me on OSX+Chrome (emulation) on localhost. Other drawing tasks on the Test Workflow look good too.

I'll give it a go on Android.

**Comment by eatyourgreens** [comment]
I was using the line tool on iOS, trying to draw a vertical line. 

If this PR fixes drawing on Android, I’m inclined to merge it even if iOS is still broken.

**Comment by shaunanoordin** [comment]
Confirmed for Android 8.0.0 + Chrome 77: all Drawing Tasks in the Project Testing Ground's "Test Workflow" work as expected. 👍 

Certain drawing tools are "slow and fiddly" as earlier remarked, but they're all working and definitely not causing a drag-to-pan/scroll error as before.

**Pull request merged**
