### PR TITLE
messaging around rate limited dump workers

### PR DESCRIPTION
**Pull request by camallen**
depends on https://github.com/zooniverse/Panoptes/pull/1376, once this is in then it's appropriate we provide some messaging for users.

### CODE REVIEW

**Comment by chrissnyder** [comment]
Could the text be changed to "Please note that the Zooniverse will process at most 1 of each export within a 24 hour period"

**Comment by camallen** [comment]
yep will do.

**Comment by camallen** [comment]
done, thanks for picking up on a stupid typo.

**Comment by chrissnyder** [comment]
:+1:

**Pull request merged**
