### PR TITLE
Add link to new workflows settings location.

### PR DESCRIPTION
**Pull request by simoneduca**
Staging branch URL: https://lab-workflows-link.pfe-preview.zooniverse.org/

Describe your changes.
Add a link to the new workflows settings location in the Lab.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by simoneduca** [comment]
I'm happy to change it if you have a suggestion.

**Comment by camallen** [comment]
Perhaps, "We've moved the Workflow settings page, please click [here](link_location) to access the settings page that previously lived here."

**Comment by eatyourgreens** [comment]
Please [don't use generic link text](https://webaccess.berkeley.edu/ask-pecan/click-here) like 'Click here'.

**Comment by simoneduca** [comment]
Yeah I thought that was bad accessibility. Any different suggestions @eatyourgreens?
How about "Workflows Settings have moved. <link>Go to the new page<link>"?

**Comment by eatyourgreens** [comment]
@simoneduca "the new page" is still generic. I'd follow the advice on the page that I linked to.

**Comment by simoneduca** [comment]
"The Workflows Settings section have moved. To find it, go to the <link>workflows page<link>"?

**Comment by camallen** [comment]
"We have moved this section to the [workflow settings page](new_page_link_here) for some reason like it's easier to discover as it's workflow related..."

**Comment by simoneduca** [comment]
What would "this section" refer to? The section isn't there anymore.

**Comment by srallen** [comment]
How about we be as precise as possible:
```
The workflow settings for activeness, stats type, and stats visibility have moved from the visibility page to the workflows page (link). For improved discoverability, we have moved these settings so all relevant information and configuration of workflows is in one place.
```

**Comment by simoneduca** [comment]
Restaged https://lab-workflows-link.pfe-preview.zooniverse.org/

**Comment by simoneduca** [comment]
Shortened Sarah's text a little.

**Pull request merged**
