### PR TITLE
Scaleable subject

### PR DESCRIPTION
**Pull request by eatyourgreens**
Work towards zooming subject images for #278 
- renames SubjectViewer to SubjectAnnotator, to avoid confusion with the shared SubjectViewer component
- adds an SVG image for image subjects
- sizes SVG elements to scale with the subject image
- adds a crop method to crop the view box to x, y, width, height

### CODE REVIEW

**Comment by edpaget** [comment]
Any reason we never did anything with this? Is it still useful?

**Comment by camallen** [comment]
It's for the retina project and the start of a zoom tool that may get folded into the front end. I think @eatyourgreens threw it up for reference but probably needs a rebase now. Any ideas on merging this?

**Comment by eatyourgreens** [comment]
Rebased to the latest master.

Should be safe to merge. I haven't really had time to look at adding a UI for zooming in/out of an image.

**Comment by aliburchard** [comment]
@chrissnyder @edpaget @brian-c -- would you guys be able to have a look at this to okay the code for merging?

Note that this doesn't specify the retinas workflow-specific zooming, just the changes to the subject viewer that allows for the retinas-specific zoom. We still need to decide how to meet the need for zoom on a live retinas project, as there is some discussion about integrating custom code with the generalized PFE vs. having a live project exist on a different branch. Will need a conversation with @brian-c and @chrislintott for that.

**Comment by brian-c** [comment]
Talked to @chrislintott about integrating this, but I'm not sure how it integrates so I'm playing with it on #/dev/classifier. Just a couple notes:

- Calling `crop` with a box not matching the aspect ratio of the original image doesn't re-size the view of the subject so the original  shows behind it. I don't think we can render both the  and the <image> at the same time.

- What actually calls `crop`? I'm imagining a crop task that stores x, y, width, and height in an annotation, and during subject render any crop-task annotations are found and viewBox is built from the last one.

**Comment by eatyourgreens** [comment]
@brian-c there's an example on staging:
http://demo.zooniverse.org/panoptes-front-end/retinas/#/projects/aliburchard/ieye/classify?workflow=1039 Draw a rectangle for the third task, and the viewbox changes to that rectangle.

I can't get the original subject to show behind the SVG, no matter what shape rectangle I draw. `crop` changes the viewbox, but it shouldn't touch the height and width of the SVG element.

A crop task that defines a rectangle somewhere on the subject sounds like exactly what the Retinas project needs. At the moment, it's using an ugly hack based on task ID: 1d4d0a1f8b0dcffb20a6ee8e4e7fcd829953d721

**Comment by brian-c** [comment]
Thanks @eatyourgreens. The viewbox changes to the rect, but the SVG doesn't resize so its aspect ratio is still whatever the original image's was. I can see the original behind the cropped image when I draw a tall rectangle off to the side.

screen shot 2015-08-05 at 9 19 51 am

Is Retinas going to live on www.zooniverse.org, or will it be its own deploy?

**Comment by aliburchard** [comment]
I think the plan is for it to be on zooniverse.org so it is maintained
along with the platform (my conversation with @camallen makes me think this
is ideal). But also if we make this a different task type, then it is
generalizable to all projects (and we can authorize projects to access it
with the admin flag)

On Wednesday, August 5, 2015, Brian Carstensen <notifications@github.com>
wrote:

> Thanks @eatyourgreens <https://github.com/eatyourgreens>. The viewbox
> changes to the rect, but the SVG doesn't resize so its aspect ratio is
> still whatever the original image's was. I can see the original behind the
> cropped image when I draw a tall rectangle off to the side.
>
> [image: screen shot 2015-08-05 at 9 19 51 am]
> <https://cloud.githubusercontent.com/assets/464389/9087974/66c79ea4-3b53-11e5-84a9-e1f729c4601f.png>
>
> Is Retinas going to live on www.zooniverse.org, or will it be its own
> deploy?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes-Front-End/pull/529#issuecomment-128013908>
> .
>


-- 
Sent from my moderately intelligent phone.

**Comment by eatyourgreens** [comment]
@brian-c Got it. That is a bug. I should alter the default `xMidyMid meet` for `preserveAspectRatio` if they draw a weird rectangle.

**Comment by eatyourgreens** [comment]
Background showing through should be fixed by 87dcad2 (fingers crossed)
I've deployed it to the retinas branch on demo, if anyone has some time to try and break it.

If a project really needs to crop the image down to a thin rectangle eg. lines of text, we'll need to dynamically change the subject height and width, which will probably mess with the `SubjectViewer` component. Something like the specimen labels tool in Orchid Observers, which resizes the subject based on a rectangle you draw: http://www.orchidobservers.org/#/transcribe 
but we can deal with that problem if/when it comes up.

**Comment by camallen** [comment]
@eatyourgreens tried it out [here](http://demo.zooniverse.org/panoptes-front-end/retinas/#/projects/aliburchard/ieye/classify?workflow=1039), seems to work well.

**Comment by eatyourgreens** [comment]
@camallen Cool. Rebased, and moved the crop functionality into a new component.

**Pull request merged**
