### PR TITLE
Add "App Status" banner

### LINKED ISSUE #3530: Add "App Status Banner" to Zooniverse.org
## Feature Request
* Users of zooniverse.org must be able to see any status updates - notably "emergency broadcasts" such as "sorry folks, server is down, brb"
* Zooniverse admins must be able to send out status updates to users.
* Proposed mechanism is as follows:
  * PFE will check a static resource to determine if there's a status message. (REQUIREMENT: this resource must be low-cost and easily scalable, as it'll be accessed every time a user accesses zooniverse.org. An API call to a paid API service is out of the question. A simple .txt file on an S3 bucket is acceptable - better if it's cached.)
  * If the static resource indicates a status message, that message will be displayed on the PFE as a banner.

Part of the (Stargazing Live 2017 project)[https://github.com/orgs/zooniverse/projects/5]. Original text:
```
Let PFE check if status.zooniverse.org is indicating a known issue. If so, display a small banner on every page. - marten
```

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview
Closes #3530

* New feature: a "status banner" is displayed on zooniverse.org, if PFE detects a status message on a secondary location.
* Mechanism: PFE checks static.zooniverse.org for a static resource (expecting to find a simple .txt or .html file). If the resource exists, the status banner appears and displays the contents of the file to the user. (Final static resource URL not finalised: see Notes)
* Zooniverse admins will need to manually add/edit the static resource. (e.g. via the AWS CLI) We're going for _a simple and primitive, but reliable_ solution.
* The static "app status" resource will be hosted on static.zooniverse.org, as that would make it scalable to the number of PFE users. (Each active user will ping the resource once per loading of Zooniverse.org, whether or not there's a status message.)

Tagging @marten as request originator.

## Notes
* Open dev question: **should we only allow text for the status update message, or are we going to allow HTML and JavaScript to be part of the message?** (Shaun: leaning towards HTML+JS)
* Open dev question: XMLHttpRequest or fetch()? (Shaun: I have both working, but I like XMLHttpRequest since nothing else is using fetch(), and we don't need that extra `isomorphic-fetch` package.json dependency.)
* **Current dev issue:** setting up the static "status message" resource on static.zooniverse.org - along with the necessary CORS settings - is as easy as pulling out teeth. _And not through the mouth._
* Future plans: a more advanced implementation that uses WebSockets and Amazon Lambda to more consistently monitor changes to the status update resource. (Tagging @rogerhutchings for the idea.)

screen shot 2017-03-01 at 15 52 11
_Behold, the status banner. At the bottom of the screen. With a nonsense message._

## Status
WORK IN PROGRESS - please don't merge, but feedback is welcome (2017.03.01)

## Preview
URL: https://status-banner.pfe-preview.zooniverse.org/
What you're expected to see:
* The status banner should appear at the bottom of the screen, with gibberish text.

## Review Checklist
- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

### CODE REVIEW

**Comment by astopy** [comment]
> If the resource exists, the status banner appears and displays the contents of the file to the user.

Only superusers can actually delete things from zooniverse-static (and only then when they're explicitly using the superuser role, so that it's not possible to accidentally delete a bunch of stuff), though anyone can overwrite individual files.

From a quick look at the code, I think it's already doing the right thing, but just to make it clear: You'll want to check if the file exists _and_ contains stuff. If it doesn't exist (it'll actually be a 403 rather than a 404 with S3) or if it's empty then don't display the banner.

> setting up the static "status message" resource on static.zooniverse.org - along with the necessary CORS settings

It should just be a case of uploading a file, and CORS should already be set up. Let me know if you're having trouble.

> a more advanced implementation that uses WebSockets and Amazon Lambda to more consistently monitor changes to the status update resource

Nice idea, but probably overkill for something that's rarely (hopefully never) going to be used.

**Comment by srallen** [comment]
Re the two questions:
I think I'd prefer txt. Even though access to the static bucket should be locked down, fetching and displaying whatever is there could open us up to a vulnerability if we allowed html/js.

We already polyfill for fetch (see: https://github.com/zooniverse/Panoptes-Front-End/blob/master/views/index.ejs#L72) and it's the current web spec standard, so that is what should be used.

**Comment by eatyourgreens** [comment]
👍 for `fetch` here's [an example for grabbing text subjects](/zooniverse/Panoptes-Front-End/blob/master/app/components/text-viewer.jsx#L16) You don't need the `import` as @srallen says, it's supported in the browser now.

**Comment by shaunanoordin** [comment]
## PR Update
Thanks for the feedback, everyone!

@astopy 
* You're right, the CORS works perfectly for a newly uploaded file! My previous error waltz must have been because I was testing on older files.
* Static status message URL set at https://static.zooniverse.org/zooniverse.org-status.txt
* Tested Input/Output:
  * static file found, is non-empty => show contents of static file in banner
  * static file found, is empty => don't show status banner
  * static file not found (403, 404, etc) => don't show status banner
* Tested on OSX+FF/Chrome/Safari, Win7+IE11

@srallen @eatyourgreens 
* Thanks for the fetch polyfill! I've removed the `isomorphic-fetch` dependency and phased out XMLHttpRequest in favour of _vanilla_ `fetch()`.
* Status Message will _only be displayed as text._ HTML+JS functionality has been removed for safety reasons.

## Notes
Not sure if tests are needed for this PR since the feature requires an external resource? If you believe I should write a test before this PR gets merged, please point me to a good example and I'll hop to it.

## Status
Ready for review, but please **do NOT merge until zooniverse.org-status.txt has been emptied**.

**Comment by eatyourgreens** [comment]
Code looks good to me. Maybe autofocus the button so I can dismiss the popup with the enter or space keys?

**Comment by shaunanoordin** [comment]
@eatyourgreens autofocus has been added! `<button autofocus />` doesn't seem to work so I've triggered it manually with `button.focus()` when the banner appears.

**Comment by eatyourgreens** [comment]
React might have its own funky spelling of the attribute. `autoFocus` perhaps?

**Comment by shaunanoordin** [comment]
Goddammit, React. Thanks @eatyourgreens - it was `autoFocus`.

**Comment by shaunanoordin** [comment]
## PR Update
The status update file - https://static.zooniverse.org/zooniverse.org-status.txt - has been emptied, so this PR is now merge-safe. 👍

**Pull request merged**
