### PR TITLE
Moved close button to outside of dialog

### LINKED ISSUE #1296: Dialog Controls overlap scroll bar
Happening in Linux and Windows where the scroll bar isn't hidden: 

screenshot from 2015-07-30 16-18-18

### PR DESCRIPTION
**Pull request by srallen**
- Fixed #1296 by moving the close button to the right of the dialog container

### CODE REVIEW

**Comment by brian-c** [comment]
Now the close button disappears on mobile.

Can we not solve this by just nudging it over to the left like, half an em?

**Comment by srallen** [comment]
I could do that, but it looks odd for dialogs that don't need to scroll.

I just updated the PR and added a media query so the fixed positioning on the close button only applies to screens larger than 768px. Also, fixed a responsive issue in the footer. Overall a lot could be done and the dialogs still don't look right at least in iOS safari since the header responsiveness needs fixing as well as dialogs showing tables (i.e. the metadata dialog in the classifier), but it makes sense to do a pass on those things in separate PRs.

**Comment by brian-c** [comment]
This still allows for situations where the close box is positioned offscreen. How about just moving it to the top side?

**Comment by srallen** [comment]
Ok, update PR. I didn't see where that was happening, but I guess I missed it.

**Comment by brian-c** [comment]
Works for me. Thanks!

**Pull request merged**
