### PR TITLE
ui update for aggregation experimental feature

### PR DESCRIPTION
**Pull request by camallen**
remove admin only view for aggregation dumps, instead change the UI to signal this a new experimental feature.

### CODE REVIEW

**Comment by edpaget** [comment]
screen shot 2015-09-30 at 9 07 32 am

I think the experimental UI maybe a little extreme...

**Comment by camallen** [comment]
Yeah - what do you think about just removing the blue highlight on "Experimental new feature"? I want to signal that this may not work properly and that it applies to the aggregation button...

**Comment by edpaget** [comment]
How about adding an *experimental* to the button?

**Comment by aweiksnar** [comment]
http://fontawesome.io/icon/flask/ may work here too

**Comment by camallen** [comment]
thanks @aweiksnar used a gear icon..look better?

**Comment by edpaget** [comment]
:ok_hand:

**Pull request merged**
