### PR TITLE
Don't override Talk links for middle and right mouse buttons

### LINKED ISSUE #3048: Zooniverse(url) links in talk reuse current window/tab on middle-mouse-click/+CTRL key.
## Expected behavior

Open clicked link, with middle-mouse-button, in a new tab.
(_Same for clicked link (left-mouse-button), while CTRL key is down._)
## Current behavior

Opens clicked link, with middle-mouse-button, in current tab/window.
(_Same for clicked link (left-mouse-button), while CTRL key is down._)
## Steps to replicate

Middle mouse click on a "`https://www.zooniverse.org/...`" link in a Talk post.
(_checked at 'Gravity Spy' and main zooniverse Talk._) 
## Additional information

Only related to links pointing to a zooniverse url.
Seems, so far, only related to links in Talk.
Seems a fairly resent behavior change.
_Links pointing outside the zooniverse domain do open in a new tab/window._
_Currently the only option to force a zooniverse-url-link to open in a new tab seems to be the trough the "open in new tab" mouse-menu option._
- **Operating system:**
- **Browser:**

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fixes #3048 .

Describe your changes.
Checks for `e.button` and doesn't override links if it exists and is greater than 0, or if `e.ctrlKey` or `e.metaKey` are set.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://talk-links.pfe-preview.zooniverse.org/
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Testing is progressing, but I'm currently encountering mild problems getting a realistic test setup since the `<a>` links on Talk point to `zooniverse.org`; whereas I'm testing on either `localhost` or `talk-links.pfe-preview.zooniverse.org`

This means that `e.target.pathname !== window.location.pathname` always evaluates to `true`.

More info as I drill down.

**Comment by eatyourgreens** [comment]
@shaunanoordin I've added a relative link, to the About page, here: https://talk-links.pfe-preview.zooniverse.org/talk/38/195

**Comment by shaunanoordin** [comment]
👍  Noice!

**Comment by shaunanoordin** [comment]
## PR Review
* As a user in Talk, I am able to left-click on an `<a>` link - that points to an address _with the same URL origin_ - to open the link _in the same tab_
* As a user in Talk, I am able to middle-click on an `<a>` link - that yadda yadda same origin - to open the link _in a **new** tab_
* However, if I try to press **Cmd + left-click**, the link will open _in the same tab_ .
  * To replicate this, go to http://localhost:3735/talk/38/195 and Cmd + left-click on talk-links.pfe-preview.zooniverse.org's About page link. 
  * Strangely, **Ctrl + left-click** (the Windows version) _works fine in IE11_ and opens in a new tab.

* Tested on Win7+IE11, OSX+Chrome/FF/Safari9 on staged environment - https://talk-links.pfe-preview.zooniverse.org/talk/38/195
* Tested with a variety of absolute links and relative links to account for different URL origins on staging.

## Status
The PR looks OK, but #3048 explicitly brought up the issue of Cmd + left-click _not_ opening in a new window/tab. What are our thoughts on the expected behaviour of Cmd + left-click for Mac users? (Also, what do the Linux people have for a Cmd/Ctrl equivalent?)

**Comment by shaunanoordin** [comment]
## PR Review (Update)
I forgot to clarify: the Cmd+left-click issue only applies to _absolute links_. Relative links have proven to be OK for all cases: left-click, middle-click, cmd+leftClick, cmd+rightClick on Chrome/FF/Safari/IE11

**Comment by shaunanoordin** [comment]
## PR Review (Update)
By the way, don't give IE11 any credit for being smart with how it handles Ctrl+leftClick. It's not that - unlike FF/Chrome/Safari - IE11 somehow miraculously recognises the Ctrl modifier key and accounts for that in the code.

No, IE11 is such a dumbass that if you middle-click or Ctrl+leftClick, it _ignores_ the `onClick` event handler altogether and just goes "Doot de doot de doo, I'm gonna open a new window now, doot dee doo". It's so dumb that it bypasses the logic of our code and comes around the other side working exactly like expected.

**Comment by eatyourgreens** [comment]
@shaunanoordin you're right, I need to update this to check for modifier keys too.

**Comment by eatyourgreens** [comment]
@shaunanoordin should be fixed now.

**Comment by shaunanoordin** [comment]
## PR Review (Update)
* Links now correctly respect Cmd-leftClick! Doing so opens a new window, as expected.
* Left-click and middle-click continue to work properly, as previously reported.
* Tested on Win7+IE11, OSX+Chrome/FF/Safari9 on localhost

## Status
LGTM! Nice on, Jim. Merging now.

**Pull request merged**
