### PR TITLE
Optimise recent projects

### PR DESCRIPTION
**Pull request by eatyourgreens**
Include avatars and owners in the initial API calls.
Update ProjectIcon to use cached resources if possible.

Supersedes #2882

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This is an alternative to #2882, which removes the network requests from the `ProjectIcon` component but doesn't use the project cards API route.

Staged at https://optimise-recent-projects.pfe-preview.zooniverse.org

**Comment by camallen** [comment]
i like this - i still think #2921 won't be fixed by this but it's a neat solution using resource links.  LGTM

**Comment by eatyourgreens** [comment]
I'm not 100% sure, but I think adding the `include` param might actually force the client to make the request for the full project resource, rather than grabbing the partial resource that was cached by the cards request. Needs checking, and still a bit of a workaround.

**Comment by wgranger** [comment]
Looks good. I think this is a clever way to make the API call more efficient. Just out of curiosity, what was the reason for adding `alt=''` in the most recent commit?

**Comment by eatyourgreens** [comment]
@wgranger Yeah, `alt` is a required attribute. If it's missing, screenreaders will generally readout the image URL, which isn't massively helpful here. You can set it to an empty string if you judge an image to be purely presentational. Here, the project name is already present inside the link, so additional text seems unnecessary in order to understand where this link goes, so I set the `alt` to nothing.

**Pull request merged**
