### PR TITLE
Use input widget state to style task inputs

### LINKED ISSUE #5096: Text highlighter button labels are unstyled
## Expected behavior
Text highlighter options should be styled like the answers to question tasks.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Screenshot showing unstyled highlighter options

## Additional information
Looks like an update to styled components deprecated `withComponent` at some point.
https://github.com/zooniverse/Panoptes-Front-End/blob/a0d50ff2e3dff385d36eddf80a20672d7c58d79a/app/classifier/tasks/highlighter/components/HighlighterButton.jsx#L14-L17

- **Operating system:**
- **Browser:**

### PR DESCRIPTION
**Pull request by eatyourgreens**
Use checkbox/radio button state (active, checked or focussed) to control the style of adjacent task labels.
Remove onFocus(), onBlur(), unfocus() and associated tests from TaskInputField.
Convert TaskInputField to a function and add React.memo() for speed.
Works around some problems with the multiple choice and single answer task tests by rewriting them to use shallow rendering. Full mounting of those components won't work until enzyme supports `React.memo()`.
Fixes #5096.

This PR should fix slow/laggy behaviour on phones, where there could be a noticeable delay between tapping an answer and seeing it change colour.

Staging branch URL: https://pr-5091.pfe-preview.zooniverse.org

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Tests are broken because of airbnb/enzyme#1875. The multiple choice and single answer question tests both run a full mount of the task component, then run tests on the input field children.

**Comment by eatyourgreens** [comment]
Single answer and multiple choice answers seem to be faster in the dev classifier on this branch, but drawing tool radio buttons are still really slow. I'm not sure why. 😞

**Comment by eatyourgreens** [comment]
Thanks for taking a look. The highlighter options are buttons that you press after each text selection (like the bold/italic buttons in a word processor), so they don’t have a checked state. I’m happy to look at those in a different PR, if these changes are ok.

**Comment by beckyrother** [comment]
Is there a project that uses this to take a look at? 
Maybe the highlight button is inactive until text is selected, with a rollover or modal on click that explains that text needs to be highlighted first before this can be used.

**Comment by srallen** [comment]
@beckyrother I think @eatyourgreens or @simensta know which projects that use this. You can also see a contrived example in the dev classifier: https://master.pfe-preview.zooniverse.org/dev/classifier select "Annotate Text" as well as the last frame for the subject viewer to get a text subject.

**Comment by beckyrother** [comment]
Thanks Sarah! You're right, this is confusing, especially since the drawing task works the opposite way – clicking the type of annotation first and then clicking in the image. Is this possible with text? That is, click the highlight tool first and then select the text?

**Comment by srallen** [comment]
@beckyrother I've opened #5099 so we can keep track in an issue and have copied your question over to there.

**Pull request merged**
