### PR TITLE
allow admin to set the project external redirect

### PR DESCRIPTION
**Pull request by camallen**
save api devs work...allow most of the admin stuff to be done here.

### CODE REVIEW

**Comment by edpaget** [comment]
I think this would actually work better with the `<Autosave>` component since that will give feed back around errors, etc.

**Comment by camallen** [comment]
so i've used the autosave component https://github.com/camallen/Panoptes-Front-End/commit/5852f574da21aa4b91733eadcfa1a5081d46b2ab but this ends up firing off a bunch a project version GETs on the text input change events that update the internal project redirect state. @edpaget thoughts on restricting these to only run on load?

**Comment by camallen** [comment]
@edpaget - should be using the updated version component and the autosave for redirect now.

**Comment by edpaget** [comment]
:shipit:

**Pull request merged**
