### PR TITLE
Sort linked comments in latest comment previews

### PR DESCRIPTION
**Pull request by aweiksnar**
- Makes it so the latest comment links correctly go to the last page 
- #873

### CODE REVIEW

**Comment by chrissnyder** [comment]
Got `Uncaught (in promise) TypeError: Cannot read property 'sticky' of undefined` in search using this. I think this unrelated to the PR, but https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/search-result.cjsx#L26 should be `<DiscussionPreview discussion={discussion} project={project} />`

**Comment by aweiksnar** [comment]
Good find! just updated

**Comment by chrissnyder** [comment]
:us:

**Comment by chrissnyder** [comment]
Looking back on it, this does make me hate how I did the search-result component. Needs some love in the future.

**Pull request merged**
