### PR TITLE
Fix discipline and other tag inputs

### PR DESCRIPTION
**Pull request by mcbouslog**
Staging branch URL: https://fix-tags-inputs.pfe-preview.zooniverse.org/

Fixes broken discipline and other tag UI in project details lab section.

Updating on project resource instead of using `handleInputChange`.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Could you update this to describe the bug that it's fixing? I'm not sure what to look for and this isn't linked to an existing issue.

**Comment by eatyourgreens** [comment]
I _think_ these changes are OK, but they work by bypassing the input sanitisation that @srallen added here. https://github.com/zooniverse/Panoptes-Front-End/blob/09cc8f46d34b2a6dbf413b14b3fa935232ab5052/app/lib/handle-input-change.coffee#L21-L24

So input from those tag text boxes is not being checked for malicious code etc.

Would a better approach be to loop through the tags array, sanitising each tag, then submit the cleaned array?

**Comment by mcbouslog** [comment]
Yes I like "loop through the tags array, sanitising each tag, then submit the cleaned array" much better, I'll update accordingly.

**Comment by eatyourgreens** [comment]
👍 By the way, I tried testing this by adding `<b>Hello</b>` as a tag. I don't think the front-end renders the HTML anywhere, but I'm not 100% sure about that.

**Comment by mcbouslog** [comment]
I'm going to close this pr in favor of one that fixes underlying issue better.

**Pull request closed without merging**
