### PR TITLE
Set Min-Width on Panoptes Container

### LINKED ISSUE #3986: Non-logged-in home page – limit width of content
At very wide screen sizes, the content stretches so far as to be illegible. **Please limit the width of the content to 1440px.** Background color when the viewport is wider than the content should be #D1D5D8 (new color)

Also, please make the "zooniverse works" section just one column.

### PR DESCRIPTION
**Pull request by wgranger**
Fixes #3986 

Describe your changes.
This PR limits the max width of the main Panoptes container to keep content readable on wide screens.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

https://fix-3986.pfe-preview.zooniverse.org/

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by beckyrother** [comment]
**Video** section gets really tall and the text stays way down at the bottom, which is weird. Can it be centered instead – I know this is a change but the position was questioned when we first updated and maybe vertically centering makes more sense.

**Discover, teach, learn** section gets really tall on a wide screen.

banners_and_alerts_and_zooniverse_720

**Comment by beckyrother** [comment]
@mcbouslog ready for your dev review!

**Comment by beckyrother** [comment]
@wgranger looks like the background is white now? if so it's good to go, ignore that grey background business

**Comment by mcbouslog** [comment]
https://fix-3986.pfe-preview.zooniverse.org/ has been updated, this LGTM. I know overkill, but @beckyrother could you take another quick pass (including on window over 1440px) and confirm all set? thanks all.

**Comment by beckyrother** [comment]
Looks awesome, thank you @wgranger and @mcbouslog ! Approved here.

**Pull request merged**
