### PR TITLE
Add css to change font-family for Czech

### LINKED ISSUE #5314: Text with diacritic marks displays with mixed fonts
## Expected behavior
Text should display consistently, regardless of language.

## Current behavior
Some characters with diacritic marks are displayed in Open Sans. This screenshot shows a block of text from Whales as Individuals which is rendered in a mixture of Karla and Open Sans. There is a clear difference in character size between the two fonts.
_Please include any error messages from the browser console and/or screenshots_
Screenshot showing Whales as Indivduals in Czech, with text displayed in Karla and Open Sans.

### PR DESCRIPTION
**Pull request by srallen**
Staging branch URL: https://pr-5575.pfe-preview.zooniverse.org

Fixes #5314

This adds a bit of simple CSS to change the font-family to Arial, sans-serif as suggested in #5314. 

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by srallen** [comment]
C&S about page: https://pr-5575.pfe-preview.zooniverse.org/projects/sassydumbledore/chimp-and-see/about/faq?env=production

**Comment by srallen** [comment]
@eatyourgreens in the future, when @beckyrother is requested for review, could you hold off on merging until she has a chance to respond? Thanks!

**Comment by eatyourgreens** [comment]
Sorry, I looked at this on my phone, saw that I was invited to review it and didn't see anyone else tagged in. If approval is required from @beckyrother to merge a PR, I'd suggest assigning those PRs directly to her, rather than inviting review.

**Comment by srallen** [comment]
Yep, we can do that in the future. Good suggestion.

**Pull request merged**
