### PR TITLE
added new publications

### LINKED ISSUE #3927: Publications page update
There are new publications to add to the publications page.

The new publications to be added are shown in white in the following document (the ones that have already been added are shown in grey):

https://docs.google.com/spreadsheets/d/1NZ31aVPiQag5V3-zY9tIP2x2WPXFEf9dLIIHBSHkx3M/edit#gid=0

Thanks,
Helen

### PR DESCRIPTION
**Pull request by mariamsaeedi**
Fixes #3927 .

Added new publications from Google doc as per the issue described.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [X] Did you deploy a staging branch? https://update-publications.pfe-preview.zooniverse.org/about/publications
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
@camallen looks like you pushed 6 unrelated commits to this branch earlier, so this branch might need rebasing against master.

**Comment by camallen** [comment]
@eatyourgreens my bad, updated with the relevant commits.

**Comment by mariamsaeedi** [comment]
Added new publications from Google doc and @trouille ’s comment

Added Bahaadini+ 2017 
Added Crowston+ 2017

Zevin+ 2017, Campbell+ 2015, and Crall 2017 were already listed in the Google doc 

@hrspiers could you please review

**Comment by hrspiers** [comment]
Hi,

Looking at the staging branch, there seem to be a few numbers that have appeared that don't look like they should be there e.g. there is a;

- '(1)' after Galaxy Zoo: morphologies derived from visual inspection of galaxies from the Sloan Digital Sky Survey, Lintott+ 2008., 
- '(1)' after Radio Galaxy Zoo: host galaxies and radio morphologies derived from visual inspection, Banfield+ 2015.,
- '(1)' after Task Workflow Design and its impact on performance and volunteers' subjective preference in Virtual Citizen Science, Sprinks+ 2017., 
- '(4)' after 'That looks weird' - evaluating citizen scientists' ability to detect unusual features in ATLAS images of LHC collisions, Barr+ 2016.

Also, the avatar images for each of the publication types don't seem to be present in the staging branch - is this expected?

Thanks
Helen

**Comment by eatyourgreens** [comment]
@hspiers are you checking the page on staging or production? The production link is https://update-publications.pfe-preview.zooniverse.org/about/publications?env=production and I can see the avatars there.

Checking the publications page on staging probably won't work, because production projects might not exist there.

**Comment by hrspiers** [comment]
Thanks @eatyourgreens, I was using the staging link from the first comment above ( https://update-publications.pfe-preview.zooniverse.org/about/publications).

Everything looks fine in the production link you shared - for future, where can I get the production link from?

**Comment by eatyourgreens** [comment]
@hrspiers just add `?env=production` to the URL to use the production database.

**Pull request merged**
