### PR TITLE
Autofocus question tasks

### PR DESCRIPTION
**Pull request by eatyourgreens**
Adds autofocus for question tasks by focusing the question, rather than the first answer, if no answer has been selected yet.

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://autofocus-questions.pfe-preview.zooniverse.org/
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This should allow you to answer question tasks from the keyboard, without raising the issues in #2563

**Comment by eatyourgreens** [comment]
https://autofocus-questions.pfe-preview.zooniverse.org/projects/mschwamb/comet-hunters/classify?env=production looks like a good project for trying this out.

**Comment by eatyourgreens** [comment]
Good point about the tutorial. It might be launching before focus is set, so that there's no active element to return focus to once it closes. I'll have a look.

**Comment by eatyourgreens** [comment]
I've fixed the tutorial focus, which reminded me that the `Tutorial` component is still written in coffeescript. I wasn't sure if converting it would be in scope here, so I might leave that to a separate PR.

Mini-courses should have similar behaviour, if they don't already.

**Comment by mcbouslog** [comment]
Looks good to me. 

Not sure if should hold anything up, but if consecutive question tasks the second won't have focus like the first - https://autofocus-questions.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?workflow=3023.

**Comment by eatyourgreens** [comment]
I thought that was fixed in 63dad58c but maybe not?

**Comment by eatyourgreens** [comment]
Checking the task sounds like a good idea. I'm not sure why I didn't do that.

**Comment by eatyourgreens** [comment]
@mcbouslog turns out that the `GenericTask` component doesn't receive `task` as a prop so I'll give this some further thought.

**Comment by eatyourgreens** [comment]
@mcbouslog should be fixed in 590d454

**Comment by mcbouslog** [comment]
Jim your prediction is correct, if a multiple question task's option(s) are selected, then unselected, a following question task's focus will be on the Done button instead of the task title. However, if the first task requires at least one answer, this issue doesn't come up.

I'm not sure if this should block things though, it might be an edgy enough case to punt on?

Regardless, I'm trying to wrap my head around a possible solution (sorry for the false start on a `task` prop). Maybe we could compare the `question` prop between `prevProps` and `this.props`, presuming they wouldn't be the same between back to back question tasks?

**Comment by eatyourgreens** [comment]
Thanks @mcbouslog you are absolutely right. I should be checking to see if the question has changed.

**Comment by eatyourgreens** [comment]
Updated to look for question changes when determining whether to autofocus the container.

**Pull request merged**
