### PR TITLE
Limit username length to 255 characters

### PR DESCRIPTION
**Pull request by rogerhutchings**
via zooniverse/Zooniverse#51 - the API errors out if usernames are too long

### CODE REVIEW

**Comment by simoneduca** [comment]
@rogerhutchings LGTM, happy for me to merge?

**Comment by eatyourgreens** [comment]
Should be `maxLength` instead of `maxlength`, I think: https://facebook.github.io/react/docs/tags-and-attributes.html

**Comment by simoneduca** [comment]
Ha! Good catch, @eatyourgreens.

**Comment by srallen** [comment]
LGTM

**Pull request merged**
