### PR TITLE
Add a featured project editor to the Projects page

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Adds a FeaturedProjectEditor, which wraps a featured project card and allows admins to edit it with the project search selector.
 - adds an optional onChange prop to the project search selector, so that we can override the default link navigation behaviour.
- adds an options prop to the project search selector, which can be used to pass query options for filtered searches.
- updates the admin project search to use the new search selector.

Staging branch URL: https://pr-5667.pfe-preview.zooniverse.org/projects

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I'll have a look at that type error. It happens on the projects page too, on master: https://www.zooniverse.org/projects

**Comment by eatyourgreens** [comment]
That overflow bug is annoying. When I open the search box, in Chrome and Firefox, it behaves fine and sits inside the project card.

Screenshot of the project search displaying nicely inside the project card.

**Comment by eatyourgreens** [comment]
The type error is fixed. The select component fires `onChange` even if you cancel, so I added a check for `option` before handling the change event.

**Comment by wgranger** [comment]
Looks good. I'm not too worried about the overflow bug as it wasn't introduced in this PR, and it is only present to admins in rare cases.

**Pull request merged**
