### PR TITLE
Add deleteIfOutOfBounds to drawing tool root

### LINKED ISSUE #4579: Out-of-bounds marks can be submitted in a completed classification
## Expected behavior
Drawing tasks that lie outside the subject image area should be automatically detected and deleted.

## Current behavior
Marks that are created by a mouseup/touchend event outside the subject image are deleted. However, if the mouseup/touchend event that creates the mark is inside the subject, the mark is not deleted, even if its final (x,y) coordinates lie outside the subject area.

## Steps to replicate
Draw a point and drag it quickly upwards to fling it outside the subject. Lift your finger (or lift the mouse button) while still inside the subject. It's possible for the subject to end up outside the image area, but the mark is not deleted and remains in the submitted classification.

## Additional information

- **Operating system:** n/a
- **Browser:** n/a

### PR DESCRIPTION
**Pull request by eatyourgreens**
Staging branch URL: https://delete-out-of-bounds.pfe-preview.zooniverse.org

Fixes #4579 .

Check deleteIfOutOfBounds on every drawing tool update and delete the current tool if outside the subject.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I'm not sure what the performance implications are of performing this check on every mark, on every component update, but this fixes a bug that's been reported by people accidentally placing marks when using Space Warps on their phones.

**Comment by eatyourgreens** [comment]
@shaunanoordin I was testing with my test workflow at https://delete-out-of-bounds.pfe-preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify It doesn't show this bug, so it must be specific to Space Warps. 🤔

**Comment by eatyourgreens** [comment]
Confirmed this is a bug when markers are cloned across more than one frame.

**Comment by eatyourgreens** [comment]
I've rewritten this to check tool positions when the renderer component update. I've also modified the destroy method so that it checks for a valid array index before splicing a mark from the annotation.

**Comment by shaunanoordin** [comment]
What the butts, it only affects multi-frame annotations? I can't even begin to comprehend why that's happening. Good news is, though, is that initial testing with the newest update looks good. 👍 Let me run through it one last time before I approve & merge.

**Comment by shaunanoordin** [comment]
## PR Review (Update)
This PR now looks good to go! The latest changes indicate that the previously detected issue - where the removal of a Marker (if it's out of bounds) results in the removal of ALL Markers - has been resolved.

This has been confirmed on localhost, with the latest branch updates, using Space Warps (?env=production) as a primary test case. Looks good on OSX+Chrome66.

Basic PFE testing looks OK (notably, marking/drawings still look OK when tested on a sample project, SCOTUS notes) 👍 

### Status
LGTM, merge & go

**Pull request merged**
