### PR TITLE
Make field guides available to all projects

### LINKED ISSUE #2662: Move field guide from experimental tool to public tool
After review @chrislintott and I decided it works well and should be offered to everyone.

### PR DESCRIPTION
**Pull request by brian-c**
Closes #2662.

### CODE REVIEW

**Comment by srallen** [comment]
@brian-c I think this needs a rebase since I merged the `make-tutorials-public` branch

**Comment by brian-c** [comment]
Rebased, thanks.

**Comment by srallen** [comment]
Tiny nitpick, but if this is ready for all projects, maybe `potential-field-guide.cjsx` could be renamed?

**Comment by brian-c** [comment]
"Potential" refers to the field guide's existence. It's saying "Here's the project, if there's a field guide, fetch it and render it.".

I'm up for renaming though. Maybe `<AvailableFieldGuide>` or something?

**Comment by srallen** [comment]
OH, I didn't read it that way and thought it was a way to indicate a dev version. I think maybe to prevent future confusion, a renaming would be useful. Thanks.

**Comment by srallen** [comment]
I noticed that the scrolling for IE11 still wasn't fixed, so I submitted #2786 which should probably merged prior to this.

**Comment by srallen** [comment]
When #2920 is merged, I'll then rebase this one and merge.

**Pull request merged**
