### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by srallen**
- Updated Home page styles and content based on @heathv's design in #205
  - Featured projects listing with scroll listener and effects 
- Reworked header
  - Updated styles including moving the main-nav-items to be inline
  - Added on hover context menu for logged in user from discussion with @heathv 
  - Added scroll listener and css transition effects.
- Added basic style guide designs from @heathv for typography and buttons

### CODE REVIEW

**Comment by brian-c** [comment]
A couple quick notes:

- Double avatars in the header. Merge error?

- Make sure the sticky header resets itself when switching pages. Does the header need to be sticky anyway? What's that for?

- The header appears to have a fixed height now, which means when it wraps lines on small screens it can't push down the content that follows.

- Let's avoid fixing sizes of things in pixel values (header height, "Get started" button width). I really want us to be in the habit of letting the content and the viewport determine how things lay out, especially since we'll have very little control over most of the content. Might be a specific thing Heath wants; defer to him.

- The featured projects are sticky too, sometimes. Class name collision?

- Lots of font styles across the site are different. Not sure if that was intentional. Might want to namespace typography changes if they only apply to the home page.

**Comment by srallen** [comment]
I've fixed the avatar thing. I didn't catch it because I don't have custom avatar. A default one should be put in place as noted in the pull request for #311. Without any avatar, the context menu isn't aligned correctly, fyi.

Also, I fixed the header when switching pages and removed the max-height. The sticky header on the home page is a design idea from @heathv. I could go either way on it.

The featured projects is supposed to be sticky initially to give site visitors an indication that there's more content to scroll down to. I changed the class names to make this more clear.

The changed typography and buttons are from [the style guide](http://adobe.ly/1E69eLu) @heathv is working on. I could scope the font-sizes, but maybe we should talk about it altogether?

**Comment by heathv** [comment]
There are some weird bits on there right now (i.e., the project cards being half-sticky) due to content not being fully flushed out. We have lots of copy via Darren, but I'm slowly working on getting artwork created to go along with it. Typography conflicts are my fault, I switched to using 10px as a base so font-sizes could be a simple multiple of 10 (i.e., 15px = 1.5em) I have no idea what conflicts this creates in the front-end so it can be switched back if need be.

**Comment by brian-c** [comment]
Cool, thanks @srallen.

Re: font size, if you want to define something in px, use px. I wrote everything using em-sized fonts so they'll grow or shrink appropriately in context but if you want to define font sizes in explicit pixels, no worries. Just keep in mind the consequences of changing the base.

**Comment by heathv** [comment]
Cool, will do.

**Comment by srallen** [comment]
@brian-c, I've changed the css to scope the font-sizes to just the homepage for now. Also added in some more designs and placeholder content that Heath had ready this morning.

**Comment by brian-c** [comment]
Sweet, thanks.

**Pull request merged**
