### PR TITLE
[Security] Upgrade css-loader to version 5

### PR DESCRIPTION
**Pull request by eatyourgreens**
Upgrade `css-loader` from 2.1 to 5.2, to fix a security vulnerability in older versions of `postcss`. I've also upgraded the related packages: `mini-css-extract-plugin`, `style-loader`, `stylus-loader` and `stylus`.

`css-loader@4` dropped support for absolute paths in URLs in CSS, which breaks a couple of our background images. I've updated those to use local file paths, which webpack will rewrite during the build. See https://github.com/webpack-contrib/css-loader/issues/1136

Staging branch URL: https://pr-5944.pfe-preview.zooniverse.org

This is a big version jump, so might break the webpack build.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Background images are broken on staging, but I think that's down to how our URLs resolve to `static.zooniverse.org`. They're also broken on master (on staging.)

Pages like https://master.pfe-preview.zooniverse.org/lab should have a dark background colour set, so that the white text is legible if the background image doesn't load.

The Zooniverse lab page, not logged-in, showing white text on a white background with no background image.

**Review by shaunanoordin — APPROVED** [review]
## PR Review

This PR updates the CSS loader dependencies.

- Testing works fine on localhost + macOS + Chrome.
- I wiped and reinstalled my dependencies and everything compiles OK.
- The background image on https://local.zooniverse.org:3735/lab loads correctly.
  - I was going to say, _"actually, maybe you don't need to worry about fixing the URL paths in the .styl file because if you go to https://master.pfe-preview.zooniverse.org/lab right now, the background images are missing too, so it's not a new problem-"_
  - ...but then I tried reverting those paths on localhost and that caused the compiler to say _"lol I have no idea where's this builder-landing.jpg you're talking about"_ so that change was totally necessary.

LGTM! 👍

**Comment by eatyourgreens** [comment]
Yeah, the linked webpack issue explains why the background image URLs stopped working. As far as I can tell, it should be either a fully resolved URL, or a local file path that webpack can convert to a URL.

**Comment by eatyourgreens** [comment]
> I wiped and reinstalled my dependencies and everything compiles OK.

@shaunanoordin (and anyone else reading this.) For future reference, run `npm ci` to do a clean install. It deletes `node_modules` before installing.

**Pull request merged**
