### PR TITLE
Throw a meaningful error when workflow.first_task is missing

### PR DESCRIPTION
**Pull request by eatyourgreens**
Throw `First task has not been set for workflow`, when `workflow.first_task` is undefined or empty.

I Fancy Cats showing 'First task has not been set for workflow' instead of the Classify page.

There's a project that's broken because `workflow.first_task` is an empty string. This PR would show them a meaningful error, although it's not clear how they created a workflow with no first task.
https://www.zooniverse.org/projects/matildagrahn/korrekturlas-svenska-skillingtryck/classify?reload=0&workflow=20341

See also this Talk post:
https://www.zooniverse.org/talk/17/2244862?comment=3681061&page=1

TODO: is there a bug in the project builder that allows you to create invalid workflows?

Staging branch URL: https://pr-6067.pfe-preview.zooniverse.org/projects/matildagrahn/korrekturlas-svenska-skillingtryck/classify?reload=0&workflow=20341&env=production

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Unfortunately (for testing purposes), Workflow 20341 has now been fixed with a proper `first_task`. Give me a minute to spin up a WF with no first_task. (note: I'm only able to do this via console commands, so I'm still not sure how a WF without a `first_task` would be created on the Project Builder)

Also, I'm unsure if we can rely on a project having a `T0` task.

**Comment by shaunanoordin** [comment]
I've created two test workflows:

- Staging Workflow 3549, which has task **T0** but no `first_task`
    https://pr-6067.pfe-preview.zooniverse.org/projects/darkeshard/test-project-2021/classify?reload=0&workflow=3549
- Staging Workflow 3551, which has task **T1** but no `first_task`
    https://pr-6067.pfe-preview.zooniverse.org/projects/darkeshard/test-project-2021/classify?reload=0&workflow=3549

As of commit 1045950, this PR's update allows 3549 to work, but 3551 still crashes, of course.

I'd normally feel strongly having a more resilient fallback for first_task, but since I'm unsure _how_ the empty first_task issue even cropped up on Project Builder, I'm OK with assuming T0 is the default for now. 🤷

(If we do want to be more resilient, I assume something like `if (!first_task) { first_task = Object.keys(workflow.tasks)[0] }` would work... right until we have a WF with 0 Tasks, which crashes anyway.)

**Comment by mcbouslog** [comment]
> Unfortunately (for testing purposes), Workflow 20341 has now been fixed with a proper `first_task`. Give me a minute to spin up a WF with no first_task. (note: I'm only able to do this via console commands, so I'm still not sure how a WF without a `first_task` would be created on the Project Builder)
> 
> Also, I'm unsure if we can rely on a project having a `T0` task.

Sorry about that! I fixed the workflow per a contact ticket before realizing it was linked here.

**Comment by mcbouslog** [comment]
I can't figure out how `first_task` became an empty string and couldn't be updated. I can't remember if before I fixed it in the originally broken workflow if the first task select input showed T0 was the first task, if the select was disabled, or something else? I see in https://pr-6067.pfe-preview.zooniverse.org/lab/1873/workflows/3549 if you select the task it doesn't update `first_task`, but I'm not sure why, maybe an AutoSave issue.

In this line - https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/workflow-tasks-editor.cjsx#L280:
`@props.workflow.update first_task: @props.workflow.tasks[taskKey].next ? Object.keys(@props.workflow.tasks)[0]`

I'm rusty on my coffeesscript, but should it be:
`@props.workflow.tasks[taskKey].next ? @props.workflow.tasks[taskKey].next : Object.keys(@props.workflow.tasks)[0]`

Prob not even be related to this bug.

I don't know, I don't have a strong opinion on what to do, but we could create an issue and revisit if occurs again? This PR will likely fix most of similar issues, but like Shaun notes if there isn't a T0 there'd still be an issue and with uncertainty around why maybe ok to punt until further occurrences?

**Review by mcbouslog — APPROVED** [review]
This fixes the issue noted. How the issue arose is unclear, and a similar issue could arise if there's no tasks or no `T0`, but this will likely solve the vast majority of related issues.

**Comment by eatyourgreens** [comment]
@shaunanoordin @mcbouslog You're right that we can't really guess which task key should be first for a give workflow. I'm altering this PR to show a more meaningful error instead.

**Pull request merged**
