### PR TITLE
Remove word in order to fit bio onto three lines

### PR DESCRIPTION
**Pull request by alexbfree**
Noticed that my bio flows onto 4 lines following latest update. Removing a word to make it fit.

### CODE REVIEW

**Comment by alexbfree** [comment]
@edpaget I did a rebase, in an attempt to clean this up, based on your previous suggestion, but i am not sure that i did it right. let me know if i need to do something further to tidy this.

**Comment by edpaget** [comment]
It doesn't quite look like it. Do you have time tomorrow and I can walk you through how to do squash extra commits?

**Comment by alexbfree** [comment]
@edpaget Yeah that would be great. Last time @camallen pointed me to squash commits i accidentally deleted some changes on the repo so a walkthrough would be great.

**Comment by edpaget** [comment]
@alexbfree sorry I didn't get to work on this with you today. Maybe friday morning?

**Comment by edpaget** [comment]
Closed via #1531

**Pull request closed without merging**
