### PR TITLE
Link to talk comments from subject page

### PR DESCRIPTION
**Pull request by aweiksnar**
- Link to individual talk comments from subject page
- ~~Also fix rounding error on getting a comment's page number~~

### CODE REVIEW

**Comment by brian-c** [comment]
Looks good to me. Just to confirm: pages are zero-indexed in Talk?

**Comment by aweiksnar** [comment]
They should be one-based: https://talk-staging.zooniverse.org/comments

**Comment by brian-c** [comment]
I think you were right with `Math.ceil` then. See the links for these comments on page 1:

screen shot 2015-06-10 at 10 00 33 am

(Also, I'm only getting three comments per page, is that right?)

**Comment by aweiksnar** [comment]
Ah yep! Just updated to use `ceil`. 3 Per page is just for dev, but can bump that up anytime

**Comment by brian-c** [comment]
Links from subject page look good.

I'm getting the wrong link when creating a new comment. Probably unrelated, I'll open an issue.

**Pull request merged**
