### PR TITLE
Move external links in main nav to triggered modal

### PR DESCRIPTION
**Pull request by aweiksnar**
- Real-estate is getting pretty tight in the main nav. The external
  links are probably not essential to always be visible, so this moves them to a
  dropdown modal

### CODE REVIEW

**Comment by brian-c** [comment]
Text in the popup is a bit giant on project pages (this might need a lower level fix, the root font size shouldn't be changing depending on what page you're on) and seems to disappear on hover.

**Comment by aweiksnar** [comment]
@brian-c I took a stab at a lower level fix / cleaning up some of the css that was causing different secondary pages to behave differently. 

I think it makes sense to set the top level em font to the main size used on the page and scale from there instead of using 10px and accounting for it. Let me know if the changes look okay

**Comment by brian-c** [comment]
Sizing looks solid now, thanks.

Links in the popup still turn white on hover though.

**Comment by aweiksnar** [comment]
Oh good catch, wasn't getting that in FF. Just pushed an update

**Comment by brian-c** [comment]
Awesome, thanks!

**Pull request merged**
