### PR TITLE
[Do Not Merge until Dec 2] Additional content pages

### PR DESCRIPTION
**Pull request by wgranger**
Staging branch URL: https://pr-5572.pfe-preview.zooniverse.org

Describe your changes.
This PR adds content for the Highlights Book and Donations about pages. Translation placeholders are also available for the content herein. Note, I also added some missing translation placeholders for the ES and NL locales.

Do Not Merge until newsletter is released.

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [x] Can you post a talk comment?

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by beckyrother** [comment]
Copy edits on book page:
- [ ] Remove hyphen in `hard-copy`
- [ ] Caitlyn `Buongiorno`

**Comment by beckyrother** [comment]
Please merge this Monday morning UK time, the link will be sent out in an Adler newsletter at 7am CST

**Comment by eatyourgreens** [comment]
Longer term, can new content pages be published with the [`content-pages`](https://github.com/zooniverse/front-end-monorepo/tree/master/packages/app-content-pages) app in the monorepo?

**Comment by wgranger** [comment]
@shaunanoordin Thanks for double checking those links. They were down late last week but appear to be working again, so this should be good to merge on Monday.

**Comment by rogerhutchings** [comment]
I've checked the links again, everything looks good. I'll merge it now.

**Pull request merged**
