### PR TITLE
Preserve language codes in project navigation

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add the current location's `env` and `language` query parameters to project navigation links, so that query parameters are preserved when you change pages, or reload a page.

Prepend the locale to page URLs when we're linking to pages in the NextJS project app.

Try it out on:
- PH TESS in Spanish: https://pr-6146.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk?language=es
- PH-TESS in Spanish, without query parameters: https://pr-6146.pfe-preview.zooniverse.org/projects/es/nora-dot-eisner/planet-hunters-tess/talk
- or with the test locale: https://pr-6146.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk?language=test
- I Fancy Cats without any query parameters: https://pr-6146.pfe-preview.zooniverse.org/projects/brooke/i-fancy-cats?env=staging
- Every Name Counts in German: https://pr-6146.pfe-preview.zooniverse.org/projects/arolsen-archives/every-name-counts?language=de

Staging branch URL: https://pr-6146.pfe-preview.zooniverse.org

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
It looks like this works on PH TESS except for links to `/about` and `/classify`, which redirect in NextJS to a new URL path without query parameters. The redirects in the project app (in the monorepo code) need to be updated to preserve any URL query parameters in the incoming request.

**Comment by eatyourgreens** [comment]
Here
https://github.com/zooniverse/front-end-monorepo/blob/8a58a91105c0a3fe70e121e87e3f05d9028b4802/packages/app-project/pages/%5Bowner%5D/%5Bproject%5D/classify/index.js#L12-L19

and here
https://github.com/zooniverse/front-end-monorepo/blob/8a58a91105c0a3fe70e121e87e3f05d9028b4802/packages/app-project/pages/%5Bowner%5D/%5Bproject%5D/about/index.js#L9-L17

the project app preserves the `env` query param but throws all the other request parameters away.

https://github.com/zooniverse/front-end-monorepo/pull/3152 might fix this by setting the locale before the page request is handled, but we might still want to keep the `language` param in order to add it to links to Talk etc. This might need testing on staging to see how it works once https://github.com/zooniverse/front-end-monorepo/pull/3152 has merged.

**Comment by goplayoutside3** [comment]
Looking good! Thinking more about navigation from PFE to FEM, this PR definitely works for Project Header nav links. Is there a plan on how to handle navigating to FEM while preserving the language from other pages? 

For example, PH TESS's Talk Board can be viewed in Spanish with `language=es`. Then, clicking on a Talk tag navigates to https://pr-6146.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/tags/transits. In this case, the language param isn't preserved, and won't be available to NextJS middleware if someone clicks About or Classify in the nav.

**Comment by eatyourgreens** [comment]
I’ve no idea about those links, without going through PFE and rewriting all the internal links.

**Comment by goplayoutside3** [comment]
Is manually attaching the language param to all links within PFE the only solution? Or is there another way to preserve the language param while navigating around project page links in PFE? I guess I’m wondering about writing some type of middleware like available to us in FEM.

**Comment by eatyourgreens** [comment]
I don’t know. The version of React router that’s used here is pretty old, but there might still be documentation for it online. 

For what it’s worth, this is a long-standing issue, since it also means that you can’t reload a PFE page that relies on query parameters. If you try it for one of those Talk pages, you’ll get ‘Not found’ if the project doesn’t exist in the staging API.

**Comment by eatyourgreens** [comment]
Remember that PFE is a single page JavaScript app that runs in your browser. We can use middleware in NextJS because that runs in Node on our servers.

**Comment by eatyourgreens** [comment]
On page routes like this, we wouldn’t want to add all the query parameters to navigation links. 
https://pr-6146.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/2112/2435547?page=1&scrollToLastComment=true&env=production

**Comment by eatyourgreens** [comment]
A better solution:
- only copy `env` and `language` to navigation links.
- PFE links should append a `language` query param but FEM links should include `locale` in the URL path.
- get the locale from the global store. It's available from both Redux and Counterpart, so whichever is easiest, I think.

**Comment by eatyourgreens** [comment]
@goplayoutside3 I've rebased to bring in the language picker changes, with a new commit message to reflect the new logic. FEM links should look a lot better now, and the `language` parameter should be ignored if it matches a project's primary language (which will be `en` for 99.99% of projects but leaves us breathing space for any future projects that are created in other languages.)

**Comment by goplayoutside3** [comment]
When I’m currently viewing a PFE page, such as Talk or Collections, the links to /classify or /about or the home page are correctly converted to the FEM syntax for /projects/locale/owner/project 👍 One question:
 
- If I’m viewing a PFE page such as [https://pr-6146.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/recents?env=production&language=es](https://pr-6146.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/recents?env=production&language=es) and then I navigate to one of TESS’s FEM pages, and then use the browser’s back button, the query params `env` and `language` are not saved in the url - is that expected?

**Comment by eatyourgreens** [comment]
That’s weird. The query parameters are preserved for me, when I use the Back button (or swipe back one page) in mobile Safari.

**Comment by goplayoutside3** [comment]
I think I see what's happening. Initially I thought it had to do with any PFE page, but instead what I've found is:
- Go to Spanish TESS Talk board: https://pr-6146.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk?env=production&language=es
- Click on a tag such as "transit": https://pr-6146.pfe-preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/tag and neither of the query params are preserved.
- The FEM links such as /classify and /about are still okay since their href's are correctly formed in the Project Header nav, but now when I try to go "back" to the above bullet's url, there's no `env=production`
 
This behavior is only troublesome on staging and shouldn't affect the live site - is that the correct assumption?

**Comment by eatyourgreens** [comment]
Yeah, that’s a long-standing problem with the PFE code. You can reproduce by clicking around links on staging here. 
https://master.pfe-preview.zooniverse.org/?env=production

**Comment by eatyourgreens** [comment]
We could update PFE staging to use the production API. That might make it easier to test staging before deploying it.

**Comment by eatyourgreens** [comment]
I’ve opened #6152 so that we don’t need to add `?env=production` on staged branches.

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/front-end-monorepo/pull/3192 should fix the About link in the project navigation menu.

**Comment by goplayoutside3** [comment]
Okay this is looking good then. However, before it's merged and deployed with PFE, I think FEM needs to have all Zooniverse-supported locales registered in next.config.js and their blank dictionary files.

Once this PR is merged, FEM projects with translations still have a language toggle on their Talk, Collections, and Recents pages. So as more projects are migrated to FEM, someone could go to a project's talk board, change the language to something not registered yet in FEM, click /about and the app will 404.

**Comment by eatyourgreens** [comment]
Outside of PH-TESS, are there any translated FEM projects? I don't think any transcription projects are translated, and none of the Engaging Crowds projects are translated.

**Comment by eatyourgreens** [comment]
I've added this link to the test URLs at the top of the PR. It tests localisation without query parameters (locale in the URL.)
https://pr-6146.pfe-preview.zooniverse.org/projects/es/nora-dot-eisner/planet-hunters-tess/talk

**Comment by goplayoutside3** [comment]
Coming back to document that this PR can be merged and deployed once FEM's [3469](https://github.com/zooniverse/front-end-monorepo/pull/3469) is deployed.

**Review by goplayoutside3 — APPROVED** [review]

**Pull request merged**
