### PR TITLE
WorldWide Telescope ES6 Rewrite

### PR DESCRIPTION
**Pull request by wgranger**
Describe your changes.
ES6 doesn't allow class variables, so I had to be a bit creative with this rewrite. I've been testing this against the education subject set of Astronomy Rewind, which can also be found on a test project in staging.

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

https://wwt-es6.pfe-preview.zooniverse.org/projects/wgranger-test/old-astro-test

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I might be misunderstanding your comment, but class variables are part of JavaScript so exist in ES6 too eg. `MyClass.x = 1` would set a static property on `MyClass`. Similarly, you can add class methods by defining functions on the class, instead of an instance `MyClass.doStuff = () => { return "Hello!";}`.

**Comment by wgranger** [comment]
Yes, that's what I wound up doing. However, I was unable to define a static variable from within a class (without using the constructor).

**Comment by eatyourgreens** [comment]
You could use `this.constructor.staticProperty = 1;` to add class properties and methods inside the class but I find that syntax harder to read.

**Comment by eatyourgreens** [comment]
Looks good to me, but could maybe do with a look from someone more familiar with the WWT component. I'm happy to merge this if it isn't breaking anything.

**Comment by wgranger** [comment]
I believe @amyrebecca might be the only other person with WWT knowledge. However, she may be on vacation.

**Comment by eatyourgreens** [comment]
Good point. I'll merge this.

**Pull request merged**
