### PR TITLE
Improve settings page, ImageSelector

### PR DESCRIPTION
**Pull request by brian-c**
This split email out the settings page.

ImageSelector components now know how to size themselves relative to their containers.

For #894:

- Added some guidance for image sizes

- Fixed rendering bug with no image selection

### CODE REVIEW

**Comment by chrissnyder** [comment]
:+1: :+1: :+1: for the settings organization.

I couldn't test the ImageSelector as it was squished it to a pixel or two high. Unless I'm missing something on how it's expected to be used.

**Comment by brian-c** [comment]
Oh boyyy, let me look. Sorry.

**Comment by brian-c** [comment]
Should be solid now.

**Comment by chrissnyder** [comment]
Worked like a charm.

Bit pedantic, but the file size limits don't mean too much because it will auto-shrink them for you (which is absolutely the desired behavior in my opinion).

Other than that, looks great.

**Pull request merged**
