### PR TITLE
Roll back markdownz version

### PR DESCRIPTION
**Pull request by brian-c**
Emergency rollback for #1734.

### CODE REVIEW

**Comment by brian-c** [comment]
@aweiksnar @edpaget Any ideas?

**Comment by chrissnyder** [comment]
Installing the dependencies for markdownz fails in node >= 4.0.0. Don't know what version the CI server is running on. Possible problem there? The deploy output didn't have any errors though.

**Comment by edpaget** [comment]
This should be fixed now. I'm going to propose a revert.

**Comment by chrissnyder** [comment]
Fresh npm install also gets the follwing error:

```
Error: Cannot find module './components/markdown-editor' from '/Users/bumishness/Documents/Zooniverse/Panoptes-Front-End/node_modules/markdownz/src'
    at /Users/bumishness/Documents/Zooniverse/Panoptes-Front-End/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/bumishness/Documents/Zooniverse/Panoptes-Front-End/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/bumishness/Documents/Zooniverse/Panoptes-Front-End/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/bumishness/Documents/Zooniverse/Panoptes-Front-End/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
public/vendor.js: 0 bytes
```

**Comment by edpaget** [comment]
Can you try again? That looks like the other error. What version do you have?

**Comment by chrissnyder** [comment]
Yep, was fixed with 3.0.3.

**Pull request merged**
