### PR TITLE
refactor project urls sub-nav icon

### PR DESCRIPTION
**Pull request by mcbouslog**
Staging branch URL: https://project-urls-icon.pfe-preview.zooniverse.org/
Staged project with external and social project urls/links: https://project-urls-icon.pfe-preview.zooniverse.org/projects/markb-panoptes/nfnorgtest-moths

Per design discussion with @beckyrother - in project's sub-nav:
- adds external-link fa-icon to external project url links
- makes external-link fa-icon default icon for social project url links if link's icon is not in [SOCIAL_ICONS](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/lib/social-icons.js)

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [x] Can you post a talk comment?

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by mcbouslog** [comment]
Update per Slack convo - I'm going to refactor this from `renderExternalLinks` and `renderSocialLinks` to use components instead

**Comment by eatyourgreens** [comment]
Looks good to me. When did you want this to appear on the live site, @beckyrother @mcbouslog?

**Comment by mcbouslog** [comment]
I think it's good to go, but defer to @beckyrother. Becky for ref this is actually what was previously included in #4110, but I made into it's own PR.

**Comment by beckyrother** [comment]
Looks great! Good to go on my end, thanks for checking!

**Pull request merged**
