### PR TITLE
Add Jenkinsfile to automatically stage branches

### PR DESCRIPTION
**Pull request by eatyourgreens**
Adds a Jenkinsfile to stage branches at {BRANCH_NAME}.pfe-preview.zooniverse.org.

NB. `BRANCH_NAME` will be something like `PR-4753` for a PR branch.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This is completely broken. I don't think you can stage with `npm run stage` any more. 😞

**Comment by eatyourgreens** [comment]
I've rebased this to update to the new Dockerfile.

**Comment by eatyourgreens** [comment]
I'm not sure if the new Docker image has bash, so that might fail now.

**Comment by eatyourgreens** [comment]
Jenkins is dying with a different error now. `95% emitting 95% emitting CopyPlugin 95% emitting HtmlWebpackPluginError: EACCES: permission denied, mkdir '/src/dist'`.

**Comment by eatyourgreens** [comment]
This is still giving a permissions error when it tries to write the HTML/CSS/JS files: `EACCES: permission denied, mkdir '/src/dist'`

**Comment by eatyourgreens** [comment]
After chatting to @rogerhutchings about this, he reckons Docker is creating `/src` as root, but Jenkins runs webpack as the node user. Changing the user to `node` in the docker build might fix it.

**Comment by camallen** [comment]
Jenkins is launching that docker image as the underlying jenkins user to gain access to the workspace context:
```
$ docker run -t -d -u 1000:1000 -w "/var/jenkins_home/jobs/Zooniverse GitHub/jobs/Panoptes-Front-End/branches/PR-4753/workspace" --volumes-from ee78bd3ad5932a2e8a901dd9f881240ae381976f9369c97e41e67eb4e5fb8d5f zooniverse/panoptes-front-end:PR-4753
```

Looks like this won't be fixed, https://issues.jenkins-ci.org/browse/JENKINS-38438

latest commit to this branch should fix this.

**Comment by eatyourgreens** [comment]
> Staged at https://PR-4753.pfe-preview.zooniverse.org/
🎉

**Comment by eatyourgreens** [comment]
Might need to lowercase the branch name though.

**Comment by eatyourgreens** [comment]
Working now! https://pr-4753.pfe-preview.zooniverse.org/

**Comment by eatyourgreens** [comment]
@camallen I'm going to rebase this and squash, now that it's working.

**Pull request merged**
