### PR TITLE
Use s3-batch-upload for deploys

### PR DESCRIPTION
**Pull request by eatyourgreens**
Remove publisssh and use s3-batch-upload to copy files to zooniverse-static.
Update the Cache-Control headers for better caching of static files:
- 60s for `index.html`.
- 1 week for all other files (JS, CSS, images etc.)

Staging branch URL: https://pr-5840.pfe-preview.zooniverse.org

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by srallen** [comment]
Could we check in with the migration status?  If we're close to moving static assets over to Azure, then it make sense to switch this to an Azure CLI at that time than an updated S3 one.

**Comment by eatyourgreens** [comment]
[s3-batch-upload](https://github.com/mediamonks/s3-batch-upload) has a `--dry-run` option, which might be useful for testing this without actually overwriting the live site.

**Comment by eatyourgreens** [comment]
@srallen the last conversation I had with Adam, we talked about making sure that the static sites all had Docker builds and Jenkinsfiles. I think we're on S3 for the near future but, yeah, it's worth thinking about how we'll copy files to Azure.

`publisssh` is very much out-of-date, so I'd consider upgrading at the same time as adding Jenkins builds to the static repos. I've just finished doing that for Pandora.

**Comment by srallen** [comment]
Ok, we should check in with the ops team. Presumably that information is at least several weeks out of date. @zwolf can you provide us an update with the migration of static assets to Azure?

**Comment by eatyourgreens** [comment]
Here’s the ops issue for switching over. It’s open for discussion at the moment. https://github.com/zooniverse/operations/issues/494

**Comment by eatyourgreens** [comment]
I’ve posted a couple of useful links, over on that issue, for Azure Storage node clients.

**Review by srallen — COMMENTED** [review]
Based on the update @nciemniak and @zwolf gave at this morning's stand up, it sounds like the migration of the subject static assets is getting close to completion. One of the next to do items include migration of static sites, so it'll be coming up. That being said, not close enough to hold this up I don't think. Could you try the dry-run option and share the output? I think it'd be useful in review. Thanks!

**Comment by eatyourgreens** [comment]
lab.zooniverse.org is deploying automatically with s3-batch-upload (https://github.com/zooniverse/pfe-lab/pull/214) and translations.zooniverse.org too (https://github.com/zooniverse/pandora/pull/166.) This branch deployed to https://pr-5840.pfe-preview.zooniverse.org without problems, so I think we are good to go.

**Comment by eatyourgreens** [comment]
Let me double-check the deployed commit, because this is what I'm seeing on in the HTML on the staging branch.
```html
<!--Last build: Fri Nov 13 2020 11:22:16 GMT+0000 (Coordinated Universal Time)-->
<!--Deployed commit: 1d59a980-->
<!--Build env: staging-->
```

**Comment by eatyourgreens** [comment]
A production deploy with the `--dry-run` flag runs without errors.
```
asosxlap127:Panoptes-Front-End odonnell$ npm run deploy

> panoptes-front-end@ deploy /Users/odonnell/zooniverse/Panoptes-Front-End
> export NODE_ENV=production; npm run _deploy


> panoptes-front-end@ _deploy /Users/odonnell/zooniverse/Panoptes-Front-End
> export PATH_ROOT=www.zooniverse.org; npm run _build && npm run _publish


> panoptes-front-end@ _build /Users/odonnell/zooniverse/Panoptes-Front-End
> export HEAD_COMMIT=$(git rev-parse --short HEAD); check-engines && check-dependencies && rimraf dist; webpack --config ./webpack.build.js --progress --profile --colors

49758ms building                                                                    
16ms finish module graph                            
12ms sealing                               
0ms basic dependencies optimization 
22ms dependencies optimization                          
0ms advanced dependencies optimization 
0ms after dependencies optimization 
22ms chunk graph
1ms after chunk graph                          
1ms optimizing 
0ms basic module optimization 
0ms module optimization 
0ms advanced module optimization 
0ms after module optimization 
1ms basic chunk optimization                             
0ms chunk optimization 
37ms advanced chunk optimization                        
0ms after chunk optimization 
0ms module and chunk tree optimization 
0ms after module and chunk tree optimization 
0ms basic chunk modules optimization 
53ms chunk modules optimization                          
1ms advanced chunk modules optimization 
0ms after chunk modules optimization 
7ms module reviving                 
13ms module order optimization                               
1ms advanced module order optimization 
0ms before module ids 
0ms module ids 
7ms module id optimization 
1ms chunk reviving                 
0ms chunk order optimization                               
0ms before chunk ids 
3ms chunk id optimization                          
6ms after chunk id optimization 
3ms record modules                 
0ms record chunks                 
46ms hashing
11ms content hashing                        
0ms after hashing 
0ms record hash 
1ms module assets processing 
264ms chunk assets processing
7ms additional chunk assets processing 
0ms recording 
1ms additional asset processing 
23234ms chunk asset optimization          
0ms after chunk asset optimization 
0ms asset optimization 
0ms after asset optimization 
1ms after seal 
873ms emitting                 
13ms after emitting                 
Hash: dcda24474baf98338525
Version: webpack 4.29.6
Time: 74449ms
Built at: 16/11/2020 17:59:55
                                                                     Asset       Size  Chunks                    Chunk Names
                                                     assets/about-hero.png    362 KiB          [emitted]  [big]  
                                              assets/all-projects-hero.png    171 KiB          [emitted]         
                                                assets/builder-landing.jpg    297 KiB          [emitted]  [big]  
                                         assets/default-project-avatar.png  949 bytes          [emitted]         
                                     assets/default-project-background.jpg    107 KiB          [emitted]         
                       assets/dev-classifier/1715_labs/building_plans.jpeg   96.7 KiB          [emitted]         
            assets/dev-classifier/1715_labs/greenwich_satellite_image.jpeg    295 KiB          [emitted]  [big]  
                   assets/dev-classifier/1715_labs/london_street_view.jpeg    301 KiB          [emitted]  [big]  
                                        assets/dev-classifier/algernon.txt  942 bytes          [emitted]         
                                      assets/dev-classifier/landscape.jpeg   66.3 KiB          [emitted]         
                                       assets/dev-classifier/portrait.jpeg   79.8 KiB          [emitted]         
                                          assets/dev-classifier/small.jpeg     28 KiB          [emitted]         
                                       assets/dev-classifier/testData.json   4.34 KiB          [emitted]         
                                      assets/dev-classifier/testData0.json   4.34 KiB          [emitted]         
                                      assets/dev-classifier/very-tall.jpeg    189 KiB          [emitted]         
                                      assets/dev-classifier/very-wide.jpeg    218 KiB          [emitted]         
                                                  assets/donate-button.png   21.3 KiB          [emitted]         
                                         assets/featured-projects/1104.jpg   72.7 KiB          [emitted]         
                                           assets/featured-projects/21.jpg   59.5 KiB          [emitted]         
                                         assets/featured-projects/3063.jpg   72.1 KiB          [emitted]         
                                         assets/featured-projects/3098.jpg   98.9 KiB          [emitted]         
                                          assets/featured-projects/376.jpg   46.6 KiB          [emitted]         
                                         assets/featured-projects/4973.jpg   56.4 KiB          [emitted]         
                                           assets/featured-projects/60.jpg     83 KiB          [emitted]         
                                         assets/featured-projects/6263.jpg     26 KiB          [emitted]         
    assets/featured-projects/featured-project-20170328-stargazing-live.jpg    278 KiB          [emitted]  [big]  
    assets/featured-projects/featured-project-20170403-stargazing-live.jpg    420 KiB          [emitted]  [big]  
   assets/featured-projects/featured-project-20170531-galaxy-nurseries.jpg   89.1 KiB          [emitted]         
          assets/featured-projects/featured-project-20170711-milky-way.jpg   86.6 KiB          [emitted]         
            assets/featured-projects/featured-project-20170801-steller.jpg    238 KiB          [emitted]         
assets/featured-projects/featured-project-20170829-steelpan_vibrations.jpg   50.3 KiB          [emitted]         
               assets/featured-projects/featured-project-20170913-irma.jpg   27.8 KiB          [emitted]         
        assets/featured-projects/featured-project-20171023-autumnwatch.jpg     74 KiB          [emitted]         
 assets/featured-projects/featured-project-20171204-fossil_atmospheres.jpg   63.8 KiB          [emitted]         
    assets/featured-projects/featured-project-20180108-project_plumage.jpg    176 KiB          [emitted]         
       assets/featured-projects/featured-project-20180223-scotus-notes.jpg   50.7 KiB          [emitted]         
                                               assets/feedback-details.png   26.8 KiB          [emitted]         
                                               assets/feedback-summary.png    100 KiB          [emitted]         
                                                assets/feedback-toggle.png   49.6 KiB          [emitted]         
                                           assets/highlights-book-2019.png    128 KiB          [emitted]         
                                           assets/highlights-book-2020.jpg   1.32 MiB          [emitted]  [big]  
                                                  assets/home-appStore.png   13.7 KiB          [emitted]         
                                               assets/home-collaborate.gif    351 KiB          [emitted]  [big]  
                                                  assets/home-computer.png    780 KiB          [emitted]  [big]  
                                                assets/home-contribute.gif    558 KiB          [emitted]  [big]  
                                                  assets/home-discover.gif   67.1 KiB          [emitted]         
                                                   assets/home-explore.gif    217 KiB          [emitted]         
                                                assets/home-googlePlay.png   17.5 KiB          [emitted]         
                                              assets/home-researchers1.jpg    612 KiB          [emitted]  [big]  
                                              assets/home-researchers2.jpg    660 KiB          [emitted]  [big]  
                                              assets/home-researchers3.jpg    563 KiB          [emitted]  [big]  
                                                     assets/home-video.jpg   87.8 KiB          [emitted]         
                                                     assets/home-video.mp4   1.86 MiB          [emitted]  [big]  
                                                     assets/home-video.ogv   7.16 MiB          [emitted]  [big]  
                                                    assets/home-video.webm    5.2 MiB          [emitted]  [big]  
                                            assets/how-to-lab/how-to-1.jpg    107 KiB          [emitted]         
                                           assets/how-to-lab/how-to-10.jpg    186 KiB          [emitted]         
                                           assets/how-to-lab/how-to-11.jpg   26.3 KiB          [emitted]         
                                           assets/how-to-lab/how-to-12.jpg   85.5 KiB          [emitted]         
                                           assets/how-to-lab/how-to-13.jpg    121 KiB          [emitted]         
                                            assets/how-to-lab/how-to-2.jpg   74.6 KiB          [emitted]         
                                            assets/how-to-lab/how-to-3.jpg    154 KiB          [emitted]         
                                            assets/how-to-lab/how-to-4.jpg    167 KiB          [emitted]         
                                            assets/how-to-lab/how-to-5.jpg    135 KiB          [emitted]         
                                            assets/how-to-lab/how-to-6.jpg    173 KiB          [emitted]         
                                            assets/how-to-lab/how-to-7.jpg    202 KiB          [emitted]         
                                            assets/how-to-lab/how-to-8.jpg    127 KiB          [emitted]         
                                            assets/how-to-lab/how-to-9.jpg    191 KiB          [emitted]         
                                                  assets/mobile-sample.png   43.1 KiB          [emitted]         
                                                  assets/simple-avatar.jpg   5.69 KiB          [emitted]         
                                                  assets/simple-avatar.png   11.7 KiB          [emitted]         
                                                 assets/simple-pattern.jpg   7.47 KiB          [emitted]         
                                                 assets/simple-pattern.png   3.59 KiB          [emitted]         
                                                      assets/team/adam.jpg   2.23 KiB          [emitted]         
                                                      assets/team/alex.jpg   11.4 KiB          [emitted]         
                                               assets/team/alex_bowyer.jpg   2.01 KiB          [emitted]         
                                                       assets/team/ali.jpg   3.01 KiB          [emitted]         
                                                      assets/team/amit.jpg   1.61 KiB          [emitted]         
                                                       assets/team/amy.png   8.96 KiB          [emitted]         
                                                    assets/team/andrea.jpg   24.8 KiB          [emitted]         
                                                     assets/team/arfon.jpg   6.78 KiB          [emitted]         
                                                     assets/team/becky.jpg   6.49 KiB          [emitted]         
                                               assets/team/beckyrother.jpg     89 KiB          [emitted]         
                                                  assets/team/beverley.jpg   21.1 KiB          [emitted]         
                                                     assets/team/brian.jpg   9.07 KiB          [emitted]         
                                                    assets/team/brooke.jpg   7.08 KiB          [emitted]         
                                                       assets/team/cam.jpg    6.1 KiB          [emitted]         
                                                   assets/team/chris-d.jpg   20.7 KiB          [emitted]         
                                                   assets/team/chris-l.png   13.9 KiB          [emitted]         
                                                    assets/team/chriss.png     13 KiB          [emitted]         
                                                   assets/team/coleman.jpg   3.62 KiB          [emitted]         
                                                    assets/team/darren.jpg   35.3 KiB          [emitted]         
                                                        assets/team/ed.png   18.3 KiB          [emitted]         
                                                     assets/team/grant.jpg   4.96 KiB          [emitted]         
                                                      assets/team/greg.jpg    2.5 KiB          [emitted]         
                                                  assets/team/hannah_s.jpg   11.6 KiB          [emitted]         
                                                     assets/team/heath.png   17.6 KiB          [emitted]         
                                               assets/team/helenspiers.jpg   30.5 KiB          [emitted]         
                                                      assets/team/hugh.jpg   5.17 KiB          [emitted]         
                                                     assets/team/james.jpg   36.4 KiB          [emitted]         
                                                 assets/team/jen_gupta.jpg   7.21 KiB          [emitted]         
                                                       assets/team/jim.jpg   6.31 KiB          [emitted]         
                                                    assets/team/jordan.jpg   21.3 KiB          [emitted]         
                                                     assets/team/julie.png   15.5 KiB          [emitted]         
                                                     assets/team/karen.jpg   11.1 KiB          [emitted]         
                                                     assets/team/kelly.jpg   7.28 KiB          [emitted]         
                                                      assets/team/kyle.jpg   10.1 KiB          [emitted]         
                                                     assets/team/laura.jpg   13.9 KiB          [emitted]         
                                                   assets/team/laura_w.jpg   9.53 KiB          [emitted]         
                                                      assets/team/lucy.jpg   10.2 KiB          [emitted]         
                                                  assets/team/mariam_s.jpg    2.8 KiB          [emitted]         
                                                      assets/team/mark.jpg   20.2 KiB          [emitted]         
                                                    assets/team/marten.jpg   5.13 KiB          [emitted]         
                                                       assets/team/meg.jpg   20.9 KiB          [emitted]         
                                                   assets/team/melanie.jpg   2.09 KiB          [emitted]         
                                                   assets/team/michael.png   3.26 KiB          [emitted]         
                                                      assets/team/noah.jpg   12.8 KiB          [emitted]         
                                                     assets/team/perry.jpg   10.3 KiB          [emitted]         
                                                       assets/team/rob.jpg   1.41 KiB          [emitted]         
                                                     assets/team/robin.jpg   12.4 KiB          [emitted]         
                                                     assets/team/roger.jpg   24.6 KiB          [emitted]         
                                                      assets/team/rona.jpg   7.63 KiB          [emitted]         
                                                       assets/team/sam.jpg   91.5 KiB          [emitted]         
                                                    assets/team/samuel.jpg   81.5 KiB          [emitted]         
                                                    assets/team/sandor.jpg   1.18 KiB          [emitted]         
                                                     assets/team/sarah.jpg   13.3 KiB          [emitted]         
                                                    assets/team/sascha.png   17.3 KiB          [emitted]         
                                             assets/team/shaunanoordin.jpg     52 KiB          [emitted]         
                                                    assets/team/simone.jpg     17 KiB          [emitted]         
                                                     assets/team/steve.png   16.1 KiB          [emitted]         
                                                    assets/team/stuart.png   14.5 KiB          [emitted]         
                                        assets/team/team-member-avatar.jpg   5.37 KiB          [emitted]         
                                                  assets/team/veronica.jpg   19.8 KiB          [emitted]         
                                                  assets/team/victoria.JPG   6.96 KiB          [emitted]         
                                                      assets/team/will.jpg   31.1 KiB          [emitted]         
                                                      assets/team/zach.JPG   9.02 KiB          [emitted]         
                                            assets/user-header-default.jpg    149 KiB          [emitted]         
                                                   assets/zoohome-hero.jpg   63.7 KiB          [emitted]         
                                                               favicon.ico    5.3 KiB          [emitted]         
                                                                index.html   3.98 KiB          [emitted]         
                                             main-9cda41f726b4accd5caa.css    288 KiB       0  [emitted]  [big]  main
                                              main-d73f7f3f159ca9c10627.js   3.44 MiB       0  [emitted]  [big]  main
                                           vendor-8786d83f76a19bbbc727.css   25.5 KiB       1  [emitted]         vendor
                                            vendor-f74b8e1c4a8f959319d2.js   1.99 MiB       1  [emitted]  [big]  vendor
Entrypoint main [big] = vendor-8786d83f76a19bbbc727.css vendor-f74b8e1c4a8f959319d2.js main-9cda41f726b4accd5caa.css main-d73f7f3f159ca9c10627.js
   [6] ./node_modules/react-router/es/index.js + 32 modules 76.4 KiB {1} [built]
       |    33 modules
  [18] ./node_modules/react-redux/es/index.js + 19 modules 37 KiB {1} [built]
       |    20 modules
  [64] ./app/redux/ducks/classify.js 22.3 KiB {0} [built]
       [810] 2ms -> [811] 6022ms -> [174] 17064ms -> factory:4790ms building:0ms dependencies:33729ms = 61607ms
 [113] ./app/pages/collections/favorites-list.cjsx 473 bytes {0} [built]
       [810] 2ms -> [811] 6022ms -> [1163] 17064ms -> factory:39105ms building:601ms dependencies:35094ms = 97888ms
 [114] ./app/pages/collections/collections-list.cjsx 484 bytes {0} [built]
       [810] 2ms -> [811] 6022ms -> [1163] 17064ms -> factory:39105ms building:601ms dependencies:35094ms = 97888ms
 [174] ./app/redux/ducks/interventions.js 3.88 KiB {0} [built]
       [810] 2ms -> [811] 6022ms -> factory:1618ms building:15446ms dependencies:38514ms = 61602ms
 [190] ./app/talk/recents.cjsx 7.46 KiB {0} [built]
       [810] 2ms -> [811] 6022ms -> [1163] 17064ms -> factory:39105ms building:601ms dependencies:35094ms = 97888ms
 [810] multi ./app/main.cjsx 28 bytes {0} [built]
       factory:1ms building:1ms = 2ms
 [811] ./app/main.cjsx 3.44 KiB {0} [built]
       [810] 2ms -> factory:66ms building:5956ms = 6024ms
 [820] ./app/locales/index.js 834 bytes {0} [built]
       [810] 2ms -> [811] 6022ms -> factory:1618ms building:15446ms dependencies:38514ms = 61602ms
 [849] ./app/redux/store.js 1.15 KiB {0} [built]
       [810] 2ms -> [811] 6022ms -> factory:1618ms building:15446ms dependencies:38514ms = 61602ms
[1163] ./app/router.cjsx 24.2 KiB {0} [built]
       [810] 2ms -> [811] 6022ms -> factory:1618ms building:15446ms dependencies:38514ms = 61602ms
[1787] ./css/main.styl 39 bytes {0} [built]
       [810] 2ms -> [811] 6022ms -> factory:1618ms building:15446ms dependencies:38514ms = 61602ms
[1788] ./app/lib/log-deployed-commit.coffee 2.93 KiB {0} [built]
       [810] 2ms -> [811] 6022ms -> factory:1618ms building:15446ms dependencies:38514ms = 61602ms
[1789] ./app/lib/split-config.js 867 bytes {0} [built]
       [810] 2ms -> [811] 6022ms -> factory:1618ms building:15446ms dependencies:38514ms = 61602ms
    + 1781 hidden modules

WARNING in EnvironmentPlugin - PANOPTES_API_APPLICATION environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in EnvironmentPlugin - PANOPTES_API_HOST environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in EnvironmentPlugin - STAT_HOST environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in EnvironmentPlugin - SUGAR_HOST environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in EnvironmentPlugin - TALK_HOST environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  main-9cda41f726b4accd5caa.css (288 KiB)
  main-d73f7f3f159ca9c10627.js (3.44 MiB)
  vendor-f74b8e1c4a8f959319d2.js (1.99 MiB)
  assets/about-hero.png (362 KiB)
  assets/dev-classifier/1715_labs/greenwich_satellite_image.jpeg (295 KiB)
  assets/dev-classifier/1715_labs/london_street_view.jpeg (301 KiB)
  assets/featured-projects/featured-project-20170403-stargazing-live.jpg (420 KiB)
  assets/featured-projects/featured-project-20170328-stargazing-live.jpg (278 KiB)
  assets/home-collaborate.gif (351 KiB)
  assets/home-contribute.gif (558 KiB)
  assets/builder-landing.jpg (297 KiB)
  assets/home-researchers3.jpg (563 KiB)
  assets/home-computer.png (780 KiB)
  assets/home-researchers2.jpg (660 KiB)
  assets/home-researchers1.jpg (612 KiB)
  assets/highlights-book-2020.jpg (1.32 MiB)
  assets/home-video.mp4 (1.86 MiB)
  assets/home-video.webm (5.2 MiB)
  assets/home-video.ogv (7.16 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (5.74 MiB)
      vendor-8786d83f76a19bbbc727.css
      vendor-f74b8e1c4a8f959319d2.js
      main-9cda41f726b4accd5caa.css
      main-d73f7f3f159ca9c10627.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./views/index.ejs 4.12 KiB {0} [built]
        factory:38ms building:29ms = 67ms
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
        [0] 67ms -> [1] 588ms -> factory:5393ms building:18ms = 6066ms
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        [0] 67ms -> [1] 588ms -> factory:5393ms building:18ms = 6066ms
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/stylus-loader/index.js!css/main.styl:
    Entrypoint mini-css-extract-plugin = *
    [1] ./node_modules/css-loader/dist/cjs.js!./node_modules/stylus-loader!./css/main.styl 300 KiB {0} [built]
        factory:2ms building:14546ms = 14548ms
        + 5 hidden modules

> panoptes-front-end@ _publish /Users/odonnell/zooniverse/Panoptes-Front-End
> s3-batch-upload --dry-run -b zooniverse-static -p ./dist -C 200 -acl 'public-read' -r "$PATH_ROOT/$SUBDIR"

✔ Found 144 files at ./dist, starting upload:
[====================] 100% | 0.0s | 144 / 144 | 2667/fps 
Upload complete!
asosxlap127:Panoptes-Front-End odonnell$ 
```

Checking `dist/index.html`, the webpack build is injecting the correct commit hash.
```html
<!--Last build: Mon Nov 16 2020 17:59:54 GMT+0000 (Greenwich Mean Time)-->
<!--Deployed commit: 397c7ef4-->
<!--Build env: production-->
```

I'm a little puzzled as to why the staging branch for this PR has the wrong commit hash in the HTML, but the production build looks good.

**Comment by eatyourgreens** [comment]
To double check, I viewed the source of https://pr-5834.pfe-preview.zooniverse.org/ and the deployed commit info on that branch is wrong too. I don't think this PR has broken the deployed commit comments. Here's the code from #5834. 
```html
<!--Last build: Fri Nov 13 2020 11:22:09 GMT+0000 (Coordinated Universal Time)-->
<!--Deployed commit: df7e3cb2-->
<!--Build env: staging-->
```

**Comment by eatyourgreens** [comment]
publisssh adds Cache-Control headers to uploads, so I've added those here too.
https://github.com/zooniverse/publisssh/blob/af6e2f9cc45fe24fa78bd8fd47f173393d9160bf/lib/publish.iced#L245-L248

**Comment by eatyourgreens** [comment]
Those cache-control headers that `publisssh` sets might not be correct. We don't really want `no-cache` on `index.html` and there should be no whitespace in `max-age=86400` for the JS, CSS and images.

Now that the uploader config includes JSON, it might be more convenient to move the config into its own script. See https://github.com/zooniverse/pandora/pull/169

**Comment by eatyourgreens** [comment]
I've moved the uploader config into its own script, and updated the Cache-Control headers to match zooniverse/pandora#169.

**Comment by eatyourgreens** [comment]
I've added the `bug` label because this now fixing the Cache-Control headers on https://www.zooniverse.org.

**Comment by eatyourgreens** [comment]
`highlight.js` is one of the outdated dependencies that's removed here, so this will also close #5849.

**Review by shaunanoordin — APPROVED** [review]
## PR Review

This PR changes the upload script (relevant to `npm run deploy`, `npm run stage`). The new `s3-batch-upload` dependency punts the obsolete `publisssh` to the retirement bin.

Changes are LGTM:

- dry run (add `dryRun: true` to config in upload.js) works with no issues
- I wanted to run `npm run stage` to confirm manual deployment works from a local machine, but this may be testing overkill.
  - Automated deploy works as far as I can tell: https://s3-upload.pfe-preview.zooniverse.org
- code change follows pattern used in Zoo-Note (see https://github.com/zooniverse/zoo-notes/pull/23) and that's proven to work fine.

### Status

LGTM 👍 I'm happy to see this merged. I understand concerns that we'll eventually need to move to an Azure deployment tool, but at the moment we're still using S3 and this PR works as a fine bridge until we're fully Azure-ified.

**Pull request merged**
