### PR TITLE
Redo highlights page for 2020

### LINKED ISSUE #5839: Update Highlights Page
Update Zooniverse Highlights Book About page with new content to accompany release of 2020 edition.

Copy is available in [this Google Doc](https://docs.google.com/document/d/1QWEOPKHIcNGtxmPpgWgx7bPcMo--uOlcMBAlM9ecdoY/edit).

Edits required in https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/about/highlights.jsx and https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/locales/en.js required.

Bonus challenge: remove any now-out-of-date content from other locale files (fine to default only to the `en` content for other languages).

### PR DESCRIPTION
**Pull request by srallen**
Staging branch URL: https://pr-5842.pfe-preview.zooniverse.org

Fixes #5839 

Implements the new highlights page. Preview at https://pr-5842.pfe-preview.zooniverse.org/about/highlights

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Review by lcjohnso — APPROVED** [review]
Approved!  But two optional comments: 
1.  Download URLs (reposted from Slack): I'd recommend updating the download link to the raw Github URL to skip seeing the Github web interface (might be confusing).  Becky encoded these with bit.ly URLs -- not sure whether these can be changed, or whether Sarah should just put the full URL into the code (I think this is fine since it is it linked text / never shown raw anyway). Recommended raw URLs:
https://github.com/zooniverse/Brand/raw/master/style%20guide/downloads/Printables/Zooniverse-book-2020.pdf
https://github.com/zooniverse/Brand/raw/master/style%20guide/downloads/Printables/Zooniverse-book-2019.pdf

2. For locale files: Thanks for going through to add updated data.  In practice, the non-`en` files tend to get out of sync, and if the content added is only in English (as it is here), one could simply remove the highlights block all together from non-`en` files (so content defaults back to `en`).  For new translations, I base all input on `en.js` to avoid missing any recent changes for this reason.  But again, totally fine to leave as-is after all your effort!

**Comment by srallen** [comment]
@lcjohnso The URLs are updated and I did a find and replace in VSCode once I had the new structure in place for the locale file, so not too much effort. I'll plan on merging first thing on Monday.

**Comment by srallen** [comment]
Ok, reverted the URL change since they're needed for analytics.

**Comment by beckyrother** [comment]
Sorry, the URL needs to be bitly for tracking. Please use:
https://bit.ly/zoonibook20-download
https://bit.ly/zoonibook19-download

Here's a cover jpg to use (it looks weird to have the 19 one flat the the 20 one like a book mockup) 
Into the Zooniverse cover final

**Comment by beckyrother** [comment]
Ack sorry to have the same conversation in two places!

**Review by beckyrother — CHANGES_REQUESTED** [review]
See previous comments, sorry!

**Comment by srallen** [comment]
@beckyrother this is ready for review again

**Comment by beckyrother** [comment]
Sorry I keep looking at this and seeing things. `beckyrother--` Can you change 'To download a free electronic copy' to 'Download a pdf' for both links? 

@lcjohnso clicking on those links immediately starts a download, is that what you'd intended?

**Comment by lcjohnso** [comment]
> @lcjohnso clicking on those links immediately starts a download, is that what you'd intended?

Yes!  I think that's strongly preferable to dropping someone unexpectedly into GitHub.

No problem using the bit.ly link versions - glad Becky could change those appropriately.

I agree with Becky: I prefer 'Download a pdf' or 'Click to download the free PDF' over 'to download a free electronic copy'

**Comment by srallen** [comment]
@lcjohnso and @beckyrother I've updated the link text to "Download a pdf". Anything else or is this approved to merge?

**Comment by lcjohnso** [comment]
LGTM!

**Review by beckyrother — APPROVED** [review]
Looks great!!

**Pull request merged**
