### PR TITLE
unsubscribe all zoo emails via html form

### PR DESCRIPTION
**Pull request by camallen**
html form based email unsubscription for users that can't login. We may end up pulling this and just use the API GET with uniq token links but for now this will save some effort.

### CODE REVIEW

**Comment by chrissnyder** [comment]
Two questions:

- I'm only getting 404s when trying to unsubscribe. I'm assuming that's related to zooniverse/Panoptes#1068?
- Doesn't seem to matter if I'm logged in or not. The backend checks if I actually have permission to unsubscribe via email, right?

**Comment by camallen** [comment]
1. that post route isn't in the backend yet
2. It's for non-logged in users mostly but it doesn't really matter, backend will unsubscribe from all emails any known email address.

**Comment by chrissnyder** [comment]
Ok, was just checking that I couldn't put your email in and unsubscribe you if I was so inclined.

Code here looks fine, so merging in.

**Comment by camallen** [comment]
Ah - sorry, it actually will work that way. This is a replica of the old zoo home form till the per user unsubscribe links get into emails, etc.

**Comment by chrissnyder** [comment]
Just putting it on record that that seems dangerous, but if that exact functionality existed previously, then I guess it isn't any more harmful than before.

**Pull request merged**
