### PR TITLE
Store admin toggle state between refreshes

### PR DESCRIPTION
**Pull request by chrissnyder**
- Plops `params.admin` into localStorage for retrieving.
- Also makes the admin toggle a bit more noticeable, since it's easier to leave it on now.

### CODE REVIEW

**Comment by camallen** [comment]
Local testing when had the admin box checked, i then unchecked it and then reloaded the page via url hacking / reload button and it reset the state to be checked. Code looks good, not sure what's going on here.

**Comment by eatyourgreens** [comment]
maybe delete the local storage key if the box changes from checked to unchecked?

**Comment by chrissnyder** [comment]
Yea, not sure how it worked for me yesterday sufficiently to open the PR. Should be good now.

**Comment by camallen** [comment]
Nice work :+1:

**Pull request merged**
