### PR TITLE
Use referenced replies instead of quoted text

### LINKED ISSUE #1434: Make replies automatically link back to the original posts
As discussed in #888 and #1428 --

Replies (and replies of replies) should generate in the text box with an automatic link back to each original post.

### LINKED ISSUE #1435: Make cursor appear below reply in comment box
For flow purposes, so that to reply, you just hit reply and start typing, the cursor should appear in the box below the quoted text when you do a reply.

Currently:

screen shot 2015-08-18 at 6 55 05 pm

Ideally:

screen shot 2015-08-18 at 6 56 23 pm

### PR DESCRIPTION
**Pull request by aweiksnar**
- Provides link to reply author and comment
- Closes #1434
- Closes #1435 (not relevant anymore)
- Some examples on dev at `/talk/38/92`

### CODE REVIEW

**Comment by parrish** [comment]
Some issues so far.

- Clicking on reply reloads everything
- Clearing a reply doesn't seem to work, but does reload everything
- Clicking on the in-reply-to link doesn't scroll the page to the comment if it's on the same page
- Clicking on the in-reply-to link doesn't change pages to the page of the comment

I think it may be a bit of a challenge to follow a series of replies as well.

Any opinions on the pseudo-nested layout that talk 2.0 used?  IMO, It feels like a bit less of a click-maze that way.

**Comment by aweiksnar** [comment]
Ok cool let me take care of those refreshes, I believe their happening currently too. I'd be up for adding nesting, or maybe clicking the 'comment' link renders the chain of replies in an aside or modal

**Comment by aweiksnar** [comment]
@parrish I think I've got it in line with how we talked about today. Let me know if you have any more thoughts on how to improve

**Comment by parrish** [comment]
Looks like it's working well, except it's still not clearing replies.

To reproduce:

- Click reply
- Clear reply
- Submit comment

Comment is still a reply

**Comment by aweiksnar** [comment]
Ah I see I didn't realize that was happening after submit (I thought you just meant visually). I'll post a fix and comment again when it's up

**Comment by aweiksnar** [comment]
Cool, replies should be clearing correctly now

**Comment by parrish** [comment]
Did you add a commit somewhere else?

**Comment by parrish** [comment]
Nevermind, must've been a force push

**Comment by parrish** [comment]
:+1:

**Comment by aweiksnar** [comment]
Yeah just squashed it into feature commit

**Pull request merged**
