### PR TITLE
[Security] Refactor putFile and validate content

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Rewrite `putFile` to use `fetch` instead of XHR.
- Validate the Content-Type header of uploaded files.

`putFile` is now restricted to the following content types:
- `image/*`.
- `audio/*`.
- `video/*`.
- `text/plain`.
- `application/json`.
- `application/pdf`.

Staging branch URL: https://pr-6260.pfe-preview.zooniverse.org

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Review by shaunanoordin — CHANGES_REQUESTED** [review]
## PR Review

Affects: Project Builder, User Profile

This PR changes the `putFile()` function, which is used to move media files onto our storage servers.

- New behaviour: when uploading media files _to our storage_ via Project Builder or the User Profile, only the following types are allowed: image, audio, video, plain text, JSON, PDF.
  - Of course, if a feature has a stricter media whitelist, the strictest parameters are used. (e.g. a User Profile's Avatar only accepts image files, it won't accept a video)

Please see Testing for which file types we're looking at, and where these files are uploaded.

### Dev Notes

❗ The first thing I noted, however, is that **the imports for putFile is broken on every page that uses it,** because the new putFile code makes putFile the **default** export. For testing, I've made the fixes to local, with the assumption that those fixes will be made to the branch before this PR is merged. (See Status for CR list.)

Changes should be simple, e.g.

```
// In lab/actions/media.js...
const putFile = require('../../../lib/put-file');
// -- change to -->
const putFile = require('../../../lib/put-file').default;
// -- or --
import putFile from '../../../lib/put-file';
```

### Testing

Tested on localhost with macOS + Chrome, with a [random test project](https://local.zooniverse.org:3735/lab/1986) and a selection of files. See Slack for the [files used](https://zooniverse.slack.com/archives/C06LHUC6R/p1668537414186829?thread_ts=1668537365.690079&cid=C06LHUC6R)

For this review, I'm going through _every feature on PFE_ that uploads a media file to our storage server, and then attempting to _upload multiple types of files._

Below, I've listed the various **file types** I've tried to upload to various **features.** The symbol next to each feature indicates which file types were successfully uploaded ; .e.g I was able to successfully upload png, jpg, gif, & svg images to my user profile's avatar, but not mp4, mp3, txt, json, nor pdf. 

**File types tested:**
- 🖼 can upload .png, .jpg, .gif
- 📹 can upload .mp4, .mp3
- 🖊️ can upload .svg (but won't display properly)
- 📃 can upload .txt, .json
- 📘 can upload .pdf
- 🏁 🏴 🏳 see [Slack](https://zooniverse.slack.com/archives/C06LHUC6R/p1668537371862759?thread_ts=1668537365.690079&cid=C06LHUC6R)

**Features tested:**
- User Profile -> Settings -> Customize Profile (avatar & header) 🖼 🖊
- Project Builder -> Project page (avatar & background) 🖼 🖊
- Project Builder -> Media page 🖼 📹 📃
- Project Builder -> Field Guide page (icons) 🖼 🖊
- Project Builder -> Tutorial / Mini-Course (step image) 🖼 📹 🖊 📃 📘 🏴 🏳
  - Note 1: no 🏁 
  - Note 2: .mp4 renders OK, .mp3 doesn't render (no player), .svg renders OK
- Project Builder -> Subject Sets page -> upload Subjects 🖼 🖊 📃 🏴 🏳
  - ❓ 📹 can't upload .mp4, but can upload .mp3. (.mp4 isn't listed as a valid upload file type on the Subject Uploader. Not sure if this is expected.)
  - 📘 can't upload .pdf, but this is because the Subject-Uploader has its own file-type whitelist
  - Special: I can also upload 3 images with additional metadata with a manifest.csv

### Status

The change to `put-file.js` new code and new whitelist feature works as intended, but the `putFile` imports need to be fixed.

Changes Required (for PR writer):
- [x] need to fix `lab/project-details.jsx`'s import: `putFile = require('../../lib/put-file').default`
- [ ] need to fix `lab/actions/media.js`'s import: `const putFile = require('../../../lib/put-file').default;` or `import putFile from '../../../lib/put-file';`
- (minor) `lab/media-area/index.js` imports putFile, but doesn't use it
- [ ] need to fix `lab/field-guide/actions.js`'s putFile import.
- [ ] need to fix `partials/project-modal-editor.cjsx`'s putFile import
- [ ] need to fix `partials/subject-uploader.cjsx`'s putFile import

Other than that, I need to dig in a bit as to why I couldn't upload the .mp4 file as a Subject. This might not be a problem with the PR; I first need to compare this "issue" against `master` to check my baseline assumptions.

Further Checks Required (for Reviewer):
- Why can't I upload an .mp4 file via the Subject Uploader? Is this intentional? Where's the blocker? Investigation continues

**Comment by eatyourgreens** [comment]
I think video subject upload is still admin-only. Could be wrong.

**Comment by eatyourgreens** [comment]
I have no idea why `putFile` was still using CommonJS `module.exports` instead of ES `export`, but all the files that use it should be updated to ES `import` now.

**Comment by eatyourgreens** [comment]
Unlike Media uploads, I think Subject creation has additional checks in Panoptes, which can be overridden by the admin flag.

**Pull request merged**
