### PR TITLE
make the talk tagged subject view easier to use

### LINKED ISSUE #3173: Getting a bigger subimage of the subject on the Talk search results when you search a hashtag. Current size is too small.
It would help if the thumbnail was bigger like what you get for the Recent Comments to be able to quickly scan the subject and see if it has what you're looking for. I'm trying to find new targets locations from Talk before the seasonal campaign window ends and if I want to use the talk hashtag search I'd have to click on each subject to get a clearish picture.  There's 52 pages, so not something I'm going to do, but I would scroll through them if the thumbnail was bigger.

screen shot 2016-10-31 at 4 13 27 pm

Recent comments page:

screen shot 2016-10-31 at 4 16 32 pm

### PR DESCRIPTION
**Pull request by camallen**
Fixes #3173 @mschwamb i've increased the thumb size to 300px and put them into a grid view for easier perusal. Might not work well on mobile devices and I haven't tested css flow on changes but i tried to use new classes and not pollute existing ones.

Branch staged here for review / thoughts https://tagged_view_thumb.pfe-preview.zooniverse.org/

nicer url for seeing the changes, https://tagged_view_thumb.pfe-preview.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/spiders?env=production

Describe your changes.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Needs a rebase to resolve merge conflicts.

**Comment by parrish** [comment]
🏓 @camallen 

Happy to merge after a rebase

**Comment by mschwamb** [comment]
That looks great.

**Comment by eatyourgreens** [comment]
There was only one small conflict, so I had a go at fixing it with the new github editor.

**Comment by camallen** [comment]
@eatyourgreens thanks, this slipped of my radar.

**Pull request merged**
