### PR TITLE
Introduce an alumni page, and other team page updates.

### LINKED ISSUE #2578: Update team page
Related to #2575, we have lots of new people! Let's get the team page updated. @mcbouslog, @amyrebecca, @zwolf, @wgranger could you write up a short 2-3 sentence bio and pick out a nice photo for a mugshot? @mrniaboc do you know who else may be missing?

### PR DESCRIPTION
**Pull request by alexbfree**
Also fixes #2578.

- Restore all old deleted staff members that have previously had a profile into an alumni section.
- Alumni members do not show up under "show all".
- Modify styling to have a line above alumni section.
- Fix Lucy's Twitter logo being on next line.
- Add a California section for Brooke and Sascha
- Some profiles were on four lines which breaks the styling - made small word changes to fit them onto three lines.
- Modified all alumni profiles to past tense.
- This is written for the time when Veronica, Ali, Alex B and Chris D have all left (we are all in the process of leaving). If @aliburchard and @doogue haven't yet left at time you want to merge, please check OK with them. I'm OK with this being merged whenever. Veronica has already left.
- Added placeholders for Amy & Darryl (see #2578). And also Hugh.
- Add former members Stuart, Perry, Laura W, Arfon, Rob with placeholders and simple text.
- Introduce a zoo avatar as placeholder where image not on hand.
- Added Melanie bio
- Added detail for Rob and others from the OWD bios (Thanks @eatyourgreens for pointing those out).
- Added some detail from old ZooHome repo and some profile images found on S3 and online.

Needs @chrislintott and @trouille approval before merge.

Visible on staging at https://alumni-section.pfe-preview.zooniverse.org/about/team

### CODE REVIEW

**Comment by trouille** [comment]
@saschaishikawa Can we keep you in Chicago or should we find a 'California' solution for you and @vrooje ?

**Comment by trouille** [comment]
@amyrebecca Take a moment today (Thursday) to input your bio.

**Comment by trouille** [comment]
@amyrebecca Take a moment today (Thursday) to input your bio. Thanks!

**Comment by trouille** [comment]
Other than the two above, looks good from the Chicago and alum side. Nice work @alexbfree

**Comment by amyrebecca** [comment]
I'm fine making the change myself if you're too busy (just let me know, i've cleared up a bunch of nonsense notifications so I should actually be able to pick meaningful things out of the flood), but here's some text and a picture:

Amy has been a Zooniverse developer at the Adler since November 2015. She holds a BS and MS in software engineering and over a decade of industry experience. An aspiring astronomer as a child, she couldn't be happier to have landed here.
amy

**Comment by alexbfree** [comment]
OK no worries @amyrebecca I have added your photo and bio as part of this PR. Thanks for the update.

I've created a California section for Brooke and Sascha. I've also moved Kyle to alumni, and added a placeholder for Hugh.

**Comment by alexbfree** [comment]
Have updated https://alumni-section.pfe-preview.zooniverse.org/about/team if anyone wants to take a look.

**Comment by alexbfree** [comment]
Pending @chrislintott approval then, this is ready for merge.

**Comment by alexbfree** [comment]
Have pushed another update to https://alumni-section.pfe-preview.zooniverse.org/about/team

**Comment by alexbfree** [comment]
Did one more update to show counts next to each city/location/section

**Comment by trouille** [comment]
Need Amit Kapadia on the Alum page @alexbfree

**Comment by trouille** [comment]
Also, @alexbfree 

Need to add a line at the end of Arfon's: "Arfon served as Director of Citizen Science at the Adler Planetarium and co-lead of the Zooniverse until fall 2013."

Then we should update Laura Whyte's to: "Laura was the Director of Citizen Science at Adler Planetarium and co-lead of the Zooniverse from fall 2013 to summer 2015.

**Comment by trouille** [comment]
@alexbfree I would like to get permission from all the Chicago alum before having their info post publicly. I'll be sending emails this week, and will post updates here as people respond.

**Comment by alexbfree** [comment]
Thanks @trouille . What was Amit's role, and what would we say about what he did?
Will do those updates and await those approvals before we merge this.

**Comment by alexbfree** [comment]
I found amit's picture 
amit

**Comment by trouille** [comment]
Just a note - I've given till Sept 12th for Chicago alum to respond with permission, edits, etc.

**Comment by alexbfree** [comment]
OK Thanks @trouille . In the absence of a reply from past employees are you happy to assume it's ok we list them? Or do you prefer they only are listed if they specifically reply to say Yes? Out of interest any replies so far?

**Comment by alexbfree** [comment]
BTW just noting that Chris L has given his approval to me verbally when I was in Oxford last week - so once we have resolved the questions/outstanding tweaks above i will mark this PR as ready for merge.

**Comment by trouille** [comment]
On the Chicago alum side:

Alex W gave his thumbs up and says bio looks good as is. 

Chris Snyder also gave thumbs up and said he'll submit a PR for any updates he has. 

I'm waiting to hear from Ed, Heath, Darren, Stuart, and Laura W. If I don't hear back, I think better would be to not include them in the alum list, since they haven't given permission. I'm sure I'll eventually hear back and/or succeed in getting in touch with them. We can always add them in at that time, if they give permission. 

I wasn't able to find an email for Amit. If anyone has one, let me know. 

So, short answer is -- please don't merge until the September 12th deadline, at which time we'll look through the list and remove anyone who hasn't given permission.

**Comment by trouille** [comment]
Update from Heath:

Yes, with these edits:

Heath was the UI/UX Designer at the Zooniverse where he worked to craft
thoughtful and engaging user experiences. Apart from design Heath also enjoys illustration,
a good sci-fi or fantasy novel, and exploring his new home in the Pacific Northwest.

**Comment by trouille** [comment]
Once @wgranger and team have completed https://github.com/zooniverse/Panoptes-Front-End/pull/2979, then this will be his next go-to task on zooniverse.org

**Comment by trouille** [comment]
Update from Darren:

Yes, with the edit to change 'assists' to 'assisted'.

**Comment by trouille** [comment]
Update from Stuart:

Yes, with this updated/edited text:
Stuart arrived at the Adler as a developer in July 2011, having been one of the founding developers at Oxford. He studied mathematical physics at Edinburgh University and received his doctorate in astrophysics from Royal Observatory Edinburgh. Data analysis maestro and web developer.

**Comment by trouille** [comment]
Update from Laura Whyte -- yes, looks good. No edits needed.

**Pull request closed without merging**
