### PR TITLE
Get thumbs from first comment instead of latest

### PR DESCRIPTION
**Pull request by aweiksnar**
- This got changed at some point, Since the first comment is
  the one that sets the focus of the discussion this pulls the thumb
  from that
- #1338

### CODE REVIEW

**Comment by chrissnyder** [comment]
This was changed in the last commit on the file at https://github.com/zooniverse/Panoptes-Front-End/commit/467fd4aff98216e1985c5b37c43f1f6a2b225f6f. Without looking further, is there conflicting goals here?

**Comment by aweiksnar** [comment]
I think the desired behavior for thumbnails should be the image of the focus of the first comment instead of the last. The last commit changed it to generate thumbs from the latest comment, which I believe is causing the discussions not to always have thumbs if there are replies without foci

**Comment by chrissnyder** [comment]
Sounds reasonable to me. Pinging @parrish to make sure there wasn't a different consideration going on, but it looks good to merge to me.

**Comment by parrish** [comment]
When display discussion previews on the subject_default board, you'd probably want the focus that the discussion was started on.

Everywhere else -- search results, other boards, etc., etc. -- you'll want to show the focus from the last comment if it exists (you're showing a preview of the last comment in the discussion, right?)

**Comment by DarrenMcRoy** [comment]
No, we only want these thumbnails for the Notes board right now... which I assume is what you're calling the "subject_default" board, right?

**Comment by parrish** [comment]
Yep, "Notes" is what the subject default board is generally being called.

The thumbnail will show up everywhere the discussion preview is used

**Comment by aweiksnar** [comment]
It seems like the safest assumption to make is that a discussion's first comment focuses on a subject then that discussion is about it, for any board

**Comment by parrish** [comment]
My proposal is:

If a discussion is started with a comment about a focus, then the discussion should store that focus.

That gets us away from N+1 queries as well as just generally making sense I think

**Comment by aweiksnar** [comment]
@parrish I like that solution

**Comment by parrish** [comment]
Cool, ticketed in zooniverse/Talk-Api#59

**Comment by aweiksnar** [comment]
:ok_hand:

**Comment by parrish** [comment]
Blah, The code is ready to go, but dockerhub is broken after their upgrade.  I'll try to get this out tomorrow.

**Comment by aweiksnar** [comment]
Ok cool, I'm happy to leave this one open until it's ready and then I'll update

**Comment by aweiksnar** [comment]
Just updated to use the new discussion focus id/type columns

**Comment by parrish** [comment]
Looks good, but I don't think wet need this linked sorting anymore: https://github.com/zooniverse/Panoptes-Front-End/commit/fa601bbc32de148e7e9af252b04d8ee58f69fde0#diff-c56c806db68922bcecc89dda1372778bL46

**Comment by aweiksnar** [comment]
Oh yep just removed the sort param too

**Comment by parrish** [comment]
Awesome.  LGTM :+1:

**Comment by chrissnyder** [comment]
Cool, merging.

**Pull request merged**
