### PR TITLE
Workflow visualization updated to react 14

### PR DESCRIPTION
**Pull request by CKrawczyk**
@brian-c I just updated my visualization to react 14 and rebased it to the current master.  Everything should be good to go now.

### CODE REVIEW

**Comment by brian-c** [comment]
Still getting quite a few errors, and this doesn't seem to be working on my dev workflow: http://localhost:3735/lab/231/workflow/622/visualize (let me know your login if I need to make you a collaborator).

screen shot 2015-12-16 at 5 13 31 pm

**Comment by CKrawczyk** [comment]
Strange, I will look into it.  My zooniverse user name is cmk24.

**Comment by CKrawczyk** [comment]
OK, I have fixed up the first warning.  I can't seem to reproduce the other errors on my end, when you get a chance add me to that workflow and I will see what is going on with it.

screen shot 2015-12-17 at 12 59 06 pm

**Comment by CKrawczyk** [comment]
Fixed the code to handle survey, corp, and text tasks (and any task that only has one "next task" by default).

**Comment by CKrawczyk** [comment]
Survey images are now shown in the visualization
screen shot 2015-12-18 at 12 19 56 pm

**Comment by brian-c** [comment]
Lookin' good! Thanks.

**Pull request merged**
