### PR TITLE
Hide the new discussion link on subject default (notes) boards

### LINKED ISSUE #872: Remove "create discussion" from Notes board
It should not be possible to create a new discussion in the Notes board, because said board should be reserved entirely for subject threads. Having anything else able to go there would be confusing and counterproductive.

### PR DESCRIPTION
**Pull request by parrish**
Closes #872

### CODE REVIEW

**Comment by DarrenMcRoy** [comment]
Oh, thanks, dude! This is a really helpful tweak for keeping threads organized.

**Comment by chrissnyder** [comment]
That'll cause the "sign in" message to appear on the notes board if the user is actually signed in.

**Comment by parrish** [comment]
Oops, good catch.  Updated

**Comment by chrissnyder** [comment]
LGTM :shipit:

**Pull request merged**
