### PR TITLE
Store workflow task history in Classifier state.

### PR DESCRIPTION
**Pull request by eatyourgreens**
https://update-annotations.pfe-preview.zooniverse.org

Get the current task, and corresponding annotation, from classifier state.
Add handlers for task navigation changes, so that feedback can hook into the Next and Done buttons.

Continuation of #4440, slowly getting rid of all code which would block us from deprecating combo task annotations.

~@rogerhutchings this PR can also add hooks to fire off feedback checks when navigating backward and forward through a workflow, rather than checking for prop changes and assuming that those correspond to navigation buttons being pressed.~

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by rogerhutchings** [comment]
Okay, tracking the state through `i-fancy-cats`, everything works as expected, and the task key is correctly stored in the state. I did notice that the task ID doesn't change even when technically out of the workflow and on the classification summary, which might be a useful hook?

**Comment by eatyourgreens** [comment]
Good point. I need to split the `onNewTask` handler up into different handlers for Back, Next and Done. Feedback for the current task should be called on next task, before state is updated with the new task key.

Should feedback use promises, so that it interrupts UI changes until the OK button is clicked? I'm thinking it needs to interrupt new subjects loading, or Talk pages loading.

**Comment by eatyourgreens** [comment]
When those changes are made, I think this PR could close #3679, #4433 and #4434.

**Comment by eatyourgreens** [comment]
Feedback checks removed from `componentDidUpdate` and checked instead when you move forward through the workflow, but not back.

TODO: fix focus for the modal's ok button being stolen by the task's Next button.

**Comment by eatyourgreens** [comment]
I kind of hacked the summary step by calling `onNextTask` with no task key. 😕

**Comment by rogerhutchings** [comment]
The feedback modal is created using [ModalFormDialog.alert()](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/features/feedback/classifier/helpers/open-feedback-modal.jsx#L58), which returns a promise 💥

**Comment by eatyourgreens** [comment]
@rogerhutchings `ModalFormDialog` wraps everything in `<form>` so I’d recommend not using it, except for forms. See #4288.

**Comment by eatyourgreens** [comment]
This now blocks the Next and Done buttons while feedback is open. The Done & Talk link still needs some work, and the whole thing needs checking with summaries turned off.

**Comment by eatyourgreens** [comment]
Restaged to work with summaries turned off. Done & Talk still needs to be looked at, but then this should be done.

**Comment by eatyourgreens** [comment]
Now fixes #4433.

**Comment by eatyourgreens** [comment]
Fixes #4434 but hijacks the Done & Talk link, so cmd-click to open in a new tab no longer works.

**Comment by eatyourgreens** [comment]
Cmd-click should work now. Also fixed pushState not being used correctly.

Closes #3679.

**Pull request merged**
