### PR TITLE
Bump panoptes-client to 3.4.1

### PR DESCRIPTION
**Pull request by eatyourgreens**
Upgrade `panoptes-client` and remove the old `json-api-client5.0.0-rc.0`, which bumps `superagent` from v3.8.3 to v7.1.3.

This fixes an install warning about an outdated version of `superagent`.
>warning panoptes-client > json-api-client > superagent@3.8.3: Please upgrade to v7.0.2+ of superagent. We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing. See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.

Staging branch URL: https://pr-6141.pfe-preview.zooniverse.org

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Local testing in progress

**Comment by shaunanoordin** [comment]
Sorry Mark & Delilah, I'm taking this PR for review now!

( @goplayoutside3  for context: on the Front End Dev Slack call today, if a PR has multiple requested _pending_ reviewers, Mark & me thought we might _un-tag_ the other reviewers to reduce confusion of who's focused on the review.)

( @mcbouslog 🤔 wait I just realised that we may need to revise this idea if some PRs DO require multiple reviewers.)

But anyway, on to my review!

**Review by shaunanoordin — APPROVED** [review]
## PR Review

This PR updates PJC to 3.4.1, addressing a potential security issue, since older versions of PJC uses an extremely outdated version of superagent.

### Testing

Tested on localhost with macOS + Chrome 101 / Firefox 100 / Safari 15

- I can view the home page
- I can login/logout from the home page
- I can view the projects page
- I can select a random test project (I Fancy Cats), then make & submit Classifications

Manual tests indicate no issues with anything that may require PJC. Authentication works fine, and I'm not seeing any issues with insecure calls (i.e. no calls to _http:_ //panoptes-staging.zooniverse.org) in any of the auth requests, Classification posts, etc etc.

### Status

LGTM, let's get this merged and deployed ASAP

**Comment by eatyourgreens** [comment]
The project builder uses PJC to make POST and PUT requests (probably DELETE too) but those should also be ok.

**Pull request merged**
