### PR TITLE
Remove PromiseRenderer from the favourites button

### PR DESCRIPTION
**Pull request by eatyourgreens**
Describe your changes.
Removes the PromiseRenderer in favour of storing the favourited status, and the favourites collection, in component state.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://favorites-promise-renderer.pfe-preview.zooniverse.org/
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I came across this while working on #2984 The PromiseRenderer throws 'unknown props' warnings in React 15.

Has anyone got time to look over it today or early next week?

**Comment by simoneduca** [comment]
Sure

**Comment by rogerhutchings** [comment]
#3216

**Comment by rogerhutchings** [comment]
Okay, I've tested this out by cherry-picking this commit into the `react-15` branch - seems to work just fine.

**Pull request merged**
