### PR TITLE
Paginate boards list, increase request size

### LINKED ISSUE #1815: (Old Weather) Talk is only displaying the first 10 boards
The Old Weather Talk community is telling me that they've created 13 or 14 boards, but only the first 10 are displaying.

If we're not going to have any way to nest boards, then we really can't put limits on the number of top-level boards.

https://www.zooniverse.org/projects/zooniverse/old-weather/talk/

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #1815

### CODE REVIEW

**Comment by DarrenMcRoy** [comment]
I don't know about paginating the boards list. I would rather they just all displayed on one page. I know that might increase load time, but I've never been to a forum where boards are paginated.

(a la the [old-school Old Weather forum](http://forum.oldweather.org/) where they have 17 boards all displaying on the front page -- and then more nested beyond that)

**Comment by aweiksnar** [comment]
@DarrenMcRoy It'll only show them as pages if there are more than 20 boards. It'll now request 20 at a time

**Comment by DarrenMcRoy** [comment]
I can live with that for now, then. Especially since you can manually order them. Good work.

**Comment by chrissnyder** [comment]
:hamster:

**Pull request merged**
