### PR TITLE
Convert urls to links in md, and add breaks

### LINKED ISSUE #853: If you write out a url in Talk it doesn't become a hyperlink
lower in the queue -  Posting this before I get about it , since i saw it. Just noticed that one of the P4T moderators tried to post a link to a P4 Talk thread and it doesn't show up as a url. I know there's a good fraction of people write the full address and don't use the linking. In current Talk is identified those are links and makes them by default hyperlinks, I think  this would be handy if in the future panoptes Talk could do this as well 

http://preview.zooniverse.org/panoptes/#/projects/mschwamb/planet-four-terrains/talk/8/118?page=1&comment=216

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #853

### CODE REVIEW

**Comment by brian-c** [comment]
The hashtag replacement breaks links with #fragments.

Might want to update the regexes to check for a `\s` or `^` before matching.

**Comment by aweiksnar** [comment]
Ooh good thinking, just pushed a fix for that case

**Comment by brian-c** [comment]
Sorry this is taking so long. Want to do the same thing with `@`? Email addresses are caught too.

**Comment by aweiksnar** [comment]
I didn't realize linkify does emails too, sorry about not checking that. Just updated in 3de94e9

**Comment by brian-c** [comment]
Sweet, thanks.

**Pull request merged**
