### PR TITLE
Lab: Refactor workflow subject sets

### PR DESCRIPTION
**Pull request by eatyourgreens**
TODO:
- [x] Move all workflow subject set logic into a `SubjectSetLinker` component.
- [x] Change the sort order of requested sets from `display_name` to `-id`, so that newer sets are received first.
- [x] display sets in alphabetical order, by  `display_name`. 

UPDATE: Alphabetical sorting, by name, is preserved while still showing the 2021 sets for Radio Meteor Zoo.
Screenshot of Radio Meteor Zoo subjects, listed alphabetically for recent years.

The motivation for this is that [Radio Meteor Zoo](https://www.zooniverse.org/lab/2471) has hit a hard limit for the number of sets displayed for a workflow, so can't link up new sets to new workflows.

Try it out on Radio Meteor Zoo, where you should see the latest 2021 subject sets listed for a workflow:
https://pr-6042.pfe-preview.zooniverse.org/lab/2471/workflows/19930?env=production

Staging branch URL: https://pr-6042.pfe-preview.zooniverse.org

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by camallen** [comment]
I've added https://github.com/zooniverse/panoptes/pull/3722 to allow subject set id sorting. The ID attribute is auto incrementing so is a proxy for created_at but is indexed so should be a faster sort.

**Comment by eatyourgreens** [comment]
Oh, good idea!

**Comment by eatyourgreens** [comment]
> On PR-6042, clicking the button above will show no visible change to the page.

Agh, that's because I took the `PromiseRenderer` out.

Side note: we should be removing `PromiseRenderer` whenever we can, see https://github.com/zooniverse/Panoptes-Front-End/issues/3216 and https://github.com/zooniverse/Panoptes-Front-End#async-helper-components.

**Comment by eatyourgreens** [comment]
I've just pushed a fix for the `addDemoSet` function.

**Comment by shaunanoordin** [comment]
Nuts, I'm still getting the same error. I've moved testing to localhost to ensure it's not the staging link being outdated, and I can see that I'm on commit 07514e7eea1f3d47e083650fdc07cbc3f10e5eeb

One sec while I see if I can debug this.

Current testing URL: localhost, same WF https://local.zooniverse.org:3735/lab/1951/workflows/3535

**Comment by shaunanoordin** [comment]
Oh, do we also need to update `projectSets` in addition to `workflowSets`?

**Comment by eatyourgreens** [comment]
D'oh! You're right. And the new set ID will not be `DEMO_SUBJECT_SET_ID`, because Panoptes clones the subject set.

**Comment by shaunanoordin** [comment]
> D'oh! You're right. And the new set ID will not be DEMO_SUBJECT_SET_ID, because Panoptes clones the subject set.

Haha, jinx again!

**Comment by eatyourgreens** [comment]
OK, I've overwritten that last commit with a second go at making it work. Otherwise, I'll have another look tomorrow.

**Comment by eatyourgreens** [comment]
You were right, `fetchData()` has to be run after making changes to the project.

**Review by shaunanoordin — APPROVED** [review]
## PR Review (Update)

The updates to this PR have fixed the bug! 👍 

- When the project has no SSets, I _can_ add an "Example Subject Set"
  - Minor note: on PR 6042, the Example SSet is added to the Project, but _not attached to the Workflow._ On `master`, the Example SSet is both added to the Project _and_ attached to the WF. This change is perfectly fine, though - it just means the user has to perform one additional click, and this new behaviour doesn't contradict any known user expectations. 👌 

### Status

Code read looks good, and functionality tests pass. LGTM! 👍

**Comment by shaunanoordin** [comment]
Note to self: remember to copy changes to `workflow.cjsx` to #6037

**Comment by eatyourgreens** [comment]
Cool. Let’s get this out and show it to Radio Meteor Zoo.

**Pull request merged**
