### PR TITLE
Make the freehand drawing tools public - BLOCKED

### PR DESCRIPTION
**Pull request by eatyourgreens**
Staging branch URL: https://freehand-tools.pfe-preview.zooniverse.org

Makes all four freehand line tools available in the workflow task editor.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by camallen** [comment]
The data that comes out of this tool can result in really large annotation payloads, it would be better if we modify how the annotation data in tool is stored to reduce duplication of nested objects (e.g. each node on the line is {x: 1, y: 1} but we could easily strip out the x/y, though we should probably self document the schema in the payload as well to avoid mistakes when interpreting.

**Comment by eatyourgreens** [comment]
I thought @rogerhutchings had already reduced the large number of points being recorded by Etch-A-Cell in #3827?

**Comment by rogerhutchings** [comment]
I did, points are rounded to 1 decimal place and then duplicates are removed. But the way the data are stored could still be optimised:

```
// Current annotation array
[
	{
		x: 123,
		y: 456
	},
	{
		x: 789,
		y: 123
	}
]

// Proposed
[
	[123, 456],
	[789, 123]
]

**Comment by eatyourgreens** [comment]
Should we block this PR until that change is made?

**Comment by rogerhutchings** [comment]
Yes, and I'd want to warn Etch-A-Cell that the annotation schema is going to be changed. Besides, I don't want any other projects to have to handle a change like this when we can do it before the tools are public.

**Comment by rogerhutchings** [comment]
@hrspiers Can you get in touch with the EaC team about the above?

**Comment by rogerhutchings** [comment]
One other thing - do we want to announce that we've made these tools public, and how / where if so?

**Comment by tlalka** [comment]
I was looking at this build, and it seems like some of the free hand tools aren't completely working. Free hand segment shape, and free hand segment line cannot make concave lines/shapes, and they also cannot place a point that overlaps another line/shape. When you attempt to place a point within another segment line/shape, you automatically select the new shape for dragging, but you can't move the line/shape anyway.

**Comment by eatyourgreens** [comment]
There’s been a request to use these tools in a project. Is this still blocked by #4423?

**Comment by eatyourgreens** [comment]
Rebased to the latest master.

**Comment by srallen** [comment]
I think we should build the updated version of the freehand tools in the rewrite and ask project using it to migrate to the new classifier once it is ready. Then we can have a clear delineation of the tools.

**Pull request closed without merging**
