### PR TITLE
Add project card hover/reveal effect

### PR DESCRIPTION
**Pull request by aweiksnar**
:copyright: @jwbmartin's wireframes

### CODE REVIEW

**Comment by brian-c** [comment]
Looks nice! A couple things:

`.card`'s `overflow: hidden` kills the keyboard focus ring.

Mobile/keyboard users won't see content on `:hover`.

**Comment by jwbmartin** [comment]
Would it be possible to turn off :hover styling in mobile?

**Comment by aweiksnar** [comment]
Just added card focus-ability in 6af10ee, That look okay or think it's worth revealing on `:active` too?

**Comment by brian-c** [comment]
Just fixed focus on cards. Couldn't find a quick fix for mobile. @jwbmartin I suggest not using hover states to reveal information. Mobile won't get to see it, or worse, they'll see it for the split second before the page changes.

Looks good to me otherwise. @aweiksnar go ahead and merge if you're happy with my change.

**Pull request merged**
