### PR TITLE
Native video

### LINKED ISSUE #3765: Internet explorer bug: video playback options below the fold
## Expected behavior

video playback speed buttons should be above the fold for all browsers. They are except for Internet Explorer. 

Here is an image of what it looks like in Chrome, which is correct. 

screen shot 2017-05-05 at 8 43 41 pm

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

The playback speed buttons for video projects on Internet Explorer are below the fold. 
screen shot 2017-05-05 at 8 39 53 pm

This came to attention of the research lead because of comments in Talk where users didn't realize there were playback speed options. Figured out it was browser differences. 

## Additional information

- **Operating system:**
Mac, but using an internet explorer emulator in Chrome

- **Browser:**
Internet Explorer 11. The IE emulator just let me test in 11. I haven't tested in older versions of IE.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fixes #3765 

Removes the custom video play button and scrubber, in favour of the native browser controls.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://native-video.pfe-preview.zooniverse.org/
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
https://native-video.pfe-preview.zooniverse.org/projects/zooniverse/arizona-batwatch?env=production to see this on a live project.

Needs testing on a variety of browsers and devices, since everyone has their own idea about how to implement video controls.

**Comment by eatyourgreens** [comment]
Tagging @beckyrother for design feedback.

**Comment by beckyrother** [comment]
@eatyourgreens looks good to me! not sure if this is entirely related, but can the speed controls be on the same line as the info/fav/collect icons? 
arizona_batwatch_ _classify_ _zooniverse

**Comment by eatyourgreens** [comment]
@beckyrother I've changed the positioning of those controls. It'll need testing on different browsers/devices but should work.

**Comment by eatyourgreens** [comment]
@beckyrother the only thing we probably can't do is style the native video controls ourselves.

**Comment by beckyrother** [comment]
@eatyourgreens looks good, thank you!

**Comment by simensta** [comment]
The native video controls work for me in both:
Windows 10/Microsoft Edge 14 
edge-14-batch-watch

Windows 10/Internet Explorer 11
ie11-batch-watch

**Pull request merged**
