### PR TITLE
Use discussion link comment for board preview

### LINKED ISSUE #873: Most recent post link doesn't go to the most recent post
The front page of Talk, when showing recent threads, displays not the name of the most recent person to post, but instead the name of the person who started the thread.

screen shot 2015-06-29 at 1 09 01 pm

when you can see that Chris' post was actually from a long time back, and the most recent posts were mine and Janet's

screen shot 2015-06-29 at 1 10 37 pm

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #873

### CODE REVIEW

**Comment by edpaget** [comment]
Shouldn't the behaviour be the same on this page too? 

screenshot from 2015-07-16 16-39-26

**Comment by aweiksnar** [comment]
Those discussion previews are currently correct in that they both advertise & display the time/user they were started from (originally took that line from the design).

I will display the latest comment in those though since it was requested in #874, but can do that in a separate PR

**Comment by aweiksnar** [comment]
Edit: Just added in the the same behavior for that other page, so if that looks okay this'll close #874 too

**Comment by edpaget** [comment]
:fist:

**Pull request merged**
