### PR TITLE
Drawing subtask theming

### LINKED ISSUE #4544: Add light and dark theme styling for the drawing tools subtask.
We do not have design reference files for this and will possibly need a consult with @beckyrother, however, the basic styles from the task area for light and dark themes may be reusable. 

screen shot 2018-04-03 at 3 05 53 pm

### PR DESCRIPTION
**Pull request by srallen**
Staging branch URL: https://drawing-subtask-theming.pfe-preview.zooniverse.org/

Dev classifier using the circle drawing tool: https://drawing-subtask-theming.pfe-preview.zooniverse.org/dev/classifier

Whales as Individuals uses a drawing subtask: https://drawing-subtask-theming.pfe-preview.zooniverse.org/projects/tedcheese/whales-as-individuals/classify?env=production

@beckyrother is the styling ok?

Fixes #4544.

I found writing tests to be a bit tricky because of the modal-form dependency, so I only added a basic scaffold for just checking it renders without crashing. I'll follow up with fixing the keyboard focus bug separately.

Describe your changes.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by beckyrother** [comment]
Mostly looks good, just check the spacing on the additional options: 
zooniverse
1. Maybe half the padding between the question and the buttons
2. Text input is too short – can this be the same height as the buttons?
3. Weird inset shadow on the slider?
4. Text input is too tall – can this also be the same height as the buttons?
5. Can this button be the entire width of the box?

**Comment by eatyourgreens** [comment]
There's an open bug for the sizing of the text input box in drawing subtasks: #4095

**Comment by srallen** [comment]
@beckyrother I've followed up on your notes:

1. I removed the styling for the question paragraph for all tasks in general. It was inheriting a defined `margin: 1em 0 1.5em`. Removing this causing the paragraph style to fallback to the browser default of 1em on the top and bottom. Is this ok?
2. Since this is the bug reported in #4095, I'd like to hold off on trying to fix it for this here. I don't think we have any launched projects using the free text input in a subtask, so I think we ok for doing the fix for #4095 separately.
3. Fixed.
4. Fixed.
5. Fixed.

**Comment by CKrawczyk** [comment]
Just want to note that SCOTUS Notes does use a free text box as a subtask: https://www.zooniverse.org/projects/zooniverse/scotus-notes-behind-the-scenes-at-supreme-court-conference/classify

**Comment by srallen** [comment]
@CKrawczyk Thanks for letting me know. We really need to have a better handle on the kinds of tasks our launched approved projects have!

I don't think this PR should be held up for fixing it still though since #4095 mentions checking to make sure the removal of that inline style doesn't break other tasks' styling.

**Pull request merged**
