### PR TITLE
Lab: Add instructions in Translations tab for new language

### PR DESCRIPTION
**Pull request by goplayoutside3**
Staging branch URL: https://pr-6755.pfe-preview.zooniverse.org

I added an additional sentence to the Translations tab in the lab instructing project owners to email Zooniverse if they've submitted translations for a language, but that language doesn't show up as a checkbox. That scenario means they're the first project to translate that language and it needs to be added to the menus on frontend apps.
Screenshot 2023-08-04 at 10 42 51 AM

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by seanmiller26** [comment]
Thanks for flagging. I'd like to make the following copy changes for clarity, if possible:

'Check which languages you’d like to make available to your volunteers. If you don’t see a published language here please email contact@zooniverse.org with the preferred language and project ID.'

Let me know if that wording would cause any confusion re published languages, I'm not 100% clear on the translations approval process etc.

Can we also change the check box column to say ‘Publish’

**Comment by goplayoutside3** [comment]
I do want to make it clear the instructions are only for the list of checkboxes. Would this work?

'Check which languages you’d like to make available to your volunteers. If you don’t see a published language in the checkboxes please email [contact@zooniverse.org](mailto:contact@zooniverse.org) with your project ID.'

**Comment by goplayoutside3** [comment]
Sounds good - how does this look?

Screenshot 2023-08-07 at 1 18 40 PM

**Review by seanmiller26 — APPROVED** [review]
LGTM!

**Pull request merged**
