### PR TITLE
[WIP Do not merge] New Project Builder Documentation

### PR DESCRIPTION
**Pull request by BNewing**
Fixes # .

Rewriting the Project Builder Documentation so that it is easier to navigate and use, based on a draft that @aliburchard li started a few months ago.

I'm keeping in a link to the old 'How to' guide for those who want to see a detailed run through of it. This page is stored separately and not currently linked up in any nav bars.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://projectbuilderdocumentation.pfe-preview.zooniverse.org 

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
…nto old file

### CODE REVIEW

**Comment by BNewing** [comment]
Still in the drafting phase at the moment!

**Comment by BNewing** [comment]
Now staged: https://projectbuilderdocumentation.pfe-preview.zooniverse.org 

It's happening @aliburchard!

**Comment by trouille** [comment]
@mrniaboc When you're back from holiday, could you take a look at this and see what to do next?

**Comment by BNewing** [comment]
I haven't forgotten about this - have just had a manic month with job hunting, interviews and negotiations which has just ended. Nvm is acting up a bit on my windows laptop but I'll have another go at fixing it and then carry on. Helen has helped me with the draft so the content is ready to be added in.

**Comment by BNewing** [comment]
I'm still getting a weird issue with this when I try to start the local host. @marten could you have a look at the console error that I'm getting when I see you next please? I think it's  to do with the node version I've got but I'm not 100% sure :(

**Comment by camallen** [comment]
@BNewing check the version of your node / npm against the required engine [here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/package.json#L98)

**Comment by BNewing** [comment]
Got it working again. Re-downloaded Helen's draft feedback and I'm going to carry on with this.

**Comment by srallen** [comment]
Just to clear out current open PRs, I'm going to close this since it's been open about 10 months. It can be reopened when it is ready.

**Comment by hrspiers** [comment]
Hey,

Would anyone be able to bring this to completion? It looks like this was 90% of the way there.

I think Bev was up to the point where she was editing the text based on the edits in the attached document;

[All sections.docx](https://github.com/zooniverse/Panoptes-Front-End/files/1457485/All.sections.docx)

H

**Comment by BNewing** [comment]
That was the point I was at! It got a bit lost, and I think I was having an issue linking it up to one page in the React router stuff, but otherwise it was just mostly text editing

**Comment by jelliotartz** [comment]
@hrspiers Happy to pick this up and finish it off :)

**Comment by hrspiers** [comment]
Brilliant, thanks @jelliotartz - let me know if you have any questions about the changes!

H

**Comment by jelliotartz** [comment]
Unless anyone minds, I'll open a new PR (and close this one) rather than rebase and deal with all the merge conflicts from changes that have happened since this PR was started. I'll make sure to cross reference the old and new PRs so there's continuity and connection between them.

I'll use that `All Sections.docx` text in the new PR.

**Comment by jelliotartz** [comment]
I'll leave this PR open until we get done with review of #4194.

**Comment by jelliotartz** [comment]
Closing due to merge of #4194.

**Pull request closed without merging**
