### PR TITLE
Add UI button for transcription task to lab

### PR DESCRIPTION
**Pull request by srallen**
Staging branch URL: https://pr-5899.pfe-preview.zooniverse.org

This adds a button in the list of tasks when you click "Add Task" for transcription task, if the project has the `transcription-task` experimental tool enabled. This can be setup in the admin pages for a project. Once it is, you'll see it in the list:

Screen Shot 2021-02-17 at 11 25 02 AM

For existing projects setup with the transcription task, it also adds the icon to the task in the task list:

Screen Shot 2021-02-17 at 11 25 12 AM

Both of these can be demoed by checking out https://pr-5899.pfe-preview.zooniverse.org/lab/1764/workflows/3392

Right now the button doesn't do anything other than console log. Functionality will come in a future PR.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by srallen** [comment]
@beckyrother I've added the font icon for transcription task (only visible to projects with it enabled). Let me know if you still want to go with that.

**Review by beckyrother — APPROVED** [review]
I like the A! Approved on my end 👍 

Possibly unrelated / wontfix but it looks like the Text and Survey task icons are bigger than the others? Or I'm losing my mind? 

108242895-1379d180-7113-11eb-8883-bebbd9c2944a

**Comment by srallen** [comment]
@beckyrother they're all set to use font-awesome's `fa-2x` class which sets the size.

**Review by shaunanoordin — APPROVED** [review]
## PR Review

This PR adds a new (non-functional) button the the Lab's selection of Tasks.

- The option appears in Lab -> (choose a project) -> Workflows -> (choose a workflow) -> "Add Task" button
- The option only appears when a project has the experimental flag "Transcription Tasks" switched on.

Tested on macOS10+Chrome88 at https://pr-5899.pfe-preview.zooniverse.org/lab/1929/workflows/3459 (Davy Notebooks, with appropriate flag)

Code stuff LGTM 👍

**Pull request merged**
