### PR TITLE
Set pointer events CSS for combo tasks

### LINKED ISSUE #3803: inconsistent pan-zoom enabling on subject image click
## Expected behavior
If pan & zoom is enabled and click anywhere on subject image pan & zoom functionality will enable
Example: https://www.zooniverse.org/projects/zooniverse/notes-from-nature/classify?reload=1&workflow=3948

## Current behavior
With pan & zoom enabled, in a combo task consisting of no drawing or crop tasks, clicking in the image doesn't enable pan & zoom functionality
Example: https://www.zooniverse.org/projects/zooniverse/notes-from-nature/classify?reload=1&workflow=2838

User can click cross-hair button to enable pan & zoom. This may be an unfortunate but necessary side-effect to allowing drawing/crop tasks in a combo task.

## Steps to replicate
https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify
vs
(not sure how far behind master) https://pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fixes #3803 .

Describe your changes.
Add `pointerEvents: 'none'` to the SVG inline styles if the combo does not contain any drawing tasks.

We should really be using CSS classes instead of inline styles. This is just a quick patch to get Notes from Nature working again.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://combo-pointer-events.pfe-preview.zooniverse.org/
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by wgranger** [comment]
This is making the SVG image active, but the subject is not draggable, as the pan and zoom should enable.

**Comment by eatyourgreens** [comment]
My bad. Pan/zoom should override styles that are set by the tasks.

**Comment by wgranger** [comment]
Dragging the image uncovers a duplicate background of the same image. Not sure if it's getting that `background: black` style.

screen shot 2017-05-18 at 9 35 02 am

**Comment by eatyourgreens** [comment]
Shallow merge was overwriting the existing style. Should be fixed now.

**Comment by eatyourgreens** [comment]
It turns out that any subject image on any live project is draggable if you click on it, so I've disabled that too.

**Comment by wgranger** [comment]
Now getting `TypeError: Cannot read property 'togglePanOn' of undefined`. Not sure if this is related to the merge conflict.

**Comment by eatyourgreens** [comment]
Rebased to bring in React 15.4 and updated slightly to fix that undefined variable error. Should be read to go now (fingers crossed.)

**Comment by wgranger** [comment]
Ok. This looks to be good now.

**Pull request merged**
