### PR TITLE
Sort recent blog posts by created_at

### LINKED ISSUE #6813: Recent blog posts are out of order on the home page
## Expected behavior
Recent blog posts, on the home page, should show the most recent blog post first.

## Current behavior
Chris' announcement is buried in the list because we concatenate our blog feeds without sorting the result.

The recent blog posts list from the Zooniverse home page, showing yesterday's blog post behind two posts that are four months old.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Sort recent blog posts by `created_at`, so that the most recent blog post is always first on the home page.

The recent blog posts section, from the home page, showing yesterday's announcement at the top of the list.

Staging branch URL: https://pr-6814.pfe-preview.zooniverse.org

Fixes #6813.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by goplayoutside3** [comment]
Hmm when I visit https://pr-6814.pfe-preview.zooniverse.org, I still see blog posts not sorted by date. Am I looking in the wrong place?

Screenshot 2023-09-07 at 11 00 40 AM

**Comment by eatyourgreens** [comment]
That's the right link, but my screenshots are from Firefox.

**Comment by eatyourgreens** [comment]
Oh wait, `created_at` is a string, not a Date. Chrome is probably comparing the string lengths or something.

**Comment by eatyourgreens** [comment]
Safari has the right order. 🤔

**Comment by eatyourgreens** [comment]
I've converted `post.created_at` from a string to a Date. Let's see if that fixes it.

**Comment by eatyourgreens** [comment]
D'oh! Realised my error. The fix should be up shortly.

**Comment by eatyourgreens** [comment]
The return value from an array sort should be +1, 0, or -1. Not a Boolean.

**Review by goplayoutside3 — APPROVED** [review]
Looks good!

**Pull request merged**
