### PR TITLE
Remove 'Audio Projects' from the 'Call for Projects' page

### LINKED ISSUE #6083: Remove audio call from CFP page
https://www.zooniverse.org/get-involved/call-for-projects

Audio call text can be removed from the Call For Projects page.

### PR DESCRIPTION
**Pull request by shaunanoordin**
## Overview

Closes #6083 
Preview: https://pr-6084.pfe-preview.zooniverse.org/get-involved/call-for-projects

This is a content update. The "Get Involved > Call for Projects" [page](https://www.zooniverse.org/get-involved/call-for-projects) on the Zooniverse currently has calls for two kinds of projects: **Audio Projects,** and Bio Projects; this PR removes the former.

### Status

Ready for review

### CODE REVIEW

**Review by snblickhan — COMMENTED** [review]
Looks great. Thanks Shaun!

**Comment by eatyourgreens** [comment]
Looks good, but there's also a test that checks for the CFP section.

**Comment by eatyourgreens** [comment]
The staging site doesn’t exist. Looks like an error with the Azure login.

**Comment by shaunanoordin** [comment]
Thanks Jim, I've updated the CallForProjects.spec.js tests! 👍 

And also, booo, it is indeed a full-on Azure login issue - I thought it was a temporary problem (I was also encountering some weirdness on Panoptes, and those issues suddenly disappeared in the middle of me documenting them) but I'm still seeing "The provided client secret keys are expired" errors after re-running the job. 😞 I'll post on #dev for help

**Comment by shaunanoordin** [comment]
Deployments fixed! Big thanks to Zach for getting this fix in 👍

**Comment by eatyourgreens** [comment]
There was a typo in the staging link: `pr-6083` instead of `pr-6084`. Looks good now.

**Review by eatyourgreens — APPROVED** [review]

**Pull request merged**
