### PR TITLE
Add prompt to set login name for migrated users

### LINKED ISSUE #598: Prompt migrated users to set their login
When a user first logins into Panoptes with a pre-existing Zooniverse account, we should show them the login name we've given them for @-mentions and their url slug and allow them to change it if they want. This is the only time we should allow those to be changed.

### PR DESCRIPTION
**Pull request by edpaget**
Triggered by a user.login_prompt field on serialized response

Closes #598

### CODE REVIEW

**Comment by edpaget** [comment]
This depends on zooniverse/Panoptes#1000 Also I'm not sure what the text for the field should be @DarrenMcRoy any thoughts?

**Comment by DarrenMcRoy** [comment]
First draft of content is in: https://docs.google.com/document/d/17JL1SHuSEng0rM3YjDthLSARoPRGhbeaaWAJ_CdnZ5A/edit

**Comment by edpaget** [comment]
This should also be good to go. @aweiksnar I've just been editing https://github.com/edpaget/Panoptes-Front-End/blob/login-prompt/app/partials/login-dialog.cjsx#L48 to be `if true` for most of my testing. Let me know if you also want me to set the flags on your Panoptes account to see it that way.

**Comment by aweiksnar** [comment]
Sweet! Just tested it out and looks like it works great

**Pull request merged**
