### PR TITLE
Catch breadcrumbs for unpermitted boards

### LINKED ISSUE #1047: Gracefully handling  trying to go to a restricted access Talk board while non-logged in -
low in the queue - Talk should gracefully handle trying to go to a restricted access board or thread while non-logged in or for an account that doesn't have access - currently get a bunch of errors/json spit out

screen shot 2015-07-13 at 10 02 28 am

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #1047

### CODE REVIEW

**Comment by edpaget** [comment]
I think this needs the :( Not Found error you get when you visit a project that's private.

**Comment by edpaget** [comment]
Otherwise the page is a blank and user can't be sure of what error was encountered.

**Comment by aweiksnar** [comment]
Ah yeah way better idea. I'll work on adding in a 'You don't belong here' type page, since apparently the react router NotFoundRoute is only indended for [poorly formed urls](https://rackt.github.io/react-router/#NotFoundRoute)

**Comment by edpaget** [comment]
Couple small things left. It looks like the boards remain visible if you log out from your account but don't refresh the page. 

And if you try to visit the talk of a private project you don't have access do it still just shows a blank page instead of a not found error.

**Pull request merged**
