### PR TITLE
Add invert subject button to Talk

### LINKED ISSUE #5094: Add invert button to Talk subject viewer
## Requested behavior
Add invert button to Talk subject viewer.

## Current behavior
Subjects viewed within Talk do not have the invert button.

### PR DESCRIPTION
**Pull request by mcbouslog**
Staging branch URL: https://pr-5275.pfe-preview.zooniverse.org/projects/markb-panoptes/backyard-worlds-test-project-mb/talk/187/319

Closes #5094.

Describe your changes.
- adds invert button to Talk discussion
- adds invert button to Talk subject page
- adds simplified svg layer on subject

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by mcbouslog** [comment]
I'm not wild about what I named the new component.

**Comment by eatyourgreens** [comment]
CSS filters have good support nowadays, so you could try styling the HTML image with `invert()`, instead of using SVG. https://caniuse.com/#feat=css-filters

**Comment by mcbouslog** [comment]
That sounds so much cleaner, I'll try that! Thanks.

**Comment by mcbouslog** [comment]
Closing in favor of #5276.

**Pull request closed without merging**
