### PR TITLE
Fixing favorite button to set flag

### PR DESCRIPTION
**Pull request by edpaget**
Also has the favorites button make fewer requests

### CODE REVIEW

**Comment by aweiksnar** [comment]
:+1: :+1: Much cleaner than before

**Comment by edpaget** [comment]
@aweiksnar Just FYI this adds the idea of a global Favorites collection which it will add subjects to unless you explicitly pass a project property to the component.

**Comment by aweiksnar** [comment]
:ok: cool, Yeah it'll be neat to see how users end up using global collections

**Comment by edpaget** [comment]
Yeah I'm still making a collection scoped the project when you favorite from the classification interface. I think there are other places that button shows up though.

**Comment by aweiksnar** [comment]
It's in all talk comments that mention a subject and the talk object page. They may have to remain separate for the favorite button since there's no way to safely resolve a subject's project without asking the user to do it

**Comment by edpaget** [comment]
Cool yeah I was briefly looking to see if Project Talk pages had a project property I could pass down to the subject, but couldn't find it.

**Comment by aweiksnar** [comment]
Yeah I'll can look into adding that in, so far it's just been reading from the url

**Pull request merged**
