### PR TITLE
Markdown project prop

### PR DESCRIPTION
**Pull request by aweiksnar**
- Updates to correspond with markdownz@2.0.0 release

### CODE REVIEW

**Comment by brian-c** [comment]
Looks like `^123` isn't picked up, and `@name/project^123` only links the user.

See #/projects/brian-testing/ghosts/talk/53/78?comment=466

**Comment by aweiksnar** [comment]
Yeah it'll need an `S` prefix now to match. That was my mistake for initially matching cases without the resource type prefix.  See https://github.com/zooniverse-ui/markdownz/issues/11

**Comment by brian-c** [comment]
Cool, got it now. Anything need to happen before we can use this in Talk comments?

**Comment by aweiksnar** [comment]
Should be good to go with the markdowz update, Mentions will just have to look something like `S123123`

**Comment by brian-c** [comment]
It doesn't look like the project is included in the comment-preview module, so `@u/p^S123` works but `^S234` just turns into "234" for some reason (where'd the "^S" go, anyway?).

**Comment by aweiksnar** [comment]
I just tested locally - `^S123123` should be working ok in project talks, but in zooniverse-wide talk it needs to be project specified. It'll currently fall back to just the id so there's not a weird caret in the text if the comment happens to be rendered outside of the context of the project

**Comment by brian-c** [comment]
Can I see a link to a project comment on dev? I must be doing something wrong here.

**Comment by aweiksnar** [comment]
Ah so sorry! I was looking at a different preview. Now I see where  you're not seeing it:  Will push up a fix in a min

**Comment by aweiksnar** [comment]
I just pushed up a change removing that `comment-preview` module in favor of just markdown, since it was a waste of a class. Deployed [here](http://demo.zooniverse.org/panoptes-front-end/markdown-project-prop/#/projects/alex-panoptes/test-proj/talk/21/80) for testing

**Comment by brian-c** [comment]
Glorious now, thanks!

**Pull request merged**
