### PR TITLE
Updating Featured Project copy

### PR DESCRIPTION
**Pull request by beckyrother**
Updating copy for August featured project.

Describe your changes.

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by beckyrother** [comment]
I'm sorry for the two PR's, just not sure how to do them both at once.

**Comment by shaunanoordin** [comment]
@beckyrother does this PR include the file for `featured-project-20170801-steller.jpg` ?

**Comment by beckyrother** [comment]
@shaunanoordin it's in a separate PR: https://github.com/zooniverse/Panoptes-Front-End/pull/3965

**Comment by shaunanoordin** [comment]
OH! OK, I see, that other PR is #3965. No worries, we can combine these two things into one PR easily.

Please do the following:
1. In your Panoptes-Front-End repo, checkout this branch - `git checkout beckyrother-august-featured-1`
2. Add the Steller JPG into `src/public/assets/featured-projects/`
3. `git add .`
4. `git commit -m "Added my seal of approval" `
5. Avoid angry marine biologists arguing that a sea lion isn't a seal and that joke doesn't work.
6. `git push origin beckyrother-august-featured-1`

I'll close the second PR as that's unnecessary.

**Comment by shaunanoordin** [comment]
PS: @beckyrother the `featured-project-20170801-steller.jpg` file on that other PR is maybe a bit on the kinda humongous side?

**Comment by shaunanoordin** [comment]
Nice! I give this PR my seal of- no, used that one already.

### Status
LGTM, approved and merging

**Pull request merged**
