### PR TITLE
Infinite loop

### PR DESCRIPTION
**Pull request by wgranger**
Describe your changes.
This PR adds an infinite loop to the subject flipbook so a user doesn't have to keep pressing "play" after `playIterations` has run its course. This was deceptively easy to add, so I'm curious if I'm missing something with the flipbook functionality. Seems to work well though.

I also enlarged the play/pause icon size based on feedback.

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

https://infinite-loop.pfe-preview.zooniverse.org/projects/wgranger-test/single-task-bug
* The "Infinite Loop" workflow on this project has a flipbook. 

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Would it be worth making `playIterations` a workflow setting too, with a default of 3 for backward compatibility? I think that would also be a small change but feel free to ignore it if it turns out to be more complicated.

**Comment by wgranger** [comment]
Are you thinking of making `playIterations` a number somebody sets in the project builder, with an option for infinite? That makes sense.

**Comment by eatyourgreens** [comment]
Yeah, maybe a number you can input, then set it to `Infinite` if the input is blank. Default setting would have to be 3, I guess, since that's the current hardcoded value.

**Comment by wgranger** [comment]
Are you thinking of keeping this on the `configuration` tag, or making it a separate/new tag on the workflow resource?

**Comment by eatyourgreens** [comment]
`workflow.configuration` sounds good. Won't the Panoptes API throw 422 errors if you try to add arbitrary new properties to a Workflow resource?

**Comment by wgranger** [comment]
It will. Wasn't sure if we were going to add another tag on the backend, but I was worried that might bloat the resource. I think keeping it on `configuration` makes sense. I'll push up a commit with those changes above soon.

**Comment by eatyourgreens** [comment]
Looks good to me. Maybe set a placeholder to indicate that blank=Infinity, like the min/max controls do for the drawing tools. https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/drawing/min-max-editor.jsx#L87

**Pull request merged**
