### PR TITLE
Fix multiple tutorials

### LINKED ISSUE #3598: GZ3D: two tutorials load on first visit
## Expected behavior
Only the tutorial for the chosen workflow should load

## Current behavior
On starting a workflow for the first time, the default workflow tutorial loads behind the chosen workflow tutorial.

## Steps to replicate
Visit https://www.zooniverse.org/projects/klmasters/galaxy-zoo-3d while not logged in and choose the Bars or Spiral Arms workflow.

## Additional information
EDIT: Can still be reproduced in #3556

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fixes #3598 .

Describe your changes.
Moves code for the tutorials and mini course into the classify page wrapper.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://fix-multiple-tutorials.pfe-preview.zooniverse.org/
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
NB there's still a subtle bug here in that `Tutorial.startIfNecessary` will always create a new tutorial in the DOM when the workflow changes, rather than changing the content of any existing tutorial element.

**Comment by eatyourgreens** [comment]
Sorry, I should have said potential bug. I haven't been able to trigger it either. Just noting that the code still allows two tutorials to open if the workflow prop changes.

**Comment by eatyourgreens** [comment]
Custom sign-in prompt should be fixed now.

**Comment by eatyourgreens** [comment]
The Classify Page Wrapper has grown to the point that it should probably be split out into its own file, but I'll wait on #3590 before doing that.

**Comment by srallen** [comment]
Agreed about the wrapper.

**Pull request merged**
