### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by srallen**
Staging branch URL: https://update-packages.pfe-preview.zooniverse.org/

This has major version updates for several of our packages for the production build including webpack and some of the plugins. This also updates markdownz since running `npm audit fix` on it ~as well as removes `engine.io-client` since it didn't do anything and was one of the packages that was flagged by `npm audit`.~

After this update, PFE will be down to known 13 vulnerabilities, some which still can be addressed. 

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by srallen** [comment]
The tests fail with errors without `engines.io-client`. The `TalkStatus` component won't compile for the tests. I've added the package back to get the tests working again, but there may be a better way to get tests working since it isn't clear to me that this is an actual peer dependency for the sugar client or not.

**Comment by eatyourgreens** [comment]
#4713 should fix all but two of the remaining vulnerabilities. Those two are unpatched markdown-it plugins.

**Comment by shaunanoordin** [comment]
FWIW, testing looks good for this branch, with the latest PJC 2.10.0 update.

### Testing
Basic PFE functionality:
- Users can login/logout
- Users can view the Projects page
- Users can view a Project page (random sampling)
- Users can submit classifications for a Project (random sampling)

Additional checks:
- Project info pages (i.e. sections using Markdown) display content properly

Tested on localhost with OSX+Chrome67/FF60/Safari11. Windows testing incoming.

**Comment by shaunanoordin** [comment]
Update: Win7+IE11 and Win10+Edge testing both look good too.

**Comment by srallen** [comment]
I've run manual updates in the PR zooniverse/markdownz#70 which fixes one of the known markdown-it plugin vulnerabilities. We could still get markdownz published and updated in this branch since this hasn't merged yet.

**Comment by eatyourgreens** [comment]
Updating Markdownz sounds good to me.

**Comment by srallen** [comment]
I've updated markdownz and the staged branch. Everything looks ok to me. Project contents display fine and can make a Talk comment. Could @eatyourgreens or @shaunanoordin could do one last quick look over just on the markdown functionality just to confirm? Thanks!

**Comment by eatyourgreens** [comment]
Anchor links in Markdown work here so I think this is good to merge. https://update-packages.pfe-preview.zooniverse.org/help

**Comment by eatyourgreens** [comment]
I did a little bit of digging around and I *think* zooniverse/Sugar-Client is using Primus, which in turn [uses engine.io](https://nodesource.com/blog/understanding-primus/), which would explain the mysterious `engine.io` dependency.

**Comment by srallen** [comment]
@eatyourgreens it appears that there's a problem with the production build. I wasn't careful and didn't notice that my restaging here failed after the latest markdownz update. `markdown-it-anchor` is apparently using some ES6 features that aren't properly compiled to ES5 and Uglify is failing when trying to build the vendor chunk. Their repo has an issue open as of 2 days ago about it. I'm trying to modify the webpack build config to include markdown-it-anchor for now.

**Comment by srallen** [comment]
Re: the Sugar client, it should be updated to specifically require `engine.io` as a peer dependency if it's needed.

**Comment by eatyourgreens** [comment]
Yep. zooniverse/Sugar-Client  contains a copy of `primus.js` although it’s `panoptes-client` that actually uses it. I find it very confusing. https://github.com/zooniverse/panoptes-javascript-client/blob/master/lib/sugar.js

**Pull request merged**
