### PR TITLE
Add redirect for stellar sleuths

### PR DESCRIPTION
**Pull request by srallen**
Staging branch URL: https://pr-5824.pfe-preview.zooniverse.org

Describe your changes.
This is in preparation of the beta test next Tuesday so that zooniverse.org URLs routes to the new app.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by srallen** [comment]
@adamamiller let me know when the project gets renamed so I can update the redirect appropriately. We should get this in place at the latest on Monday.

**Comment by adamamiller** [comment]
@srallen Will do - I know I'm being slow to decide on this front, but, we will definitely have a decision by then. Part of the reason is I don't want to change anything right now and risk breaking our ability to test the system as we are finalizing the tutorial and Field Guide.

**Comment by srallen** [comment]
Going to https://pr-5824.pfe-preview.zooniverse.org/projects/adamamiller/zwickys-stellar-sleuths/ and https://pr-5824.pfe-preview.zooniverse.org/projects/adamamiller/zwickys-stellar-sleuths/classify should redirect to the fe-project sub domain and load the new app.

**Comment by adamamiller** [comment]
@srallen I'm guessing you know this is the case, but currently the About and Talk pages are throwing a 404 error.

**Review by mcbouslog — APPROVED** [review]
LGTM!

I believe the project nav links like About, Talk, Collect, and Recents will function as expected once this is merged and they're linking from within the `zooniverse.org` domain vs the `fe-project.zooniverse.org`.

**Comment by adamamiller** [comment]
@mcbouslog Does this mean that https://www.zooniverse.org/projects/adamamiller/zwickys-stellar-sleuths/ should point to the new VSLCV?

**Comment by srallen** [comment]
Not yet, this is only half the setup and the other half requires config on our cloud service. I'll report back when the other half is done.

**Comment by mcbouslog** [comment]
Update - https://www.zooniverse.org/projects/adamamiller/zwickys-stellar-sleuths/ should now load as expected.

We're working on deploying some additional UI updates, but the UI updates are unrelated to the urls working.

**Comment by adamamiller** [comment]
👍  –– thanks to everyone for the help getting this up and running

**Pull request merged**
