### PR TITLE
Allow drawing on audio subjects

### PR DESCRIPTION
**Pull request by eatyourgreens**
Staging branch URL: https://audio-drawing-task.pfe-preview.zooniverse.org

Describe your changes.
Add the SVG marking renderer for annotations on audio subjects.
Make the SVG background transparent for audio subjects.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Here's a project that was having trouble drawing on audio subjects: https://audio-drawing-task.pfe-preview.zooniverse.org/projects/mrniaboc/manu-maori-i-wellington/classify?env=production

**Comment by rogerhutchings** [comment]
It works, but the marking area extends underneath and below the player controls.

screenshot 2017-11-30 13 05 16

**Comment by eatyourgreens** [comment]
@rogerhutchings Any ideas about how to fix that? The current setup has the marking surface wrapped around the viewer. https://github.com/zooniverse/Panoptes-Front-End/blob/950c140b5227d85beae25abe71ca6c6dd8032785/app/components/frame-viewer.jsx#L69-L92

**Comment by rogerhutchings** [comment]
Blork. I think you'd have to pass down the marking surface to the viewer and let it handle where it goes. Which would change how they all work :(

**Comment by eatyourgreens** [comment]
One for whoever has time to continue working on the audio player.

**Comment by eatyourgreens** [comment]
Are we okay to merge this as-is, until someone has time to work properly on audio projects?

**Pull request merged**
