### PR TITLE
Improve sidebar load projects request

### PR DESCRIPTION
**Pull request by aweiksnar**

### CODE REVIEW

**Comment by parrish** [comment]
Seems to work fine locally.

I am seeing a `Warning: setState(...): You passed an undefined or null state object; instead, use forceUpdate().` now though

**Comment by parrish** [comment]
Think it might be this [`setState`](https://github.com/zooniverse/Panoptes-Front-End/pull/1583/files#diff-f400dfd5fa10c5405fcdb39e4a201796R41) causing it.  It calls once correctly, then again with an empty object

**Comment by aweiksnar** [comment]
Good call, just updated so that `setState` will be called only after request cycle is done

**Comment by parrish** [comment]
:+1:

**Pull request merged**
