### PR TITLE
Click for account menu

### PR DESCRIPTION
**Pull request by brian-c**
Account menu now drops down on click instead of hover.

Also added some handsome icons.

### CODE REVIEW

**Comment by edpaget** [comment]
Sorry for being late to this, is it possible to do both? Won't it be a bit of an unexpected change for people if the hover doesn't work?

**Comment by brian-c** [comment]
That's why the hover state is there. People'll get it. I'd prefer to not have things pop up on hover ever.

**Comment by eatyourgreens** [comment]
Looks like this kills the accessibility fixes added in #1096. I can tab to the control, press enter to activate the menu, but can't enter the menu using either tab or the cursor keys.

**Comment by brian-c** [comment]
Whoops, sorry about that. Should be fixed now.

**Comment by eatyourgreens** [comment]
Excellent! It's working exactly like the profile button on twitter.com now.

Is it possible to pass `aria-haspopup` and `aria-expanded` through as attributes to the trigger button element? I don't think VoiceOver will read them on the span.

**Comment by brian-c** [comment]
@eatyourgreens I've just made `aria-haspopup` and `aria-expanded` attributes on the trigger component in its repo. That'll have to be updated before this can be merged. Also added `menu` and `menuitem` roles.

**Comment by brian-c** [comment]
Closing until new modules is finished.

**Pull request closed without merging**
