### PR TITLE
Remove hash

### PR DESCRIPTION
**Pull request by edpaget**
This remove the need to use the hash fragement for URLs.

I'm working on a corresponding update to the nginx static server.

### CODE REVIEW

**Comment by chrissnyder** [comment]
Looks fine and dandy to me. I assume nginx will worry about directing say `/api` requests to the appropriate place and everything else to the app?

**Comment by edpaget** [comment]
Yes I just finished https://github.com/zooniverse/static/pull/14 once that's merged we should be set to merge this.

**Comment by edpaget** [comment]
@chrissnyder the nginx changes have been made, so this should be good to go whenever @astopy says its deployed.

**Comment by astopy** [comment]
The nginx changes are live now.

**Comment by chrissnyder** [comment]
I get `ERR_TOO_MANY_REDIRECTS` error in Chrome trying some URLs. Caching or someting else?

**Comment by astopy** [comment]
Which URLs?

**Comment by chrissnyder** [comment]
/about -> ERR_TOO_MANY_REDIRECTS
/accounts/settings -> /settings (but no page exists at this route, so it just goes to the homepage)
/lab -> ERR_TOO_MANY_REDIRECTS
/contact -> /about -> ERR_TOO_MANY_REDIRECTS

Pretty much any of them.

**Comment by astopy** [comment]
Seeing the home page is to be expected until this is deployed.

The others will be fixed shortly.

**Comment by astopy** [comment]
The redirect issue isn't related to this PR, so no need to delay merging/deploying this.

**Comment by astopy** [comment]
Actually, on second though *do* wait to deploy this.

**Comment by chrissnyder** [comment]
This sort of breaks demo.zooniverse.org/panoptes-front-end as everything is an absolute URL. Don't know how much we care about that, considering how often we use it. Branch deploys are super useful though.

**Comment by astopy** [comment]
Redirects are fixed now (pending CloudFront cache invalidation).

**Pull request merged**
