### PR TITLE
Updated styling for resource cards

### PR DESCRIPTION
**Pull request by srallen**
- Made project card avatars square for #728
- Added descriptions and removed owners for #662 
- Updated button styling for #688 
- Styled pagination buttons for #703

### CODE REVIEW

**Comment by alexbfree** [comment]
Yay :-) Nice one @srallen !

**Comment by edpaget** [comment]
We should consider keeping the owner name in the box. Projects are only unique per owner. While not a big deal as long as we're approving projects. It's totally possible for there to be a 'Galaxy Zoo' by Random Person and a 'Galaxy Zoo' by 'The Galaxy Zoo Team' and a 'Galaxy Zoo' by 'Zooniverse'.

**Comment by DarrenMcRoy** [comment]
Again, my concern is that we do not want to create a delineation between "projects created in-house" and "projects created by users," especially not one that makes in-house projects look more valid than project-builder projects. The two should be as indistinguishable as possible on the projects page.

The only projects that will appear here are ones that have been approved for launch, so there's no need to worry about two having the same name.

Additionally, we've been worried about the cards getting too tall; removing one line helps at least a little with that.

We could discuss again later, but I think that the information in that box should be just what a user needs to make a decision whether or not they are interested in that project, and the username of the creator shouldn't influence that.

**Comment by edpaget** [comment]
I'd argue who produced a project is a pretty important piece of information to have when deciding whether to participate in a project, but again, as long we're approving them it doesn't matter for now.

**Pull request merged**
