### PR TITLE
Update featured project to Seabird Watch for AutumnWatch

### PR DESCRIPTION
**Pull request by srallen**
This updates the featured project to Seabird Watch. 

Can any one who has experience with the Thumbnail component tell me why this is erroring with a 415? The previous src used `www.zooniverse.org` in the src URL, but I can't get the image to load at all using that. 

https://update-featured-project-autumnwatch.pfe-preview.zooniverse.org/

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] Did you deploy a staging branch?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

## Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
The Thumbnail component expects an S3 path, I think. There's a discussion on #3998.

**Comment by srallen** [comment]
@eatyourgreens so, if I use the S3 bucket, it'll be broken locally at first, but would work after it deploys to production? I already manually resized and compressed the image, so it's it doesn't really need the thumbnail service at the moment.

**Comment by eatyourgreens** [comment]
This was a safeguard against large static assets tha had been uploaded previously. Feel free to switch it back to using an `img` tag.

**Comment by beckyrother** [comment]
Looks good to me!

**Comment by srallen** [comment]
Noting that the travis build errored because I merged and deleted the branch before it finished. I'm trying to get the deploy out before the AutumnWatch air time.

**Pull request merged**
