### PR TITLE
Fix freehand line static methods and tests

### PR DESCRIPTION
**Pull request by eatyourgreens**
Updates the generic drawing tool tests to expect initMove to return an object.
Applies changes to the mock mark before rendering the tool component.
Fixes the freehand line tools to conform with the behaviour expected by the marking initialiser in the drawing task.

Staging branch URL: https://test-drawing-tools.pfe-preview.zooniverse.org/

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by wgranger** [comment]
LGTM. Thanks for these changes.

**Comment by eatyourgreens** [comment]
@wgranger it just occurred to me that these expectations will never fail, because `initialMark` and `mark` are always different copies of the same object. Maybe they should be deleted too?
`expect(initialMark).to.not.equal(mark);`

**Comment by wgranger** [comment]
Ah! Of course. I suppose in this case the best we can do is check that mark is an object, unless there's a way to check for deep vs shallow equality with the exception library.

**Comment by eatyourgreens** [comment]
I think you can `expect(a).to.not.deep.equal(b)` with chai. It's pretty powerful.
https://www.chaijs.com/api/bdd/

**Comment by eatyourgreens** [comment]
In that case, I think the drawing tools API expects you to do something like:
`const mark = Object.assign({}, initialMark, TaskComponent.initStart(props, mark))`
in order to get the new mark from the initial mark.

Returning a new mark from those static methods is something to consider if we rewrite that drawing tools API in PFE. It might just end up getting thrown out for the new classifier, though.

**Pull request merged**
