### PR TITLE
Subject discussion list

### PR DESCRIPTION
**Pull request by parrish**
Depends on #1855 (merge that one first).

I'm also not attempting to paginate the subject discussion list.  Aside from having to dance around multiple page query params, I doubt we really care about anything but the 20 most recent discussions about a subject.  Happy to change later on if that becomes an issue.

### CODE REVIEW

**Comment by DarrenMcRoy** [comment]
I'll keep an eye on if the 20-discussion display limit becomes an issue, but that should be plenty for 99.9% of cases.

**Comment by aweiksnar** [comment]
Looks solid, can you rebase to master and then I'll merge

**Comment by parrish** [comment]
Updated

**Comment by aweiksnar** [comment]
:shipit:

**Pull request merged**
