### PR TITLE
Policies page edits

### PR DESCRIPTION
**Pull request by hrspiers**
Hi,

I've given this page a heavy edit, and have included a note on policy review timelines to address PFE issue #3303.

One thought to improve things further - it may be worth splitting this page into two pages "How to Launch your Project" and "Policies". I'm not sure how to do this yet, but if others think this is a good idea I'm happy to give it a go...

H

### CODE REVIEW

**Comment by mschwamb** [comment]
I think that info should stay together on one page.  It makes it easier for a project owner and really the process and the requirements go hand in hand, so for me as a project owner it's easier for me that I know there's one page I need to go to that succinctly has all this info.

I found the first sentence confusing: ' This page is for people who have used our Project Builder, and would now like to share their project' share it with who? 

' It takes approximately six weeks to receive project feedback after applying for review.'  - is that for the Zooniverse team to get back to you with their review before beta or is this the full time from hitting the button to then being able to move on to the next phase (applying for full launch)?

I think this paragraph you  deleted is really important and should be in there:

  _During the review phase, you should be checking for suggestions and comments on the project's Talk discussion pages in addition to reviewing the formal feedback from the volunteer project testers that will be provided by the Zooniverse team. Technical issues can be reported to us via [the GitHub repository](https://github.com/zooniverse/Panoptes-Front-End), but you will need to consider carefully comments on workflow design. Remember to look at the results produced during this review phase too - are they of sufficient quality for your research? If not, then a redesign or a rethink is in order; go back, make changes to your project and then submit it for review once again.__

Above actually gives useful advice for things to consider and what things a researcher should be looking at in review and insight into what things the Zooniverse is taking into account This is the only page that contained this info and I think it's important it be here. It was very useful  when I read this page the first time I did as I knew what was in Zooniverse core team's head for review. I'd strongly suggest keeping that in. 

' It is important you analyze the results produced during this review phase to ensure they are of sufficient quality for your research. If they aren’t, please consider re-approaching your project design, make any changes, and submit for review again.'  To me that says very strongly a research team needs to fully reduce their classifications with 'analyze' . Maybe there's a different word choice to use instead?

I think it would be helpful to add in the average duration of a beta test?


>  This review process can take a variable amount of time, from weeks to months.
I didn't find that description helpful. What's the average amount of time it takes?  I'd add a sentence to say after that what's the average amount otherwise this might scare off some researches. 

I'd suggest moving up part ' By using the Zooniverse Project Builder, you are using our software and hosting... ' bit as it applies to all project owners and by putting the details of Zooniverse approved projects first I might as a reader stop reading as it seems like the policies are meant from only Zooniverse approved. So I'd move this bit up front to the top of that section so it's easily visible

I liked 'put in the effort to turn them into a formal publication.' that you edited out because a lot of people don't realize how much work it takes to from clicks to a science paper, and that emphasized the amount of time and effort this process takes

You took out '  We're keen to find out how people want to use our platform, and at present it’s free to use.', but there's now where that explicitly states that. So I'd add that in somewhere that the project builder is free to use somewhere in the text.

**Comment by hrspiers** [comment]
Hi Meg,

Thanks for your feedback. 

How are you viewing the changes? - it seems there must have been a crossed line some where as a lot of the paragraphs you suggest keeping are still in there.

I'll take the other bits into account though...

Many thanks,
Helen

**Comment by mschwamb** [comment]
@hrspiers I used the link on top for files edited and clicked on view. that takes me to [here](https://github.com/hrspiers/Panoptes-Front-End/blob/2c61cdc09329f8357069a372e4fdc9af13e7ed25/app/pages/lab/help/lab-policies.cjsx). 

I see where you've got 

> During the review phase, you should be checking for suggestions and comments on the project's Talk discussion pages in addition to reviewing the formal feedback from the volunteer project testers that will be provided by the Zooniverse team. Technical issues can be reported to us via the GitHub repository, but you will need to consider carefully comments on workflow design. Remember to look at the results produced during this review phase too - are they of sufficient quality for your research? If not, then a redesign or a rethink is in order; go back, make changes to your project and then submit it for review once again.

in now. Must have missed it while reading it. Sorry about that.

**Comment by hrspiers** [comment]
nw, just addressing the other bits now - thanks for your thoughts!

**Comment by hrspiers** [comment]
Hi Meg,

I think the only comment I've not addressed is this one - 

"This review process can take a variable amount of time, from weeks to months.
I didn't find that description helpful. What's the average amount of time it takes? I'd add a sentence to say after that what's the average amount otherwise this might scare off some researches."

From speaking to Grant, we can't be any more specific about this at the moment.

H

**Comment by hrspiers** [comment]
@parrish are you able to review the changes before I merge?

Thanks!
Helen

**Comment by parrish** [comment]
Sure.  I'll check it out.

**Comment by parrish** [comment]
Looks good

**Comment by hrspiers** [comment]
Thanks!

**Comment by mschwamb** [comment]
@hrspiers thanks for those updates. Looks great.

**Pull request merged**
