### PR TITLE
Add security page

### PR DESCRIPTION
**Pull request by astopy**
cc @zooniverse/developers @zooniverse/team-zooniverse Any final comments/suggestions for this?

### CODE REVIEW

**Comment by rogerhutchings** [comment]
Worth linking to the Zooniverse health page in the footer as well?

**Comment by astopy** [comment]
Health page?

**Comment by rogerhutchings** [comment]
The one with the Zooniverse status and whatnot? Can't remember the url offhand

**Comment by astopy** [comment]
That's already on there :)

**Comment by rogerhutchings** [comment]
derp. Then naa, looks good!

**Comment by brian-c** [comment]
Looks good to me.

**Comment by brian-c** [comment]
Well since there are no objections...! Thanks @astopy.

**Pull request merged**
