### PR TITLE
New api root

### PR DESCRIPTION
**Pull request by brian-c**
Changes the API subdomain and the page from which to scrape the CSRF token.

Up at https://www.zooniverse.org/temp for now.

### CODE REVIEW

**Comment by astopy** [comment]
@brian-c I get "Failed to get auth token" in the console when I try to sign out.

**Comment by edpaget** [comment]
I am unable to get any avatar images (the responses are empty when my browser requests them) on Firefox and Chrome on Arch Linux.

**Comment by frankvitaleiv** [comment]
On the publication page, I am seeing the first publication for each project on the same line as the project name when my browser screen is not as wide as the descriptions are long.  

screen shot 2015-08-03 at 15 25 03
screen shot 2015-08-03 at 15 25 10

**Comment by astopy** [comment]
@frankvitaleiv That's actually a problem with the live version of the site, not specific to this version. Could you open a new issue for that?

**Comment by brian-c** [comment]
@astopy @edpaget I can't reproduce either of these issues. You're sure you're on https://www.zooniverse.org/temp/? Any weird browser settings?

**Comment by astopy** [comment]
I'm concerned that both of those might be due to CloudFront caching, even though it shouldn't be caching those requests as far as I can see. I'll try and investigate further.

**Comment by frankvitaleiv** [comment]
@astopy sure, no problem

**Comment by edpaget** [comment]
@brian-c @adam I can confirm it's happening on the zooniverse.org/#/temp page. I have a bunch of extensions installed on Firefox, but Chrome is entirely stock. In my network tab, I see requests to https://panoptes-uploads.zooniverse.org/..., but with no responses.

**Comment by camallen** [comment]
@edpaget change the URL to https://www.zooniverse.org/temp/#/ ?

**Comment by edpaget** [comment]
@camallen I was already on that I'm fairly sure (zooniverse.org is redirected to www. right?), but all of sudden everything is working.

**Comment by camallen** [comment]
Cool - i couldn't reproduce the avatar issue you were seeing but glad it's working now.

**Comment by astopy** [comment]
The auth token issue on sign out appears to be specific to safari... can anyone test it in that?

**Comment by eatyourgreens** [comment]
@astopy I can reproduce that auth token issue in Safari 7.1.7

**Comment by brian-c** [comment]
I think this is because of the /users/sign_in to panoptes.zooniverse.org redirect when someone's already signed in.

Is there anywhere I can get a CSRF token from another domain that never redirects somewhere else?

**Comment by astopy** [comment]
Would it make sense to just add a dedicated /csrf route to to panoptes, rather than relying scraping the HTML?

**Comment by brian-c** [comment]
That would be sweet.

**Comment by edpaget** [comment]
Also I figured out why I couldn't see avatar when testing this. I had redirected panoptes-uploads.zooniverse.org to 127.0.0.1 in my /etc/hosts file to test something out.

**Comment by astopy** [comment]
OK, I think this is good to merge. Everyone happy with that?

**Comment by brian-c** [comment]
Fine by me.

**Pull request merged**
