### PR TITLE
[DO NOT MERGE] Expose translator role

### LINKED ISSUE #3884: Expose translator role under the lab "Collaborators" section
This would be helpful for project owners to allow translations

### PR DESCRIPTION
**Pull request by simoneduca**
Fixes #3884 .
Describe your changes.
Adds "translator" to the list of project roles.

However this role isn't supported in Talk-api https://github.com/zooniverse/Talk-Api/blob/d9917117fb6497a47170d59fd41817d39087a72f/spec/factories/roles.rb#L7
and if you try to add a translator you'll see this
screen shot 2017-06-23 at 13 36 18

I've opened an issue https://github.com/zooniverse/Talk-Api/issues/118 and plan to fix it shortly.
Till then, please do not merge this.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://add-translator-role.pfe-preview.zooniverse.org/?env=production
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

### CODE REVIEW

**Comment by camallen** [comment]
@simoneduca i don't think you need to add that role to talk api, maybe it does but I think this role is just the panotpes api specific. See [here](https://github.com/zooniverse/Panoptes-Front-End/blob/5612ccb170dde2923c7f183380e90ec5013c7d21/app/pages/lab/collaborators.cjsx#L108) you could just filter out this specific role for talk roles instead of forcing them in.

**Comment by simoneduca** [comment]
@camallen I thought of filtering that out and I quite like it. However perhaps translators would like to see their effort acknowledged with a role under their username, no?

**Comment by camallen** [comment]
i guess that makes sense, i assume it's project specific then.

**Comment by simoneduca** [comment]
I assumed so, because it is so in Panoptes. I will check.

**Comment by simoneduca** [comment]
@camallen actually I'm not sure how to check if a role is project-specific. Thoughts?

**Comment by simoneduca** [comment]
I guess that `git rebase master` didn't go to plan. Pesky ancient branch. I'll issue another PR on a fresh branch.

**Pull request closed without merging**
