### PR TITLE
Get project avatars.

### LINKED ISSUE #439: Project cards lost their avatars
@srallen mind fixing this? I should have caught this in review, sorry.

### PR DESCRIPTION
**Pull request by srallen**
- Refactored project card component to get project avatars
- Fixed #439

### CODE REVIEW

**Comment by brian-c** [comment]
Avatar aspect ratios were off for me, that commit fixed it.

@heathv avatars are not square in these cards. Is this intentional?

**Comment by srallen** [comment]
@heathv is out today and Monday. Here's [the design](http://adobe.ly/1FktURG) for reference. They're not square.

**Comment by brian-c** [comment]
Gotcha. That aspect ratio change work for you? Looks good to me otherwise.

**Comment by srallen** [comment]
Yeah, that's better. Thanks.

**Pull request merged**
