### PR TITLE
Sanitise SVG file uploads

### PR DESCRIPTION
**Pull request by eatyourgreens**
Update the `putFile` helper to sanitise SVG files and remove unsafe tags, such as `script`.

Towards https://github.com/zooniverse/panoptes/security/advisories/GHSA-85fr-5pvp-fmjm

You can test this out by uploading an SVG file, containing malicious content, via any of the components that use `putFile`:
- project media uploads.
- project subject uploads.
- project avatars.
- user avatars.
- field guide icons.

Any scripts etc. in the original SVG should be stripped out before it is uploaded.

https://pr-6479.pfe-preview.zooniverse.org

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Review by lcjohnso — DISMISSED** [review]
Current sanitization added in this PR will remove animation from newly upload SVGs, braking new subject uploads for [Gaia Vari](https://www.zooniverse.org/projects/gaia-zooniverse/gaia-vari).

Examples
no sanitization: [Subject 86167985](https://panoptes-uploads.zooniverse.org/subject_location/76760201-68be-4659-b969-3b0c8aed771f.svg)
with sanitization: [Subject 86167792](https://panoptes-uploads.zooniverse.org/subject_location/9c66ccd6-285b-4659-a048-d680592cb830.svg)

Breaking change needs approval from @trouille (point of contact for Gaia Vari project team) before proceeding.

**Comment by eatyourgreens** [comment]
That's interesting. Do you know which tag it's stripping out of the SVG string? We can configure [DOMPurify](https://github.com/cure53/DOMPurify), which is very strict by default. At the moment, I'm applying the defaults, which we also apply to project titles and descriptions.

**Comment by eatyourgreens** [comment]
`<animate>` and `<use>` are whitelisted now. The sanitiser only allows SVG and SVG filters. I think the only open question is which SVG attributes we should support.

These subjects would also fail a number of basic accessibility tests, but that is a separate issue.

**Comment by eatyourgreens** [comment]
I've set up a subject set with two Gaia Vari subjects: one sanitised, one unsanitised.
https://pr-6479.pfe-preview.zooniverse.org/lab/908/subject-sets/5086?env=staging

This workflow loads in that set, with just the two subjects.
https://pr-6479.pfe-preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify?reload=0&workflow=3743&env=staging

**Comment by eatyourgreens** [comment]
OK, this is now updated to allow [`<animate>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate), [`<use>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use) and interpolations other than `linear` with [`calcMode`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/calcMode).

**Pull request merged**
