### PR TITLE
Add subject viewer to feedback modal

### PR DESCRIPTION
**Pull request by mcbouslog**
Staging branch URL:

- demo with current PFE: https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/backyard-worlds-test-project-mb/classify?reload=0&workflow=3312
- demo with changes to PFE feedback: https://add-subject-viewer-feedback-modal.pfe-preview.zooniverse.org/projects/markb-panoptes/backyard-worlds-test-project-mb/classify?reload=0&workflow=3312

Uses SubjectViewer instead of FrameViewer in the feedback modal. Provides multi-image subject image buttons and other related controls. Hides Collection button, as I think issues with modal on top of modal, but allows favoriting, which might be handy if user wants to follow-up on why they got feedback right or wrong.

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [x] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
IIRC we removed the subject viewer from feedback because it allows you to move/edit drawn marks in the feedback popup for Space Warps. Have a look at #4535 in case you've accidentally regressed that bug here.

**Comment by eatyourgreens** [comment]
I think I'm missing something here. On the test project linked above, I'm not seeing any feedback when I press Done, and I'm not seeing a new subject load either.

**Comment by mcbouslog** [comment]
Sorry about that! It should be updated to public now.

I tried [the originally linked workflow](https://add-subject-viewer-feedback-modal.pfe-preview.zooniverse.org/projects/markb-panoptes/backyard-worlds-test-project-mb/classify?reload=0&workflow=3312) and [a TESS-like workflow](https://add-subject-viewer-feedback-modal.pfe-preview.zooniverse.org/projects/markb-panoptes/feedback-testing-mb/classify?reload=0&workflow=3292) and wasn't able to edit the markings, but I'm not sure if/how I can test the SpaceWarps case, it doesn't look like [the current project](https://www.zooniverse.org/projects/aprajita/space-warps-hsc) shows the subject. Maybe #4595 fixed that issue as it would apply to these changes as well?

**Comment by eatyourgreens** [comment]
looking back through the history, switching from the subject viewer to the frame viewer was a fix for #4509. This PR enables panning by dragging the image, but I don't know if that's a big deal.

**Comment by mcbouslog** [comment]
Yep this leaves the `subjectViewerProps` with `zoomControls: false` so as not to re-trigger #4509.

**Comment by wgranger** [comment]
This PR checks out for me. I agree, the only potential issue here is users being able to move the subject on the viewer. I don't think it's an issue since it doesn't affect the classification, but if necessary we can make a change later, probably similarly to how you added the `showCollect` prop here. 

Merging

**Pull request merged**
