### PR TITLE
Language: add Armenian to Translations

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview

Freshdesk ticket: https://zooniverse.freshdesk.com/a/tickets/20207
Staging branch URL: https://pr-7140.pfe-preview.zooniverse.org/lab/21445/translations?env=production

This PR adds Armenian to the list of languages you can publish on the Project Editor -> Translations tab. [(example)](https://www.zooniverse.org/lab/21445/translations)

- Currently, the list of languages that project teams can select on [Zooniverse Translations](https://translations.zooniverse.org/) isn't synced with the list of projects that can be published on the Project Editor -> Translations tab. (This appears to be an oversight where [languageMenu.js](https://github.com/zooniverse/Panoptes-Front-End/blob/2d0f81aa18b1ede650f7c1360ce108214754dbd8/app/constants/languageMenu.js) is kept separate from [languages.js](https://github.com/zooniverse/Panoptes-Front-End/blob/2d0f81aa18b1ede650f7c1360ce108214754dbd8/app/constants/languages.js))
- Affected project: [AtmosEleC - Atmospheric Electricity for Climate](https://www.zooniverse.org/projects/hripsi-19/atmoselec-atmospheric-electricity-for-climate) 

### Status

Ready for review.

Short term: a quick review is requested as this affects a live project, and the change should be small enough to quickly verify.

Long term: a future improvement to syncing the language lists would be ideal.

### CODE REVIEW

**Comment by shaunanoordin** [comment]
## Additional Context

The problem: in the screenshot below, the option to publish Armenian isn't available.

image

The intended solution:

image

**Review by mcbouslog — DISMISSED** [review]
LGTM!

**Comment by lcjohnso** [comment]
@shaunanoordin  Please do not merge -- enabling a new language/locale option also requires creation of a new locale file with translated content (e.g., see https://github.com/zooniverse/Panoptes-Front-End/pull/7122 for Bengali). This PR would only add the language dropdown option but without a locale file all the platform-level content will appear in English and create a poor user experience.  I've followed up in Slack re: next steps.

**Comment by mcbouslog** [comment]
Thanks for noting @lcjohnso ! I'll dismiss my review and re-review when the additional changes, similar to #7122 , are added.

**Comment by shaunanoordin** [comment]
We now have Armenian translations, with all thanks going to our wonderful volunteer: https://zooniverse.freshdesk.com/a/tickets/20207

I'll make it a point to get `app/locales/hy.js` added to this PR as soon as I can.

Follow up on Slack: https://zooniverse.slack.com/archives/C06LHUC6R/p1720732272389049

**Review by goplayoutside3 — APPROVED** [review]
Testing at https://pr-7140.pfe-preview.zooniverse.org/projects/hripsi-19/atmoselec-atmospheric-electricity-for-climate/classify 👍

**Pull request merged**
