### PR TITLE
Cleanup footer CSS

### PR DESCRIPTION
**Pull request by chrissnyder**

### CODE REVIEW

**Comment by aweiksnar** [comment]
Looks good :100: 
I had a responsive footer branch started but never PR'd it. Want to combine forces? Just opened  #1872 that would merge it into this branch

**Comment by chrissnyder** [comment]
Sounds like a plan to me.

**Comment by aweiksnar** [comment]
Cool thanks! 
And I think you mean SLAP  :sunglasses:

**Comment by chrissnyder** [comment]
SLAP :hand:

**Pull request merged**
