### PR TITLE
(WIP) Featured Project on Homepage - Stargazing Live March 2017 Edition

### LINKED ISSUE #3605: Add Featured Project section to home page
## Expected behavior
home-feature

Please shorten the height of the video by about 200px and add this section below it. It should use the existing stylesheet (if this mockup is slightly off, please just use the stylesheet rather than matching the mockup exactly).  

The button should point to Planet Nine for the first week and the exoplanet project (with updated copy) for the second week. 

Happy to provide the Illustrator file if it would be beneficial.

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview
* Closes #3605 , tagging @beckyrother 
* Adds a new "Featured Project" section to the Home Page
* View online at: https://new-homepage-2017-mar.pfe-preview.zooniverse.org/
* **NOTE:** Currently the featured project (and all text, links, images) have to be hardcoded into the PR. We do NOT appear to have a mechanism for managing this via the backend controls yet, AFAIK.
* **NOTE:** This only appears on the Not-Logged-In Home Page. I can spin this off into a shared component between both Logged-In and Not-Logged-In version if design decides to go this way. (My opinion: absolutely)

screen shot 2017-03-16 at 15 26 48
_Desktop view_

screen shot 2017-03-16 at 15 27 09
_Mobile view_

## Status
DO NOT MERGE, this is only at the mockup stage. Those aren't astronomy pictures we're looking at, after all.

## Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

### CODE REVIEW

**Comment by astopy** [comment]
Just noting that the ABC project won't be searching for Planet 9.

**Comment by shaunanoordin** [comment]
Dammit man then how are we going to know which penguin is hiding planet 9

**Comment by beckyrother** [comment]
@shaunanoordin 
Here's the copy for the first week, from Grant:
The Zooniverse has teamed up with BBC Stargazing Live and the SkyMapper Telescope team to bring you Planet 9. Join us in our quest to discover our Solar System's elusive 9th planet!

Second week:
The Zooniverse has teamed up with ABC Stargazing Live and astronomers at UC Santa Cruz to bring you Exoplanet Explorers. Join us in our quest to discover planets around distant stars in our Milky Way galaxy!

I'll upload photos here soon!

**Comment by beckyrother** [comment]
### Here's photos 
**Reference layout:**
home-planet_nine

Both photos at @2x for retina screens
**Week One**
sgl-planet_nine

**Week Two**
home-exoplanets-img

**Comment by shaunanoordin** [comment]
## PR Update
* Text, link and image have been updated. Check it out at https://new-homepage-2017-mar.pfe-preview.zooniverse.org/
* @beckyrother let me know if you have any comments on the design implementation.
* Ready to roll any time! @mrniaboc , just give the signal.

**Comment by beckyrother** [comment]
@shaunanoordin looks great! just a couple copy changes:
• change "FEATURED PROJECTS" to "FEATURED PROJECT"
• can we link "BBC Stargazing Live" to http://www.bbc.co.uk/programmes/b019h4g8
• please make sure we're spelling out 9 or using a numeral – looks like change the button to say Planet 9

Other than that looks good!

**Comment by shaunanoordin** [comment]
@beckyrother Updates made!

screen shot 2017-03-28 at 15 31 00

**Comment by beckyrother** [comment]
@shaunanoordin Please update the photo with the one from above for week 2. @mrniaboc, can you please add new copy for the ABC broadcast here? 
Thanks all!

**Pull request merged**
