### PR TITLE
Volunteering Page

### PR DESCRIPTION
**Pull request by BNewing**
Page to describe the Zooniverse volunteering roles a bit more explicitly.

### CODE REVIEW

**Comment by BNewing** [comment]
Thank you for the feedback @mschwamb!

**Comment by BNewing** [comment]
I spoke to Grant and got some feedback from him regarding the content. I've added those changes in with the last commit.

**Comment by BNewing** [comment]
Did the rebase! @srallen

**Comment by BNewing** [comment]
Removed the space @srallen ! Will it need another rebase or is it okay to be merged? (I've still got the github fear a little bit and feel a bit anxious about merging stuff still!)

**Comment by srallen** [comment]
@BNewing it looks great. No additional rebases needed.

**Pull request merged**
