### PR TITLE
Updated to node 8 and npm 5. Added lock file

### PR DESCRIPTION
**Pull request by srallen**
Updates to node 8 and npm 5. Includes new package-lock.json file 💯 

Compiles, builds, and got a staging deploy up: https://update-node-version.pfe-preview.zooniverse.org/

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Runs fine for me too. [Travis is complaining](https://travis-ci.org/zooniverse/Panoptes-Front-End/builds/239696718#L152) about one of the markdown modules but tests are also running fine locally.

**Comment by eatyourgreens** [comment]
I think Markdownz is using @edpaget's [fork of markdown-it-imsize](/edpaget/markdown-it-imsize), so that Travis failure is probably github being down yesterday.

Do we still need that version now that we're using webpack?

**Comment by srallen** [comment]
Travis failed again to install `markdown-it-imsize` today. I'll hold off merging since we shouldn't break travis with this. I'll look into that markdown dependency later in the week.

**Comment by srallen** [comment]
Travis is working now with the updated markdownz version.

**Comment by srallen** [comment]
@eatyourgreens as soon as tests are done, this should be ready for review again. I've rebased and resolved the merge conflict with the package.json file.

**Pull request merged**
