### PR TITLE
Convert CharLimit to stateless component

### PR DESCRIPTION
**Pull request by rogerhutchings**
Turns the dead simple CharLimit component into a React 0.14-style stateless component.

Discussed further on zooniverse/rfc#5

### CODE REVIEW

**Comment by rogerhutchings** [comment]
ref zooniverse/rfc#5

**Comment by eatyourgreens** [comment]
Looks good to me.

**Comment by eatyourgreens** [comment]
ESLint complains about a few things though.
```
❌ at line 7 position 8:  There should be no space after '{' (react/jsx-curly-spacing)
❌ at line 7 position 20:  There should be no space before '}' (react/jsx-curly-spacing)
❌ at line 7 position 25:  There should be no space after '{' (react/jsx-curly-spacing)
❌ at line 7 position 33:  There should be no space before '}' (react/jsx-curly-spacing)
❌ at line 10 position 3:  Missing semicolon. (semi)
```

**Comment by rogerhutchings** [comment]
Is ESLint not run by webpack? The more you know...

**Comment by eatyourgreens** [comment]
I've got it set up to run when I save in the editor.

**Comment by eatyourgreens** [comment]
:+1: from ESLint

**Pull request merged**
