### PR TITLE
Use frame viewer to display drawing feedback

### LINKED ISSUE #4509: Feedback: Remove pan&zoom buttons for subject viewer in feedback
## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Hi @rogerhutchings @eatyourgreens @trouille 
One more question from #4320: if we do want to enable the subject viewer in the feedback, is it possible to resolve the issues with the pan & zoom buttons appearing on the line below? i.e. Can the subject panels be shown without the buttons so there aren't the extra grey lines? Thanks

If this can't be resolved we will run without the subject viewer (which is totally fine so don't worry about this if you are short of time, just thought it might be of use to other projects)

image

thanks
aprajita.

## Steps to replicate
View any training image with subject viewer enabled.

## Additional information

- **Operating system:**
- **Browser:**

### PR DESCRIPTION
**Pull request by eatyourgreens**
Use the frame viewer component to display feedback for drawing tasks. Always use the first subject frame to show feedback.

Staging branch URL: https://feedback-subject-viewer.pfe-preview.zooniverse.org

Fixes #4509

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by rogerhutchings** [comment]
Looks good to me. I noticed you can edit annotations inside the feedback modal, but this doesn't affect the actual annotations submitted on completion, so I'm happy to just issue that and merge this.

**Comment by aprajita** [comment]
Hi @eatyourgreens thanks for letting me know about this & sorry I missed it.  I think when I got a github notification for this I did see that the number of frames became a single one, but also saw the pan&zoom buttons are still plotted below the image, so thought this was sill in progress. Here's a screen grab from today.

image

is this what I should expect or can it be shown without the buttons underneath (even if they were on the side would be fine)?

many thanks
Aprajita.

**Comment by eatyourgreens** [comment]
That’s weird. This PR turned off the zoom buttons.

**Comment by eatyourgreens** [comment]
@aprajita I missed a setting in the code. See #4582.

**Comment by aprajita** [comment]
thanks @eatyourgreens

**Pull request merged**
