### PR TITLE
Add 2022 Into the Zooniverse Vol. 4 to Highlights page

### PR DESCRIPTION
**Pull request by mcbouslog**
Staging branch URL: https://pr-6267.pfe-preview.zooniverse.org/about/highlights

Describe your changes.
- adds Into the Zooniverse Vol. 4 to highlights page
- reduce 2021 image size

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by seanmiller26** [comment]
The links function properly. Everything looks good.

I noticed the 2021 image fidelity has decreased, and the 2022 one is a bit blurry too. Would you like a new jpg or png with a reduced file size? If so, whats the ideal size?

**Comment by trouille** [comment]
Looks good to me! Links worked. Language is good (only change this year is the addition of the Volume 4 and its associated links). And see comments in[ this doc ](https://docs.google.com/document/d/14HaF8p1EX8jFSH9Tz5o4KEDlHq03LoqWRWuvEvhuKao/edit)about how there's no Translations effort for this. Thanks all!

**Comment by mcbouslog** [comment]
The max width for the cover images is 300px (per [this css styling](https://github.com/zooniverse/Panoptes-Front-End/blob/master/css/highlights-page.styl#L10-L11)). I think a file size less than around 250KB is reasonable, but there's no hard cut-off. I adjusted the images up a little more, let me know what you think.

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Affects: About > Highlights Book page

This PR is a basic content update, adding details for the 2022 Into The Zooniverse book.

- Content (image + alt text) for the 2022 book looks fine when [previewed.](https://pr-6267.pfe-preview.zooniverse.org/about/highlights) 
- Links to _Download_ and to _Purchase_ the 2022 book work fine.
- Additional checks: the above checks also pass for the 2019, 2020, and 2021 books as well.

LGTM 👍 If Laura & Sean both gave this a thumbs up, then this is ready to go.

**Review by seanmiller26 — APPROVED** [review]

**Pull request merged**
