### PR TITLE
fix line spacing issue on publications page, and add some missing links to the sitemap

### PR DESCRIPTION
**Pull request by alexbfree**
i noticed the line spacing is messed up on the publications page. this should fix it.

### CODE REVIEW

**Comment by chrissnyder** [comment]
Could the history be cleaned up? Would like to not have rebase commits in master.

**Comment by alexbfree** [comment]
@chrissnyder I didn't do any rebase commits. Just merged latest from main repo to my master, and merged from my master to my branch. is that not the correct procedure when working on a branch on a forked repo?

**Comment by alexbfree** [comment]
Ps, there is a secondary fix I added here, to add some missing links to the sitemap.. 
screenshot

**Comment by edpaget** [comment]
@alexbfree I generally prefer to rebase from the master branch, since commits like `merge branch 'master'` just clutter the history. You can always squash unneeded commits with `git rebase -i`

**Pull request closed without merging**
