### PR TITLE
Add Helen to bio and fix twitter links

### PR DESCRIPTION
**Pull request by hrspiers**
Fixes # .

Describe your changes.
Added biography for Helen. Fixed twitter links for Beverley and Jordan, removed Julie's twitter. 

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] Did you deploy a staging branch?

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?

### CODE REVIEW

**Comment by hrspiers** [comment]
@srallen could merge this please. Thanks!

**Comment by marten** [comment]
@hrspiers approval means you can click the green "merge" button here on github, and that will then deploy it to the site!

**Comment by marten** [comment]
And well done on your first PR! 👍

**Comment by hrspiers** [comment]
Thanks @marten - maybe being an idiot but I can't see the merge button...where does it live? Thanks!

**Comment by marten** [comment]
@hrspiers Ah, small permissions issue. There should be one near the bottom of the page now. :)

**Comment by hrspiers** [comment]
yeeeeeeeyyyyyyyy big moment for me! Thanks @marten!

**Pull request merged**
