### PR TITLE
Revert "Workflow visualization updated to react 14"

### PR DESCRIPTION
**Pull request by brian-c**
Reverts zooniverse/Panoptes-Front-End#2032

Deploy issues again. @astopy?

### CODE REVIEW

**Comment by astopy** [comment]
Looks like it. You should probably have the build/deploy scripts abort if something goes wrong, rather than just blindly continuing.

```
'build/main.js' -> 'build/main.76519fe79eae075bd803f693b2ba6995.js'
/src/node_modules/stylus/bin/stylus:662
              throw err;
                    ^
Error: css/workflow-visualizer.styl:1:9
   1| @import "jsPlumb"
--------------^
   2| @import "react-resizable"
   3| 
   4| .answer-item

failed to locate @import file jsPlumb.styl

    at Evaluator.visitImport (/src/node_modules/stylus/lib/visitor/evaluator.js:901:21)
    at Evaluator.Visitor.visit (/src/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/src/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitBlock (/src/node_modules/stylus/lib/visitor/evaluator.js:706:39)
    at Evaluator.Visitor.visit (/src/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/src/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.importFile (/src/node_modules/stylus/lib/visitor/evaluator.js:95:18)
    at Evaluator.visitImport (/src/node_modules/stylus/lib/visitor/evaluator.js:906:27)
    at Evaluator.Visitor.visit (/src/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/src/node_modules/stylus/lib/visitor/evaluator.js:156:18)
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'build/main.css'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.<anonymous> (/src/node_modules/csso/lib/csso.js:29:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
md5sum: build/main.css: No such file or directory
mv: cannot stat 'build/main.css': No such file or directory

vendor.64a378ced7fcb0b52c6bdd04e82b9c1e.js: 176266 bytes gzipped
main.76519fe79eae075bd803f693b2ba6995.js: 296283 bytes gzipped
cat: build/main..css: No such file or directory
main..css: 20 bytes gzipped
Local: ./build
Bucket: zooniverse-static
Prefix: www.zooniverse.org 
Adding 3, replacing 1, skipping 71... 
[90m1/4 [39m[32m+[39m jsPlumb.min.js 
[90m2/4 [39m[32m+[39m main.76519fe79eae075bd803f693b2ba6995.js 
[90m3/4 [39m[32m+[39m vendor.64a378ced7fcb0b52c6bdd04e82b9c1e.js 
[90m4/4 [39m[33m∆[39m index.html 
[32mFinished in 13.087 seconds[39m 
```

**Comment by CKrawczyk** [comment]
@astopy is this something that needs to be fixed in my PR, or is this an issue in the deploy process?

**Comment by astopy** [comment]
@CKrawczyk I think the problem is that css/jsplumb.styl should be called css/jsPlumb.styl.

**Comment by CKrawczyk** [comment]
Your right, now I am wondering how it even worked locally...

**Comment by astopy** [comment]
OS X’s filesystem isn’t case sensitive by default, so this kind of thing is easy to miss.

**Comment by CKrawczyk** [comment]
OK, fixed my branch, do I need to make a new PR since the original was already merged and then reverted?

**Comment by astopy** [comment]
Yeah, I don’t see an option to re-open the original PR so I think you’ll need to make a new one.

**Comment by CKrawczyk** [comment]
Hmm, that is odd.  I am only getting changes since the merge, none of the original commits are in the PR.

**Comment by astopy** [comment]
Hmm. I suspect you may need to revert @brian-c's commit (ea16f2575f65d2603b0aed16a303605337c3cda0) as part of the new PR.

Running `git revert ea16f2575f65d2603b0aed16a303605337c3cda0` should do it.

**Pull request merged**
