### PR TITLE
Add workflow image layout to project admin form

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add an image layout section to the workflow settings on the project admin page, with a checkbox for the no-max-height setting.

Staging branch URL: https://no-max-height.pfe-preview.zooniverse.org

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I think it was originally added for Notes from Nature. It overrides the height restriction that's normally applied to  subjects. Here's an example of a project that uses it.
https://www.zooniverse.org/projects/tkotwim/the-american-soldier/classify

**Comment by beckyrother** [comment]
This is great for now but will it be possible to fix the task/tutorial section so that volunteers don't need to scroll up and down so often? I'm going to open another issue for this.

**Comment by eatyourgreens** [comment]
@beckyrother This just allows people to manage project workflow settings without having to use the Python command line tools to update the workflow config. I'm assuming layout changes will happen in the new classifier, rather than PFE?

**Comment by wgranger** [comment]
Alright, I can see the use case for this now. It is awkward that users can't conveniently turn this on themselves using the site. 

I'm just seeing one bug with the toggle button. Currently, I am able to toggle a workflow on or off for no-max height. However, if I refresh the page, there are issues toggling the button a second time. The second time around, the button.checked doesn't update instantly upon toggle.

**Comment by eatyourgreens** [comment]
That's weird. Are there any errors in the console?

**Comment by eatyourgreens** [comment]
I think this is me not understanding controlled vs. uncontrolled components in React.

**Comment by eatyourgreens** [comment]
@wgranger the latest commit should fix that.

**Comment by wgranger** [comment]
That'll do it. LGTM

**Pull request merged**
