### PR TITLE
Subject default discussion thumbnail previews

### LINKED ISSUE #1166: Request for thumbnails in Talk next to discussions on 'Notes' board
Can we have thumbnails in Talk on the Notes board, so we can preview the images that people are discussing?

### PR DESCRIPTION
**Pull request by aweiksnar**
- Closes #1166
- For subject_default discussions

### CODE REVIEW

**Comment by edpaget** [comment]
So this looks fine on the note page to me, but at the moment I'm unable to post a discussion with a focus on a non-Notes board to test it out there.

**Comment by DarrenMcRoy** [comment]
Ooh, are thumbnails going to appear on non-Notes boards as well when the initial discussion has a featured image?

**Comment by aweiksnar** [comment]
I'll work on an update to make this also work for discussions where the first comment has a focus set and let you know when it's pushed

**Comment by edpaget** [comment]
@aweiksnar no biggie on that. I just wasn't able to create a focused discussion at all.

**Comment by aweiksnar** [comment]
Yeah, I just hit the same issue too. I can get a fix for that that in here since they're related

**Comment by edpaget** [comment]
Thanks :+1:

**Comment by aweiksnar** [comment]
Okay just pushed so you should be able to create discussions with a focus from anywhere, and also it'll now check if the first comment has a focus when rendering previews

**Comment by edpaget** [comment]
Now I'm getting a 401 not authorized when trying to create a discussion with a focus.

**Comment by aweiksnar** [comment]
Ah sorry, things are working for me locally, which form are you using so I can debug?

**Comment by edpaget** [comment]
I'm using the one at the top of the the board page.

**Comment by edpaget** [comment]
Huh, it just worked this time: 

screenshot from 2015-07-30 16-52-28

**Comment by DarrenMcRoy** [comment]
I assume this is you two?

screen shot 2015-07-30 at 4 55 52 pm

**Comment by edpaget** [comment]
Is that on production? If so no, why would debug on Production?

**Comment by edpaget** [comment]
I think it's michael deploying a new talk version

**Comment by DarrenMcRoy** [comment]
Yeah, never mind, it's back now. Was out for a few minutes.

**Pull request merged**
