### PR TITLE
Add experimental "anchored ellipse" tool

### PR DESCRIPTION
**Pull request by tlalka**
Adds the "anchored ellipse" tool, which is initialized to x: 256, y: 256, rx: 50, ry: 50, angle: 0 during the user's first click. The ellipse cannot be dragged away from this original x and y position. 
This tool is experimental, so experimental tools must be enabled on a project for it to use them

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by tlalka** [comment]
Alright, I added it to mock-data and rebased the branch. I've started rewriting it as JS in another branch, but I was wondering if this CoffeeScript version could be pulled so the rest of my team doesn't have to wait for me in-order to continue the research project?

**Comment by srallen** [comment]
@tlalka It looks like maybe the rebase didn't go quite cleanly (maybe there was a merge conflict?). I see a lot of unrelated updates in the diff. I'm going to try to cherry pick out the changes just for the new tool and make a new branch that you're welcome to fork if there are any more updates we'd like to request.

**Comment by srallen** [comment]
@tlalka what is the name of the project that this is for?

**Comment by tlalka** [comment]
"Spiral Graph"

**Comment by srallen** [comment]
Superseded by #4692

**Pull request closed without merging**
