### PR TITLE
minor grammar edits to volunteering page

### PR DESCRIPTION
**Pull request by mschwamb**
Describe your changes.

made a few grammar suggested edits to the volunteering page

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] Did you deploy a staging branch?

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?

### CODE REVIEW

**Comment by BNewing** [comment]
I noticed one more typo that I added in a commit to fix. Looks good to me!

**Comment by mschwamb** [comment]
@srallen since the travis CI checks failed, I wanted to double check it's okay to merge this.

**Comment by BNewing** [comment]
Ah - I've no idea what will have caused that. I've just had another look over it and double-checked I'd done npm install in case that was causing it but that didn't update anything. Sorry!

**Comment by marten** [comment]
Seems like it's been a weird Travis glitch, rather than an issue with the changes. LGTM.

**Pull request merged**
