### PR TITLE
Hide page links from redirectable projects

### PR DESCRIPTION
**Pull request by edpaget**
Closes zooniverse/wildcam-gorongosa#90

### CODE REVIEW

**Comment by aweiksnar** [comment]
Cool, Looks good to me. Are all the custom projects coming out using `/#/classify`?

**Comment by edpaget** [comment]
I'm not sure. I think most are (or could be modified to).

**Comment by aweiksnar** [comment]
Ok cool, I'll double-check the ones in production and then merge this in :shipit:

**Comment by aweiksnar** [comment]
Looks like old-weather and annotate will have different url schemas, but bats & gorongosa will be ok

**Comment by edpaget** [comment]
Cool I'll open an issue for those two to have `classify` redirect to thier classification page.

**Comment by aweiksnar** [comment]
Sweet. otherwise maybe this could read a classify-return-path from localstorage

**Pull request merged**
