### PR TITLE
Refactor external links section for organization redesign - 3

### PR DESCRIPTION
**Pull request by mcbouslog**
Staging branch URL: https://pr-5557.pfe-preview.zooniverse.org

Helpful links:
- staging testing project: https://pr-5557.pfe-preview.zooniverse.org/organizations/markb-panoptes/urban-wildlife-org-test
- Snapshot Serengeti: https://pr-5557.pfe-preview.zooniverse.org/organizations/meredithspalmer/snapshot-safari?env=production
- Notes from Nature: https://pr-5557.pfe-preview.zooniverse.org/organizations/md68135/notes-from-nature?env=production

Describe your changes.
- refactors ExternalLinks component in accordance with [InVision organization landing page redesign](https://projects.invisionapp.com/d/main/default/#/console/12924056/391430827/preview)

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [x] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [x] Does talk load correctly?
- [x] Can you post a talk comment?

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by mcbouslog** [comment]
Small edits, added tests. I think this is ready for review.

**Comment by mcbouslog** [comment]
Weird! I'm seeing the same behavior currently on https://www.zooniverse.org/organizations/meredithspalmer/snapshot-safari.

If in ExternalLinksBlock.jsx I add:
```
i::before {
  display: inline-block;
}
```
after the current icon styling it appears to consistently remove an underline, but feels a bit hacky.

**Comment by simensta** [comment]
> Weird! I'm seeing the same behavior currently on https://www.zooniverse.org/organizations/meredithspalmer/snapshot-safari.
> 
> If in ExternalLinksBlock.jsx I add:
> 
> ```
> i::before {
>   display: inline-block;
> }
> ```
> 
> after the current icon styling it appears to consistently remove an underline, but feels a bit hacky.

Since this is a styling issue in the main branch, how do you feel about creating an issue and addressing the inconsistency in a separate PR?

**Comment by mcbouslog** [comment]
> > Weird! I'm seeing the same behavior currently on https://www.zooniverse.org/organizations/meredithspalmer/snapshot-safari.
> > If in ExternalLinksBlock.jsx I add:
> > ```
> > i::before {
> >   display: inline-block;
> > }
> > ```
> > 
> > 
> > after the current icon styling it appears to consistently remove an underline, but feels a bit hacky.
> 
> Since this is a styling issue in the main branch, how do you feel about creating an issue and addressing the inconsistency in a separate PR?

Yes that's a good idea, will do.

**Pull request merged**
