### PR TITLE
Alteration of Header Size

### PR DESCRIPTION
**Pull request by BNewing**
Fixes # .

I've altered the size of the header, because there was a lot of space in it - @mschwamb raised an issue about it  - [#3156](https://github.com/zooniverse/Panoptes-Front-End/issues/3156)

I wasn't too sure what the min-height bit did, but shrinking it stopped having a visual effect on the header at 190px so that's what I've set it as in this PR. 
# Review Checklist
- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch? https://headerspace.pfe-preview.zooniverse.org/
## Optional
- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?

### CODE REVIEW

**Comment by camallen** [comment]
seems like the blue zooming background is affected by this change

**Comment by BNewing** [comment]
I can't reproduce it on Firefox, Safari or Chrome

**Comment by camallen** [comment]
Hmm - it only does it on firefox (49.0) Ubunutu for me. Only any event in the browser (key / mouse) it fixes itself. Unless someone else can reproduce just consider my setup a bit odd.

**Comment by BNewing** [comment]
@srallen @rogerhutchings @jwbmartin What do you think about this PR?

**Comment by simoneduca** [comment]
I was thinking about this the other day. Thanks for sorting it out @BNewing! I'd probably set `min-height: 200`, but apart from that LGTM.

**Comment by BNewing** [comment]
Changed it to 200px! Will it need rebasing?

**Comment by simoneduca** [comment]
There's no conflict with master, so I don't think. Happy to merge, but waiting on other people to comment too.

**Comment by jwbmartin** [comment]
I dig it

**Comment by BNewing** [comment]
Is it okay to merge it :)?

**Comment by rogerhutchings** [comment]
LGTM, hit the button

**Pull request merged**
