### PR TITLE
 Upgrading enzyme to 3.x (#4305)

### PR DESCRIPTION
**Pull request by eatyourgreens**
Staging branch URL:

Continues #4305

Upgrades React to 15.6.2 and enzyme to 3.3.0. Enzyme migration guide can be found [here](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#lifecycle-methods)

Currently have a few tests still failing, have already corrected a few.

### Currently failing tests

- [ ] Shortcut functionality should show an active button with a shortcut
- [ ] ShortcutEditor methods should call toggleShortcut with an input toggle
- [ ] ShortcutEditor methods should call remove handler when clicked
- [ ] ShortcutEditor methods should call add handler when clicked
- [ ] SVGImage it should contain an image element
- [ ] SocialLinksEditor should call handleRemoveLink() when link is removed

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
The React update might make this harder to test than just updating enzyme alone, since upgrading React potentially breaks zooniverse.org.

**Comment by tingard** [comment]
I can't remember why I decided to upgrade react to 15.6, it probably wasn't needed

**Comment by eatyourgreens** [comment]
I'm going to stage this on pfe-preview and we'll see if anything breaks. Some of the dependencies, like Markdownz and SevenTen might still be using 15.4, in which case we could run into problems caused by having multiple copies of React.

**Comment by eatyourgreens** [comment]
Actually, I'm going to rename the branch because https://upgrading-enzyme-3.x.pfe-preview.zooniverse.org/projects probably doesn't work.

**Pull request closed without merging**
