### PR TITLE
Unsubscribe all the things

### LINKED ISSUE #4487: Create button for general unsubscribe request
Add on the email settings page.
Just needs to be wired to the existing `unsubscribe` endpoint.

### PR DESCRIPTION
**Pull request by simoneduca**
Staging branch URL: https://unsubscribe-everything.pfe-preview.zooniverse.org/settings/email

Fixes #4487 .

Describe your changes.
Adds an unsubscribe from everything button to the email settings page.
Uses pretty much the same code as `/unsubscribe`.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by camallen** [comment]
I'm not sure i can review this properly, @eatyourgreens i've added you instead though feel free to take yourself off as well.

**Comment by eatyourgreens** [comment]
7ab1e14e-c15d-480e-81ed-ebdc759eb710

The big blue submit button looks out of place to me. It isn’t clear how to unsubscribe with this form.

**Comment by srallen** [comment]
#4487 is reassigned to @camallen

**Comment by srallen** [comment]
Closing this as it's getting further behind master.

**Pull request closed without merging**
