### PR TITLE
Mobile usability fixes

### PR DESCRIPTION
**Pull request by wgranger**
Describe your changes.
Fixes several design and usability issues experienced on mobile.
1) Fixes margin issues on About header
2) Provides margin for project stats
3) Adds a line break aside the project name to separate project nav bar onto new line
4) Increases the click area for the "play" button when visible for a subject
5) Allows touch scrolling for subjects with non-drawing tasks
6) Increases delete button size on smaller screens
# Review Checklist
- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [X] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch?

https://mobile-fixes.pfe-preview.zooniverse.org/
## Optional
- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [X] If changes are made to the classifier, does the dev classifier still work?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
@wgranger on Notes from Nature and Decoding the Civil War, if I zoom the image I can't pan it by dragging it, presumably because the SVG doesn't respond to touch events on this branch?

**Comment by wgranger** [comment]
@eatyourgreens Right, that makes sense and I didn't take into account that any image (despite the task) would still need the dragging capability on a zoom. I'll see if I can enable dragging when using pan and zoom.

**Comment by wgranger** [comment]
@eatyourgreens Any other changes you can think of on this?

**Comment by eatyourgreens** [comment]
The project nav looks weird on a phone with a 414px screen, so 400px might be the wrong place to have that media query breakpoint. Otherwise, looks good so I'm going to merge and project nav can be handled in a new PR if necessary.

**Pull request merged**
