### PR TITLE
add link to examples in the data digging repo

### PR DESCRIPTION
**Pull request by camallen**
Add links to our data digging repo example code.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [X] Did you deploy a staging branch? https://dig_the_data.pfe-preview.zooniverse.org/
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

**Comment by mrniaboc** [comment]
This looks good to me, but I suggest you get someone who actually know how to review code properly!

**Comment by camallen** [comment]
Did you try the staging link? It's just html copy not code.

**Comment by mrniaboc** [comment]
I can't view it on the staging branch as it won't allow login, with this error "Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc."

**Comment by camallen** [comment]
Which browser? Will try and reproduce.

**Comment by camallen** [comment]
Reproduced, i'm a bad human and made my branch with underscores. turns out the staging server doesn't accept this as a valid CORS domain.

**Pull request merged**
